### ISSUE TITLE
build failure because of incorrect 'The JAR is empty' warning

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bnd#1022]
A 'dist' project with
```
-nobundles
```

still gives
```
:dist:jar
Warning: File on classpath that does not exist: /home/ferry/vcs/nbs/ahrplefe/dist/bin
Warning: The JAR is empty: The instructions for the JAR named dist did not cause any content to be included, this is likely wrong
Error  : Unexpected ProjectBuilder init,  error java.lang.IllegalArgumentException: A Jar can only accept a valid file or directory: /home/ferry/vcs/nbs/ahrplefe/dist/bin, 
:dist:jar FAILED
```

biz.aQute.bnd.gradle.jar
Git-Descriptor: 2.4.0.REL-647-g1bcf573
Git-SHA: 1bcf573eaf8da498f75787227e1549e0e6bcb353

**Comment by bjhargrave** [comment]
You should say: `-nobundles: true`. With `-nobundles: true`, is there an issue on the latest 3.0 build?

**Comment by fhuberts** [comment]
is this a change in behaviour?
If so I'd kindly request that that change be reverted: there now is an ABI break

**Comment by bjhargrave** [comment]
In bnd 3.0, -nobundles is now consistently treated as a boolean. So you can use expressions which evaluate to true or false. Previously bnd was inconsistent. Project treated it as a presence test but Builder treated it as a boolean.

Consistently treating it as a boolean is valuable since you can say things like: `-nobundles: ${is;${driver};eclipse}` to skip building expensive projects conditionally.

To the extent this is a breaking change, we believe it is acceptable for bnd 3.0 which is major version bump.

**Comment by fhuberts** [comment]
Then please check if empty and set default to true to avoid breakage

**Comment by fhuberts** [comment]
well, then at least document the breakage

**Comment by bjhargrave** [comment]
I added it to https://github.com/bndtools/bndtools/wiki/Changes-in-3.0.0#backwards-compatibility
