### ISSUE TITLE
Run no longer works from bnd.bnd

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#1123]
Resolving from bnd.bnd and then running does not work anymore. There is an error that the JAR is empty.

Related tot this, JUnit OSGi tests in enRoute also do not work. They whine that the aQute.bnd.tester cannot be found.

This all works fine in 3.0

**Comment by bjhargrave** [comment]
Hopefully no code is looking for aQute.bnd.tester in a specific folder in `cnf/cache`. For 3.1, the embedded repo files have been renamed to have version numbers instead of `latest` and to also be in a version folder under `cnf/cache`. For example: `cnf/cache/3.1.0/biz.aQute.tester/biz.aQute.tester-3.1.0.jar`.

**Comment by pkriens** [comment]
The launcher seems to work so I have to debug by the tester cannot be found.

**Comment by njbartlett** [comment]
Was this fixed by the fix for [Bndtools issue 1190](https://github.com/bndtools/bndtools/issues/1190) or it is a separate issue?

**Comment by bjhargrave** [comment]
I suspect this is the same issue. Closing for now.
