### ISSUE TITLE
Bnd should use a snapshot version until the release build is done

### ISSUE THREAD

**Issue by cschneider** [bndtools/bnd#1141]
Currently bnd uses version 3.1.0 for master. The problem with this is that once this version is in your local maven repo then maven will not reload a new version from a remote repo.

So maven projects should generally build with a snapshot version and only use the release version for the final release build.

**Comment by bjhargrave** [comment]
You need to see the commands in the .travis.yml file: https://github.com/bndtools/bnd/blob/master/.travis.yml#L17. First you need to run the gradle build, and then 2 files from that build need to be installed in the maven/target/m2 repo. Then you run the maven build.

Once bnd it updated to enable releasing into an m2 repo, we can simplfy this. But for now, this is how you need to build the maven parts.

**Comment by timothyjward** [comment]
> So maven projects should generally build with a snapshot version and only use the release version for the final release build.

bnd is not a maven project, and does not use snapshot versions because they are not legal in OSGi. If we use snapshot versions in the associated plugins then this also prevents the normal bnd release process, and forces us to make changes to the "release" driver.

If we were releasing to a public repository then I would have some sympathy for the reasoning behind this bug, however the bnd build output is not a normal repository and should not be used as such. It is really only there for early adopters to try things out in a "release-like" way.
