### ISSUE TITLE
Problem in bnd-indexer-plugin: IllegalArgumentException: Cannot index files above the root URL.

### ISSUE THREAD

**Issue by cschneider** [bndtools/bnd#1142]
I am trying the bnd-indexer-plugin 3.1.0 from master.

This is the pom I use:
https://gist.github.com/cschneider/10880871330fc2e445b2

When running mvn install I get this error on all three deps:
IllegalArgumentException: Cannot index files above the root URL.
https://gist.github.com/cschneider/9e6adf915a795a07a319

Am I doing this wrong or is this a bug?

**Comment by timothyjward** [comment]
I have tried running the pom you provided with the latest build and it works for me. It looks to me like you may be running with an out of date repo index and/or indexer plugin, but it's hard to be sure.

**Comment by timothyjward** [comment]
Another option is that it doesn't like the location of your local repository, is it in a non-standard location?

**Comment by cschneider** [comment]
My local repo is at the standard location of ~/.m2/repository. I checked out the bnd source today. So it should be quite fresh. I will try to deploy the most current jars into my local repo.

**Comment by timothyjward** [comment]
So I took your gist, put it in a folder, and ran `mvn install`. Are you doing anything different?

**Comment by cschneider** [comment]
I was unsure if I really had the most current bnd and index plugin jars in my local repo as the build steps do not use the standard maven repo. So I just removed bis/aQute in my local repo and built and deployed the bnd lib as well as the plugin. 

I still get the same error though. 
I uploaded the full log to a gist now. Not sure if it helps:
https://gist.github.com/cschneider/7430988e5c7d241b21d4

**Comment by timothyjward** [comment]
So the actual problem is here: https://gist.github.com/cschneider/7430988e5c7d241b21d4#file-complete-log-index-plugin-L194

I don't know what the error is, but we probably should put a try/catch and some logging in there. The rest of the errors are a logical consequence of the error logged on that line.

**Comment by timothyjward** [comment]
Try the code at 6cfc3b1683dc8e4304a124db3adcc4078a0a3524 and see if it helps.

**Comment by cschneider** [comment]
I debugged through the unchanged code and it seems the cause is this:
throw new FileNotFoundException("The repository " + artifactResult.getRepository().getId() + " is not known to this resolver");
So artifactResult.getRepository() is the LocalRepository. So it looks like the url could not be resolved to the original repository where the file was loaded.

In this case the repository should be maven central.

**Comment by cschneider** [comment]
I just found that when I remove the artifacts from my local repo it works. Interestingly it keeps working now. So my assumption is that the reason why I got the error is that I built the aries jpa release on my system. So the artifacts were never loaded from a remote repository. When I then removed them maven seems to remember where they originated. So it works.

**Comment by timothyjward** [comment]
Hi,

Yes, that would make sense. The indexer does try to load metadata from the repository to find the jar, but that still won't work if aether has decided that it's definitely local. It should work ok in CI though (where the deploy happens).

Tim

**Comment by cschneider** [comment]
I think the core problem is that the plugin trys to create a http url for the maven artifact. Of course this is the only way to make it work in bndtools at the moment but I think we should instead use a mvn URL like in Apache Karaf. This will make the index independent from the maven repository the artifacts are deployed on and also allows to use a maven proxy or company repo.
To make this work we would need to add pax-url to bndtools. Then it could resovle such mvn urls and use them to download the artifacts.
mvn urls would also allow karaf to reuse the indexes for bundle and feature resolution.
Do you think that would work?

**Comment by timothyjward** [comment]
> I think the core problem is that the plugin tries to create a http url for the maven artifact. Of course this is the only way to make it work in bndtools at the moment but I think we should instead use a mvn URL like in Apache Karaf. This will make the index independent from the maven repository the artifacts are deployed on and also allows to use a maven proxy or company repo

This is not the purpose of this indexer. the point is to produce standard indexes that can be used without requiring further proprietary features in the client. The mvn: URL scheme is non standard, and as you have pointed out, it requires the client to have some 'magic' at the other end. These indexes are not simply for use in bndtools and/or Karaf, the point is that anyone can create an index of their bundles and use it with a standard tool.

> This will make the index independent from the maven repository the artifacts are deployed on and also allows to use a maven proxy or company repo.

The indexer already works this way - try it! I have done plenty of testing against "private" Nexus repositories and mixtures of private/public repositories. The index points at the artifact where it lives in the repository that it's from, and it uses the Aether API to construct the URI path so that it works with any Maven supported repository format. Another benefit of the current model is that the index produced uses a fixed URI for each of the dependencies, so each client will get the same resource and you don't have to play around with a settings.xml on a non-build machine.

> Another benefit is that the mvn urls also would support the SNAPSHOT semantics of maven. So it would work very well with automated CI builds of projects.

The indexer already supports SNAPSHOT artifacts. There are even tests for it in the integration test suite!

> So it would work very well with automated CI builds of projects.

Again the documentation shows how to make the indexer work really well in CI, for local/Development building you can require the use of local URLs, then force the use of remote URLs in CI using a profile. Profiles are a pretty common way for Maven to work. I suggest that you re-read the [documentation] (https://github.com/bndtools/bnd/blob/master/maven/bnd-indexer-maven-plugin/README.md)

**Comment by cschneider** [comment]
I agree that the index like it is will work if people create their own indexes only. 
What I have in mind though is that open source projects can provide their own indexes and deploy them to maven central or any other maven repo. This can not work with absolute http uris.
I think it will also not work to create an index at one point then move the nexus to another uri (which might happen over time) and still use the unchanged index.
Of course the ideal solution would be to allow that users of the index do not need additional magic and still can use the index but I think this is not possible.
To some degree bndtools currently already has the magic inside to resolve maven artifacts as you can specify them in the .bnd files. So I think the concept is not completely alien to bndtools.
Ultimately my goal is to make it simpler for people to start with OSGi development. A big part of this is to specify the correct dependencies for the set of frameworks/libs they want to work with. So I think we need more coarse grained building blocks than single jar dependencies and the indexes could do exactly that in a fairly standardized way.

**Comment by timothyjward** [comment]
> What I have in mind though is that open source projects can provide their own indexes and deploy them to maven central or any other maven repo. This can not work with absolute http uris.

Why exactly does this not work? In fact the HTTP URIs are the only way I can see to make SNAPSHOT versions work reliably. The content capability of the resource includes the SHA of the bundle and its length, both of which typically change between snapshot builds. A mvn: URL is therefore only valid until the next build, at which point it is pointing at the "wrong" artifact (i.e. not the one that was indexed).

> Of course the ideal solution would be to allow that users of the index do not need additional magic and still can use the index but I think this is not possible.

I still haven't seen you give a reason for why this is not possible. If anything the solution you're suggesting seems more error prone.

> Ultimately my goal is to make it simpler for people to start with OSGi development. A big part of this is to specify the correct dependencies for the set of frameworks/libs they want to work with. So I think we need more coarse grained building blocks than single jar dependencies and the indexes could do exactly that in a fairly standardized way.

I agree with this statement wholeheartedly, which is why I want to avoid non-standard URL schemes as the default content capability. Ease of use for the developer is significantly about not requiring large numbers of tools and configurations to make something work. The current model uses URLs which "just work" in any tool or web browser, without requiring an extra bundle and/or settings.xml.

Also, you keep mentioning Bndtools, which is of course an important consideration, but Bndtools is not the only user of bnd. We do not control all of the clients for this scenario, and we must not make assumptions about the sorts of URL that they can use. At the moment the indexer creates a URL with the same URL scheme as the configured Maven Repository URL to ensure maximum portability.

> If you have concerns about the mvn URIs then maybe we could use a translation between the index on maven that contains the mvn URI and the index given to bndtools. If we do this translation as late as possible then there should be no issue with outdated absolute http URIs.

The correct way to do this would be to add a second content capability containing the mvn: URL. The default should still be the http(s) URL because it has numerous advantages (it works for snapshots, it's interoperable with all clients, it gives the same result for all clients...). If the http URL does not work then the client is free to try using the next content capability (and so on) until it finds one that works.

Allowing content capabilities would involve a significant overhaul of the indexing process to allow multiple locations to be provided and output for the same input artifact. There is also a plan to overhaul the indexer in bnd 3.2. I suggest that you create a feature request for that and, if you have time, to start work on a PR.

**Comment by timothyjward** [comment]
Closing this issue as the original problem is solved (remote URLs were required but no remote URL could be found due to missing Aether metadata).

**Comment by cschneider** [comment]
The URI of a maven repository is not stable. So using it in an index can never be a long term solution. The maven idea for publishing artifacts (releases) is that you publish them once and then they have to be stable for long term usage. If the index contains such a non stable URI then this will simply not work.

Your statement about SNAPSHOTs is not correct. If you refer to a artifact using e.g. 1.0.0-SNAPSHOT then what you want is that maven tries to find the newest snapshot. So it is completely intended that you do not get the same artifact all the time. If you want a fixed snapshot then you use its fixed id (http://www.mojohaus.org/versions-maven-plugin/examples/lock-snapshots.html). Maven automatically takes care of this translation when you publish a snapshot to a remote repository.
In any case I think it makes sense we move this discussion to a separate issue as it is not about the original bug anymore :-)
