### ISSUE TITLE
org.osgi.service.component.annotations are carried in bndlib

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bnd#1269]
This is quite unfortunate since they will conflict with OSGi R6 annotations when both are on the buildpath

**Comment by bjhargrave** [comment]
Why is bndlib in the buildpath of a normal bundle?

**Comment by bjhargrave** [comment]
Also, the were added to bndlib as far back as 2.1.0.REL: https://github.com/bndtools/bnd/commit/53ebcf3187962371355e1cfa40dad7950508d1ee.

**Comment by fhuberts** [comment]
my gradle headless build plugin needs access to bndlib and I'm trying to swtich it over to R6 annotations.

Eclipse is giving me non-API warnings and lands me in the bndlib carried annotation on F3

**Comment by bjhargrave** [comment]
The packages in bndlib are the R6 annotations. If you also have the proper osgi jars on your classpath ahead of bndlib, I would imagine those will be preferred. If you want to use the annotations from bndlib, just add the packages attribute to the bndlib entry in the -buildpath to tell bndtools they are "exported".

I don't see that it is possible to not include the annotations in bndlib since it needs them to process the annotations in bundles.

**Comment by fhuberts** [comment]
I want to use the annotations from the R6 jar, what incantation is needed in the buildpath entry?

**Comment by fhuberts** [comment]
I used
```
osgi.annotation;version=${osgi.annotation.version};-split-package:=merge-first,\
```

since that one comes before bndlib

**Comment by bjhargrave** [comment]
osgi.annotation does not include the DS annotations which you want. They are in osgi.cmpn or org.osgi.service.component.annotations.

**Comment by fhuberts** [comment]
ah yeah. not enough sleep.
tnx
