### ISSUE TITLE
Please add an WAB example to bnd-maven-plugin

### ISSUE THREAD

**Issue by thomasmey** [bndtools/bnd#1273]
Hi,

using this bnd.bnd file:

Bundle-Name: RESTful API
Bundle-SymbolicName: de.m3y3r.example
Import-Package: de.m3y3r.fields;version="[2.4.4,3.0)"
Web-ContextPath: /rest
-wab: src/main/webapp/

and the packaging jar and 
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<configuration>
					<useDefaultManifestFile>true</useDefaultManifestFile>
				</configuration>
			</plugin>

gives me a strange jar files which seems to have the classes duplicated under the root of the JAR and under WEB-INF/classes/

Bug or feature?

An example in the bnd-maven-plugin would clarifiy the correct creation of an WAB file.

**Comment by bjhargrave** [comment]
@timothyjward Can you provide some advice here?

**Comment by timothyjward** [comment]
The `bnd-maven-plugin` tries to be a good citizen in a maven build and therefore doesn't do as much as the `maven-bundle-plugin` did. In particular the `bnd-maven-plugin` *only* creates OSGi metadata (bundle manifests, DS XML files...) and it *never* packages the final artifact. This is a very different behaviour from the `maven-bundle plugin`.

 I don't have much experience with using the `-wab` instruction, but given my understanding of what it does it should probably be considered harmful when used with the `bnd-maven-plugin`. Setting `-wab` tells bnd to move the compiled class output into `WEB-INF/classes` and to set the `Bundle-Classpath` header. In a world where bnd isn't responsible for packaging this creates the mess you found...

I believe the correct way to structure this project would be to use a `war` packaging type so that the `maven-war-plugin` moves things around correctly. This will have the benefit of making the project work as a WAR file with other tools. You will need to set your `Bundle-Classpath` appropriately, and to tell the `maven-war-plugin` to use the generated manifest. 

Just to warn you, this may not work very well because the bnd-maven-plugin doesn't know that the maven-war plugin is going to pull the compile-time dependencies into WEB-INF/lib. As a result the computed Import-Package statements may not be correct. It all depends on exactly what the `maven-war-plugin` is doing. It should work if you're building a skinny WAR though.

**Comment by thomasmey** [comment]
Hi,

Okay, thanks for the hint, I'll play around a bit with it.

**Comment by thomasmey** [comment]
Hi,

okay I did debug this a bit and your statement "In particular the bnd-maven-plugin only creates OSGi metadata (bundle manifests, DS XML files...) " is not true at least for wab instruction.

Here is what I understood and what's happing in the bnd-maven-plugin (3.1.0):

1.) All classes are compiled to target/classes directory
2.) Then the bnd-maven-plugin runs and creates the "metadata-only jar file in memory" and it add first all relevant classes:
Thread [main] (Suspended)	
	Builder.doExpand(Jar) line: 512	
	Builder.build() line: 97	
	BndMavenPlugin.execute() line: 161	
2.) possible includes are added to the metadata-jar:
Thread [main] (Suspended)	
	Builder.build() line: 98	
	BndMavenPlugin.execute() line: 161	
3.) then the wab instruction is processed:
here happens the problem/error as all classes are renamed, i.e. moved(!) in the in memory metadata jar.
when tracing is enabled this will be outputted to stderr:
"# wab: moving: de/m3y3r/testing/Example.class"

Inside Jar.rename() the resource is moved from target/classes/ to target/classes/WEB-INF/classes/
Thread [main] (Suspended)	
	Jar.rename(String, String) line: 732	
	Builder.doWab(Jar) line: 224	
	Builder.build() line: 99	
	BndMavenPlugin.execute() line: 161	
4.) finally all additional resource from the -wab instructions are added to the metadata-jar.
After this step the resource of the metadata jar will look like this:
[WEB-INF/classes/de/m3y3r/Example.class, WEB-INF/web.xml, doc/index.html]

And the resource entry of WEB-INF/classes/de/m3y3r/Example.class will actually point to target/classes/de/m3y3r/Example.class

Then the manifest is processed/created and some other things are happing. you can expand the metadata jar with undocumented bnd instruction: "-expand: /dir/to/expand/to" after that the builder is finished.

Fun fact 1: The expanded metadata jar nearly looks correct. There is only a duplicated content of doc/index.html under expanded/WEB-INF/classes/. But this is maybe a bug in the dot.expand(out) (line 174 of aQute.bnd.osgi.Builder class, need to check this again).

5.) After the builder is finished actually resources are created in the target/classes directory:
First the META-INF/MANIFEST.MF file is created at BndMavenPlugin.execute() line: 164

And then the metadata jar is "expanded":
BndMavenPlugin.execute() line: 171	

Here the bug manifests itself:
in this method all metadata-jar resource are actually *copied* from their original position to WEB-INF/classes! I think this is a bug, as before those resource were meant to be moved (in the Builder) but here they are copied and after the copy process the original file is not deleted in target/classes:

Thread [main] (Suspended (breakpoint at line 241 in BndMavenPlugin))	
	BndMavenPlugin.expandJar(Jar, File) line: 241	
	BndMavenPlugin.execute() line: 171	

This leaves the target/classes directory in an inconsitent state, with duplicated classes:
1.) the original classes from the compile step under target/classes and
2.) the copied classed from the wab osgi Builder move step under target/classes/WEB-INF/classes.

So what do you think about this? I would argue that this is a bug and should be fixed, but I'm not sure what's the best solution for this. Probably remove the original resource after the IO.copy()?

And after going throuh all this, I would argue that using the type jar is the correct "packager" (maven-jar-plugin) for wab files created by the bnd-maven-plugin, as most work to create a correct war/wab structure is done already in this plugin.

Hope this all makes sense.

Feedback is most welcome!
