### ISSUE TITLE
Use normal maven repo in travis and maven plugins build

### ISSUE THREAD

**Issue by cschneider** [bndtools/bnd#1369]
I just checked out the newest bnd master and saw that it now uses SNAPSHOT versions for maven dependencies. This allows to make the build a little simpler.

Currently in the travis script  org.osgi.impl.bundle.repoindex.cli-latest.jar and biz.aQute.bndlib-latest.jar are installed into the maven repo using a SNAPSHOT version like 3.2.0-SNAPSHOT.

As they are not using a fixed release version as before I think it should be safe to write them into the normal local maven repo. 

So I think the -Dmaven.repo.local=maven/target/m2 can be safely removed from the travis script.

The advantage is that the maven plugins can then be nicely imported into eclipse using import maven project and the build in eclipse works out of the box. This should lower the barrier of entry for new developers.

Additionally I think the grade main build could already install these two files into the local maven repo. So there are less manual steps to do for a build.

WDYT?

**Comment by bjhargrave** [comment]
We are working to use Peter's new, forthcoming maven repo support for releasing to maven repos in the bnd build. This is a series of incremental steps of which you just observed the change in the build to use SNAPSHOT versions. More work is forthcoming. Be patient :-)

The CI builds will not use `~/.m2/repo` (as you call the "normal maven repo") since it may be polluted and/or vary from user to user, system to system. But someone building locally can use `~/.m2/repo`.
