### ISSUE TITLE
Can bnd Gradle plugin (biz.aQute.bnd.gradle/) help build Eclipse plugins with gradle?

### ISSUE THREAD

**Issue by paulvi** [bndtools/bnd#1381]
There's open-source Editor for `.gradle` files for Eclipse https://github.com/Nodeclipse/GradleEditor that I'd like to build with gradle.

Can bnd Gradle plugin (biz.aQute.bnd.gradle/) help build Eclipse plugins?

ref https://github.com/Nodeclipse/GradleEditor/issues/1

docs https://github.com/bndtools/bnd/tree/master/biz.aQute.bnd.gradle#gradle-plugin-for-non-workspace-builds

**Comment by paulvi** [comment]
UPDATE Should be looking at https://github.com/bndtools/bndtools/blob/master/build.gradle first, but it is still not clear how to add gradle build for an Eclipse plugin project.

**Comment by bjhargrave** [comment]
Yes, you can build eclipse plugins with the gradle plugin since we build bndtools as you note above.

But first you must convert the Eclipse PDE project to a bnd/bndtools project and then you can build with the gradle plugin. PDE is manifest first and bnd is not. 

Since there is no bug in bnd here, I am closing this issue. You can ask usage questions in the bndtools-users mail list <https://github.com/bndtools/bnd#feedback>.
