### ISSUE TITLE
Support start levels and eager activation in launcher

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bnd#141]
Unfortunately we sometimes need support for:

a) Specifying start levels;
b) Eagerly starting bundles even when they are marked as `Bundle-ActivationPolicy: lazy`.

Proposal: add directives to the -runbundles instruction. Also required is a single property to set the target start level of the framework. For example:

```
-runbundles: org.example.foo;version=latest;start:=eager;level:=3
-runlevel: 4
```

**Comment by kriegfrj** [comment]
> I agree, let's do this [force-starting bundles] with a bundle.

@njbartlett, I know that this issue is pretty old, but I have hit up against this issue of needing to force-start bundles, and I have been searching in vain for a solution for this in bnd, and I simply keep coming back to this page.

Is this bundle that force starts bundles something that you developed in-house, or is it publicly available? If the latter would you be so kind as to put a post here with pointing readers like me (who have followed the trail this far) in the right direction? I know it shouldn't be too difficult to develop something like this from scratch, but I'd rather not re-invent the wheel.

**Comment by njbartlett** [comment]
The "caffeine" bundle from this repo is probably what you are looking for: https://github.com/bndtools/bndtools-rt

I haven't touched the code for a while so I don't know how easy it will be to build. Then again, the code of the bundle itself is trivial.

**Comment by kriegfrj** [comment]
Thanks @njbartlett, that will certainly get me started (and hopefully anyone else who follows this post after me!)

**Comment by laeubi** [comment]
I found this thread while searching for the meaning of the property `launch.activation.eager` I see in the debug output of the launcher, was something like this added in the meantime?
If not, equinox-launcher behaves like this:

1. nothing specified = just behave as the default
2. `start=true` always start
3. `start=false` never start

probably BND could do something similar, having an extra bundle for this seems a bit cumbersome.
