### ISSUE TITLE
Bnd fails to discover attributes for package imports if the package is contained in multiple jars, but not all of them export it

### ISSUE THREAD

**Issue by sag-test** [bndtools/bnd#1484]
Hi,
  We recently switched to Gradle 2.13 thereby upgrading Bndlib to from 2.1 to 2.4 and noticed that Bnd no longer generates package imports for split packages. Our bundle is referencing the 'org.eclipse.core.runtime' package which is provided by both 'org.eclipse.osgi' and 'org.eclipse.equinox.common' bundles on the classpath. In our case, Bnd processes the 'org.eclipse.osgi' bundle first and adds an entry for the package in the 'classpathExports' without adding any attributes for the package (this happens in Analyzer.learnPackage method). Later on in Analyzer.getManifestInfoFromClasspath method, the package is discovered in 'org.eclipse.equinox.common' bundle but it is not updated in the 'classpathExports' map which results in missing import definition for this package.
This issue is most probably caused by the following commit:
https://github.com/bndtools/bnd/commit/5bfda07bde53125db611aaaa8e3c0687930fff92

Any chances that this issue is fixed in later Bnd versions?

Regards,
   Detelin

**Comment by bjhargrave** [comment]
Bndlib was just released at version 3.2. 2.4 is very old. Please try the latest version.

I notice you mention Gradle as a reason Bndlib was updated. What gradle plugin are you using? Have you seen the gradle plugin from bnd? https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.gradle/README.md

**Comment by sag-test** [comment]
I'm using [Gradle OSGi](https://docs.gradle.org/current/userguide/osgi_plugin.html) plugin which internally seems to use the `aQute.bnd.osgi.Analyzer` API, I will try the Bnd Gradle plugin and let you know the result.

Thanks,
   Detelin

**Comment by sag-test** [comment]
I tried the Bnd Gradle plugin 3.2.0 and it seems the bug is present there as well. Attaching a [sample Gradle project](https://github.com/bndtools/bnd/files/294496/SplitPackageTest.zip) that demonstrates the issue. Run `gradle clean bundle` with Gradle 2.13 and notice that the generated manifest contains just `Import-Package: org.eclipse.core.runtime` while it should contain `Import-Package: org.eclipse.core.runtime;version="[3.5,4)";common=split` instead.

Regards,
   Detelin

**Comment by bjhargrave** [comment]
I don't think is a split package issue per se. The problem is that `org.eclipse.core.runtime` is not a _real_ package in the first jar. It is a prefix of actual packages:

```
Export-Package
  org.eclipse.core.runtime.adaptor       {x-friends:=org.eclipse.core.runtime}
  org.eclipse.core.runtime.internal.adaptor {x-internal:=true}
```

while it is an actual package in the second jar:

```
Export-Package
  org.eclipse.core.runtime               {common=split, version=3.5.0, mandatory:=common}
```

@pkriens What is supposed to happen here?

**Comment by pkriens** [comment]
Well, bnd gets the info from the manifest,packageinfos, package-info.class ...

I created a test in bnd to check different orderings but it al seems to work fine there. Something happens on the gradle side it seems. I need a way to see the classpath that is given to bnd?

**Comment by detyo** [comment]
Yes, the classpath must contain a bundle that contains a package, without actually exporting it, followed by another bundle, which exports this package - this order is important to reproduce the issue. With this ordering `Analyzer.learnPackage(..)` would populate the `classpathExports` map with the package entry from the first bundle, which does not contain any attributes (since the package is not actually exported by the bundle), afterwards when `Analyzer.getManifestInfoFromClasspath` is called for the bundle which actually exports the package, the `classpathExports` is not updated with the attributes of the package since it is already present in the map. As a result, the package attributes are not present in the map and not added for the import package header.

Regards,
   Detelin

**Comment by pkriens** [comment]
I created a test case exactly like that but that seemed to work well in both orders. Guess have to dig deeper ...

**Comment by rotty3000** [comment]
Could this be due to a poorly formed jar/zip file? I think a properly built
jar (using the jar tool, or good zip tool) will not contain empty directory
resources, but a poorly constructed zip file _may_ contain them. Could this
be the issue bnd is having trouble with?

**Comment by bjhargrave** [comment]
I am debugging. There appears to be a problem in the gradle plugin.

**Comment by bjhargrave** [comment]
With the fix in PR #1490, the correct manifest is generated for the supplied test case.

```
Import-Package
  org.eclipse.core.runtime               {version=[3.5,4), common=split}
```

**Comment by detyo** [comment]
Thanks,
   My product build actually uses an Ivy repository and still had the issue, so I switched to a sample to use a local Ivy repository and the standard jar task Bnd integration and noticed that the issue is present in 3.1.0 and gone in 3.2.0, which means that Gradle OSGi plugin should upgrade to Bndlib 3.2.0 to resolve the problem at least for the ivy dependencies case.
Apart from that, after getting familiar with Bnd Gradle plugin, I think I like it more than the standard Gradle one. I wonder whether you have considered donating it to Gradle to replace the standard one.

Regards,
   Detelin

**Comment by bjhargrave** [comment]
> I wonder whether you have considered donating it to Gradle to replace the standard one.

I have not thought about that. Not sure what would be involved. The Bnd Gradle plugin has multiple facets. It handles bundle building via the Bundle task type and amending the standard jar task. It also has the Baseline task. And it also has support for builds using the Bnd Workspace model build layout. So it is not clear to me what would be donated to Gradle to replace their OSGi plugin which only seems to deal with manifest content. In same ways, it would be better for Gradle to deprecate their OSGi plugin and point people to the Bnd Gradle plugin.
