### ISSUE TITLE
fragment requirement not resolved with nexus repo

### ISSUE THREAD

**Issue by Danipiario** [bndtools/bnd#1599]
If I deploy fragment to Nexus OBR repo the fragment inside obr.xml is inserted with this requirement
```
  <require extend='true' filter='(&amp;(symbolicname=org.eclipse.rap.jface)(version&gt;=0.0.0))' multiple='false' name='bundle' optional='false'>
    Required Host org.eclipse.rap.jface
  </require>
```
When the repo index is parsed by ObrContentProvider class the requirement is translated into
`osgi.wiring.host;filter='(&(symbolicname=org.eclipse.rap.jface)(version>=0.0.0))'`

IMO inside method translateObrFilter is missing code like this:

```
if (HostNamespace.HOST_NAMESPACE.equals(namespace)) {
    filter = filter.replaceAll("\\(symbolicname", "(" + HostNamespace.HOST_NAMESPACE);
    return filter.replaceAll("\\(version", "(" + BundleNamespace.CAPABILITY_BUNDLE_VERSION_ATTRIBUTE);
}
```
that would build a requirement like this
`osgi.wiring.host;filter='(&(osgi.wiring.host=org.eclipse.rap.jface)(bundle-version>=0.0.0))'`

Without this change bnd fails to resolve the requirement if I insert the fragment inside 'run requirement' section in a bndrun file.
Instead if the fragment is in the local repo the resolution succed.
Besides this the fragment is parsed but is marked with type `osgi.bundle` and not `osgi.fragment` because the method `addBasicCapabilities` doesn't make difference from bundle and fragment.

**Comment by rotty3000** [comment]
For reference the code in question is https://github.com/bndtools/bnd/blob/master/biz.aQute.repository/src/aQute/bnd/deployer/repository/providers/ObrContentProvider.java#L228-L247 and does appear to ignore fragments.

However, this might be worked around by using either the MavenBndRepository or the upcoming PomRepository instead of the OBR repo.

It should be noted that the old OBR repository format leaves much to be desired and likely will not get much love.

**Comment by pkriens** [comment]
I agree with Ray
