### ISSUE TITLE
pom parser must handle version ranges

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#1693]

**Comment by joerg-wille** [comment]
Will this bug be closed in 3.4?

**Comment by bjhargrave** [comment]
Not necessarily. It is targeted for 3.4 but still requires someone to make the changes to the code. If no fix is provided, it will slide out of 3.4.

**Comment by joerg-wille** [comment]
To be precise, the problem I want to solve is a IllegalArgumentException for transient dependencies of a pom, which are specified using version-ranges.
It looks to me as this error is in the MavenVersion.jar parseString method:
```
Matcher m = VERSION.matcher(versionStr);
if (!m.matches())
throw new IllegalArgumentException("Invalid syntax for version: " + versionStr);
```
Changing the mather to also accept a VERSIONRANGES is obviously easy but probably not the solution ;-)
This whole class seems to be partially prepared for ranges (e.g. cleanupVersion) but since I am new to bnd I am lacking context of why range-parsing was not completely implemented in MavenVersion.

Could someone describe the task what needs to be done to fix this?

**Comment by pkriens** [comment]
The solution is non trivial, that is why today version ranges in maven are not recommended. Maven does not have a strong syntax for versions to properly have ranges, a version in maven is used literally. I.e. 1.0 is different from 1.0.0 and 1, unlike OSGi.

So when we parse the pom and encounter a version range we need to get the metadata.xml in the version directory, for example http://repo1.maven.org/maven2/aelfred/aelfred/maven-metadata.xml

This metadata contains all the versions. We then should parse these versions out of the XML and match them against the versions in there. Once you know the exact matching versions we need to pick a strategy. We could take all or the highest. My suggestion is to take the highest because the resolver gets very slow if you take all. The lowest does not seem to make sense.

There are routines in place to read the project metadata.xml, they need to be expanded to read the version directory metadata.xml, this should be relatively straightforward.

**Comment by bjhargrave** [comment]
Fixed by https://github.com/bndtools/bnd/pull/2044
