### ISSUE TITLE
Enable bnd resolver to only return the "best" candidate

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#1706]
Currently, the bnd resolver returns the expected list of all possible candidates in the result from `findProviders`. However, I would argue that while this is spec compliant this is rarely if ever the desirable outcome because bnd's resolver is intended for assembling a runnable set of bundles at which time it is desired to return the minimal set of bundles possible.

**Comment by timothyjward** [comment]
Hi Ray,

Just thinking quickly I can foresee some issues with this approach when handling non-trivial resolves:



  *   Multiple requirements will not be satisfied multiply - it will be as if one, and only one, capability exists in the universe
  *   We risk failing to resolve when resolution is possible, for example:
     *   In the presence of uses constraints the “best” provider from our perspective may be invalid in the resolve
     *   When the repository is not transitively complete and the “best” provider doesn’t resolve
     *   When the capability is provided by one of several platform specific bundles and we pick Linux rather than Windows (or whatever).

I certainly wouldn’t want this to be a new default behaviour, although I would be interested to see how much of an impact it has.

Regards,

Tim

On 18 Sep 2016, at 16:19, Raymond Augé <notifications@github.com<mailto:notifications@github.com>> wrote:


Currently, the bnd resolver returns the expected list of all possible candidates in the result from findProviders. However, I would argue that while this is spec compliant this is rarely if ever the desirable outcome because bnd's resolver is intended for assembling a runnable set of bundles at which time it is desired to return the minimal set of bundles possible.

**Comment by rotty3000** [comment]
I'm glad you brought these up. You may well be correct and we should certainly explore all of these concerns.

However on complicated resolves I've yet to see this happen. In fact what I've seen is that on complicated resolves (and where there are many providers) you're more likely to end up where a wire is satisfied by a resource which is not in the keyset and which the resolver ultimately rejected because it used a "better" provider.

This leads to a rather complex scenario because bnd is doing something which is *not* expected by the resolver in attempting to invert the result such that capabilities can be traced back to their requirers and during this process is exposing rejected candiates.

**Comment by bjhargrave** [comment]
This is an issue in the Felix Resolver, not the Bnd implementation of the ResolveContext.
