### ISSUE TITLE
Leaving a colon out of an -includeresource spec led to no error and a surprise

### ISSUE THREAD

**Issue by benson-basis** [bndtools/bnd#1737]
One of my co-workers wrote the below text, in which four ':' characters went astray.

The result was no diagnostic messages, and jars not included in the Bundle-Classpath.

So, I wonder, would it be reasonable to ask for this to warn or error? What does it mean to have `lib:=true` stuck on the end without the colon?

```
-includeresource: \
   lib/=${de.bwaldvogel:liblinear:jar};lib:=true, \
   lib/=${com.basistech.rli-je:rli-je-core:jar};lib=true, \
   lib/=${com.basistech.tcat:tcat-core:jar};lib=true, \
   lib/=${com.basistech.tcat:tcat-rli-s:jar};lib=true, \
   lib/=${com.basistech.tcat:tcat-rli-s-models:jar};lib=true
```

**Comment by bjhargrave** [comment]
Bnd parses most instructions using OSGi's model of directives (:=) and attributes (=). Bnd, like OSGi, also generally ignores unknown directives and attributes since they may be meaningful to some one else such as a Bnd plugin.

So when you say lib=true instead of lib:=true, Bnd does not know that is an error. Its just means you did not specify a lib directive but did specify a lib attribute.

Bnd has a `-pedantic: true` mode but I don't know that it checks for some specifying an unknown directive/attribute which has the same name as a known attribute/directive.

**Comment by bjhargrave** [comment]
The bnd maintainers discussed this issue. We agreed that we should transition bnd to just use attributes instead of directives to avoid any confusion about `:` usage.  So this means any places we use directives, we will also support the same named attribute as well. The directives will need to remain supported for backwards compatibility.
