### ISSUE TITLE
FileSystemException creating cache symlinks for P2Repository due to insufficient priviliges in Windows

### ISSUE THREAD

**Issue by eliasvasylenko** [bndtools/bnd#1834]
Since the changes in #1831 the following `java.nio.file.FileSystemException` is thrown when attempting to create cache symlinks in Windows: `A required privilege is not held by the client`.

Currently to resolve this users must turn off UAC.

This could be addressed with a fall-back behaviour which copies instead of links, as suggested in #1829

To give the best behaviour for the greatest number of users the ideal solution may be to implement a series of fallbacks: `Soft link -> Hard link -> Copy`.

**Comment by bjhargrave** [comment]
I think for windows, we abandon all hope of links and always make a copy. Windows FS is too brain damaged. Making symlinks requires a permission windows users don't normally have or, if they are admin, requires run as admin to make symlinks <https://technet.microsoft.com/en-us/library/cc766301(WS.10).aspx>.

Hard links don't work across file systems anywhere, so that can fail on a regular basis.

So I think we need to use symlinks if not windows. If windows or symlinking fails, then copy.
