### ISSUE TITLE
Inconclusive BndPomRepository documentation

### ISSUE THREAD

**Issue by rherrmann** [bndtools/bnd#1847]
The documentation of the _Maven Bnd Repository Plugin_ at http://bnd.bndtools.org/plugins/maven.html differs from the instructions given in _Bnd Pom Repository_ at http://bnd.bndtools.org/plugins/pomrepo.html

In particular the configuration properties are different:

* releaseUrls vs. releaseUrl and snapshotUrls vs snapshotUrl
* readOnly and index don't exist in _Bnd Pom Repository_
* pom does not exist in _Maven Bnd Repository Plugin_

**Comment by rotty3000** [comment]
There are two distinct maven repositories implementations:

1) aQute.bnd.repository.maven.provider.MavenBndRepository
2) aQute.bnd.repository.maven.pom.provider.BndPomRepository

Is it possible you are confusing the two?

**Comment by rherrmann** [comment]
@rotty3000 you are right, I confused thw two. Do you know which one should be preferred or in which aspect they do differ?

**Comment by rotty3000** [comment]
The recently preferred one is `BndPomRepository`. It has many more features such as automatically scanning for transitive dependencies, uses the latest bnd Http client with support for authentication, network proxies, and overall better network performance. It supports local and remote BOM files, it supports multiple GAVs, it supports searches against Maven Central search engine. All in all it's the most powerful one.

However, `MavenBndRepository` does have it's uses because it's very light. However, it requires a secondary text file in the cnf directory using the lower cased name of the repository configuration and the extension `mvn`. Each line of this file contains one single GAV. As such it's convenient when working with just a few artifacts.

**Comment by rotty3000** [comment]
... oh, one last thing. The `MavenBndRepository` is harder to use in bnd-maven's `-standalone` build model. It's usually only used in the bnd workspace model.

**Comment by rherrmann** [comment]
Thank's a lot for your explanation - and sorry for confusing the two.

Maybe such an explanation should be included in a section on one or both of the documentation pages. Please let me know if you want me to open a separate issue therefore or feel free to close this issue if you disagree.

**Comment by bjhargrave** [comment]
Can you please make a PR to improve the documentation?

**Comment by juergen-albert** [comment]
@bjhargrave I guess we should close this one.
