### ISSUE TITLE
NullPointerException in Traverser::parsePom()

### ISSUE THREAD

**Issue by rherrmann** [bndtools/bnd#1849]
While debugging Bndtools to find out why certain Maven repository artifacts cannot be resolved, I found a possible or related problem with `MavenRepository` and its clients.

`MavenRepository::getPom()` may return `null` but its callers aren't prepared to handle this.

If `getPom` cannot find a local (pom) file for the requested revision, it fails the deferred runnable in `MavenRepository::get()` with a `FileNotFoundException` and returns `null`. The exception, however, gets later covered by a `NullPointerException` when callers try to access the return value.

**Comment by bjhargrave** [comment]
Can you please supply the full stacktrace. I am not sure I fully understand the problem here. 

get always returns a Promise that will either be failed or resolved. The Promise cannot be failed and resolved with a null value. If a Promise is failed, you cannot the value. Calling getValue on a failed Promise will throw an InvocationTargetException.

**Comment by timothyjward** [comment]
I think the exception is the same as the one in bndtools#1622

**Comment by rherrmann** [comment]
@bjhargrave I am referring to this line:
```
Thread [pool-2-thread-74] (Suspended (breakpoint at line 140 in MavenRepository$1))	
	MavenRepository$1.run() line: 140	
	ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) line: 1145	
	ThreadPoolExecutor$Worker.run() line: 615	
	Thread.run() line: 744	
```
However, I can't see the `MavenRepository::getPom(Revision)` returning `null` any more. I must have got lost in debugging.

@timothyjward yes that's likely, sorry for not linking to the issue in the first place.

**Comment by bjhargrave** [comment]
Closing since this exception is expected for a missing artifact. The caller needs to protect against this. bndtools/bndtools#1622 needs to fix the viewer in Bndtools. 

This issue title mentions Traverser.parsePom(), but I don't see any stacktrace including that method here. Can you provide a stacktrace?

**Comment by rherrmann** [comment]
Stacktrace while using bnd through Bndtools:
```
Thread [pool-2-thread-4] (Suspended (exception NullPointerException))	
	Traverser.parsePom(POM, String) line: 171	
	Traverser.parseArchive(Archive) line: 164	
	Traverser.access$100(Traverser, Archive) line: 41	
	Traverser$1.run() line: 126	
	ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) line: 1145	
	ThreadPoolExecutor$Worker.run() line: 615	
	Thread.run() line: 744	
```
