### ISSUE TITLE
-connection-settings does not support maven password encryption

### ISSUE THREAD

**Issue by jwausle** [bndtools/bnd#1971]
Authentication to nexus fail silent if I use
`-connection-settings: ~/.m2/settings.xml, ~/.m2/settings-security.xml`
with encrypted maven password (https://maven.apache.org/guides/mini/guide-encryption.html)
---

bnd-3.3.0 with gradlew

**Workaround**

> -connection-settings: my-settings.xml
```
<settings>
  <servers>
    <server>
      <id>https://my-secure-host</id>
      <username>me</username>
      <password>decrypted-password</password>
      <verify>true</verify>
      <trust></trust>
    </server>
  </servers>
</settings>
```
- Thats solve the problem. 
- But every developer of the team download with my credentials.
- Special system-user is not possible (security constraints)

**Comment by jwausle** [comment]
Authentication to nexus fail silent if I use 
> -connection-settings: ~/.m2/settings.xml, ~/.m2/settings-security.xml

with encrypted maven password.
- https://maven.apache.org/guides/mini/guide-encryption.html

## Workaround 
-connection-settings: my-settings.xml

```
<settings>
  <servers>
    <server>
      <id>https://my-secure-host</id>
      <username>me</username>
      <password>decrypted-password</password>
      <verify>true</verify>
      <trust></trust>
    </server>
  </servers>
</settings>
```

Thats solve the problem. But every developer of the team download with my credentials. 
- special system-user is not possible (security constraints)

**Comment by pkriens** [comment]
I've read up on the maven 'secure' passwords and I am a bit puzzled. Why do you share your settings.xml in the first place? This file should be local to every user?

http://stackoverflow.com/questions/30769636/how-does-maven-3-password-encryption-work/43118084#43118084

**Comment by jwausle** [comment]
It was not my first approach. 

1) First I try to use (without success :( )
```
-connection-settings: ~/.m2/settings.xml, ~/.m2/settings-security.xml 
```

2) The simplest fix (for me) is to provide my-settings.xml in connection-settings format like here explained http://bnd.bndtools.org/instructions/connection-settings.html 
- the trick was to use the real decrypt password from nexus and not the encrypted password from maven in '~/.m2/settings.xml'

**Comment by pkriens** [comment]
I will make the fix but after analyzing the Maven code I am utterly puzzled. Therefore, my question is about 'why' you need this since I cannot see how you get any extra protection with this scheme.

The master password in ~/.m2/settings-security.xml is only _obscured_. If you send the encoded form in `<master>{...}</master>` in your `~/.m2/settings-security.xml`  file to me then I can tell you what your master password is, it as safe as plain text. So I fail to understand why it is obscured in this rather complex way at all.  

I will make a fix and support the same scheme to be compatible.  However, I am curious what benefit you think you get. And I might of course miss something so then I can learn ...
