### ISSUE TITLE
Import-Package not generated for <Generics> Class

### ISSUE THREAD

**Issue by alexweirig** [bndtools/bnd#2086]
Hello,

I have encountered the following problem. I have 3 bundles
```
1) example-model
    com.example.model
        Model1
        Model2
2) example-service
    com.example.service
        Service
             uses Model1 and Model2
3) example-rest
    com.example.rest
        RestService
             ...
             List<Model2> model2 = service.getModel2();
             ... some jackson processing here
```
Since in example-rest the class Model2 is only used in the Generics specification, it seems bnd doesn't add the package to the Import-Packages in the MANIFEST.MF. Also, when looking at the calculated imports in bndtools (3.4 in Eclipse Oxygen.R) the package is not showing up.
This of course leads to a ClassNotFound error at runtime.

If I simply add a 
`new Model2();`
statement e.g. before the `List<>` statement, the package is added to the Import-Packages list.

I've found a reference to a similar problem in maven-bundle-plugin-2.3.7 [FELIX-3407] that dates back a couple of years.

Is there a different (and better) solution that adding a new statement?

Many thanks in advance for your support,

Alex

**Comment by bjhargrave** [comment]
Bnd examines the class files in the bundle to compute the import package statement. Since no class in the bundle directly references the Model2 type, Bnd wont automatically add an import package for it. You can either create a direct reference as you did or you can just add 

`Import-Package: com.example.model, *`

to the bnd file to force the import for that package. The following `*` tells Bnd to compute any additional imports.

**Comment by alexweirig** [comment]
Hi BJ,

thanks for the confirmation. At least this means I don't do anything wrong here.

I will probably go with the Import-Package statement since I think it's cleaner than creating a direct reference in the code.

I suppose it's simply impossible to find this import becaus of type erasure for generics.

Let's close the ticket if that's OK for you.

Thanks a lot for your reply.

Alex
