### ISSUE TITLE
Don't export conditional packages that have versions

### ISSUE THREAD

**Issue by njbartlett** [bndtools/bnd#2131]
In most of my Maven projects I use the following macro to export all versioned packages from the bundle:

    -exportcontents: ${packages;VERSIONED}

However I noticed that this causes problems when used in conjunction with `-conditionalpackage`. Sometimes the conditional package contains a version marker in its `package-info.java` and as a result of the above macro, the package is not only included in the bundle but also exported, which is usually not desired. I think the best way to address this would be an option on the `${packages}` macro to filter out conditionally included packages. Comments?

**Comment by bjhargrave** [comment]
That seems to conflate two things. Conditional package are about adding contents to the bundle to avoid importing those packages. Export contents is then about declaring some content packages as exported.

Also, when the ${packages} macro is evaluated, I suspect the information about why a package is content (that is, is it content because conditional package included it) is not available. At that point, the package is just contents of the bundle.

**Comment by njbartlett** [comment]
I don't think I'm conflating anything? I'm not confused regarding conditional packages and export contents; I am using both in the way they are intended.

I want to add some packages to the bundle to avoid importing them, AND I don't want to export them. Can you think of any other way to achieve this? The use of the `${packages;VERSIONED}` macro is extremely convenient (and users love it) but it clashes with `-conditionalpackage`.

**Comment by bjhargrave** [comment]
My point is that I do not think they clash. They both do things that operate at different points in the bundle construction. One is part of determining the bundle contents. The other is part is determining the manifest contents (based on the previously established bundle contents).

I am not saying what you want is wrong, I am saying the current code doesn't handle it as far as I can tell. The code would need to mark packages as added because of conditional packages so those package could be later identified as such for manifest content generation.

Conditional packages are added early. https://github.com/bndtools/bnd/blob/f1aeacda844d28ea717d24c8291e0c023afe468f/biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java#L212

The code loops until no more conditional packages are added. https://github.com/bndtools/bnd/blob/f1aeacda844d28ea717d24c8291e0c023afe468f/biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java#L360-L373

This is all done before the manifest is generated. And there is no indication that the packages were added due to conditional packages.

**Comment by rotty3000** [comment]
Could the conditionalpackage statment support a flag which prevents including of versioning information? Since there's no manifest brought over the only things to exclude would only be `packageinfo` and `package-info.class` files from the package.

**Comment by bjhargrave** [comment]
> Could the conditionalpackage statment support a flag which prevents including of versioning information? Since there's no manifest brought over the only things to exclude would only be packageinfo and package-info.class files from the package.

This seems wrong since you are subsetting the package.

**Comment by rotty3000** [comment]
Would a negation on package elements listed in exportcontents work?

**Comment by njbartlett** [comment]
If `-conditionalpackage` subsetted the package by omitting `package-info.class` then that might work for this specific problem. However it would also omit any other annotations that might be on the package, possibly breaking other things.

**Comment by njbartlett** [comment]
Is there any way to correlate the packages with the source project, during manifest generation? If so then at that point we could use a macro like `${packages;VERSIONED;SOURCE}`.

**Comment by djencks** [comment]
I like this idea. Isn't this a bit of an odd situation? If there's versioning then the package was designed to be exported so why aren't you exporting it? The situation I can think of is a library that can be embedded or shared. From a purist point of view perhaps the sharing ability is not so good. If we're compensating for badly designed packages perhaps the solution doesn't need to be the most convenient.

David Jencks

**Comment by njbartlett** [comment]
@djencks I guess we could ask Peter whether all of the `aQute.lib.*` and `aQute.libg.*` packages were intended to be exported, since they are versioned.

**Comment by pkriens** [comment]
I think the best solution is:
- add a CONDITIONAL to the packages macro
- Add a macro that can remove one list from the other

**Comment by bjhargrave** [comment]
Then you can do

`-exportcontents: ${removeall;${packages;VERSIONED};${packages;CONDITIONAL}}`
