### ISSUE TITLE
Generate a file that reports the bundle metadata

### ISSUE THREAD

**Issue by cdelg** [bndtools/bnd#2138]
This issue derives from the issue #2123 

The goal is to generate a file that resume some metadata extracted from a jar. The metadata could be the manifest headers, the component declarations, the metatype definition, etc.

The preferred format for this file is Json, and is intended to facilitate the access to the metadata of a jar to any processes that need them. So, the generator should not preprocess too much the metadata to keep them generic but can improve the usability by computing default values where possible, preprocessing the localization, etc...

**Comment by cdecode** [comment]
I propose to also generate metadata files from projects and workspace. Those files can be simple and structured like the following:

* bundle.json: contains the bundle metadata and stored to /OSGI-OPT/bundle.json
* project.json: contains a list of bundle metadata built by the project and stored to ./generated/project.json
* workspace.json: contains a list of project metadata in the workspace and stored to cnf/generated/workspace.json

Those files could then be used by a template engine as a data model for exemple (see #2123).

**Comment by pkriens** [comment]
I wonder if we should not use XML for this. Though I prefer JSON in most cases it is clear that most output is going to be HTML. XML has excellent support this with XPATH and XSLT. Also, in bnd there is very nice support to generate XML with the Tag class. Last, we already have some files in XML like DS that can just be included. And XSLT can also generate text files like markdown. It is also very well supported in Java and command line tools.

It looks like we need a new class that can look at the Jar and then turn it into a (giant) XML file. Second then is a model where we can add generators for output. With the XML model we can easily take a template and the XML file and turn it into a text or HTML file. This looks quite flexible.

I am not sure if we need to store this file inside the jar? We can always regenerate it since it is supposed to describe the JAR.

Since Javascript is built into Java 8 we could provide a means for a Javascript program (or Groovy) to access the JAR and contribute to the XML file?

From commandline

       $ bnd info readme.xslt 
       # My Bundle
       This is the bundle description ...

       ## Services

       | MyService | ...

I think we should do this as a separate project biz.aQute.report. This should have a class that extends Processor can can build the XML file in memory with the Tag class. It gets a bnd.bnd file for parameters. It should not do the reporting or output. This can be done by bnd or Groovy since this is quite trivial in Java.

Maybe we should define a format that would allow others to add an XML file in the bundle that would be picked up by the reporter?

If you think this is the right direction I can setup a project for you with a simple implementation.

**Comment by cdecode** [comment]
My first objective was to help users of bnd to produce a documentation of their bundles which is contextualized, didactic and uniform with a minimal effort. So any way to achieve this is fine for me.

In my first implementation (#2134), users only have to add an instruction such as `-readme:true` to get a readme file that describes the bundle. I admit it was a bit rigid because end users had little control on what to report and how. To get this better, you propose in #2123  to:

* Allow this feature to be part of a build.
* Allow this feature from the command line on existing jar.
* Support a templating approach, where the process, first, **extract** the information from the jar and produce a file which could be used as a model. Second, the users define their own templates and invoke a **generative** process that takes the templates and the model, and generates the file they want.

I proposed a second implementation (#2139) which includes an **extractor** that reads manifest headers, ds and metatypes, computes the default values when not declared in the bundle and the localization, and stores those information in dtos. It includes also a simple command implementation that produce this dtos and write them to a json file (as recommended in #2123). For the **generative** part my plan was to use a template engine such as FreeMarker which can take any property, json or xml file as a model to produce the output file. This will allow users to declare some variables accordingly to their template directly in the bnd.bnd file, and to use the **extracted** json file or any custom file they want in the model.

To continue,

> I wonder if we should not use XML for this.

1. >it is clear that most output is going to be HTML. XML has excellent support this with XPATH and XSLT.

   The choice is between *template engine vs xml-xslt*. Template engines have generally a simpler syntax and an imperative approach, it could be more easy for an end-user than xslt. The model can also be provided by java objects, properties, json and xml structure. It is just my personal opinion, so if you prefer xslt it's ok.
2. >Also, in bnd there is very nice support to generate XML with the Tag class.
   
   I had the same argument for Json in #2123  :)
3. >Last, we already have some files in XML like DS that can just be included.
   
   I think the **extractor** process should preprocess the extracted data (defaults, localization) to make the **generative** process simpler. So maybe it will works for DS but not for metatypes because the template will have to manage localization variable or the default value for the *required* attribute for example.

So, I prefer the *template engine / Json* than the *xml / xslt* solution for simplicity (dev and users), but it is ok if you prefer xml.

>It looks like we need a new class that can look at the Jar and then turn it into a (giant) XML file. Second then is a model where we can add generators for output. With the XML model we can easily take a template and the XML file and turn it into a text or HTML file. This looks quite flexible.

This is the way I go in the PR #2139 but with Json.

>I am not sure if we need to store this file inside the jar? We can always regenerate it since it is supposed to describe the JAR.

ok.

>Since Javascript is built into Java 8 we could provide a means for a Javascript program (or Groovy) to access the JAR and contribute to the XML file?

Ok, we can let bnd generates data for the main manifest headers and things that are in the OSGI spec and create a plugin interface for the **extractor**. I don't know how to do this in bnd.

For the rest:

I can just tell you what I whould like as a bnd user. Based on the requirements that I exposed above and the fact that some documentations need a set of input jars (such as the main workspace readme file which could resume the workspace content for example): 

note: I am not insisting with json, it is just for the examples.

#### From command line:

> bnd extract my.bundle.jar

give a big my.bundle.json "raw" metadata

> bnd extract my.bundle.jar --locale en_US

give a big my.bundle_en_US.json "raw" metadata for the en_US locale.

>bnd generate myTemplate.\<template extension\> myOutput.md my.bundle.jar --models myOtherModel.xml

give a readme file with my.bundle.json and myOtherModel.xml as model

>bnd generate myTemplateUS.\<template extension\> myOutputUS.md my.bundle.jar --local en_US

give a readme file for the local en_US.

#### From the build

##### build.bnd

```
-plugin.Extractors:
    aQute.bnd.MyCustomExtractor;
    ...

-generate:
    templates=./worksace.template;
    models= <special for worksapce>;
    output=./readme.md
```

##### bnd.bnd

```
-sub:true
-generate:
    templates=./multiproject.template;
    models= <special for multiproject>;
    output=./readme.md

multiProjectName= My multi project name // custom variable
```

##### api.bnd

```
-generate:
    templates=${workspace}/api.template;
    models= generated/${bsn}.json;
    output=./readme.api.md;
    include=true
```

##### provider.bnd

```
-generate:
    templates=${workspace}/provider.template, ./myspecificneeds.template;
    models= ./generated/${bsn}.json;
    output=./readme.provider.md;
    include=true
```

Does something like that is possible ? Maybe there is a better way. 

In any case, some examples or starting codes will be great!

**Comment by pkriens** [comment]
XML – I do agree that other template engines are easier to get started with but XSLT has 2 humongous advantages. First, it is build in. Second, XPath, which is quite impressive once you get the hang. However, this does not mean I do not see the disadvantages of XML. (I actually hate XML with a vengeance.) Imho, most people will use existing templates and tune them. And you can always use other engines externally once you got XML. So despite my disgust for XML (since 1998) I still think it is probably the best default option :-(

The commands generally look good. However, the options must come before any remaining arguments. I also think the commands are better nested. I.e. `bnd report extract` and `bnd report generate`. There are already lots of commands in bnd (it is gotten a bit of a mess  over time.) and nested makes it easier to separate the code.

I think we should also scope the instructions in the bnd file with the -report.* so they stand out.

There is always a bit of tension here where the initiative should be. The initiative for the report generation could be in bnd but also in Gradle. The advantage of bnd is that even in eclipse your reports are generated but the disadvantage is that this costs CPU cycles. I guess we can always do this from Gradle so let's start inside bnd.

I've created a skeleton for you: https://github.com/bndtools/bnd/pull/2143

It implements a bnd command (bnd report generate), it participates in the build if a plugin is added, and there is some simple test case. 

have fun!

**Comment by cdecode** [comment]
I didn't react to 

>There is always a bit of tension here where the initiative should be. The initiative for the report generation could be in bnd but also in Gradle. The advantage of bnd is that even in eclipse your reports are generated but the disadvantage is that this costs CPU cycles.

but maybe you're right, this task is not necessary for the bundle to work and more flexible from Gradle. This will result in less of code in bnd, just two commands, report extract and report generate (just to give access to the Transform class, don't know if there is a built-in xslt functionality in Gradle).

The only thing I have done with Gradle is to run `./gradlew`, so : 

* Can we add the generated files to the jar from gradle?
* Can we declare plugins and run the **extract** command from Gradle?
* Does this extra work could be done in build.gradle?

In this case the PostBuild plugin is not necessary as well as the instruction. Also, the RepoterPlugin in bndlib service.reporter package leads to private reference warning (Tag class) can we move this interface to the reporter project or it needs to be in bndlib?

**Comment by pkriens** [comment]
I like the PostBuild service for other things so let's keep it :-)

I think @bjhargrave needs to chime in. Currently we have a number of projects that need bndlib + others. I already created an project to have them all so I can test things better. However, I think we now do not have a single place for the full distribution.

**Comment by cdecode** [comment]
I created a PR for this (#2148). 
In addition, I can create a ReportGenerator plugin which can take a file in the Jar and add it to the report. 

The plugin could support different types of file (XML, Json, Properties, Manifest...). Plugins develop in the PR  will be still useful because they do things that cannot be done with XSLT (localization, search files in the jar, ...) but they could be simplified with this plugin and XSLT for default values for example.

I think we should keep the instruction for the build process, in this way Gradle and bnd still build the same jar. 

For extra stuff, such as documentation, a Gradle plugin could be added to BND providing a new task such as `gendoc` which could generate documentation for workspace, multi-project and bundle on the file system. Then a project like Enroute can provide templates for several project types (api, provider, command, ...) 

What do think ?

**Comment by cdecode** [comment]
I closed the PR #2148 and create a new one #2169 leaving aside the transformation feature. It did not add much (transformation libraries are easily accessible).

So, actually the implementation of the report generation works from command line and as a PostBuild plugin but does not cover the use case that leads me to this feature. I also need the metadata of the bnd workspace structure (to generate a jekyll website for example).  

The desired output would be:

```
cnf/cache/metadata/workspace.xml  #Contains all the project reports and other metadata.
project1/generated/metadata/project.xml #Constains all bundle reports and other metadata.
project1/generated/metadata/org.project1.xml #bundle report
project2/generated/metadata/project.xml #Constains all bundle reports and other metadata.
project2/generated/metadata/org.project.api.xml #bundle report
project2/generated/metadata/org.project.provider.xml #bundle report
```
Actually I generate only the bundle reports, their contents are configured with plugins, can be generated for a specific language, imports any property, xml, json, manifest file coming from the Jar or the file system and includes arbitrary properties defined in the instruction.

My questions are:

1. Do you have a requirement to generate reports from a `PostBuild` plugin ? Or can I still provide configuration for this feature with bnd instructions and plugins but trigger the report generation only from a gradle task on the root project which will generate all this files in one go.

   The problem with the `PostBuild` plugin is that `project.xml` and `workspace.xml` will have to be generated after each bundle build (not really efficient). Note that we can make both if the `PostBuild` is important and generate workspace and project metadata only from gradle.

2. As you advised me, I do the report in `XML` but `XSLT` is really not appropriate to generate user readme file because they will often need to edit the file per project. User not happy with an XML file will have to transform report into another format (jekyll works with json for example), this conversion could be better handled inside the plugin. I propose to generate the report in an intermediate structure as `DTO` or `Map` and allow to configure the desired output `JSON` or `XML` (Collection handling will be better).  what do you think ?

**Comment by pkriens** [comment]
1) You can initiate a task from gradle only and then use the bnd instructions per project/workspace. I agree that it is not necessary to do this on each build inside eclipse, a gradle command makes sense.

2) You my relation to XML is ambivalent. Making DTOs makes sense and then you can generate XML and JSON output trivially. That said, I think you underestimate XML/XSLT. Although it is more to learn it is amazingly powerful and can do things that are more difficult in Jekyll/JSON. It is one of the technologies that lost because its alternatives were simpler and often good enough. 

So I would appreciate a flag to switch at least. It should be easy to make a general codec from DTO to XML by placing all content in the text element and not attributes. (We an make this a standard feature on the Tag class.)

**Comment by cdecode** [comment]
I have updated the PR #2169. The report is now generated with DTOs and you can serialize to json or xml (the Tag class was modified to add DTO contents). It works, but in order to tune some configuration/instructions I need to know how to integrate this feature to make it useful. For my use case a gradle task that export the metadata, either for the workspace, projects or bundles should be enough, but maybe there is a plugin system in bnd, like the Exporter plugin for bndrun files, which is already integrated with bndtools and gradle? Something that could be triggered by a task in gradle or as a contextual menu/button in bndtools that would allow to trigger some bnd actions...  in fact a plugin for occasional actions ?

**Comment by cdecode** [comment]
To be more specific, what is the Actionable plugin, it seems to be very generic but only used for repositories in bnd and bndtools ? And what are the Action and NamedAction? Not used in gradle and bndtools, the command line is able to only show a list of actions but cannot execute them.

**Comment by pkriens** [comment]
I think Act* is going to be deprecated in 4.0. This was once a good idea.

I am waiting for @bjhargrave to chime in here since he knows everything about Gradle.

**Comment by cdecode** [comment]
I have updated the PR #2169. This works from the bnd command line, I think we can do the maven, gradle or bndtools integration in another step, the PR is already a little big.

**Comment by cdecode** [comment]
You can have a look at this repo [https://github.com/cdecode/org.cdecode.docdemo](https://github.com/cdecode/org.cdecode.docdemo) and try to add project, change settings, ... to see the plugin in action.

**Comment by pkriens** [comment]
@bjhargrave Can you take a look at the Gradle issues/questions?

**Comment by cdecode** [comment]
@bjhargrave @pkriens the PR #2169 is not assigned but it can be reviewed now

**Comment by bjhargrave** [comment]
I see it failed the windows CI build. Can you investigate and fix?

**Comment by cdecode** [comment]
I started to use this plugin on several projects, now I would like to develop another extractor plugin that can look for examples source code in my project in order to illustrate packages use in my documentation (this will allow to sync my documentation with what my api offers in my code). But, I don't know if you want such plugins in the bnd code base ? If not, do you know a better project for them ?

Note that there is already a manifest, a metatype and a ds plugin that could be moved too.

**Comment by cdecode** [comment]
I added the reporter feature to the gradle plugin. Note that I have no skills with gradle, but it's few lines of code and maybe this will help @bjhargrave to give more targeted advice.



Lists the documents that can be generated at the workspace scope *(with -report.bundle: metadata.json in biz.aQute.bnd.reporter/bnd.bnd file)*:
```
$ ./gradlew :listReport
:listReport
/home/cde/repo/bnd/biz.aQute.bnd.reporter/metadata.json
```

And then to generate the documents that match the glob expression:
```
$ ./gradlew :report -Pglob="*.json" --info
:report
generate report /home/cde/repo/bnd/biz.aQute.bnd.reporter/metadata.json
```

**Comment by cdecode** [comment]
Do you have an estimation of time that will be necessary to have this feature into bnd (week, month, year)? In my company we would like to used it in several projects but before I would like to know whether or not it is worthwhile to spend time to release this in another way.

**Comment by cdelg** [comment]
Scheduled PR for this issue:

- [ ]  Modify the Tag class to accept DTO object.
- [ ]  Add the report generation APIs to the bndlib project.
- [ ]  Add the report generation implementation in a separate project.
- [ ]  Add the report generation tasks in the Gradle plugin.
- [ ]  Add the report generation commands to the Bnd command line tool.

**Comment by pkriens** [comment]
I am assigned to this issue but not sure what to do?

**Comment by cdelg** [comment]
The previous comment lists the scheduled PR,  the current PR is #2566 and will be reviewed by @bjhargrave.  I think this issue could be closed when all the checkboxes will be validated.
