### ISSUE TITLE
Can not subst and replace square brackets "[" and "]" in deps list

### ISSUE THREAD

**Issue by soberich** [bndtools/bnd#2296]
Hi,
I have to filter gradle `project.sourceSets.main.runtimeClasspath.files` property (kotlin-dsl if matters)
becouse after some magic the receiving list has a form `"[C:// .... many many entries like *.jar here ..... .jar]`
so it looks like an `Array` which was `toString()` becouse of the brackets on the corners.
So, after finding out that I do not receive the very last dependency to my wab if it satisfies filtering (it is a jar = ending with `*.jar` or `*.jar$`) I started tring to "unwrap" the Array from brackets, BUT not of replacing ir substitution macroses work the way, I beleive, they should. 
Of course, even if I iterate through the wholу list I got the same result (plus `subst` says it can have only 16 args) , but for the simplicity I just explicitely took the last one. But it still does not work. 
I have trieв many regexps, even simple explicit `\\]` instead listed below. Still same result.

```
deps: ${project.sourceSets.main.runtimeClasspath.files}
#lastDep: {subst;{last;{deps}};(^\\[)|(\\]\$)}   does not work
#lastDep: {replace;{last;{deps}};\\]; }             does not work
lastDep: ${substring;${last;${deps}};0;-1}     only this onу works!
-wablib: ${format;%s,;${filter;${deps},${lastDep};.*\.jar$}}
```

Tool: Bnd-4.0.0.201802022314-SNAPSHOT

**Comment by bjhargrave** [comment]
Can you please provide a small github repo which demonstrates the problem? Then we can investigate. Thanks.

**Comment by soberich** [comment]
Hi,

Here is the repo https://github.com/soberich/bnd_issue2296

**Comment by bjhargrave** [comment]
OK, there are a couple of issues here.

subst: There is a bug which requires 3 arguments instead of 2 which means you must specify the replacement string. And since you want an empty replacement string, you need to specify a 4th argument. So `${subst;${last;${deps}};(^\\[)|(\\]\$);;10000}` will work as desired.

I will make a PR to fix the bug with requiring 3 arguments.

replace: This currently requires your to specify the replacement value and you did not. Since you want an empty replacement string, you need to specify a 4th argument. So `${replace;${last;${deps}};\\];;,}` will work as desired.

I will update the replace macro to allow the replacement string to be omitted and default to the empty string.

**Comment by soberich** [comment]
Hi, Thanks for your help.
I was actually relying on examples [here](http://bnd.bndtools.org/macros/subst.html)
`${subst;foo.bar;.bar}       =>  foo`
as you see there is no `count` which, if so, I considered optional.

**Comment by bjhargrave** [comment]
> as you see there is no count which, if so, I considered optional.

It is optional. The example on the mentioned link is valid since it specifies a non-empty replacement string.

You wanted to specify an empty replacement string. But the way the macro is parsed means that the ending `;}` is ignored as if no replacement string is specified which was an error. So you has to use a count to allow for an empty replacement string `;;10000}`.
