### ISSUE TITLE
Resolving files at Gradle configuration phase

### ISSUE THREAD

**Issue by pun-ky** [bndtools/bnd#2300]
Hi!

https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndBuilderPlugin.groovy#L89

I am not sure if resolving this detached configuration is a good idea, because it is being done always regardless the type of task being executed (Gradle file configurations resolution is most often being done at execution phase). This noticeable decreases build performance and I am curious about the reason what is a purpose of that resolution. As I see, it is mostly or always not finding any files when I am using the plugin `biz.aQute.bnd.builder` to just build OSGi bundles. Maybe it would be good if there will be a switch to disable that resolution by default to boost the build speed?

**Comment by bjhargrave** [comment]
That is not executed at configuration time. It is a closure for [defaultDependencies](https://docs.gradle.org/4.5.1/dsl/org.gradle.api.artifacts.Configuration.html#org.gradle.api.artifacts.Configuration:defaultDependencies(org.gradle.api.Action)) which is evaluated when the configuration first participates in dependency resolution and has no defined dependencies. 

The baseline configuration is to hold the bundle to baseline against. You can specify a dependency rather than letting the defaultDependencies closure execute. You can also not use the baseline task. But if you do use the baseline task, it must know what bundle to use as the baseline.

**Comment by pun-ky** [comment]
I am aware that bnd plugins offer more than just processing OSGi annotations and generating proper bundle manifest, but I want to do only that. What plugin I need to apply and how to avoid that default dependency resolving? I don't get it / that baselining... 😀

**Comment by bjhargrave** [comment]
Perhaps you just then need to modify your jar task to add the BundleTaskConvention? See https://github.com/bndtools/bnd/blob/4d0201012739b859aadb2d3529116b646ff1978f/biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndBuilderPlugin.groovy#L48-L58

**Comment by bjhargrave** [comment]
> I don't get it / that baselining...

Also, if you never execute the `baseline` task, I don't see how it would get in your way. The `baseline` task is not connected to the other tasks by default. You would need to add it yourself to the task graph.

**Comment by pun-ky** [comment]
Ok I will try with it. 😉

**Comment by pun-ky** [comment]
@bjhargrave thanks, works like a charm
