### ISSUE TITLE
Bnd launch fails on first use of the day

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#2340]
I have noticed that when I sit down to my workspace in the morning to start work, trying to launch the target platform fails with the following error message:
![launcher error](https://user-images.githubusercontent.com/7224087/37006957-cfdf179a-212a-11e8-8b36-aa5bd55a6316.png)
Whether I click "Yes" or "No", Eclipse takes me to the Run Configurations dialog.

This keeps happening every time I try and launch, until I manually refresh the Bnd repository or restart Eclipse. Once reindexed and/or restarted it seems to go back to normal.

Platform is Windows 10/Eclipse Oxygen (release 2)/Bndtools HEAD.

I have observed the same behaviour on my home laptop (also Windows 10/Oxygen/Bndtools HEAD).

**Comment by bjhargrave** [comment]
Perhaps this issue would be more appropriate in the https://github.com/bndtools/bndtools repo? I know is can be a bit confusing, but the bnd repo is for the underlying Bnd code and the maven and gradle plugins. The Bndtools repo is for the Eclipse plugins which integrate Bnd into the Eclipse environment. Your issue seems to be more about the latter.

**Comment by kriegfrj** [comment]
Sorry, you're right - this was inattentiveness, pure-and-simple. I'll close this issue and re-raise it on the bndtools repo.
