### ISSUE TITLE
BndPomRepository.getRoot() returns wrong value

### ISSUE THREAD

**Issue by mnlipp** [bndtools/bnd#2372]
From its usage in bndtools (`bndtools.central.Central.refreshPlugins()`), one can deduce that `Refreshable.getRoot()` is supposed to return the common root of all refreshed resources (which, in turn, is used by bndtools to refresh the classpath container).

`MavenBndRepository.getRoot()` (3.5.0) returns the root of the local maven repository, which matches this requirement.

`BndPomRepository.getRoot()` returns "`repoImpl.getLocation()`" which points to the XML file used as cache index. Therefore, the bnd(tools) classpath container is not properly refreshed after an update of a BndPomRepository.

**Comment by bjhargrave** [comment]
`BndPomRepository.getRoot` can be changed to return `localRepo` (like MavenBndRepository) but then it will not return the xml file since the localRepo is likely disjoint from the location of the xml file. localRepo defaults to `~/.m2/repository` while the xml defaults to a file in `cnf/cache`. 

Furthermore, the code in Bndtools uses getRoot to ask the Eclipse workspace to refresh resource in the workspace. If the files are in `~/.m2/repository` then they are not in the Eclipse workspace, so refreshing them does nothing.

So I am not sure how changing the result of `BndPomRepository.getRoot` to point to `~/.m2/repository` will change anything in Eclipse.

**Comment by mnlipp** [comment]
Tricky. I had thought that I had found out why my bnd class container is not being updated when the repository changes. But you have a point there, the repository is not part of the workspace. I'll keep looking.
