### ISSUE TITLE
Feature: SubsystemExporter for bnd-export-maven-plugin

### ISSUE THREAD

**Issue by JohneDoe** [bndtools/bnd#2389]
it would be great if bnd-export-maven-plugin can handle the SubsystemExporter -Types

osgi.subsystem.application
osgi.subsystem.feature
osgi.subsystem.composite

**Comment by bjhargrave** [comment]
I did a bit of cleanup in the biz.aQute.bnd.exporters project which holds a SubsystemExporter. This class is not yet finished or tested. After that, it can be used with the maven exporter plugin (and some configuration) to export esa. But someone needs to help finish the exporter.

**Comment by stbischof** [comment]
Thank you fore the cleanup!!

It works with this configuration:

pom.xml
```
<plugin>
	<groupId>biz.aQute.bnd</groupId>
	<artifactId>bnd-export-maven-plugin</artifactId>
	<configuration>
		<exporter>**osgi.subsystem.application**</exporter>
		<resolve>true</resolve>
		<failOnChanges>true</failOnChanges>
		<bndruns>
			<bndrun>application.bndrun</bndrun>
		</bndruns>
	</configuration>
</plugin>
```

bndrun file
```
-plugin.subsystem=aQute.bnd.exporter.subsystem.SubsystemExporter;\
	path:=/home/bischofs/.m2/repository/biz/aQute/bnd/biz.aQute.bnd.exporters/4.0.0-SNAPSHOT/biz.aQute.bnd.exporters-4.0.0-SNAPSHOT.jar
```

i think it would be nice if the -plugin property (and path do plugin) in bndrun file isnt neccesary
- add aQute.bnd.exporter to maven-exporter classpath
- add the aQute.bnd.exporter.subsystem.SubsystemExporter by default to the BndRun


ExportMojo in maven exporter plugin
```
Bndrun run = Bndrun.createBndrun(null, runFile)
run.addBasicPlugin(new SubsystemExporter());
```


**what do you think what would be a better way?**

**Comment by bjhargrave** [comment]
Instead of the `-pluginpath` (which is obviously unsuitable since it references a local file), try adding the exporter jar as a dependency for the plugin. Something like:

```
<plugin>
	<groupId>biz.aQute.bnd</groupId>
	<artifactId>bnd-export-maven-plugin</artifactId>
	<dependencies>
            <dependency>
         	<groupId>biz.aQute.bnd</groupId>
	        <artifactId>biz.aQute.bnd.exporters</artifactId>
            </dependency>
        <dependencies>
</plugin>
```
 Hopefully this should put the subsystem exporter plugin class on the classpath of the exporter maven plugin.

You will still need to put the `-plugin` property in your bndrun files to "install" the plugin so that Bnd can find it.

I don't think we want to make biz.aQute.bnd.exporters part of the defaults. Currently I don't think the subsystem exporter is complete nor tested. We need someone to work on completing this (via a PR). See https://github.com/apache/aries/tree/trunk/esa-maven-plugin for an older, but more functionally complete ESA builder that can be used as inspiration to complete the subsystem exporter in Bnd.

**Comment by stbischof** [comment]
Hi,

this put the subsystem exporter plugin class on the classpath of the exporter maven plugin!
That is really nice. so there is absolutly no need to set the exporter by default.

If I'm a bit more familiar with bnd and OSGi I may try to create ab PR to improve the subsystem functionality. 

At the moment I stuck while importing the bnd project into eclipse ;-)

**Comment by stbischof** [comment]
Hi,

i cleaned my local m2 Repository
now i got.


```
[ERROR] Failed to execute goal biz.aQute.bnd:bnd-export-maven-plugin:4.0.0-SNAPSHOT:export (default) on project _assembly: Execution default of goal biz.aQute.bnd:bnd-export-maven-plugin:4.0.0-SNAPSHOT:export failed: Plugin biz.aQute.bnd:bnd-export-maven-plugin:4.0.0-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact biz.aQute.bnd:biz.aQute.bnd.exporters:jar:4.0.0-SNAPSHOT in bnd.master (https://bndtools.ci.cloudbees.com/job/bnd.master/lastSuccessfulBuild/artifact/dist/bundles) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal biz.aQute.bnd:bnd-export-maven-plugin:4.0.0-SNAPSHOT:export (default) on project _assembly: Execution default of goal biz.aQute.bnd:bnd-export-maven-plugin:4.0.0-SNAPSHOT:export failed: Plugin biz.aQute.bnd:bnd-export-maven-plugin:4.0.0-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact biz.aQute.bnd:biz.aQute.bnd.exporters:jar:4.0.0-SNAPSHOT in bnd.master (https://bndtools.ci.cloudbees.com/job/bnd.master/lastSuccessfulBuild/artifact/dist/bundles)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
```

I also couldn't find it here
https://bndtools.ci.cloudbees.com/job/bnd.master/lastSuccessfulBuild/artifact/dist/bundles/biz/aQute/bnd/

**Comment by bjhargrave** [comment]
You need to rebuild that project locally. It is not built as part of the
build since it is incomplete.
-- 
BJ

**Comment by stbischof** [comment]
Hi,

if somebody has some ideas, please tell me

work in progress here:
https://github.com/bipolis/bnd

**Comment by bjhargrave** [comment]
> BJ please tell me if i'm on the wrong way.

I don't have anything to comment on (like a PR).

Some notes:

Don't modify Domain for this. If you need special support, put it in the packages in the exporter bundle. Basically, all the changes should be in the exporter bundle unless we really need to change core bndlib code. You can put ContainerType in the exporter package and subclass Domain to add whatever additional support you need.

Don't know where `.bar`/bundlearchiv come from. That does not seem to be part of the subsystems spec.

**Comment by stbischof** [comment]
Hello,

thank you for your answer. 

*.bar/bundlearchiv is from felix.
more Information:
https://github.com/apache/felix/commit/bd389e28802368095278369df37581e637996c71
 I will remove if before PR.

I put containertype it inside the bndlib because i want to index, resolve Subsystems with bnd. Putting Subsystems inside of Subsystems is also necessary. I'm not sure if i could do this from only from exporterPlugin.
i will try.

**Comment by stbischof** [comment]
Is the Exporter the right way?

-includeresource:   \
	@jar/bundlle1.jar, \
	@jar/subsystem1.eas

may  solve the Problem better.
What do you think?

**Comment by bjhargrave** [comment]
@stbischof Do you still plan to make a PR for this?

**Comment by stbischof** [comment]
Hi,

**I do not have enough time for that at the moment!**
There are only 2 commits (https://github.com/bipolis/bnd/commits/master)

But I think that a good tooling inside bndtools very important for the acceptance of subsystems.

On the other hand side I am waiting a bit because I'm not sure what happened with "OSGI-Features(RFP 188)"

**Comment by bjhargrave** [comment]
Fixed by https://github.com/bndtools/bnd/pull/2530
