### ISSUE TITLE
Bndlib is generating duplicated Require-Capability for osgi.extender=osgi.component

### ISSUE THREAD

**Issue by cvgaviao** [bndtools/bnd#2545]
I'm upgrading my project to R7. I've changed the osgi.core, osgi.annotation and osgi.cmpn dependencies to version 7.0.0 and started to play with some annotations DS 1.4.
 
As I use maven-bundle-plugin I needed to add a dependency to it in order to use bndlib 4.0.0 and also tried with the latest 4.1.0-SNAPSHOT.
With both versions I've identified an issue where two Require-Capability declarations are being created for DS: 

`
Require-Capability: osgi.extender;filter:="(&(osgi.extender=osgi.component)(version>=1.3.0)(!(version>=2.0.0)))",osgi.service;filter:="(objectClass=org.osgi.service.component.ComponentFactory)";effective:=active,osgi.extender;filter:="(&(osgi.extender=osgi.component)(&(version>=1.4.0)(!(version>=2.0.0))))",osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"`

**Comment by bjhargrave** [comment]
We don't develop maven-bundle-plugin, so it is unclear what it may be adding and what bndlib may be adding. Can you make a test case which does not require maven-bundle-plugin?

**Comment by cvgaviao** [comment]
@bjhargrave, what I was able to understand from m-b-p code it delegates all manifest generation to bndlib.

**Comment by bjhargrave** [comment]
OK, but we would still need a small example to demonstrate the problem so it can be investigated. Thanks.

**Comment by cvgaviao** [comment]
@bjhargrave, I've created a small project using bndlib-4.0.0.  In order to use 4.1.0-SNAPSHOT you would need to modify and build m-b-p from source since it need a class that was removed from bndlib.
[TestingBND.zip](https://github.com/bndtools/bnd/files/2250486/TestingBND.zip)

I was not able to find anything in m-b-p code that would be responsible for such duplication.
Let me know If you need anything more... ;)

**Comment by bjhargrave** [comment]
I took the source code out  of you zip and created a unit test with it in bndlib.test project. It generated the proper Require-Capability.

`osgi.extender;filter:="(&(osgi.extender=osgi.component)(&(version>=1.4.0)(!(version>=2.0.0))))",osgi.implementation;filter:="(&(osgi.implementation=osgi.cm)(&(version>=1.6.0)(!(version>=2.0.0))))",osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
`

**Comment by cvgaviao** [comment]
Well, I have to confess that I got a bit lost with your results... :D

I will dig a bit more in the m-b-p code, but meanwhile seems the best approach is to keep with bndlib 3.5 and let the cool new DS 1.4 annotations for another time...

**Comment by bjhargrave** [comment]
I tried to run `mvn package` on your zip contents and it fails. So I cannot even build the zip contents.

See https://github.com/bjhargrave/bnd/commit/84f745430186024719a069fb5d2c8cbd5cc1b615 for my test case which shows only a single osgi.extender requirement.

**Comment by bjhargrave** [comment]
> a class that was removed from bndlib (aQute.lib.spring.SpringXMLType).

This is a mistake. I will make a PR to add this back to bndlib.

**Comment by bjhargrave** [comment]
No. The pom has `<Include-Resource>{maven-dependencies},{maven-resources},META-INF/LICENSE=LICENSE.txt</Include-Resource>`. So it is the Bnd instructions that require LICENSE.txt. You made a bad zip file. Perhaps you can try again but make sure that the unzipped file can be build.


Actually, it is much better to make a small github repo instead of a zip file.

**Comment by bjhargrave** [comment]
I removed `,META-INF/LICENSE=LICENSE.txt` from the pom and I can build and see the manifest contains the 2 requirements for osgi.component.

**Comment by cvgaviao** [comment]
Wow, you are right !  I copied that plugin definition from my main project and not have repaired in that <Include-Resource>. Sorry. 
The strange is that inside Eclipse (with m2e) I have run it without any complain...

**Comment by bjhargrave** [comment]
I have converted the test project over to use bnd-maven-plugin and can see the problem. So I will debug further.

**Comment by bjhargrave** [comment]
OK, I think I know what the issue is. The DS annotation processing code in bndlib generates the 1.3.0 requirement (since 1.3.0 is the default minimum version now.) 

But since you are using osgi.cmpn-7.0.0, it has the Component annotation class meta-annotated with `@RequireServiceComponentRuntime`and processing that generates the 1.4.0 requirement.

**Comment by cvgaviao** [comment]
Wow, good to know that you have discovered where the issue is. I was almost getting crazy while digging into the m-b-p code :D 
thanks for your time !!!

But unfortunately, I can't come back to osgi.cmpn-6.0.0, just because I started to update my project to use Converter, Logging and Configurator from R7.

**Comment by bjhargrave** [comment]
I have a failing test case at https://github.com/bjhargrave/bnd/tree/issues/2545. But I wont be able to work on it for at least a week as I am on holiday now.

**Comment by kwin** [comment]
This is not possible for `org.osgi.service.component.annotations.ComponentPropertyType`. This annotation type is only defined with DS 1.4 but does not have an actual runtime dependency to DS 1.4. Therefore I would like to use component property types as annotations and I only expect the accordingly named service properties be set accordingly (i.e. the method signatures are still 100% DS 1.3 compliant!). How can I express this?

**Comment by bjhargrave** [comment]
So, you need to use the ComponentPropertyType annotation and also the 1.3 Component annotation since the 1.4 Component annotation will cause a requirement for SCR 1.4. So perhaps you can set your `-buildpath' to have `org.osgi.service.component.annotations;version=[1.3,1.4), org.osgi.service.component.annotations;version=1.4` This will put the 1.3 version ahead of the 1.4 version of Component and will also expose ComponentPropertyType. 

If that does not work for you, you may need to craft your own jar with just ComponentPropertyType to add to your buildpath with component.annotations 1.3.

**Comment by timothyjward** [comment]
As you can see from the suggested solutions, this is a bit of an odd requirement. You want to use DS 1.4 features, but not use DS 1.4. Life will be much easier for you if you just use DS 1.4.

Other options include building the Component Property types in a different maven project (using DS 1.4) and then applying them to your component build project which uses DS 1.3 annotations. 

Note that you may still end up requiring DS 1.4 if you do things like accepting a marker annotation into your activate method (which is only officially supported as of DS 1.4)

**Comment by kwin** [comment]
I am still a bit confused, is the maximum DS version derived from the DS package `org.osgi.service.component` or from the DS annotation package ``org.osgi.service.component.annotation`. For me it would make sense, to only depend on the former (if it exists), although not all bundles relying on DS require an explicit dependency towards `org.osgi.service.component`, but at least if it is there, it gives the correct maximum version IMHO.

**Comment by bjhargrave** [comment]
See https://github.com/bndtools/bnd/blob/e9f87d0544ccee9998966561b8883797045fe82e/biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotations.java#L179-L189

If the component needs at least 1.3 then a check is made to see if the `Component` annotation is annotated with `RequireServiceComponentRuntime`. If it is, then it is left to that annotation to set the extender requirement. Otherwise the extender requirement is set to 1.3.

If the component does not need at least 1.3, then no extender requirement is set since the DS 1.2 spec predates the extender requirement.
