### ISSUE TITLE
Support release with aQute.bnd.repository.p2.provider.P2Repository

### ISSUE THREAD

**Issue by eliasvasylenko** [bndtools/bnd#2592]
It would be nice to have support for releasing to p2 repos. Releasing a set of plugin artifacts to a standard layout p2 repo probably isn't too complicated, but for many use-cases this might be pretty useless without also having some ability to publish features. Unfortunately publication of features isn't as neatly captured by the usual bnd release model so I'm not sure what it would look like to implement/configure.

**Comment by pkriens** [comment]
The primary problem with P2 is that I've never been able to find a even remotely decent definition for what it is. When I tried to get it a good many years ago I was told that I should use the API and not bother with the data formats. (Which I find not a good idea, the formats are primary, code is second.) For the current P2 repo I've just reverse engineered every repo I found and saw that the diversity (and unnecessary complexity!) of P2 is quite amazing. Maybe a document now exists?

I agree that P2 output is likely to be used for features and not so much consumed in PDE. Features in bnd are captured by the bndrun files, not repositories. Instead of setting a framework you can set a 'distro' that describes the target environment. You can then create a 'feature' with the resolver. 

I think a P2 bndrun exporter would therefore be more logical than release support to a P2 repo. Exporters are now plugins thanks to BJ. See aQute.bnd.service.export.Exporter and aQute.bnd.exporter.subsystem.SubsystemExporter for an implementation. 

If you can do it without dragging megabytes of Eclipse code I think we'd be very interested in a PR!

**Comment by eliasvasylenko** [comment]
Yes I've had the same sort of experience with P2. Very complicated and poorly documented!

You're absolutely right, this maps much better to an export from a bndrun rather than a release to a repository. And perhaps if we're not building on `P2Repository` then we aren't forced to support the same diversity of layouts; the semantics of exporting to a location rather than releasing to an existing repo mean we only really have to support one canonical layout.

I'm not super familiar with P2 but think it should be straightforward enough to reverse-engineer the behaviour of the PDE's `feature.xml` export and do the same thing for a bndrun. Thanks for the tips!

**Comment by bjhargrave** [comment]
Note that should such a solution be created, we could even use it in the bndtools  build to make the bndtools update site rather than the current mess of calling p2 code. So I think it would be very useful if the exporter could generate a zip file in p2 update site format!

**Comment by bjhargrave** [comment]
Please submit a PR if you can!
