### ISSUE TITLE
Error generating Template

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#2657]
```
Error generating project content from template
Error generating project contents from template "Integration Test Project (ESH Way)": Failed to compile template 'bnd.bnd': bnd.bnd 1:50: '/qivicon' came as a complete surprise to me
```

**Comment by timothyjward** [comment]
Which template is it that you’re using? It should give you the name and version of the bundle providing the template from your configured workspace repositories.

**Comment by amitjoy** [comment]
I am using my own template and it worked previously. All of a sudden I tried it out today and it stopped working. I am currently using  4.1.0.DEV-20180926-083125-g2ed90b4.

**Comment by timothyjward** [comment]
I'm probably not the best person to help with a custom template. If it works in 4.0, but not in 4.1 then it could be the change in the properties parser? @pkriens @bjhargrave ?

**Comment by pkriens** [comment]
You will need to provide a bit more context if you want us to help?

**Comment by pkriens** [comment]
I had access to the source code and looked at what the problem was

The bnd.bnd file inside the template was 

          -include  ${build}/qivivicon
          ....

I am not sure what syntax the template processor uses but it looks like it was translating ${build} to an empty string. 

I escaped the $ in ${build} with a backslash and that solved the problem.
          -include  \${build}/qivivicon
          ....

I do not know of any changes in the template code recently that explain this. @njbartlett ?

**Comment by amitjoy** [comment]
The `\` did the trick
