### ISSUE TITLE
bnd-maven-plugin should generate optional imports for optional Maven dependencies

### ISSUE THREAD

**Issue by rombert** [bndtools/bnd#2713]
When a Maven project has [optional dependencies](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html) the `bnd-maven-plugin` will generate `Import-Package` headers without an appending `resolution:=optional`.

In my opinion the Maven optional dependencies and OSGi optional imports have a significant conceptual overlap and it makes sense for bnd to generate optional imports for optional dependencies.

**Comment by rotty3000** [comment]
I was actually thinking about this recently... though personally I would use `Dynamic-ImportPackage` in place of `resolution:=optional` because this one causes start ordering problems.

**Comment by rotty3000** [comment]
Currently the dependencies are flattened into a flat classpath handed to the bnd builder and all such information about the depedency is lost. We'd need to have a mechanism to annotate the classpath entries so we retain it down into the analyzer.

**Comment by timothyjward** [comment]
I would strongly oppose this. Optional dependencies are *hard* and most people get them wrong. Just putting the import as optional doesn't prevent all manner of class loading unpleasantness and the need to put a lot of protective code in place. I see manually adding the `Import-Package: x.y.z;resolution:=optional` as an important part of recognising that you're doing something that is:

* hard
* bad practice

Optional imports are in general a bad thing because they indicate that your bundle is improperly cohesive and coupled to more than it needs to be. If there is a cool thing that you can do with the dependency then package that implementation as a separate bundle with a mandatory dependency, or better yet put the optional bit into a separate service. Don't try to do nasty stuff to cope with or without the package in the same module.

See also [my lightning talk on the subject](https://www.slideshare.net/mfrancis/when-is-optional-really-optional-tim-ward)

**Comment by rotty3000** [comment]
@timothyjward just to be clear, I don't disagree with you in principle.

**Comment by bjhargrave** [comment]
This may also be a case for More Annotations(TM). We could define annotations which could be applied to type use to indicate the reference package should be optionally/dynamically imported. Then it is clear in the code what the developer intends and not some broad convention applied. 

If the developer cannot use the annotations in the code, then there is always the bnd instructions as Tim has stated.

**Comment by bjhargrave** [comment]
This is a bad idea. Actually package dependencies are independent of maven artifact dependency scopes. It is up to the developer to make a clear choice about optionality of package imports.
