### ISSUE TITLE
BndTools firing off multiple downloads for the same bundle simultaneously.

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#2781]
System:
* Windows 10
* jdk 1.8.0_131
* bndtools HEAD (`4.0.0.DEV-20180215-210111-g9a8b134`).

I noticed one time, when my internet connection happened to be unusually slow and a complete rebuild was taking unusually long, that it seemed to be simultaneously downloading multiple copies of the same bundle (see attached image).

![multiple downloads](https://user-images.githubusercontent.com/7224087/36479774-cec3c96c-1759-11e8-999f-44e053ae282a.png)
 
I unchecked "build automatically", which seemed to help a bit, but I was still getting the multiple download issue when BndTools was trying to refresh the workspace repositories in the background.

I'm not sure if it's relevant or if this is a coincidence, but this started to happen after I had re-instated my internet connection after I had been working without an internet connection for a while. Alternatively, perhaps this started happening because a new snapshot version was released.

I think that there should be some kind of locking so that BndTools doesn't initiate a new download for an artifact/bundle if there is already one underway.

**Comment by bjhargrave** [comment]
This problem is hard to solve easily. There is no simple way to solve it in OSGiRepository which is what is shown above. When refreshed, OSGiRepository creates a new OSGiIndex object which asynchronously reloads the index(es). Normally this only happens one at a time which is not an issue.

The real problem is in the interaction with Bndtools. There are code paths via context menus where the OSGiRepository can be refreshed multiple time. The content menu can cause OSGiRepository to refresh itself and then Bndtools helpfully sees that is a Refreshable and refreshes it after the action completes. So now you have 2 asynchronous refresh operations running...

There is no real harm here; just a waste of time and bandwidth.

I am not going to work on this any longer, so someone else is free to have a go at fixing this interaction problem between OSGiRepository and Bndtools.

**Comment by kriegfrj** [comment]
I think that this issue still probably exists in theory, but I haven't seen it in practice for some time. I'm happy for it to be left closed.
