### ISSUE TITLE
[Feature Request] Alphabetical Ordering of Entries

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#2798]
It would always be nicer if we could order the `buildpath` and `testpath` entries alphabetically either using Eclipse Formatter or shortcut keys. We definitely couldn't do it for `runbundles` since it is the order of bundle installation. Such alphabetical ordering could definitely help users to locate bundles pretty easily.

**Comment by bjhargrave** [comment]
This does not seem like a great idea. The ordering in buildpath and testpath matters since they are a flat classpath. Earlier entries can shadow items from later entries. This is why the `=split-package` Bnd directive is useful/necessary. Simply reordering entries based upon some sorting can mess things up. I think it would be a bad idea to add such a feature to Bndtools.

**Comment by pkriens** [comment]
I think a feature to format and then sort them, it should clearly not happen automatically

**Comment by bjhargrave** [comment]
I don't think anyone suggested automatic sorting.

But such a feature would need to detect any split packages across the path and warn before sorting as the sorting can change things in undesired ways.
