### ISSUE TITLE
Improve the Jar File Viewer when using Java Platform's  packages  

### ISSUE THREAD

**Issue by cdelg** [bndtools/bnd#2799]
I use the `Jar File Viewer -> Print -> Import-Package` to check if my bundle dependencies are good. 
If I see an import package without a version, this indicates that one of my dependency is not a bundle or is wrong. 

Actually, I cannot quickly discriminate  such errors with packages that come with the Java Platform and which have no version.    

Is it possible to show a default version or a string such as "framework-provided" for those packages (eg; `java.*`, `javax.*`) in this viewer?

**Comment by bjhargrave** [comment]
The Jar Viewer looks at a jar file's manifest in isolation. Not in any resolved state. So it cannot know where an imported package may come from (such as a contract or the JRE). 

While the manifest can detail which contracts a bundle may require. the requirement of a contract does not list the packages in the contract. That is listed in the `uses` directive of the contract provider. And since the jar's manifest is viewed in isolation, the viewer does not know the packages in the required contract.

So you cannot modify the jar viewer as suggested since the viewer displays the jar's manifest information in isolation.
