### ISSUE TITLE
Warning "Unable to determine whether the annotation .. applied to type ... is a component property type as it is not on the project build path." for dependencies

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#2905]
With bnd 4.1 (used together with maven-bundle-plugin) I see the following warnings when building https://github.com/Adobe-Consulting-Services/acs-aem-commons/:

```
[WARNING] Manifest com.adobe.acs:acs-aem-commons-bundle:bundle:3.19.1-SNAPSHOT : Unable to determine whether the annotation org.apache.felix.scr.annotations.Component applied to type com.day.cq.wcm.core.contentfinder.ContentFinderListInfoProviderHelper is a component property type as it is not on the project build path. If this annotation is a component property type then it must be present on the build path in order to be processed
[WARNING] Manifest com.adobe.acs:acs-aem-commons-bundle:bundle:3.19.1-SNAPSHOT : Unable to determine whether the annotation org.apache.felix.scr.annotations.Reference applied to type com.day.cq.wcm.core.contentfinder.ContentFinderListInfoProviderHelper is a component property type as it is not on the project build path. If this annotation is a component property type then it must be present on the build path in order to be processed
[WARNING] Manifest com.adobe.acs:acs-aem-commons-bundle:bundle:3.19.1-SNAPSHOT : Unable to determine whether the annotation org.apache.felix.scr.annotations.Reference applied to type com.day.cq.commons.servlets.AbstractPredicateServlet is a component property type as it is not on the project build path. If this annotation is a component property type then it must be present on the build path in order to be processed
[WARNING] Manifest com.adobe.acs:acs-aem-commons-bundle:bundle:3.19.1-SNAPSHOT : Unable to determine whether the annotation org.apache.felix.scr.annotations.Component applied to type com.day.cq.commons.servlets.AbstractPredicateServlet is a component property type as it is not on the project build path. If this annotation is a component property type then it must be present on the build path in order to be processed
[WARNING] Manifest com.adobe.acs:acs-aem-commons-bundle:bundle:3.19.1-SNAPSHOT : Unable to determine whether the annotation org.apache.felix.scr.annotations.Activate applied to type com.adobe.cq.dialogconversion.AbstractDialogRewriteRule is a component property type as it is not on the project build path. If this annotation is a component property type then it must be present on the build path in order to be processed
[WARNING] Manifest com.adobe.acs:acs-aem-commons-bundle:bundle:3.19.1-SNAPSHOT : Unable to determine whether the annotation org.apache.felix.scr.annotations.Component applied to type com.adobe.cq.dialogconversion.AbstractDialogRewriteRule is a component property type as it is not on the project build path. If this annotation is a component property type then it must be present on the build path in order to be processed
[WARNING] Manifest com.adobe.acs:acs-aem-commons-bundle:bundle:3.19.1-SNAPSHOT : Unable to determine whether the annotation org.apache.felix.scr.annotations.Component applied to type com.day.cq.wcm.workflow.process.ActivatePageProcess is a component property type as it is not on the project build path. If this annotation is a component property type then it must be present on the build path in order to be processed
[WARNING] Manifest com.adobe.acs:acs-aem-commons-bundle:bundle:3.19.1-SNAPSHOT : Unable to determine whether the annotation org.apache.felix.scr.annotations.Service applied to type com.day.cq.wcm.workflow.process.ActivatePageProcess is a component property type as it is not on the project build path. If this annotation is a component property type then it must be present on the build path in order to be processed
[WARNING] Manifest com.adobe.acs:acs-aem-commons-bundle:bundle:3.19.1-SNAPSHOT : Unable to determine whether the annotation org.apache.felix.scr.annotations.Property applied to type com.day.cq.wcm.workflow.process.ActivatePageProcess is a component property type as it is not on the project build path. If this annotation is a component property type then it must be present on the build path in order to be processed
[WARNING] Manifest com.adobe.acs:acs-aem-commons-bundle:bundle:3.19.1-SNAPSHOT : Unable to determine whether the annotation org.apache.felix.scr.annotations.Reference applied to type com.day.cq.wcm.workflow.process.ReplicatePageProcess is a component property type as it is not on the project build path. If this annotation is a component property type then it must be present on the build path in order to be processed
[WARNING] Manifest com.adobe.acs:acs-aem-commons-bundle:bundle:3.19.1-SNAPSHOT : Unable to determine whether the annotation org.apache.felix.scr.annotations.Component applied to type com.day.cq.wcm.workflow.process.ReplicatePageProcess is a component property type as it is not on the project build path. If this annotation is a component property type then it must be present on the build path in order to be processed
[WARNING] Manifest com.adobe.acs:acs-aem-commons-bundle:bundle:3.19.1-SNAPSHOT : Unable to determine whether the annotation org.apache.felix.scr.annotations.Component applied to type com.day.cq.wcm.workflow.process.DeactivatePageProcess is a component property type as it is not on the project build path. If this annotation is a component property type then it must be present on the build path in order to be processed
[WARNING] Manifest com.adobe.acs:acs-aem-commons-bundle:bundle:3.19.1-SNAPSHOT : Unable to determine whether the annotation org.apache.felix.scr.annotations.Service applied to type com.day.cq.wcm.workflow.process.DeactivatePageProcess is a component property type as it is not on the project build path. If this annotation is a component property type then it must be present on the build path in order to be processed
[WARNING] Manifest com.adobe.acs:acs-aem-commons-bundle:bundle:3.19.1-SNAPSHOT : Unable to determine whether the annotation org.apache.felix.scr.annotations.Property applied to type com.day.cq.wcm.workflow.process.DeactivatePageProcess is a component property type as it is not on the project build path. If this annotation is a component property type then it must be present on the build path in order to be processed
```

The warnings are issued for classes which are dependencies and not classes in the target directory. IMHO those dependencies are not worth to be evaluated for component property types as you never generate metadata for those. Therefore the WARNINGs should IMHO be prevented.

**Comment by timothyjward** [comment]
These warnings are valid, and important information that is being provided to you.

> The warnings are issued for classes which are dependencies and not classes in the target directory. 

In this case the bundle being built is *embedding* classes from other jars/bundles on the class path, as configured [in the bundle pom file](https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/84f76f7faccca34062008ea61499e2dd201c7a90/bundle/pom.xml#L69). If the classes end up in the bundle then they need to be scanned and processed by bnd, regardless of where they came from. You would rightly be upset if bnd ignored the dependencies added by the embedded code!

These embedded classes are annotated with annotations that make them relevant for Declarative Services metadata generation, and so the annotation hierarchy needs to be checked. Unfortunately the annotations themselves are not on the build path (which is what the warning is complaining about). In this case bnd needs the information to do its job properly (i.e. to create the relevant DS metadata for these components.

Therefore this project needs to either:

- Add the necessary annotations to the build path so that bnd can do its job
- Tell bnd not to generate Declarative Services Metadata for the embedded classes

Note that the latter option will result in no Declarative Services XML descriptors being generated for those types, which may, or may not, be a problem for you, depending on whether the bundle being built expects the components it embeds to be used as components.

**Comment by kwin** [comment]
@timothyjward Thanks a lot for your answer, but actually the class `com.day.cq.wcm.core.contentfinder.ContentFinderListInfoProviderHelper` is not embedded in the JAR. Compare with the attached screenshot: 
![screenshot 2019-02-01 at 11 50 38](https://user-images.githubusercontent.com/185025/52118843-b38d5c80-2617-11e9-87e9-753689de9ca8.png)

Still it appears in the WARNING!

**Comment by kwin** [comment]
At least for ActivatePageProcess I found the reason: There is a component in https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/a4ad6c31263588286cb5380a3919675a64707e1c/bundle/src/main/java/com/adobe/acs/commons/workflow/process/impl/ParameterizedActivatePageProcess.java#L38 which derives from it. Can we bring bnd somehow to not evaluate the parent classes for annotations?

**Comment by timothyjward** [comment]
> Can we bring bnd somehow to not evaluate the parent classes for annotations?

This is the default behaviour for bnd, however this project has deliberately enabled scanning of parent classes. https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/84f76f7faccca34062008ea61499e2dd201c7a90/bundle/pom.xml#L79

**Comment by kwin** [comment]
Thanks a lot again, indeed after disabling inheritance all those warning disappeared.

**Comment by marad** [comment]
> Add the necessary annotations to the build path so that bnd can do its job

@timothyjward Hi, how can I add the annotations to the build path? I'm using gradle with `biz.aQute.bnd.workspace` and `biz.aQute.bnd` plugins and I've tried to set my dependencies to `implementation`, `compileOnly` and `runtimeOnly` but my warnings persist.

**Comment by rotty3000** [comment]
@marad IIUC and you are using `biz.aQute.bnd.workspace` then you should not use gradle dependency management but rather bnd's workspace dependency management which would have you:

a) make sure the dependency is referred to by one of the bnd repositories (look in cnf dir for those typically)
b) refer to the dependency from the project's bnd.bnd file on the `-buildpath` instruction

Pointing at the repository in question _might_ make it easier for us to point out the issue.

**Comment by marad** [comment]
@rotty3000 Thanks for such a quick answer!
I'm very new to OSGi and bndtools. I'm learning and trying to piece all the knowledge and tools together.
Maybe it would help to just link the repository: https://github.com/marad/personal-sidecar

I'm building it with `./gradlew build`, but I'm not sure if I should use that or the bnd tool to build the workspace?

**Comment by bjhargrave** [comment]
> I'm very new to OSGi and bndtools.

It would be better to move usage questions to the bndtools-users mail list. See <https://github.com/bndtools/bnd#feedback>.

**Comment by synesty-cr** [comment]
@timothyjward since you added the `AnnotationHeaders.DO_NOT_SCAN` list in 

https://github.com/bndtools/bnd/commit/10e192479bca64244bd5ec62cb18f48dbfa13522#diff-be27a5a501f05ec3c1bc10a14a8bed0592a76cd02407998f98792675cd2b60c5R86

Could you elaborate what intentions made up that _specific_ list? 
In other words: could you imagine other annotation classes which could potentially be added to that list? 

Reason I ask:
I am in the process of cleaning up some `-pedantic=true` warnings and I noticed a lot of warnings like this:

`Unable to determine whether the meta annotation javax.annotation.Nullable applied to type org.aopalliance.intercept.Joinpoint provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed	bnd.bnd	/com.synesty.studio.apiservices	line 1	Bndtools Problem Marker`

A lot of them are referring to annotations in `javax.annotation.*` or `jakarta.xml.bind.annotations`

So since the comment 

https://github.com/bndtools/bnd/commit/10e192479bca64244bd5ec62cb18f48dbfa13522#diff-be27a5a501f05ec3c1bc10a14a8bed0592a76cd02407998f98792675cd2b60c5R76-R77

says

> Annotations to ignore scanning further because they are known to be uninteresting


I wonder if there are other "uninteresting" annotations that might be added.
