### ISSUE TITLE
[Feature Proposal] Create a maven bnd:run plugin

### ISSUE THREAD

**Issue by Sandared** [bndtools/bnd#2959]
Hi,

it would be great if bnd provided a maven plugin that offers a goal similar to the jetty:run goal for Jetty, i.e., a goal that mimics the behavior of pressing the "Run/Debug OSGi" buttons in the "run" tab of a bndrun file in bndTools.

Why:
Right now I'm tied to Eclipse when I want really good OSGi development support, especially when I want the hot reloading of bundles into a running OSGi framework during development time. If there were a Maven plugin as mentioned above, I would be able to have a similar development experience as with bndTools, but on the commandline which would be IDE independent.  I know that some features (jar viewer, repository browsing, etc.) would still be missing, but I think the hot redeployment of bundles would tremendously easen the development of OSGi applications in non-Eclipse IDEs.

Kind regards,
Thomas

**Comment by rotty3000** [comment]
There's a further issue I need to investigate which is de-referencing the artifacts from the current project as opposed to from `.m2`, but the plugin is working as is. Will fix the other issue separately since it affects all the plugins that have use Bndruns for some type of resolver, execution type operation.
