### ISSUE TITLE
Source folders are resolved incorrectly for projects with `biz.aQute.bnd.builder`

### ISSUE THREAD

**Issue by eximius313** [bndtools/bnd#2966]
1) If you import project with `biz.aQute.bnd.builder`: [TestProject.zip](https://github.com/bndtools/bnd/files/2856555/TestProject.zip)
2) Add `Bndtools Project Nature` to it
3) Add any other Bnd OSGi Project (see bug: https://github.com/bndtools/bnd/issues/2961)
4) Result is like that:
![1](https://user-images.githubusercontent.com/5578017/52649298-60a18800-2ee8-11e9-82c1-5b746cfd8457.png)

BUT when you create vanilla Java project:
![2](https://user-images.githubusercontent.com/5578017/52649339-6e570d80-2ee8-11e9-95a1-e2144eea2269.png)

and set source folder to `src/main/java` like this:
![3](https://user-images.githubusercontent.com/5578017/52649365-7e6eed00-2ee8-11e9-926a-89446082441a.png)
![4](https://user-images.githubusercontent.com/5578017/52649372-8333a100-2ee8-11e9-9856-f6a11d9269c1.png)
![5](https://user-images.githubusercontent.com/5578017/52649382-87f85500-2ee8-11e9-8004-84c843124a6e.png)

Create package `com.example` in `src/main/java` and add Activator class to this package and THEN enable project nature:
![6](https://user-images.githubusercontent.com/5578017/52649400-92b2ea00-2ee8-11e9-80b4-c1429f79ac4a.png)
(and add any other Bnd OSGi Project because of bug: https://github.com/bndtools/bnd/issues/2961)

everything is working just fine!
Compare it here:
![image](https://user-images.githubusercontent.com/5578017/52649508-c2fa8880-2ee8-11e9-8793-a8a0acd8115e.png)
![image](https://user-images.githubusercontent.com/5578017/52649562-d3126800-2ee8-11e9-93e5-df6ea1a4b8b9.png)
![image](https://user-images.githubusercontent.com/5578017/52649605-e291b100-2ee8-11e9-9879-149b2514fe21.png)
![image](https://user-images.githubusercontent.com/5578017/52649639-f3dabd80-2ee8-11e9-81d7-7f6e3ffa30e5.png)

I'm not sure which of behaviors is expected, but it should be consistent

**Comment by bjhargrave** [comment]
Bndtools nature is not meant to be use with projects that are not Bnd workspace projects.

**Comment by eximius313** [comment]
@bjhargrave then how Java project can become `Bnd workspace project`?

**Comment by pkriens** [comment]
Just use bndtools in Eclipse and use File/New/Bndtools workspace. This will setup a workspace for you. Then in the bndtools perspective you can create new projects from templates that work perfectly with the Gradle build and in Eclipse. There are some bnd command line commands but doing this work in Eclipse is infinitely more pleasant than doing it from a command line.

If you still want to do this otherwise then do it once and look at the .project and .classpath files in the projects. However, I strongly advise against doing that.

Kind regards,

	Peter Kriens

**Comment by eximius313** [comment]
Here: https://bndtools.org/concepts.html it is said that:

>A workspace is a directory on the file system that has the file cnf/build.bnd

and 

>Other directories in the workspace directory are project directories if they contain a bnd.bnd file

So if I create Java project inside my workspace, then it becomes `Bnd workspace project` after it contain `bnd.bnd file`. But it's the `Add Bndtools Project Nature` which creates this file

@pkriens 
I already have a workspace. I just want to import my existing java project to it

**Comment by pkriens** [comment]
One issue is that you need to create the project in the same directory as the cnf project resides. 

I might be wrong but if you just create a new workspace in bndtools, copy all your Java projects to the same directory as cnf (make sure the name of the project directory is the Bundle-SymbolicName), remove and add an empty bnd.bnd file then I think Bndtools should make it bndtools projects.

Make sure that the setup follows the macros:

	macro		default		maven would be
	================================================
	src		src		src/main/java
	bin		bin		target/classes
	bin_test	bin_test	target/testclasses
	test		test		src/main/test
	target		generated	target
	
You can set those macros in cnf/build.bnd . Notice that these macros must be closely aligned what is specified in .classpath.

To see your setup, create a new project in Bndtools and it would set it up exactly as the macros indicate. In your current state, it might be fastest to create a new project with bndtools and then copy the old project's src code to the new src folder? If you do it once or twice the pattern should become clear.

Hope this helps, kind regards,

	Peter Kriens

**Comment by eximius313** [comment]
Guys - here it is - pure Bndtools project created in pure Bnd workspace (that contains cnf folder):
![1](https://user-images.githubusercontent.com/5578017/52703201-19fe6d00-2f7e-11e9-969d-0d6cd09187c7.png)
![2](https://user-images.githubusercontent.com/5578017/52703214-208ce480-2f7e-11e9-89e2-965994c557a5.png)

Create maven's `src/main/java`:
![3](https://user-images.githubusercontent.com/5578017/52703251-313d5a80-2f7e-11e9-83b2-7ebf3b7f243b.png)
![4](https://user-images.githubusercontent.com/5578017/52703256-36020e80-2f7e-11e9-8898-4cabef9a91e7.png)
![5](https://user-images.githubusercontent.com/5578017/52703260-3ac6c280-2f7e-11e9-8dda-311bdf5cce4d.png)

Although bnd.bnd do not show error:
![6](https://user-images.githubusercontent.com/5578017/52703273-4619ee00-2f7e-11e9-971a-0d71a87b4a08.png)

Jar is strill ampty and packages are NOT managed:
![7](https://user-images.githubusercontent.com/5578017/52703382-837e7b80-2f7e-11e9-89d7-b9ccb96ff042.png)




Clearly bnd has some problems with `src/main/java`, so please reopen this issue

**Comment by pkriens** [comment]
You very likely did not set the src/bin etc macros to the maven values? It looks like you use the defaults which means the src folder for bnd is src, not src/main/java and the output folder is bin.

You can place the following in cnf/ext/maven.bnd to tell bnd to follow the maven layout.

	src: 			src/main/java 
	src.resources: 		src/main/resources 
	bin: 			target/classes 
	testsrc: 		src/test/java 
	testsrc.resources: 	src/test/resources 
	testbin: 		target/test-classes 
	target-dir: 		target 

Anyway, there are several things in your images that indicate that you changed settings in the different files from the defaults. Could you share this workspace on Github so I can see exactly where things go wrong?

Kind regards,

	Peter Kriens

[1]: https://v2archive.enroute.osgi.org/qs/050-start.html

**Comment by eximius313** [comment]
Sure: https://github.com/eximius313/bndtest

**Comment by pkriens** [comment]
I've imported these projects and they worked the first time. I checked if anything was changed in Git but nothing except the jars and class files.

However, this layout is the default. Did this work for you?

**Comment by eximius313** [comment]
Please perform the steps I've described in this issue

**Comment by pkriens** [comment]
Ok
First add the macros as I said:


Any bnd file in cnf/ext is read before build.bnd is read. And build.bnd is read before any project bnd.bnd is read. They inherit properties from each other in that direction. That is, a bnd.bnd file can always override a property in build.bnd or in property from the cnf/ext directory.

NOTICE! This screws up your existing API and impls project because they were created with the old properties. You can override this on a project per project basis but that is begging for problems.

---------------------------------------------------------------------------------------------------------

Create new Bndtools project, we pick the empty project


---------------------------------------------------------------------------------------------------------

Notice that the project is created in the same directory as the cnf project. In this case /Users/aqute/test/bndtest. This is the workspace directory and it differs from the Eclipse workspace.



---------------------------------------------------------------------------------------------------------

Notice that the buildpath is now correct because we have the bnd macros in `cnf/ext/maven.bnd`. The source and output directories are now in the maven 


---------------------------------------------------------------------------------------------------------
The defaults immediately build a bundle in (now) target. Since there are no classes it is empty


---------------------------------------------------------------------------------------------------------

Add a class


---------------------------------------------------------------------------------------------------------
Since we do not set Export-Package nor Private-Package bnd assumes defaults and packages the whole src folder's classes. However, once you set one of those, you're on your own and bnd expects you to set them all. I.e. you no longer get all the src's classes by default.


---------------------------------------------------------------------------------------------------------

In this default model we will need to indicate exports. We need an annotation for that:


---------------------------------------------------------------------------------------------------------
Create a package-info.java file in the pure.bnd package:



---------------------------------------------------------------------------------------------------------
Add the annotation


---------------------------------------------------------------------------------------------------------
Click on the target JAR and the Print tab. You can now see the pure.bnd package is exported.




Kind regards,

	Peter Kriens

**Comment by eximius313** [comment]
@pkriens Thank you so much! You were absolutely right:
If before importng Gradle project I create `cnf/ext/gradle.bnd` file and put these lines:
```
src: src/main/java
src.resources: src/main/resources
bin: target/classes
testsrc: src/test/java
testsrc.resources: src/test/resources
testbin: target/test-classes
target-dir: target
```

Gradle projects are imported by Buildship correctly and are visible for Bndtools (but only after a workarund from this issue: https://github.com/bndtools/bnd/issues/2961).

Unfortunatelly this is still not working for multiproject builds: https://github.com/bndtools/bnd/issues/2962

One more thing worth noting: (maybe it's good to put that in documentation) that we must import Gradle project that is in the filesystem on the same level that `cnf` folder (importing project from different location does not work. Is is a bug?)
