### ISSUE TITLE
[Feature] Let the user decide about project layout during creation of workspace

### ISSUE THREAD

**Issue by eximius313** [bndtools/bnd#2972]
Bndtools workspace works by default with `/src` and `/test` layout.
Both Maven and Gradle uses `/src/main/java` layout, so using Grale/Maven projects is not possible out of the box.
We can manually instruct Bndtools workspace to use such layout by creating `cnf/ext/gradle.bnd` file and puting these lines:
```
src: src/main/java
src.resources: src/main/resources
bin: target/classes
testsrc: src/test/java
testsrc.resources: src/test/resources
testbin: target/test-classes
target-dir: target
```

But currently it is very rare to use vanilla java projects with `/src` and `/test` layout therefore Bndtools should ask the user which layout she/he wants to use diring workspace creation.

Additionally while adding `Bndtools Project nature` plugin should detect different layout and ask the user she/he wants to change it.

**Comment by eximius313** [comment]
It's a feature request. Why it was marked as "stale"? What is missing in my description?

**Comment by gamerson** [comment]
Hey @eximius313  

There is no foul play here :) The committers are laboring out of love on this project, and trying to do the best with limited resources.  So that means we need to keep the issue list down to a manageable level instead of having issues go stale and live in abeyance forever.  

A bot was added to this repo to help identify issues that have gone stale.  The intention was that issues are first marked stale and if "stale" label is removed, this is no longer a candidate for closures.  As I mentioned in my other responses, the fact that you have responded means you are still engaged with these issues and all you simply need to do is "reopen" those issues that are still relevant to you.

Now, if you want to increase the chances of seeing a desired feature or bug fix get implemented, the best way is to try to send a PR.  The committers have a history of coaching new contributors through code reviews.  You can expect a rigorous discussion and the code quality bar is set high.  However, if effort is put in by a contributor, then as much effort will be put in by the committers to help review and guide.

Hope this helps clear things up some and please let us know if you run into blockers while trying to contribute a fix or feature.
