### ISSUE TITLE
IllegalArgumentException for optional/dynamic/reluctant annotated DS

### ISSUE THREAD

**Issue by Sandared** [bndtools/bnd#2993]
Hi,

For bnd 4.1.0, a standard enRoute project setup generated by the "project" archetype and a component with a reference like this:
```java
@Component
public class MyComp {
  @Reference(cardinality=ReferenceCardinality.OPTIONAL, policy=ReferencePolicy.DYNAMIC, policyOption=ReferencePolicyOption.RELUCTANT)
    private ITest atest;
}
```

The command  `mvn -pl app -am  bnd-indexer:index bnd-indexer:index@test-index bnd-resolver:resolve package` then results in an IllegalArgumentException with the message:
Invalid value for Annotation elementValue tag 0 at aQute.bnd.osgi.Clazz.doElementValue(Clazz.java: 1794)

Kind regards,
Thomas

**Comment by bjhargrave** [comment]
That message would indicate a corrupted class file. Since Bnd does not create nor modify class files, I am unsure how it may have become corrupted. The code for class file parsing was completely rewritten for Bnd 4.2. Perhaps you can try this again with the Bnd 4.2 snapshot plugins. They are available from https://bndtools.jfrog.io/bndtools/libs-snapshot.

Otherwise, can you please provide a small github repo which demonstrates the problem? Then we can investigate. Thanks.

**Comment by Sandared** [comment]
It seems it really was a corrupted workspace. A complete restart and the build succeeds with bnd 4.1.0 . With bnd 4.2.0 I now get build errors, but with a sensible error message because of the variable not being volatile.

**Comment by bjhargrave** [comment]
Thanks for the response.
