### ISSUE TITLE
Maven Repositories (Central & Local) stay empty in Repository View

### ISSUE THREAD

**Issue by gibelium** [bndtools/bnd#3028]
First of all this might be a lack of knowledge on my side. So please let me know if my expectation is or I am doing something wrong. I expected both the local and central maven repositories to contain the content (at least OSGi bundles) of my local .m2 folder but the repositories stay empty in the view as well as the local.maven and central.maven files within the cnf folder. My questions therefore are:

- Should the maven repositories show the content of the .m2 directory?
- Do I have to trigger a special task to create the index for the repositories?
- Is the usage of MavenBndRepository the way to go?

I did setup a fresh eclipse installation and at first installed bndtools via the market place and noticed that the Maven Central repository is empty within the Repository view. So I added an entry for the local M2 repository which also stayed empty. "Bndtools Refresh Repositories" as well as restarting eclipse did not help.
Then I installed the latest build version of bndtools via the mentioned update site (https://bndtools.jfrog.io/bndtools/update). 4.2.0 as well as 4.3.0 DEV builds do not fix the problem.

##### Steps to reproduce

1. Setup a fresh eclipse Oxygen or 2018-12
2. Install Bndtools via Marketplace or Update Site with latest CI build (https://bndtools.jfrog.io/bndtools/update)
3. Optionally add local M2 Repository entry to /cnf/build.bnd file
4. See if the maven repositories within the bndtools Repository view or central.maven and/or local.maven files within cnf folder do have any content.

##### Environment

- java version "1.8.0_181"
- bndtools versions:
   - 4.1.0.REL-20181018-142129-g0dea1cb
   - 4.2.0.DEV-20190214-191310-g3b85896
   - 4.3.0.DEV-20190226-232001-g3a46962
- eclipse versions:
   - Oxygen.3a Release (4.7.3a) (Build id: 20180405-1200)
   - 2018-12 (4.10.0) (Build id: 20181214-0600)
- OSX Mojave (10.14.3)

###### Screenshot

<img width="895" alt="bndtools-screenshot" src="https://user-images.githubusercontent.com/728680/53494351-d8051900-3a9d-11e9-94fd-ad4602db1bef.png">

###### zipped build.bnd file

[build.bnd.zip](https://github.com/bndtools/bnd/files/2910507/build.bnd.zip)

**Comment by rotty3000** [comment]
>     * Should the maven repositories show the content of the .m2 directory?

No, they should show the contents of the associated `*.maven` file (FYI the convention is to use the extension `.mvn`).

>     * Do I have to trigger a special task to create the index for the repositories?

No. Simply add GAVs  (one per line) in the form G:A:V to your `.maven` files should trigger the workspace to re-index the associated repo. Therefore any additions should immediately appear in the repo view. Here's an example https://github.com/bndtools/bnd/blob/master/cnf/ext/central.mvn

>     * Is the usage of MavenBndRepository the way to go?

If you are using the bnd workspace model, which it appears you are, then yes MavenBndRepository is the way to go.

**Comment by gibelium** [comment]
Thank very much you for the clarification, Raymond. Bndtools created the .maven files, so I guess it could create the files with the .mvn extension instead.

Where is the difference in contrast to the 'normal' local repository when I need to maintains the repository files on my own? Wouldn't it be a nice functionality - at least from usability perspective - to be able to search maven.central right inside of Bndtools and add selected JARs to the repository view?

Is there a documentation about maven based bnd/Bndtools development including a maven based build environment? I found these slides and the corresponding tutorial code but I am not sure if it's up-to-date:
- https://de.slideshare.net/mfrancis/bndtools-and-maven-a-brave-new-world-n-bartlett-t-ward
- https://github.com/paremus/osgi-community-event2017

Also the documentation about the new style maven repositories is missing/marked with a TODO here:
- https://bndtools.org/repositories.html

**Comment by bjhargrave** [comment]
Your `Local.M2` repo will not display anything since it has no urls to point to the maven repo it represents. For example, `Central` has a link to Maven Central.

For a MavenBndRepository to display contents, it must have URLs to the backing maven repository and it must have an index file (the extension of the index file is just a convention) which lists the specific GAVs which are to be available. The index file is necessary so you don't download the entire maven repository and locally index the contents for OSGi metadata.

Some MavenBndRepositories are for "reading". Like Central. Some are for "writing", like Release and Local. The reading repos must have an index file to specify what can be read. The writing repos don't need an index file since you don't read from them.

I would look at how we use MavenBndRepository in this repo. We use `noupdateOnRelease=true` on the writing repos since we don't want Bnd to attempt to modify a non-existent index file when a bundle is released to the repo.

https://github.com/bndtools/bnd/blob/444a1a118465435b89efacbee9bcb5baeb7aa2ac/cnf/ext/repositories.bnd#L19-L47

**Comment by bjhargrave** [comment]
Closing as there is no bug here.
