### ISSUE TITLE
[Feature] Smarter BndtoolsBuilder to not block test execution longer than necessary

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3032]
As has been pointed out, `BndtoolsBuilder` does an excellent job of automatically ensuring that your entire workspace's dependencies are updated. Usually, this is what you want.

However, what I have discovered while working on recent issues, is that if your workspace has a lot of projects and you are working on a project that is in the dependency hierarchy for many of those projects, this proactive building of the entire workspace can actually be counterproductive and slow you down.

For example, I'm working on enhancing `biz.aQute.junit`, with some tests using Launchpad. Ideally, I want to be able to use a Test-Driven-Development style, which requires iteratively updating the test-code, running the test, then updating the the code, then testing again. However, every time I update the code, nearly the whole workspace gets rebuilt (which takes dozens of seconds), and the test run (which also tries to build the whole workspace before is blocked waiting for the build to finish. This slows down the TDD cycle significantly. Ideally, I'd like to be able to run the test(s) as soon as the test's dependencies (including the bundle-under-test) are built (which only takes a second or two), and that would speed up the development significantly.

I'm not sure what the ideal solution is to this problem. A couple of ideas:
* Optionally configure `BndtoolsBuilder` to only re-build the current project rather than all its dependencies. The problem I forsee here is that people may set this and forget and wonder why their projects are not rebuilding.
* #2801 (parallel builds) might help to a degree. Perhaps if `BndtoolsBuilder`, instead of firing off a single instance that locks & rebuilds the entire workspace, could somehow fire off an instance for each project with project-level locking - then the test launcher should be able to launch as soon as its project's build is finished while the rest of the workspace rebuild happens in parallel.

**Comment by bjhargrave** [comment]
The Bndtools builder is an Eclipse IncrementalBuilder and is called once per project to build the project. So it is not called just once for the whole workspace. The Eclipse build process controls, through the project ordering, calling all the incremental builders on a per project basis. 

It is not clear the parallel invocations of the Bndtools builder would help given the current state of Bnd not being fully thread-safe and the need to hold a Bnd lock when calling Bnd.

**Comment by pkriens** [comment]
The general problem is that bnd is sadly not API based. It started out as a small hack and I initially thought it was sufficient to keep the properties as the API. Clearly the project became way larger than ever imagined.

With my customers I have an API project that provides interfaces for every module that talks to other modules. Just like OSGi services. Since those projects do not depend on each other (they all go through an API), even 400 project builds are very fast. Unfortunately, it is open source so no way to get do a redesign. :-(

That said, in bnd we are building the gradle plugin and bnd command line and these take quite a bit of time since they collect everything else. You can remove them from the build in Eclipse by closing those projects, this makes quite a difference. I would be ok to only build those projects in gradle in the offline build.

**Comment by bjhargrave** [comment]
> I would be ok to only build those projects in gradle in the offline build.

I am not sure I would care for that. I am not even sure that it would help much since it would not stop Eclipse from building all the other projects.

The simple thing here is to turn of Build Automatically. Launching Junit test will build the project holding the tests which is probably what you want here anyway. You can also manually build a project using the Build menu item.

**Comment by bjhargrave** [comment]
> You can also manually build a project using the Build menu item.

When you do this, Eclipse will build all dependents of the project before building the project. So this can useful for working on biz.aQute.junit (as I am now).

**Comment by kriegfrj** [comment]
Thanks, that sounds like a useable workflow. I'll give it a try.

Still think this would be a useful feature though.

**Comment by kriegfrj** [comment]
I still find working on the tester more painful than it ought to be because of this restriction.

I have the feeling that a significant reason (though probably not the only one) that no one has taken up this issue (and other issues related to the Bndtools Builder) is a lack of automated regression testing. Hopefully, now that we have a working Bndtools integration test (#3881) we can start working on some regression tests for the builder, and then look at adding features like this and #3175.
