### ISSUE TITLE
Repositories are not displayed as Plugins

### ISSUE THREAD

**Issue by eximius313** [bndtools/bnd#3054]
Documentation (https://bndtools.org/repositories.html) states: 

> Repositories are implemented as bnd plug-ins, and can be configured by editing the Plugins sections of the workspace configuration file (Bndtools menu » Open main bnd config).

and shows following screenshot:
![image](https://user-images.githubusercontent.com/5578017/53953496-c3df9e00-40d3-11e9-928c-5b7092fbd54c.png)

but when I open my `main bnd config` although I have repositories configured:
![image](https://user-images.githubusercontent.com/5578017/53953633-19b44600-40d4-11e9-84f5-2050fcbe6f0b.png)

plugins section is empty:
![image](https://user-images.githubusercontent.com/5578017/53953583-fee1d180-40d3-11e9-8839-cafb1f72defc.png)

**Comment by bjhargrave** [comment]
I suspect this is because the Plugins section displays the `-plugins` property value and not any of the merged properties `-plugins.*` (like you are using) since it is hard to support displaying the merged result, allowing editing of that and then writing it back out in some sane manner.

I suspect there are many places where the UI does not work well with the use of merged properties.

**Comment by eximius313** [comment]
@bjhargrave - this is fresh `build.bnd` file created with new bndtools workspace

**Comment by bjhargrave** [comment]
> this is fresh `build.bnd` file created with new bndtools workspace

So? It is still using merged `-plugins.*` properties. Perhaps you can fault the workspace template for doing that and not using a single `-plugins` property.

**Comment by swimmesberger** [comment]
The same behavior can be seen for *.bndrun files and the associated views in the bndtools plugin:
![image](https://user-images.githubusercontent.com/1330294/54667686-3e091d00-4aed-11e9-80c9-9730d981969b.png)

when merged properties are used. For us it's crucial to define some "base" bundles (e.g. -runrequires.1.base) which will be inherited for our more specific ".bndrun" files (e.g. -runrequires.2.specific). For this usecase resolving works fine with the UI but the run requirement view is broken which is very unfortunate because when you have many bundles it would be much easier for us to simply use the ui to modify the requirements instead of searching the bundle copying the symbolic name and manually putting it into the runrequires instruction.

Another issue with this usecase is resolving and the "-runbundles" instruction because it seems that currently it works this way:
1.  We resolve the "base" bndrun file which itself is a valid "product" - this results in the -runbundles instruction in the base.bndrun file
2.  We resolve the "specific" bndrun file which (via UI again) which results also in the -runbundles instruction. The issue is that we inherit from the "base.bndrun" which has already a -runbundles statement therefore in the -runbundles statement in the "specific.bndrun" has no effect. We then have to manually modify the -runbundles in the base.bndrun to -runbundles.1.base and in the specific.bndrun from -runbundles to -runbundles.2.specific. This resolves the issue.

A simple way to fix this usecase would be to detect single -runrequires.something statements in bnd files und showing these instructions in the UI. When editing this instruction the corresponding block will be updated. Resolving a -runrequires.1.base block results in a -runbundles.1.base block. This would be enough for our usecase.

For the case that multiple -runrequires statements are found the view again could fail and show some message or we could define an additional instruction which defines the "main" UI block? maybe multiple run requirement views for each -runrequires block? A merged read only view of the properties? A merged rw view of properties where when you add something you have to define the block you want to add it? Just some brainstorming...

**Comment by eximius313** [comment]
Bug is still there. 
Reproduce steps in description.
What additional information do you need?

**Comment by gamerson** [comment]
If you have reproduced in the latest release (5.1.1) then simply reopen this issue.
