### ISSUE TITLE
Feature Request: launcher based variable expansion

### ISSUE THREAD

**Issue by maggu2810** [bndtools/bnd#3068]
It would be nice if it is possible to prevent the bnd-export-maven-plugin to replace the variables or "runproperties" and delegate that task to the launcher.

Assume my "-runproperties" instruction looks like:

```
-runproperties: \
        osgi.console=,\
        osgi.console.enable.builtin=false,\
        my.prop.a=${env.HOME}/.myapp,\
        my.prop.b=${.}/myapp
```

So, `my.prop.a` a should point to `${HOME}/.myapp` and `my.prop.b` should point to `${PWD}/myapp`.

This works while running in the Eclipse IDE.
It seems also to work if I start the created JAR file on command line -- as long as I execute the JAR file on the generated location, as the same user.

If you look at the "launcher.properties" inside the exported JAR file, you can identify that the variable are evaluated at build time.

The values and so the paths of `my.prop.a` and `my.prop.b` contains the directory path as evaluated at build time.

Wouldn't it be nice if such directory paths can additionally be evaluated by the launcher and so `${env.HOME}` will always be the home directory of the user that executed the JAR file (and `${.}` will point to the current working directory the JAR file has been started from)?

---

Issue created by request on [Google Groups](https://groups.google.com/d/msg/bndtools-users/o40oEQJt0kw/JwJ-7yxGAgAJ)

**Comment by giamma** [comment]
This would be a very nice feature. 

At the moment I am achieving something similar by having my own embedded activator that rebinds properties with computed values. I use this to automatically relocate some configuration files used by Pax Web (jetty.xml, https certificates) as well as some configuration files or working folders needed by my application.

But this approach only works for properties that the user code reads via System.getProperty(), because when you read them via the BundleContext you are reading a read-only snapshot created by the framework (in my case Equinox) when it started, and as such changing the value of the system property has no effect. 

A way to do this more easily would be great.

It would be great to be able to

**Comment by maggu2810** [comment]
For the logger configuration my bndrun file contains a line similar to this one:

```
-runproperties: logback.configurationFile=file:${.}/runtime/logback.xml
```

This works fine as long as I do not use the `bnd-export-maven-plugin` to deploy the JAR file to another machine.

Can you give me some tips how to configure the logger so it works also for the "exported" JAR file?

Do I need to configure the logger programmatically?

**Comment by rotty3000** [comment]
System properties override those set in the launcher properties. So in
production, just set the system property with an appropriate value.

HTH,
- Ray

**Comment by maggu2810** [comment]
> System properties override those set in the launcher properties.

Tested and succeeded. :wink: 
That's good to know. Thank you.

**Comment by pkriens** [comment]
This requires dragging in the macro processor in the launcher which is not really the direction I'd like to go in. So I'd not be working on this.
