### ISSUE TITLE
bnd will ignore certain default property arguments

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#3123]
When performing a call to `Processor.getProperty(key, deflt);` the `deflt` argument will be ignored for all cases where bnd stores an internal default in https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/build/defaults.bnd .

**Comment by bjhargrave** [comment]
I think you need to be careful in a fix here. This will be tricky to do correctly and not break existing code.

Changing this would mean:

`getProperty("java", null)` should return null if "java" property is not set irrespective of defaults.bnd.

`getProperty("java")` should return "java" from defaults.bnd if "java" property is not set. 

But currently `getProperty("java", null) == getProperty("java")` if "java" property is not set. Any change here will break that.

Example solution: Disconnect defaults.bnd from the furthest ancestor processor and handle it in `Processor.getProperty(String key, String deflt)` where the default value must be computed. That is, if null is returned and you need a default, use the specified default value, otherwise consult defaults.bnd. But there are many places where `deflt` value of null means "compute the default" not null is the default value.

So I think we will be unable to change behavior here without breaking someone's code.

**Comment by bjhargrave** [comment]
An alternate solution maybe to add a new

`Optional<String> findProperty(String key)`

method which does not consult defaults.bnd. Then the caller can handle the optionality as they wish.

**Comment by rotty3000** [comment]
@pkriens and I had a brief discussion about this and we agree it's next to impossible to solve without some kind of breakage. so I really just created the issue so it's known & tracked.

**Comment by rotty3000** [comment]
Note I need to handle this, somehow, in the ProjectLauncher code which attempts to detect the java executable to use. This logic carries the slight risk of ignoring a user defined value which is identical to the default in `defaults.bnd`. In this case it will use the calculated value for the java executable.

**Comment by pkriens** [comment]
well, the default is 'java', pretty sure everybody that uses that is happy with a calculated value :-)

**Comment by bjhargrave** [comment]
Can we close this?
