### ISSUE TITLE
[bundle annotations] @Attribute/@Directive default values not used

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#3142]
[updated] removed some noise from the example.

this is a relative edge case...

given:
```java
@Capability(namespace = "foo.namespace")
public @interface Extended {
	@Attribute("foo.namespace")
	String nm() default "bar";
}

// usage
@Extended
public class It {}
```
the generated requirement is:
`Provide-Capability: foo.namespace`

Note how:
```java
@Attribute("foo.namespace")
String nm() default "bar";
```
did not get applied to the output.

**Comment by rotty3000** [comment]
the issue is that default values are not used.

**Comment by bjhargrave** [comment]
See the spec: https://osgi.org/specification/osgi.core/7.0.0/framework.api.html#org.osgi.annotation.bundle.Attribute

`If the element annotated with Attribute is unspecified when applied, then the attribute must not be generated in the generated capability or requirement clause.`

This means that defaults are not to be processed since they can only apply when the element is unspecified. And if the element is unspecified, then it must not be emitted. Basically, defaults in bundle annotations are documentary (e.g. resolution defaults to mandatory) and otherwise ignored. Defaults document the behavior when the element is unspecified.

**Comment by bjhargrave** [comment]
So Bnd is behaving correctly as required by the OSGi spec.
