### ISSUE TITLE
Classes in wrong Directory: Package/MyClass.class=char

### ISSUE THREAD

**Issue by derheld42** [bndtools/bnd#315]
Turns out bnd doesn't seem to support a class in a capitalized package name.

I accidentally called a package with a capital letter and I get the strange error message and a refusal to build it. (See title for error message)

My package could be named "Coffee" and the package named "CoffeeClient",
The bnd.bnd file could have:
Private-Package: Coffee

I'm running 2.0.0REL with Eclipse Juno.

**Comment by daustin2011** [comment]
still happening

**Comment by derheld42** [comment]
@daustin2011 - I retested with the latest bndtools and wasn't able to reproduce. Do you have a test case where it's failing?

**Comment by eliasvasylenko** [comment]
I get this error too. The reason people aren't able to reproduce may be that it only happens when the package contains classes from other jars/bundles on the build path, e.g. in the case of wrapper bundles. If the classes in the offending package are built from source files in the bundle itself there is no error.

The error occurs regardless of whether you shade in either of the following ways:

    -includeresource: @${repo;bad.jar}!/BadPackage/*

or

    -buildpath: bad.jar
    Private-Package:BadPackage.*
