### ISSUE TITLE
VERSION_STRING validation is not conform to SemVer

### ISSUE THREAD

**Issue by TamasSzerb** [bndtools/bnd#3164]
Hello,

The VERSION_STRING regexp validation at

https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/osgi/Verifier.java#L97

with "[0-9]{1,9}(\\.[0-9]{1,9}(\\.[0-9]{1,9}(\\.[0-9A-Za-z_-]+)?)?)?"

is not conform to https://semver.org/#spec-item-10

since forces the 1.2.3.<something>

while the examples are failing:

due to the greedyness of java regex:

1.0.0-alpha+001
1.0.0+20130313144700
1.0.0-beta+exp.sha.5114f85

note: https://github.com/semver/semver/blob/master/semver.svg

Tamas

**Comment by eliasvasylenko** [comment]
OSGi versions in general don't comply with that spec. In particular
they don't support negative qualifiers (i.e. pre-release versions), and
they don't honour the more complex part-wise precedence rules of
qualifiers.

It is however possible to (almost) losslessy project a semver string
into an OSGi version. The only exception is numeric components too
large to be represented with 32 bits, but I think this is probably true
of lots of semver implementations in practice. It just requries a
little mangling, which isn't always pretty.

First you need to prepend the qualifier with something to force the
correct order between release/pre-release versions, e.g. REL and PRE
depending which is is. Second, you need to pad numeric components of
the qualifier with leading zeroes so they have the same number of
digits and so can be compared lexically. Using 10 digits---i.e. enough
that you can express any 32 bit number---seems like a sensible choice,
since it matches the existing limitations of the major/minor/micro
components.

I don't think you need to do anything special to support component wise
comparison of alphanumeric parts of the qualifier, as the dot character
is already lower-precedence than any other legal characters.

Hope that helps.

**Comment by timothyjward** [comment]
As stated above, the version validation in bnd is used to validate *OSGi versions* which are similar to, but not exactly the same as, the rules at https://semver.org/#spec-item-10

Given that bnd is a project for creating OSGi bundles, and that OSGi versions have been standardised for a lot longer than server has existed, it is not sensible to change this validation.
