### ISSUE TITLE
[bnd-baseline-maven-plugin] plugin configuration is too poor for class filtering

### ISSUE THREAD

**Issue by elballa** [bndtools/bnd#3225]
For internal needs I would like to exclude some added/removed class' methods or fields from the baseline comparison. Is there any way to do it? If not, is there any plan to have it available in one future release? Thanks

**Comment by rotty3000** [comment]
I do not believe there is a way to exclude methods or fields of a class.

... nor do I see much chance of this being added. Unless someone makes a compelling case **and** provides a PR I'd be surprised if this ever comes to fruition.

A class is a cohesive, atomic unit that _should not_ be considered otherwise. So the rational for excluding parts feels somehow wrong to me (but I've been wrong before).

Maybe @pkriens, @bjhargrave @timothyjward could pipe in with a thought.

**Comment by elballa** [comment]
Actually baseline plugin offers a way to filter packages. This is a common way to filter internal packages which are not exported in an OSGI bundles. If a convention in the organization is to have a special suffix of the class name (like Impl or Internal) to identify the internal classes or classes which are not be part of the public api, maybe it can be useful to have a way to filter them. What do you think about it?

**Comment by giamma** [comment]
@rotty3000 the Google guys coding Guava use an annotation, [@ Beta](https://google.github.io/guava/releases/15.0/api/docs/com/google/common/annotations/Beta.html), to denote types or methods that, while belonging to public API, are yet to be finalized and may change in the future. This has been followed by many others, for example, the SonarQube plug-in API makes also large use of the same @ Beta annotation. Any organization having this approach, would certainly like to be able to exclude API annotated as beta from the analysis.  If I am not mistaken I have seen the same also in the Elasticsearch codebase.

As another example, I coded Eclipse plug-ins in the past, and I remember having seen in the Eclipse codebase a number of API classes that had public methods which were not meant to be API and to be used by people, but they were public anyway to ease testing (Eclipse committers own testing, not API users). Such methods had Javadoc saying that they were "test" methods not to be used by anyone. So again, they are another example of methods that should be excluded from the analysis.

Now, you may like the above approaches or not, but those examples come from reputable organization and personally I believe that a bit more flexibility could be useful and could allow a wider adoption of the tool. 

Even if a project used some exclusions, whatever the reason, there would be still value in being able to check that the remaining of the codebase is backward compatible. 

Another example I can think of is when within an organization a team is finally removing a deprecated API after many years, and after a preliminary check they are sure that such API is not used by anyone within the organization anymore, therefore they would like to get rid of it without bumping the major version, which would otherwise require updating all the dependencies of downstream projects. This would be an exceptional case, but in large organizations the possibility to define such an exclusion could save significant effort and money and make the tool more easy to adopt.

**Comment by nfalco79** [comment]
Now is possible filter only on packages using diffpackage in maven configuration.
This have much sense in OSGi where you can avoid to export those packages then you would skip any backward compatibility check. But in standard Java all packages are exported and each one could use any naming convention to indicate what is API and what is no. So for example in my case I would exclude all classes that matches *Impl.java that for me represents an internal implementation of an some interface/spi that may be placed in the same package of the interface. Actually I'm not able to configure this scenario.

**Comment by rotty3000** [comment]
It's actually possible to filter classes, but you need to use their binary resource paths:
```
    <diffignores>
        <diffignore>com/foo/Bar*.class</diffignore>
    </diffignores>
```
(the `*` catches any inner class resources)

But I think @elballa, further clarified by @giamma, is clear in their goals. We just need to think about how to achieve it.

Do we use annotations?
My doubt here is there are a number of API annotations doing this, I know of the [API Guardian](https://junit.org/junit5/docs/current/user-guide/#api-evolution-version-and-status) project used by JUnit5. The Google `@Beta` and such.

Or do we week it low level as input to the baseline operation? There are many questions.

**Comment by nfalco79** [comment]
> It's actually possible to filter classes, but you need to use their binary resource paths:
> 
> ```
>     <diffignores>
>         <diffignore>com/foo/Bar*.class</diffignore>
>     </diffignores>
> ```
> 
> (the `*` catches any inner class resources)

Our actual configuration is 
```
<plugin>
	<groupId>biz.aQute.bnd</groupId>
	<artifactId>bnd-baseline-maven-plugin</artifactId>
	<version>${maven-bnd-plugin.version}</version>
	<configuration>
		<fullReport>true</fullReport>
		<diffpackages>
			<diffpackage>!*.internal.*</diffpackage>
			<diffpackage>*</diffpackage>
		</diffpackages>
		<diffignores>
			<diffignore>*</diffignore>
		</diffignores>
	</configuration>
</plugin>
```
the * as documented is for resources like .properties, XML, manifest and so on.
Following your comment it should also ignore all changes for classes, but it is not.
I had try your suggestion and change configuration like this
```
...
<diffpackages>
	<diffpackage>!*.internal.*</diffpackage>
	<diffpackage>*</diffpackage>
</diffpackages>
<diffignores>
	<diffignore>com/acme/junit/framework/rule/ElasticsearchRule.class</diffignore>
</diffignores>
...
```
but as you can see from the output the configuration is not taken into account:

```
MAJOR                PACKAGE    com.acme.junit.framework.rule
  MAJOR              CLASS      com.acme.junit.framework.rule.ElasticsearchRule
    ADDED            METHOD     <init>(boolean,boolean,java.time.Duration)
      ADDED          RETURN     void
    REMOVED          METHOD     apply(org.junit.runners.model.Statement,org.junit.runner.Description)
      REMOVED        RETURN     org.junit.runners.model.Statement
    ADDED            METHOD     autostarting()
      ADDED          ACCESS     static
      ADDED          RETURN     com.acme.junit.framework.rule.ElasticsearchRule
    ADDED            METHOD     isStarted()
      ADDED          RETURN     boolean
  REMOVED            VERSION    1.7.5
  ADDED              VERSION    1.9.0
```

**Comment by bjhargrave** [comment]
Packages are units and should be treated as such by baselining. Having public *impl* classes in a package is wrong since any user of the package can ignore your class namning convention. Better to put impl classes in an impl package which is not part of the exported API.

As you see, you can not use `diffignore` to ignore classes from class diffing. If you must put impl classes in API package and wish to ignore any baselining errors from those classes, you will need to put appropriate `-fixupmessage` instructions to elide any errors/warnings you do not care about.

**Comment by nfalco79** [comment]
> Having public _impl_ classes in a package is wrong since any user of the package can ignore your class namning convention. Better to put impl classes in an impl package which is not part of the exported API.

This have sense in OSGi where you can choose which package is exported or not. But in standard Java all packages are exported and each one could use any naming convention to indicate what is API and what is no.

for example:
- slf4j 1.8 have `org.slf4j.LoggerFactoryFriend` classes in the same package of API packages.
- JDK `javax.management.remote.rmi` there are Impl class near interface classes and public class that starts with `_`

Those are example of naming convention to indicate what is public and what is not.

**Comment by bjhargrave** [comment]
> This have sense in OSGi where you can choose which package is exported or not. But in standard Java all packages are exported and each one could use any naming convention to indicate what is API and what is no.

My point is about proper API design. People don't always design API well and you end up with public impl classes in API packages. You mention several examples of this. Bnd supports proper API package design best. You can elide error/warning messages for badly designed API packages as I mentioned.

Also naming conventions do not stop people from using impl classes. Even JPMS considers packages to be units in that you export or open _entire_ packages in modules.

**Comment by bjhargrave** [comment]
I just added support for a `BaselineIgnore` annotation that can be used to specify that an element (type or member) should be ignored for baselining when the baseline package version is less than the version specified in the `BaselineIgnore` annotation use.

To permanently ignore an element for baselining, just use a very large version number that would probably never actually ever be used. For example, annotate an impl class with `@BaselineIgnore("9999999")`.

I know this is not necessarily helpful for packaging 3rd party code, but can be using in source code you control.

See #3274

**Comment by giamma** [comment]
@bjhargrave thanks a lot, we will give it a try as soon as possible.

**Comment by bjhargrave** [comment]
Closing as fixed.
