### ISSUE TITLE
Gradle plugin: Empty classpath warning

### ISSUE THREAD

**Issue by io7m** [bndtools/bnd#3349]
Hello!

I'm currently working on making the [Agrona](https://github.com/real-logic/agrona) project OSGi-ready. Thankfully it's an easy target: All packages are exported and there are no dependencies. Unfortunately, I'm running into a slightly irritating warning when the bundle is built:

```
> Task :agrona:jar
warning: Classpath is empty. Private-Package (-privatepackage) and Export-Package can only expand from the classpath when there is one
```

You can see this warning in the Travis build:

https://api.travis-ci.org/v3/job/562069031/log.txt

My fork is here:

https://github.com/io7m/agrona/

I feel like the warning is both unnecessary and harmless, but I'd still like to either fix it or turn it off. Is there anything I can do about it?

**Comment by bjhargrave** [comment]
https://github.com/io7m/agrona/blob/f32c78dbee58a3e17881a99c5650393fd2b64216/build.gradle#L27

should be `biz.aQute.bnd.builder`.

To fix the warning, change `Export-Package` to `-exportcontents` at https://github.com/io7m/agrona/blob/f32c78dbee58a3e17881a99c5650393fd2b64216/build.gradle#L255

`Export-Package` includes searching the classpath for packages to include in the bundle and you did not set any classpath for the Bnd Builder Plugin on the `jar` task (hence the warning). 

https://github.com/bndtools/bnd/blob/9a4d7bcc04c2377641911b517ca8b1915f763a9a/biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java#L240-L245

`-exportcontents` means export packages already included in the bundle which is what you want since you already added all the packages to the jar.

**Comment by bjhargrave** [comment]
BTW, I just realized the README uses `Export-Package` instead of `-exportcontents` in the examples for Bnd Builder plugin. I will fix that.

**Comment by io7m** [comment]
Thanks! That worked.
