### ISSUE TITLE
Are bnd reproducible jars reproducible on case-sensitive and case-insensitive file systems?

### ISSUE THREAD

**Issue by nedtwigg** [bndtools/bnd#3382]
I noticed this resolved issue in the gradle 5.6 changelog, and figured it would be good to double-check for bnd's `-reproducible: true` instruction.

https://github.com/gradle/gradle/issues/8051

**Comment by bjhargrave** [comment]
Bnd builds the Jar using its Jar class and so the order will be consistent since we use  TreeMaps to order the Jar contents. So it does not matter what order walking the file system gives.

Also, Usage questions should be asked in the bndtools-users mail list. See <https://github.com/bndtools/bnd#feedback>.
