### ISSUE TITLE
release should be able to release selected subbundles

### ISSUE THREAD

**Issue by eximius313** [bndtools/bnd#3408]
Having this project: [BndTest.zip](https://github.com/bndtools/bnd/files/3583938/BndTest.zip)

with such structure:
```
-\
  -my.first.bundle
  -my.subbundles\
    -my.second.bundle
    -my.third.bundle
```
when I do:
* `$ ./gradlew release` -> a bundle and two subbundles are released
* `$ ./gradlew my.subbundles:release` -> only two subbundles are released

What I want to do is:
* `$ ./gradlew my.subbundles:release -Pselect=my.second.bundle` -> only specific subbundle is released

could you please provide such functionality?

**Comment by bjhargrave** [comment]
First Bndlib would need to provide the function to release an individual subbundle. It does not. 

https://github.com/bndtools/bnd/blob/42640890a5874bac3cf2e5ea763bdb83f66c2e13/biz.aQute.bndlib/src/aQute/bnd/build/Project.java#L1200-L1202

The gradle plugin merely uses the underlying Bndlib function to release:

https://github.com/bndtools/bnd/blob/42640890a5874bac3cf2e5ea763bdb83f66c2e13/biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy#L328

If you need to release bundles independently, then I would recommend restructuring your projects to avoid using subbundles. Then you will have complete control over releasing bundles since there will be one per project.

**Comment by eximius313** [comment]
Shall I create Feature Request in `Bndlib`?

**Comment by bjhargrave** [comment]
This issue will serve as the feature request. I don't expect it will happen however since you can do what you want by using separate projects.

**Comment by bjhargrave** [comment]
The Bnd maintainers decided not to support releasing individual subbundles. You should refactor your code into multiple project where you can release individual projects.
