### ISSUE TITLE
Changes to bndrun triggers a rebuild

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#3433]
It seems that Bndtools will trigger a rebuild of a project if you change one of the bndrun files, even though the bndrun should not affect the bundle output.

Is the reason for this that Bndtools cannot know on the service if bnd is configured to include the bndrun file as a resource in the bundle?

**Comment by bjhargrave** [comment]
Bndtools and the Bnd Gradle plugin (Bnd Workspace model builds) assume everything in the project folder is potentially source for the bundle. Then known output folders are excluded (bin, bin_test, generated) as well as any folders in the `-builderignore` instruction.

So this is expected behavior.

**Comment by kriegfrj** [comment]
Ok, I understand why this is the default behavior, because in general we have no way of knowing if any given file affects the build. But bndrun files are somewhat of a special case. Couldn't we consider ignoring bndrun files by default, and use -dependson or -includeresource to override it?

**Comment by bjhargrave** [comment]
At the time the decisions must be made to build or not, we have of course not start to build. Either the Bndtools incremental builder is deciding based upon resource changes in the project or Gradle is deciding whether the task is out of date based upon the tasks inputs and outputs.

But in order to know if a file in the project is in fact an input to the project bundles, we need to decide if the file will be included in a project bundle by the bnd file(s) (sub bundles and nested bundles). But this is tantamount to actually building the project bundles.

So it is a chicken and egg problem. Only the Bnd Bulider can know if a file is input to a bundle, but the build drivers (Bndtools incremental builder and Gradle) need to know if a file is an input to a bundle in order to invoke the Bnd Builder. So the build drives must make an approximation to the inputs which is what they currently do. To correctly incrementally build, this approximation must not be less than the actual input so we do not fail to build when we should. And this is the current situation. So I don't this there is anything additional we can do here without replicating the initial Bnd Builder function into the build drivers which is impractical.
