### ISSUE TITLE
Enable Embedded Activators to be started right after Framework Init and before any bundle is installed

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#3445]
As Peter suggested in his PR Comment:

I'd rather not have a specific splash handler. The intention of the launcher is that the embedded activators do this. Embedded activators are on the run path.

A valid concern is that they are not run until after all bundles are installed (start happens after). In a recent discussion, a large setup took 2.5 seconds so I do not think that is a real problem. However, a change that also allows embedded activators to run before install is ok with me. Currently the before/after start flag (static boolean IMMEDIATE) could be turned into a String or so to support multiple possibilities.

Another alternative is to add code to the launcher and change the main class.  See #3410

_Originally posted by @pkriens in https://github.com/bndtools/bnd/pull/3432#issuecomment-533458038_

**Comment by juergen-albert** [comment]
I would suggest the following:
We leave the IMMEDIATE field as it is, in order top avoid breaking existing behaviour or make it awkward and just print out a warning that marks this as deprecated..
We look for a second field of type String (I would name it START_LEVEL and look for the values: AFTER_FRAMEWORK_START, BEFORE_BUNDLES_START and DEFAULT. if this is set IMMEDIATE is ignored.

**Comment by pkriens** [comment]
Just keep IMMEDIATE but allow these strings as well as being boolean. We're inspecting this reflectively so no need to deprecate anything. And anyway, a deprecation is useless since you cannot mark anything deprecated since there is no type binding. Also, don't add `DEFAULT`, call it `AFTER_BUNDLES_START`. Providing an invalid string means log error and start `AFTER_BUNDLES_START`.
