### ISSUE TITLE
bnd-resolver-maven-plugin does not report failure correctly

### ISSUE THREAD

**Issue by cdelg** [bndtools/bnd#3468]
When `bnd-resolver:resolve` fails because changes have been detected, the plugin shows the exact same bundles list in `Existing runbundles` and `Calculated runbundles`. This prevents me to debug a failure on my CI.

## Step to reproduce 
1. set `-runrequires: bnd.identity;id='ch.qos.logback.classic'` and resolve using Bndtools 4.3.0.REL
2. Remove the last bundle in `-runbundles`
3. Resolve the bndrun file with `bnd-resolver:resolve 4.3.0 and `failOnChange` set to `true`.
4. This should fail, but the two lists  `Existing runbundles` and `Calculated runbundles` are identical

Note: If instead of the last bundle you remove a bundle in the middle from `-runbundles`, the two lists contains the same bundle but in a different order (the removed bundle is shown at the end of  `Existing runbundles`.

**Comment by rotty3000** [comment]
I believe the best solution/workaround for this issue at present is to add:
```
-runstartlevel: \
    order=sortbynameversion,\
    begin=-1
```
to your bndrun file.

This will ensure that results are always ordered the same way.

This is also useful when the `-runbundles` are persisted in source control in order to make diff/merge operations a little more sane by ensuring consistent results between developers and across systems.

For now I'm going to close this as having a sufficient solution.

Please reopen and include a rational if that doesn't work.
