### ISSUE TITLE
Missing annotation for 'sourceSet' in bundle task convention

### ISSUE THREAD

**Issue by pun-ky** [bndtools/bnd#3483]
I have a Gradle task with field of type `BundleTaskConvention` coming from BND. Then I am not able to hide this Gradle task validation error when building my plugin:

```
  - Warning: Type 'com.cognifide.gradle.aem.bundle.tasks.BundleCompose': property 'bundleConvention.sourceSet' is not annotated with an input or output annotation.
```

seems that other fields/getters are having correct annotations. only this one is missing

**Comment by bjhargrave** [comment]
BundleTaskConvention is not meant to be used as a field in a task. It is meant to be applied as a convention. Hence the name.

https://github.com/bndtools/bnd/blob/2b545fa4b7987edadff3ad4b59bb4bc5a9f64fd6/biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Bundle.groovy#L38

Also, it is unclear to me what input annotation would even work on a SourceSet. Input means the field is a property-like thing. InputFile or InputFiles or InputDirectory don't make sense either since a SourceSet is a much broader aggregate. Nested may be the only possible choice, but you will need to test if that helps since I don't have any scenario where the warning you mention occurs

**Comment by pun-ky** [comment]
yep, thx or clarifying that. i tried with `@Nested`. hope so when registering in same way, Gradle plugin validation will work, thx
