### ISSUE TITLE
Designate does not work with classes not contained in the same bundle

### ISSUE THREAD

**Issue by jpchristen** [bndtools/bnd#3491]
If you e.g. create a component @Designate-Annotation with a class that is from another project, you get the following error message:

    DS Component com.example.test.TestComponent specifies ocd class 
    com.example.otherbundle.TestConfig which cannot be found; known classes [...]

**Comment by timothyjward** [comment]
Are you able to reproduce this in a small example workspace that you can share with us? 

The most likely cause is that your build's class path is set up such that bnd can't see the TestConfig class when doing its processing.

**Comment by jpchristen** [comment]
Everything I did was the following:

Having two different bundles with:

Bundle A exporting a package containing:
    
    @ObjectClassDefinition(name = TestConfig.PID)
    public @interface TestConfig
    {
       String PID = "com.example.test.config";
    }


Bundle B that has bundle A in its build path. It contains the following component:

    @Designate(ocd = TestConfig.class)
    @Component(configurationPolicy = ConfigurationPolicy.REQUIRE, configurationPid = TestConfig.PID)
    public class TestComponent
    {

    }

**Comment by bjhargrave** [comment]
Can you please provide a small github repo which demonstrates the problem? Then we can investigate. Thanks.

**Comment by jpchristen** [comment]
Done: https://github.com/jpchristen/designateConfigBug.git

**Comment by bjhargrave** [comment]
This appears to be working as designed. From the javadoc of the Designate annotation:

> Generate a Designate element in the Meta Type Resource for an ObjectClassDefinition using the annotated Declarative Services component.

So using the Designate annotation affects both the metatype resource generated and the component description resource generated. So Bnd requires both the class annotated `@Designate` and the `@ObjectClassDefinition` annotated class referenced by the `@Designate` annotation to be in the same bundle so that Bnd can properly generate both the metatype resource.

If your example, Bnd cannot generate the metatype resource since it is in an already built bundle and thus would not be able to met its obligation to  `Generate a Designate element in the Meta Type Resource for an ObjectClassDefinition using the annotated Declarative Services component.`

So in your scenario, you cannot use the `@Designate` annotation.

**Comment by pkriens** [comment]
In this case it is also possible to add the pid in the `@ObjectClassDefinition(pid=TestConfig.PID)`. I see that the `@Designate` on the `@Component` annotated class only is used to copy the PID used for the component.
