### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#3497]
have a question regarding the performance of an Eclipse build for ennexOS.
While I was testing a new Notebook hardware I was wondering why the CPU wasn’t  used with all cores.
We found an option for gradle („gradlew  –parallel jar) which leads in 25s instead of 50s without that option.
Is there any option in BND Tools or Eclipse to use all cores?
I played around with the Eclipse Build options: Max simultaneous project build
But I got only 10%, it seems like that there is only one worker job which feeds the build jobs.
I got one core with 100% and the others with 40 to 60%
And gradle is nearly 5 times faster than an Eclipse build, is that plausible?

Notebook | ennexOSLD in Eclipse | ennexOSLD mit „gradlew jar“ | ennexOSLD mit „gradlew  –parallel jar“
-- | -- | -- | --
Core i7 8665U 8GB ohne Bitlocker | 2:00 | 0:50 | 0:25
Core i5 8365U 8GBohne Bitlocker | 2:10 | 0:54 | 0:27
Core i5 6440HQUnser altes Notebookmit Bitlocker | 3:43 | 1:30 | 1:14

**Comment by bjhargrave** [comment]
Usage questions should be asked in the bndtools-users mail list. See <https://github.com/bndtools/bnd#feedback>.

**Comment by pkriens** [comment]
I want to discuss this next Friday during the meeting.

**Comment by bjhargrave** [comment]
I am unclear on what the question is here? You can use `--parallel` in Gradle starting with Bnd 4.3. But this would assume that all parts of the build are safe. For example, the Bnd build itself is not safe to use `--parallel` because we have tests which use Launchpad which is not `--parallel` safe.

See also https://github.com/bndtools/bnd/issues/2801 which is probably the proper issue for this discussion.

**Comment by pkriens** [comment]
Let's discuss this Friday?

**Comment by bjhargrave** [comment]
Traveling this Friday. So would have to be next call.
