### ISSUE TITLE
[m2e] using a project variable in a runrequires instruction doesn't resolve in the IDE

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#3508]
If you use:
```
-runrequires: \
	osgi.identity;filter:='(osgi.identity=${project.artifactId}-test)'
```
the bndtools.m2e isn't able to resolve the variable resulting in inability to run or resolve from Eclipse.

**Comment by bjhargrave** [comment]
Hehe. I just removed access to `project` and `task` properties from Gradle Bnd Workspace model builds since they are not knowable to Eclipse. b99493a023381dcc68ebeae725388528586d7def

In general, I think it is bad form for bnd/bndrun files to depend upon data from Maven POMs or Gradle build scripts.
