### ISSUE TITLE
Embedded Activator: (still) different behavior with in aQute launcher

### ISSUE THREAD

**Issue by tobigun** [bndtools/bnd#3582]
With the launcher included in bndtools 4.2 the system bundle was started before any Embedded Activator was started. This was also the case for Immediate Activators (which are now the startBeforeBundles Activators):
https://github.com/bndtools/bnd/blob/4.2.0.REL/biz.aQute.launcher/src/aQute/launcher/Launcher.java#L399

With bndtools 4.3 the system bundle was originally started after all Embedded Activators.
A few days ago a patch was applied that at least the system bundles is started for the startAfterBundles:
https://github.com/bndtools/bnd/commit/a121ba2448513ec82519dc1bf0492b5732eab58d#diff-44c67ee8afec40b1760cc3196bca58a3

But this still does not address the startBeforeBundles as the system bundle is still started after these bundles.

Isn't it possible to start the system bundle before all Embedded Activators to have the same behavior as before?

Code example (systemBundle.start() moved above start of startBeforeBundleStart):
>List<Bundle> tobestarted = update(System.currentTimeMillis() + 100);
>
>systemBundle.start();
>trace("system bundle started ok");
>
>for (BundleActivator activator : startBeforeBundleStart) {
>       result = start(systemContext, result, activator);
>}
>
>startBundles(tobestarted);
> 
>~~systemBundle.start();~~
>~~trace("system bundle started ok");~~
> 
>for (BundleActivator activator : startAfterBundleStart) {
>       result = start(systemContext, result, activator);
>}
> 
>startLevelhandler.afterStart();

**Comment by bjhargrave** [comment]
> as the system bundle is still started after these bundles.

I am not sure what you mean here. You can see from the commit that the system bundle IS now started before the `startAfterBundleStart` bundles.  When you do see the system bundle starting? Perhaps your bundle just sees some bundles as not started because their start levels are not yet met when your bundle starts or the other bundles are not fully ready yet.

> Code example (systemBundle.start() moved above start of startBeforeBundleStart):

With that change, the `startBeforeBundleStart` bundles are started AFTER the system bundle has started which seems to defeat the point of those EmbeddedActivators which need to run before the system bundle starts.

**Comment by pkriens** [comment]
@bjhargrave I already assigned myself to this.

**Comment by bjhargrave** [comment]
Yes, I saw that.

**Comment by pkriens** [comment]
That normally indicates that I will look into it?

**Comment by bjhargrave** [comment]
So I should refrain from any comment?

**Comment by pkriens** [comment]
Yup, until i worked it out or the next meeting?

**Comment by pkriens** [comment]
@tobigun can you verify the change in https://github.com/bndtools/bnd/pull/3590 ?
