### ISSUE TITLE
Deleting BndtoolsJAREditorTempFiles folder on file system breaks Jar Editor

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#3729]
The Jar Editor now creates a `BndtoolsJAREditorTempFiles` project in the workspace and hides it in the Eclipse Package and Bndtools Explorer views. But the folder is, of course, visible on the user's file system.

If the user uses a different folder for the Eclipse workspace than the git repo/Bnd workspace, they generally will not notice the folder. If they use the same folder for the Eclipse workspace and the git repo/Bnd workspace, then the `BndtoolsJAREditorTempFiles` folder will be a dirty file in the git repo.

If, for any reason, the user deletes this folder from the file system (without deleting it inside the Eclipse workspace which they probably wont since it is hidden from them by default), then the Jar Editor can no longer open to view a jar. Eclipse complains about the missing `.project` file for the `BndtoolsJAREditorTempFiles` project. To solve this, the user must unhide the `BndtoolsJAREditorTempFiles` project in Eclipse and then delete it. The Jar Editor can then recreate it.

I think the Jar Editor should know how to recover from this situation and properly restore the hidden `BndtoolsJAREditorTempFiles` project to working order.

Perhaps the folder name should even start with a `.` to indicate a hidden folder?

**Comment by pkriens** [comment]
@gamerson does the project have to be on the file system? If it is, could we not store it in the bundle data area?

I did try to find a way to create temporary IFile and IFolder nodes but Eclipse does not seem to provide any support for this. Which I find a tad odd. Sadly we cannot use the same project as the JAR since it would not allow the JAR Editor to be used by the repos.

@gamerson let me know if you do not have time.

**Comment by gamerson** [comment]
I will research if we can create the project not in the physical Eclipse workspace root, possibly in the Bndtools plugin state location.  That would prevent accidential deletion from the filesystem.  

If the above doesn't prove possible, I can also add some robustness to the getters in `TemporaryProject` so that it will do a sanity check on the project and try to recover in the case the user has manually deleted from the filesystem.

**Comment by bjhargrave** [comment]
Thanks. 

FYI: There were several places in the original code which simply swallowed exceptions which made it hard to figure out why I could no longer open the jar editor. I have changed that code to not swallow exceptions.
