### ISSUE TITLE
AnnotationHeaders: questions about filter generation

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#3776]
https://github.com/bndtools/bnd/blob/bee4405746c55273ad66f02b582a6fedd9d76ef9/biz.aQute.bndlib/src/aQute/bnd/osgi/AnnotationHeaders.java#L800-L802

Why do we check for `$` and why is the path with the `$` not checked for version syntax errors?

Any reason we do not use the FilterBuilder for this method anyway?

**Comment by rotty3000** [comment]
Because it's a macro which is only processed later.

**Comment by bjhargrave** [comment]
> Why do we check for `$` and why is the path with the `$` not checked for version syntax errors?

I would guess it is trying to see if the user has done something like `version="${@version}"`. See Macros in https://bnd.bndtools.org/chapters/230-manifest-annotations.html.

> 
> Any reason we do not use the FilterBuilder for this method anyway?

Because it is cumbersome and unnecessary? Filter strings are easy to build with StringBuilder and you avoid lots of temporary object creation. FilterBuilder also has defects in version range filter creation in that it does not handle open-on-both-ends ranges correctly. See https://github.com/bndtools/bnd/commit/67f9d2c245af9374615c9672379da50d797b7687#diff-12b4841907d8af740fc1fafbc9a253c8 where I fixed this in VersionRange.

**Comment by pkriens** [comment]
So where would this be expanded? And either we do verifying later (which makes the first verify superfluous) or we do macro expansion somewhere later and use the verification at the end of the Require-Capability header?

About the FilterBuilder, isn't easier to fix it if it has an error? The version range looks a lot less readable after your change :-( The code that constructs this filter looks very complex with these different flags to track where it is in the expression.

Do we really see a performance difference with these changes that makes the code much bigger and less readable?

**Comment by bjhargrave** [comment]
I fixed VersionRange.toFilter since I see it as the canonical place for converting version ranges to filter expressions. Given that, that code just has to be correct and performant. Since OSGi version ranges and filter expressions are unlikely to change in the foreseeable future, now that this method is correct (and has some tests), it is unlikely to need further changes.

I personally don't have see the use for FilterBuilder. They api is complex for the non-complex topic of creating filter strings. It also does not properly handle escaping `*` in values since the api does not distinguish between the `simple` and `substring` operations. So it is up the user to handle escaping `*` in equals operations to avoid them being treated as substrings. I would rather we just deprecate the whole FilterBuilder.
