### ISSUE TITLE
BND(tools) and maven Documentation

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#3781]
While preparing something for a Customer, I took a look into the bnd maven plugin. I started by asking google for "bnd maven" and "osgi maven".  The result was: Not one link to the bnd or the bndtools page (except for the maven bnd repository plugin). In both cases are more links leading to the felix bundle plugin and maven tycho than to our plugin. bnd and maven brings the github page for the plugin, which has decent documentation, but I think we need something on the bnd page as well. 

Additonally: I think we should somehow provide a space (e.g. the bndtools page) for more general tutorials surrounding bnd. Here we can explain brought concepts, additionally we can show all the different ways bnd can be used (IDEs in eclipse or intellij, console plain, with gradle or maven) .

**Comment by pkriens** [comment]
I've made videos for the workspace model and I am working on a 100+ page booklet that accompanies it. 
I actually got very impressed with anybody that got this to work :-(

**Comment by juergen-albert** [comment]
Exactly. I think we have a similar problem with a lot of the other things. We have a lot concepts in bnd e.g. namespaces for instructions that can be used for inheritance in bnd files), that come natural to us as power users but not to anybody who is new.  
We have a very good documentation, but it only works if you already know, what you are looking for. Everything else can be found somewhere in the mailing list, but only as a byproduct.

**Comment by juergen-albert** [comment]
@pkriens and I like the Videos. They are a good step in the right direction.

**Comment by pkriens** [comment]
That is why I am working on **two** books. The first book is just around getting started with the workspace so you can run Gogo and make components. I.e. HOW without understanding. Gogo is important because it allow you to use tiny snippets in making clear how things work. The second book is providing more background and explanations and lots of complex examples.
However, there is sooooo much to talk about :-( And there does not seem to be a viable way to make a living on this information :-( I might try it with the second book but hopes are not high.
