### ISSUE TITLE
bnd (gradle) uses wrong group-id for META-INF/maven/{group-id}/...

### ISSUE THREAD

**Issue by mnlipp** [bndtools/bnd#3807]
I have no `-gradle` in my configuration (which btw isn't documented, couldn't find it in bnd's instruction  index). So the value used with "`-pom: true`" should be the [bsn prefix](https://bnd.bndtools.org/instructions/pom.html).

With a bnd (5.1.0) gradle workspace build, however, the value used seems to be the name of the directory in which the toplevel project resides. I started my project in a directory "JGrapes-OSGi" and added it to GitHub later. When Travis-CI clones it, it ends up in a directory "jgrapes-osgi" (this being the GitHub project name) and I get this build error:
```
/home/travis/build/mnlipp/jgrapes-osgi/org.jgrapes.osgi.core/bnd.bnd:2: error: The bundle version (1.0.2/1.0.2) is too low, must be at least 1.0.3
CHANGED              BUNDLE     org.jgrapes.osgi.core
  CHANGED            RESOURCES  <resources>
    REMOVED          RESOURCE   META-INF/maven/JGrapes-OSGi/org.jgrapes.osgi.core/pom.properties
      REMOVED        SHA        62F7730E3C0F62FB90D597E0068991BE446627DD
    REMOVED          RESOURCE   META-INF/maven/JGrapes-OSGi/org.jgrapes.osgi.core/pom.xml
      REMOVED        SHA        B264E387C2A5572ACB5160D0EFE05F721EE96D0D
    ADDED            RESOURCE   META-INF/maven/jgrapes-osgi/org.jgrapes.osgi.core/pom.properties
      ADDED          SHA        64FABC5C18F580FB5A051286160976F45D8AB757
    ADDED            RESOURCE   META-INF/maven/jgrapes-osgi/org.jgrapes.osgi.core/pom.xml
      ADDED          SHA        C8386A3A167D24BF49042A64732C2BF6F574162B
```
(Took me a bit of time to find the subtle difference.)

So either the implementation or the documentation is wrong.

**Comment by bjhargrave** [comment]
> I have no `-gradle` in my configuration (which btw isn't documented, couldn't find it in bnd's instruction index).

There is no `-gradle` instruction in Bnd that I am aware of.

The best thing to do is to set `-groupid: jgrapes-osgi` in your `cnf/build.bnd`. Then the default groupId is explicitly set and does not need to be computed. See how we do it in Bnd:

https://github.com/bndtools/bnd/blob/612c0c3e134db12f96d1073f00f1cad2b0c82228/cnf/build.bnd#L31-L34

I don't see any code in Bnd (master branch) where is would compute the groupId from the workspace folder name. Can you please provide a small github repo which demonstrates the problem? Then we can investigate. Thanks.

**Comment by mnlipp** [comment]
What a typo (and I can't even blame auto-completion)! Of course there is no `-gradle`. What's missing in the documentation (for sure in the index) is `-groupid`.

**Comment by bjhargrave** [comment]
I made https://github.com/bndtools/bnd/pull/3815 to add the `-groupid` doc page.

**Comment by mnlipp** [comment]
* Clone https://github.com/mnlipp/groupid-test
* cd to `groupid-test`
* `./gradlew clean build`
* `jar tvf test.bundle/generated/test.bundle-0.0.0.jar` gives
```
...
... META-INF/maven/groupid-test/test.bundle/pom.xml
...
```
* `cd ..`
* `mv groupid-test GroupId-Test` (also works with rename to `Hello` or whatever you like, using caps caused my problem)
* `cd GroupId-Test`
* `./gradlew clean build`
* `jar tvf test.bundle/generated/test.bundle-0.0.0.jar` gives
```
...
... META-INF/maven/GroupId-Test/test.bundle/pom.xml
...
```

**Comment by bjhargrave** [comment]
See 

https://github.com/bndtools/bnd/blob/3205f5a02ed7d8cc35a2aa3a8f101ff85f00acb9/biz.aQute.bndlib/src/aQute/bnd/build/defaults.bnd#L39

The default for `-groupid` is the folder name of the workspace. Which is exactly what you are seeing. This behavior has been in place since the `-groupid` instruction was added 5 years back.

So what you are seeing is expected and why you should specify the `-groupid` you want instead of letting it default.

**Comment by mnlipp** [comment]
> So what you are seeing is expected

Well, not if you have read the documentation (which currently states: "Will default to bsn prefix if no groupid is set.")

**Comment by bjhargrave** [comment]
But `-groupid` is always set by default. I do agree that I was surprised by this since there is lots of code in the pom resource processing which handles `-groupid` not being set. Given that there is always a default value for `-groupid`, one would have to unset it to ever get to the place where groupid will default to the bsn prefix. I am sure there are test for that, but those tests are probably in a simple context which does not include a Bnd workspace where `-groupid` has a default.
