### ISSUE TITLE
Bnd fails to launch Bndruns for JDK 8 with Unrecognized option

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#3869]
Something noticeable I found in the latest Bndtools Snapshot Version (`5.1.0.DEV-202004021913-gd8d520f`). Unfortunately I cannot run any of the Bndrun files.

```
Unrecognized option: -ea -XX:StringTableSize=60013 -XX:+HeapDumpOnOutOfMemoryError -XX:+ExitOnOutOfMemoryError -XX:HeapDumpPath=./var/osgi/jvm/heapdumps -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.rmi.port=9999 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Xmx256M -Xms20M -Xss256K -XX:+UnlockCommercialFeatures -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints -XX:+FlightRecorder -XX:FlightRecorderOptions="loglevel=info,defaultrecording=true,disk=true,repository=./var/osgi/jvm/flightrecorder/,dumponexit=true,dumponexitpath=./var/osgi/jvm/flightrecorder/"
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

It worked perfectly till yesterday. I switched back to `Bndtools 5.0.1.REL` to see if the problem is something not relevant to Bndtools. And luckily it works in the latest release version. I believe that any of the latest changes might have caused this.

**Comment by bjhargrave** [comment]
Can you please provide the Eclipse launch and bndrun files you are using?

https://github.com/bndtools/bnd/commit/42277d5d3eeeb73a062f18a9081068682532ee34 change how Bndtools formats the vm and  program args for Eclipse launching.

**Comment by bjhargrave** [comment]
A small github repo which demonstrates the problem would be best.

**Comment by amitjoy** [comment]
Sure. I would try to prepare an example project and send you the link.

**Comment by pkriens** [comment]
This happened after the change you made yesterday, so maybe you can look if something can cause this?

**Comment by bjhargrave** [comment]
> This happened after the change you made yesterday, so maybe you can look if something can cause this?

I assume the issue results from the change I made. So I would like the launch/bndrun info to confirm.

**Comment by amitjoy** [comment]
@bjhargrave I believe it would be easier for you if I can just provide you with the bndrun that cannot be launched. The enclosed bndrun comprises only the necessary VM arguments that you can include in any of your existing bndrun files. Then you don't have to checkout my example project and test separately.

I had to rename the file since GitHub doesn't allow adding files having bndrun extensions 😉 
[vm.txt](https://github.com/bndtools/bnd/files/4427389/vm.txt)

**Comment by bjhargrave** [comment]
Well the big problem here is that `-runvm` is a comma separated list of items. See <https://bnd.bndtools.org/chapters/300-launching.html>.

But you are using SPACE separated options. This basically worked before because Bnd treated is as one option and passed it to the Eclipse launcher which parsed it by the spaces.

The recent change to Bnd to better handle options with spaces in them means that Bnd will process EACH -runvm option and quote it if it has a space. Since your bndrun file effectively has only a single -runvm option with spaces, we kindly quoted it. And the vm chokes on the very long option which it does not understand.

So you do need to use commas to separate options on your -runvm value. You are not alone in this mistake. It turns out we, the Bnd team, have made the same mistake in our own bndrun files. For example:

https://github.com/bndtools/bnd/blob/ce86242fec9115ebfb4ee7f8c0ee20976ab4352e/bndtools.core/bndtools.cocoa.macosx.x86_64.bndrun#L11

(which I will fix shortly).

Once you fix your -runvm to use comma separators, it should work fine.

**Comment by amitjoy** [comment]
Thanks @bjhargrave. It works perfectly now. 👍

**Comment by shinych** [comment]
@bjhargrave how do I escape the comma now if I want to have it in the value of a program argument? Thanks

**Comment by shinych** [comment]
@bjhargrave I will try quoting as suggested here https://groups.google.com/forum/m/?utm_source=digest&utm_medium=email#!searchin/bndtools-users/Comma/bndtools-users/9U1-WqUODeM

**Comment by bjhargrave** [comment]
> how do I escape the comma now if I want to have it in the value of a program argument?

See https://github.com/bndtools/bnd/blob/a14a1c13034bc84a1a8a686a98619d3a6c88aa80/biz.aQute.bndlib.tests/testresources/ws/p7/bnd.bnd#L1 for an example of quoting an argument containing commas.
