### ISSUE TITLE
Use Reporter to create parts of the bnd documentation

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#3879]
As discussed in the last Call, this issue should be used to discuss the possibility  of using the Reporter to extract documentation for the bnd.bndtools.org page automatically.

We should try to experiment with it and find out, what would be necessary to incorporate this in the bnd build.

@stbischof As you have invested quite a bit of work in the reporter, what do you think would be necessary to generate from some MD file for a plugin?

**Comment by stbischof** [comment]
it would help to have Annotations like the [Metatype](https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.metatype.html) `@AttributeDefinition` and `@ObjectClassDefinition` to hold the name and description of plugins and methods.

but `@AttributeDefinition` could only be used on methods
```
@Retention(RetentionPolicy.CLASS)
@Target(value = { ElementType.METHOD })
public @interface AttributeDefinition {
```
To have this on  FIELDs and PARAMETERs 
```
@Retention(RetentionPolicy.CLASS)
@Target(value = { ElementType.METHOD, ElementType.FIELD, ElementType.PARAMETER })
```

Would help with the bnd-cli calls. or some DTOs.

This would also be nice in other cases.
* generate OpenApi documentation from RuntimeDTO and Annotates Methods and Params (JaxRs)
* GraphQL Documentation
* Gogo Documentation instead of the Gogo Annotations

**Comment by bjhargrave** [comment]
You put `@ObjectClassDefinition` on classes and `@AttributeDefinition` on methods. Metatype is not designed for fields. Also, the purpose of these is to define metatype resources using a tool like Bnd. They were not design or intended just for document generation. So I would not expect them to change for this.
