### ISSUE TITLE
mandatory attributes ignored by bnd's resolve operation

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#3925]
A friend of mine had a bundle on runrequires that contained an export `org.junit.platform.commons.logging;status=INTERNAL;mandatory:=status`

bnd's resolve operation resolve a bundle which imported `org.junit.platform.commons.logging` without the mandatory attribute.

At runtime the resolve failed because the attribute was expected and missing.

Since the Felix resolver is used in both instances I can only guess that the issue is somehow in the `BndrunResolveContext`.

**Comment by bjhargrave** [comment]
@tjwatson Do you know how the Felix Resolver deals with the `mandatory` attribute? Or is this work for the resolve context?

**Comment by pkriens** [comment]
It is in the matching of the requirements to the capabilities, so therefore logically it is on our side. 

I think we need to update the ResourceUtils.matches method.

PK

**Comment by tjwatson** [comment]
Yes, that is something for the ResolveContext to handle.  See https://git.eclipse.org/c/equinox/rt.equinox.framework.git/tree/bundles/org.eclipse.osgi/container/src/org/eclipse/osgi/internal/container/Capabilities.java#n180 for example

Note that mandatory directive only applies to a small set of namespaces:

`PackageNamespace.PACKAGE_NAMESPACE.equals(namespace) || BundleNamespace.BUNDLE_NAMESPACE.equals(namespace) || HostNamespace.HOST_NAMESPACE.equals(namespace)`

**Comment by bjhargrave** [comment]
@rotty3000 Can you have your "friend" confirm the fix works for them?

**Comment by kriegfrj** [comment]
A quick question: would the fix for this issue require you to rebuild your repository indexes in order to be effective? If so, it would be ideal if the repositories automatically detected when an index was generated with old code and automatically regenerated it. Or as a minimum alternative, we should make a prominent note about this in the release notes that accompany this fix so that people know to manually refresh their indexes.

Background: while I'm not the "friend" referred to in the OP, quite independently I had a resolving issue last week that @rotty3000 and @pkriens helped me solve. We're 90% sure that it related to this issue - I was trying to resolve some core Eclipse bundles that had mandatory attributes/split packages. I think what fixed in the end was 1. upgrading my Bndtools install to incorporate #3934, *and* 2. selecting "Reload Index & Bundles" on the Eclipse 2018-12 repository (the repo containing the bundles with the mandatory attributes). The upgrade alone was insufficient.

**Comment by bjhargrave** [comment]
> would the fix for this issue require you to rebuild your repository indexes in order to be effective?

https://github.com/bndtools/bnd/pull/3764 updated (for 5.1) the resource generation code to include all the attribute values need to match mandatory directives. So basically no index generated before 5.1 is likely to be complete in this regard. So the answer is yes, if you need to support mandatory directives you need 5.1 to get both the better index generation and the mandatory matching support.

> If so, it would be ideal if the repositories automatically detected when an index was generated with old code and automatically regenerated it.

I am not sure how we would automatically detect this. Also some indexes are pregenerated (like OSGiRepository) so we could not regenerate that. For repos like MavenBndRepository, it always locally indexes and so would have the better indexes. LocalIndexRepo will reindex on rebuild of bundles. P2Repo has a local index which would need to be regenerated. It is the remote indexes like OSGiRepository which would be hard to "fix".

> Or as a minimum alternative, we should make a prominent note about this in the release notes that accompany this fix so that people know to manually refresh their indexes.

There is a lengthy note in https://github.com/bndtools/bnd/wiki/Changes-in-5.1.0#bnd about the changes and a note in https://github.com/bndtools/bnd/wiki/Changes-in-5.1.0#backward-compatibility about the possible need to reindex.

> 2. selecting "Reload Index & Bundles" on the Eclipse 2018-12 repository (the repo containing the bundles with the mandatory attributes)

I am quite sure I reindexed that repo after the changes went in for https://github.com/bndtools/bnd/pull/3764. Perhaps your local cache had not pulled down the updated index file from the server which "Reload Index & Bundles" did. But the only way "Reload Index & Bundles" would have helped here is if the remote index had in fact been updated since "Reload Index & Bundles" does not actually reindex the bundles.

**Comment by kriegfrj** [comment]
> > If so, it would be ideal if the repositories automatically detected when an index was generated with old code and automatically regenerated it.
> 
> I am not sure how we would automatically detect this. 

It seems we can't at the moment. Perhaps it is worth including a version identifier as part of the index spec to facilitate smooth migration of the index format going forward. I can think of other situations where we might like to change the index format (eg, adding a trigram index to the class index to support fuzzy matches & handle typos).

> Also some indexes are pregenerated (like OSGiRepository) so we could not regenerate that. For repos like MavenBndRepository, it always locally indexes and so would have the better indexes. LocalIndexRepo will reindex on rebuild of bundles. P2Repo has a local index which would need to be regenerated. It is the remote indexes like OSGiRepository which would be hard to "fix".
> 

So fixing the `OSGiRepository` would requiring giving it a fallback mode that operates more like `P2Repo` - ie, rather than simply using the remote index as-is, it would have to download the bundles and build the index from scratch locally. Probably not high on the priority list.

> > Or as a minimum alternative, we should make a prominent note about this in the release notes that accompany this fix so that people know to manually refresh their indexes.
> 
> There is a lengthy note in https://github.com/bndtools/bnd/wiki/Changes-in-5.1.0#bnd about the changes and a note in https://github.com/bndtools/bnd/wiki/Changes-in-5.1.0#backward-compatibility about the possible need to reindex.
> 

Guess I should have checked that first... the only improvement I would suggest is a specific reference to clearing cached indexes.

> I am quite sure I reindexed that repo after the changes went in for #3764. Perhaps your local cache had not pulled down the updated index file from the server which "Reload Index & Bundles" did.

Definitely, it was my local cache. The poll interval on Eclipse 2018-12 is set to `-1`, so it wouldn't have updated automatically.

**Comment by bjhargrave** [comment]
> > > If so, it would be ideal if the repositories automatically detected when an index was generated with old code and automatically regenerated it.
> > 
> > 
> > I am not sure how we would automatically detect this.
> 
> It seems we can't at the moment. Perhaps it is worth including a version identifier as part of the index spec to facilitate smooth migration of the index format going forward. I can think of other situations where we might like to change the index format (eg, adding a trigram index to the class index to support fuzzy matches & handle typos).
> 

It is not the format(schema) of the index that is changing. It is the content of the index. The `increment` attribute can be used to quickly tell if 2 indexes may have different content, but there is now way to know which is better.

Also, the format of the index (schema) is specified by OSGi. If OSGi were to change the schema, it would get a new xml namespace.

> > Also some indexes are pregenerated (like OSGiRepository) so we could not regenerate that. For repos like MavenBndRepository, it always locally indexes and so would have the better indexes. LocalIndexRepo will reindex on rebuild of bundles. P2Repo has a local index which would need to be regenerated. It is the remote indexes like OSGiRepository which would be hard to "fix".
> 
> So fixing the `OSGiRepository` would requiring giving it a fallback mode that operates more like `P2Repo` - ie, rather than simply using the remote index as-is, it would have to download the bundles and build the index from scratch locally. Probably not high on the priority list.
> 

One of the value props of the OSGiRepository is that you do not need to download all the indexed artifacts to know when there caps/reqs are. To reindex the entire repo could be a massive download.

P2Repo is not very efficient, but it cannot help it. :-(

> > > Or as a minimum alternative, we should make a prominent note about this in the release notes that accompany this fix so that people know to manually refresh their indexes.
> > 
> > 
> > There is a lengthy note in https://github.com/bndtools/bnd/wiki/Changes-in-5.1.0#bnd about the changes and a note in https://github.com/bndtools/bnd/wiki/Changes-in-5.1.0#backward-compatibility about the possible need to reindex.
> 
> Guess I should have checked that first... the only improvement I would suggest is a specific reference to clearing cached indexes.

Well that would only help if someone actually did a reindex and published an updated index at the repo. But they would need to communicate that to whomever was using the repo to tell them to reload.

> 
> > I am quite sure I reindexed that repo after the changes went in for #3764. Perhaps your local cache had not pulled down the updated index file from the server which "Reload Index & Bundles" did.
> 
> Definitely, it was my local cache. The poll interval on Eclipse 2018-12 is set to `-1`, so it wouldn't have updated automatically. 

Yes, I chose `-1` because I did not ever expect the contents to change. I did not consider the index generator would get better and then the index would change :-/
