### ISSUE TITLE
[bndtools] use slf4j logging everywhere

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#3938]
Recent Eclipse releases comes with slf4j in some form or another (and bndtools depends on the API anyhow). Use it everywhere to have normalized logging behaviour.

**Comment by rotty3000** [comment]
Maybe this is a no go... Would this mean no integration with the Log Viewer? maybe... need to investigate if that's the case.

**Comment by bjhargrave** [comment]
I really like that the eclipse logging shows in the Error View. I use that all the time.

I do not know where slf4j logging goes. I suspect it just goes to stdout/stderr which I normally never see since I started Eclipse from the OS UI.

Here are the slf4j component in my Eclipse install. I have no idea how they are configured or where there output goes.

<img width="911" alt="image" src="https://user-images.githubusercontent.com/277682/79672048-6fdf2e00-819c-11ea-95e3-62d26652aecd.png">
