### ISSUE TITLE
bnd.hashes encoding size

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#3984]
The class name look up hash added to Bnd for 5.1 encodes the hash values as a `List<Long>` in the generated index.

```xml
<attribute name="bnd.hashes" value="1073529815,-504136800,1431153295,1132713144,1111940789,1165,36163,36164,36165,36166,36167,1166,1167,1168,1169,1170,1171,1172,1173,-1596886080,1165,2058699256,-3966132,-1295058581,1165,-1839891448,1411123617,1165,1622085332,1165,-165456185,-701110705,35680326,-125599753,1165,1165,1622085332,1165,-165456185,-701110705,35680326,1115779173,1300492059,948989068,-346788822,-283644597,-217237293,1165,1166,1167,1168,855003877" type="List&lt;Long&gt;"/>
```

These can be quite large in the xml index. For example, reindexing our Eclipse 2018-12 repo with bnd.hashes values increased the `index.xml` size from 2.6M to 3.3M and the `index.xml.gz` size from 116K to 375K. 

Perhaps Bnd should use a more compact storage format for this information in capabilities instead of `List<Long>`?

We should come to some decision before we ship this in 5.1.

**Comment by kriegfrj** [comment]
So from the spec, we have the choice of String, Long, Double or Version.

Long seems like overkill because the hashcodes are ints, but given that the values are all bounded between INT_MAX and INT_MIN, in text form it doesn't actually make a difference to the storage size.

The only reasonable alternative is String. A Base64-encoded int requires 6 characters per value. While some of the text representations of the hashes are less than 6 bytes, most of them are more so this would probably be a space saving, with int values taking up to 10 characters (I guess we could try it and see). However, there'd be extra processing overhead in converting to/from Base64 (ie, both at lookup and generation time). We could also concatentate all of the hashes together into a binary stream of ints and Base64-encode the whole thing, which would probably reduce it further (no need for commas), but at the expense of more processing - I think we might lose the benefit of being able to use the repository capability index as-is though.

Also, I noticed in the sample that @bjhargrave used above contains many duplicate values. Given that he pulled it at random I can only assume that this is a common problem. (I also noticed a large number of consecutive values, which is concerning from the hash performance point-of-view...) We could book some space savings if we eliminated the duplicates. This would be generation-time only processing penalty and wouldn't affect lookup efficiency.

**Comment by pkriens** [comment]
We could easily take the hashes modulo-N. If N is low enough, we could use a compressed bitmap. I guess we can make the modulo 1000. 

However, why are you worried about this size increase? The compressed form difference is less than 2 ms 4K streaming, a bad quality JPEG, or the average mail? Most JARs today are a magnitude bigger still than the index.

**Comment by kriegfrj** [comment]
I personally am not too concerned with the magnitude of the size increase. But if wer can reduce it easily and without losing functionality,  lets do it. Getting rid of duplicates would be an easy win? I think the bigger concern there is why do many dups - does this mean there are lots of collisions in the hash (1165 comes up a few times).

**Comment by pkriens** [comment]
I agree dups would be a problem, but I am assuming the String.hashCode should be quite good? I find it hard to believe that will make a difference.

Sorting it could make sense, we could easily put it in a set to get rid of the dups, but I doubt it would make a noticeable difference.

**Comment by bjhargrave** [comment]
I already added a change to remove duplicates:

https://github.com/bndtools/bnd/blob/46f67265f8b080c04ffda6907c8865c766379b0d/biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceBuilder.java#L748

It made a small difference:

```shell
3.3M ndex.nodistinct.xml
3.2M index.xml
```

**Comment by bjhargrave** [comment]
Closing for now. We can address in the future with a new attribute if necessary.
