### ISSUE TITLE
[bndtools workspace] Java References/Declarations Search finds type twice

### ISSUE THREAD

**Issue by gamerson** [bndtools/bnd#4008]
In a bndtools workspace, when one class in a project refers to a type from another project in its -buildpath, searching for type "Declarations" or type "References" will return a duplicate type.

It will return the Type in the "source reference" and also in a "binary reference" from a referenced library coming from the generated folder in the workspace.

Here is the duplicate when shown in a "Declarations" search for the `Api` class.
![Screen Shot 2020-05-04 at 5 41 26 PM](https://user-images.githubusercontent.com/595221/81020796-40cceb80-8e2f-11ea-873a-428e63c6c6c6.png)

Here is a duplicate when shown in a "References" search:
![Screen Shot 2020-05-04 at 5 47 42 PM](https://user-images.githubusercontent.com/595221/81020850-622dd780-8e2f-11ea-9e09-77b490e604eb.png)

Also this happens in the "Open Type..." dialog when you search for "Api"
![Screen Shot 2020-05-04 at 5 48 12 PM](https://user-images.githubusercontent.com/595221/81021019-cb154f80-8e2f-11ea-892d-9a0576c68327.png)

**Comment by pkriens** [comment]
Yes, this is a major drawback. We talked about this but I could not find out a way to filter this? Ideas? It is a major annoyance.

**Comment by bjhargrave** [comment]
For `version=latest` references, we always put both the project's src folder and its jar in the classpath container. 

https://github.com/bndtools/bnd/blob/7f5ff09fe35ec0ca622756e27ff9dc8a916bd7c7/bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java#L379-L398

We need to include the src folder so when debugging, you are seeing real source code you can edit vs. an uneditable view of the source in the jar file. 

We need to include the jar file since a bundle can have more classes than are in the project's src folder.

The issue is really in the searching. We tried this:

https://github.com/bndtools/bnd/blob/7f5ff09fe35ec0ca622756e27ff9dc8a916bd7c7/bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java#L389-L395

 but the `EMPTY_INDEX` does not seem to do what we want.

**Comment by gamerson** [comment]
Thanks @bjhargrave  for reminding why we needed both the compiled jar and the project ref, I knew there was a requirement behind it.  

So as far as a fix, I can dig around the JDT sources and see if we have any options.  The "Java search" query is hookable, however, I don't know if we can filter existing results instead of adding more results.  

One thing we can do is 'hack' the 'filters' list that shows up Java search results page.  I've tested this out and it works, but requires reflection/internals hack which is quite ugly.

**Comment by bjhargrave** [comment]
> requires reflection/internals hack which is quite ugly.

Yes, lets not do this. We need to be able to run on many versions of Eclipse and don't want to get burned when such reflective hacks break. We have been burned by using internal packages before.

**Comment by gamerson** [comment]
So it turns out we can use standard search API query listener to remove these duplicate matches.  

The PR is API safe (no internal imports or reflection), but I ame doing a FQN check on an internal to predicate our filtering process.

**Comment by gamerson** [comment]
The PR i sent only fixes the searching for "References" or "Declarations".  The "Open Type" dialog still shows the duplicate.    There is a way to open a "Type dialog" with a filtering extension.  however, we would need to write our own "open type" action shortcut to invoke our own specialized type dialog "Open Filtered Types..." or something like that.  Let me know if anyone would be interested in that and I can open an issue.
