### ISSUE TITLE
Jar File Viewer's Print tab does not update on bundle rebuild

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#4017]
When a bundle is rebuilt, the Tree tab of an open Jar File Viewer will display the updated bundles contents. But the Print tab no longer seems to update. Wondering if this may be a side effect of the addition of searching to the Print tab?

**Comment by gamerson** [comment]
Hey @bjhargrave   I'm not seeing this behavior, for me its updating.  What exact scenario are you seeing the missing update? 

However, I am seeing this issue

Search for some text in the 'find' search box like 'foo', and see there are no results, then modify the jar contents so that there will be a 'foo' in the content, but the 'search' results are not updated accordingly.   I could fix this issue pretty easily I think.

**Comment by bjhargrave** [comment]
I opened a Jar File viewer for a bundle and went to the Print tab. I then modified a manifest header in the bundle (via editing bnd file) and after rebuilding, I can see the changed manifest in the Tree tab but the Print tab still shows the prior manifest.

**Comment by gamerson** [comment]
I'm not seeing that problem.  

![jarupdate](https://user-images.githubusercontent.com/595221/81209788-95d74180-8f96-11ea-90b4-d25827c8d569.gif)

**Comment by bjhargrave** [comment]
Weird. 

If the manifest change comes from editing the project's bnd.bnd file, then the viewer always updates for the change. 

But I was making the change in cnf/build.bnd (changing a common header like Bundle-Copyright). When you change the manifest via a change to cnf/build.bnd, then the problem occurs. I am not sure how the viewer is notified that the underlying file has changed.

**Comment by gamerson** [comment]
Ok, I can try to check that case as the flow is a bit different.

**Comment by gamerson** [comment]
I've sent this PR https://github.com/bndtools/bnd/pull/4023 but that doesn't fix this problem which seems to be related to 'lastModified' time of the jars.  I looked at that code and I'll have to yield() to BJ on that one.
