### ISSUE TITLE
[mvn repo] MavenBndRepository.get() is always synchronous

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4056]
The contract for `RepositoryPlugin.get()` is that if you don't supply a `DownloadListener` then it will execute synchronously, but if you supply at least one `DownloadListener`, the call will execute asynchronously and signal through the callback when it is done.

In appears that `MavenBndRepository.trySources()` honours this contract. However, unless I'm missing something, it seems that the main code path for `MavenBndRepository.get()` (ie, when fetching binary jars) does not - the download always happens sequentially even if the caller supplied a `DownloadListener`.

I'm not sure how this might be impacting on the user experience, or if there were technical reasons why it needs to always be synchronous. But maybe it will help if it could run asynchronously.

**Comment by bjhargrave** [comment]
> The contract for `RepositoryPlugin.get()` is that if you don't supply a `DownloadListener` then it will execute synchronously, but if you supply at least one `DownloadListener`, the call will execute asynchronously and signal through the callback when it is done.

I don't think the contract requires the download to be async. Just that it can be async.

The MavenBndRepository implementation currently updates in a "bulk" fashion. It gets all the archives in the index file and when all are available and processed into Resources, it updates the archives map and a bridge repository over them. The actual fetching from the remote repo is async, so that downloads can overlap, but this is joined together by the update logic.

The get method depends upon the archives map and bridge repository, so it waits until any in-flight update operation is complete. Normally, once the first update is complete, all the files are locally available, so the get method can immediately supply them. Even to a download listener.

So I don't think any change is suitable here.
