### ISSUE TITLE
bnd-maven-plugin: Allow to tweak builder class path via parameter

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#4057]
Currently the build classpath just takes the Maven project dependencies (https://github.com/bndtools/bnd/blob/a2e6afc591bae1353a4c91496c3f0d93f0f03a2b/maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/AbstractBndMavenPlugin.java#L220) as input. In some edge cases this is not enough:

Consider a bundle `a` which is supposed to work with older bundle `b v1.0` but also optionally leverages a feature from bundle `b v1.1`. To be able to build `a` the Maven dependency must depend on `b v1.1` but bnd should generate import-package version ranges derived from `b v.1.0` to still allow it to run together with `b v1.0`. That would allow to just tweak that one package import version range which contains the optional feature. 

To allow that `b v1.0` should be manually added to the build classpath (before `b v.1.1`). That way the import-package version ranges would ensure compatibility with `b v1.0` except for that one package containing the new feature.

If changing the build classpath is not supported one can no longer rely on any import-package version range towards `b` and must manually override all of those (which is a lot of effort if `a` consumes a lot of packages from `b`).

**Comment by bjhargrave** [comment]
So why not set the Import-Package range manually in the bnd config since you know it can be lower than the version exported by b v1.1? This is how you do this rather than putting 2 versions of b on the buildpath.

**Comment by kwin** [comment]
> must manually override all of those (which is a lot of effort if a consumes a lot of packages from b).

It is just a matter of effort here. I would like to leverage bnd for all packages except for the one with the new feature.

**Comment by bjhargrave** [comment]
`Import-Package: some.package;version="[1.0,2)", *` will leverage bnd for all the the packages.

**Comment by kwin** [comment]
`*` will generate the version ranges for `b v1.1`. I want the ones for `b v1.0`!

**Comment by bjhargrave** [comment]
So you want maven to put to versions of an artifact on the compile path?

**Comment by kwin** [comment]
I don't want to change the Maven compile path, but only the bnd build path! For Maven the versions of packages don't matter, therefore Maven only needs `b v1.1` while for bnd I would actually prefer `b v1.0`!

**Comment by bjhargrave** [comment]
So compile against 1.1, but jar against 1.0 + 1.1? There is no mode in Bnd (maven, gradle, or otherwise) that does this. When we add things to Bnd, we carefully try to support that thing across the various usage modes.

I don't think this is a good idea. It is a recipe for generating bundles which will fail since they can resolve against old package versions but require types/members from new package versions. So I don't think it is a good or wise feature to add.

For your special case where you _know_ what you are doing with protective code around using a newer version's feature, you will need to special case your Import-Package to support this

**Comment by kwin** [comment]
I am not proposing to change bnd but actually only introducing a parameter to `bnd-maven-plugin` to add additional artifacts to the bnd builder path (by slightly extending https://github.com/bndtools/bnd/blob/d725be405c1b0b017d8e4babd06d9f5c325e6e4c/maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/AbstractBndMavenPlugin.java#L223). Would it be ok if I come up with a PR for that (or will that have zero chance of getting merged)?

**Comment by rotty3000** [comment]
I disagree with this line of thinking.

Also, your statement that for `Import-Package: some.package;version="[1.0,2)", *` that `*` will result in imports for `some.package` also with version `1.1` is wrong. Bnd does not do that. If it does that is a bug and that's what should be reported.

**Comment by kwin** [comment]
@rotty3000 I think you missed the point. bnd behaves totally correct by calculating the import-package version range from the given Maven dependencies. As the Maven dependency is `b v1.1` it will by default generate version ranges starting from the package version exported by `b v1.1`. In this case I would be interested though in the package version range starting from the package version exported by `b v1.0`. Hope that makes it clearer!

**Comment by rotty3000** [comment]
So, exactly as @bjhargrave specified, override the import version since you, the human who knows that you want to continue (and CAN continue to support the lower version), are in control of the build. There is no other mechanism required here. Bnd already supports this and we do this quite a lot all over the place in other projects.

**Comment by rotty3000** [comment]
I'll repeat the answer is: `Import-Package: some.package;version="[1.0,2)", *` where `1.0` here is the lower bound for the single package you wish to retain.

**Comment by kwin** [comment]
My `b v1.0` has around 30 package exports (all used). All versioned differently. If I pass `b v.1.1` I need to overwide (potentially) the import ranges of 29 package imports. If I would pass `b v.1.0` I would only need to overwrite 1 package import version range.

**Comment by bjhargrave** [comment]
The bnd maven plugins _are_ part of Bnd. So they should not be though of otherwise.

I will note that the Bnd Gradle plugin does allow you to specify the classpath for the builder: https://github.com/bndtools/bnd/tree/master/biz.aQute.bnd.gradle#classpath

>  You will only need to specify this property if you want to specify additional classpath elements or replace the classpath.

However, the Bnd Gradle plugin is fundamentally different than Maven. In Gradle, the Bnd Gradle plugin is in complete control of the jar generation. In Maven, all we can do is modify the target/classes folder including manifest generation.

To add configuration to bnd-maven-plugin to allow replacing the classpath or extending could be done, but I am not sure how useful it is. How would one specify the additional/replacement artifacts? In Gradle you have a powerful configuration model to define artifacts and a configuration can be used to define the additional/replacement classpath. How would the equivalent be done in maven?

**Comment by kwin** [comment]
I will come up with a proposal in a PR which leverages the Maven repository under the hood. Can you reopen this issue for the time being. Then we can discuss based on my PR.

**Comment by bjhargrave** [comment]
> Can you reopen this issue for the time being. Then we can discuss based on my PR.

**Comment by rotty3000** [comment]
@kwin there is the other issue, why no merely use v1.0 while compiling? Maven doesn't support multiple versions of an artifact per project, but each project may specify their own version.

**Comment by bjhargrave** [comment]
Your idea is also predicated on adding the old version to the _start_ of the classpath, before the new version (used to compile). That would mean a complete replacement classpath for the builder since I don't think we should have config options for putting things at the beginning and at the end of the classpath.

**Comment by kwin** [comment]
I cannot use v1.0 because I also use an optional feature from v1.1

> Consider a bundle a which is supposed to work with older bundle b v1.0 but also optionally leverages a feature from bundle b v1.1. To be able to build a the Maven dependency must depend on b v1.1

**Comment by kwin** [comment]
> since I don't think we should have config options for putting things at the beginning and at the end of the classpath.

This is possible with the gradle plugin. So why not making the same feature available for the Maven plugin.

But for the reference: Yes in my use case I would need to insert a new artifact to the beginning of the classpath!

**Comment by bjhargrave** [comment]
Finally, even with a change to get 2 versions of the jar on the builder classpath, you will then need to configure Import-Package `-split-package` directive or `-fixupwarnings` to elide all the warnings about multiple versions of the packages on the classpath.

**Comment by bjhargrave** [comment]
> This is possible with the gradle plugin.

It is not possible. You can replace, or add more _at the end_.

**Comment by rotty3000** [comment]
This seems like a rare enough occurrence that the original solution should handle the case. You simply have to specify individual packages that you know need to retain a lower import boundary using the `Import-Package` header.

**Comment by rotty3000** [comment]
I could also offer that maybe the bundle which has this optional feature (hopefully in a separate package) shouldn't be part of the same bundle. It sounds like the API surface of the bundle you need to compile against is too large and too complicated. Time to modularize.
