### ISSUE TITLE
Maven Plugin to check if bundle can be resolved in a certain OSGi container

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#4058]
It would be helpful to have an additional Maven goal which could check if a given bundle could be resolved at runtime in a container given through a `bndrun` file. That is it would check if the mandatory import-package headers could be resolved.

That way one could easily check compatibility of your bundles with certain distributions. I have in mind to check against the minimum supported version as well as the maximum support versions of dependendent bundles.

**Comment by bjhargrave** [comment]
You mean like the [bnd-resolver-maven-plugin](https://github.com/bndtools/bnd/tree/master/maven/bnd-resolver-maven-plugin)?

**Comment by kwin** [comment]
I tried that. Maybe I do not really understand what the goal `resolve` does but I could not bring it to fail my build even if the built bundle would not work with a given set of bundles...

**Comment by bjhargrave** [comment]
Sounds like you have usage questions, which should be asked in the bndtools-users mail list. See <https://github.com/bndtools/bnd#feedback>, rather than an issue with Bnd.

You can also look at https://github.com/osgi/osgi.enroute which uses the Bnd maven plugins and the test cases for the bnd-resolver-maven-plugin.

**Comment by rotty3000** [comment]
Yeah, the answer here is the resolver plugin/task. This exactly what it's for.
