### ISSUE TITLE
NPE while building the workspace

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#4085]
The following error log gets generated after clicking on the new `Reload Workspace` button on the `Bndtool Explorer` View.

```
eclipse.buildId=4.15.0.I20200305-0155
java.version=1.8.0_241
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.java.product -keyring /Users/amit/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.java.product -keyring /Users/amit/.eclipse_keyring

org.eclipse.core.jobs
Error
Wed May 20 20:37:14 CEST 2020
An internal error occurred during: "Reload".

java.lang.NullPointerException
	at bndtools.explorer.BndtoolsExplorer$3.lambda$run$1(BndtoolsExplorer.java:369)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:185)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Installed Bndtools Version: `5.2.0.DEV-202005241847-gaad2b9c`

**Comment by kriegfrj** [comment]
I just saw this too when working on a bndtools-maven project (osgi-test).

**Comment by kriegfrj** [comment]
When I got my error, I also found this error in the Eclipse log:

`Cannot find workspace location for bnd configuration file C:\Users\fr.jkrieg\.bnd\default-ws\cnf\build.bnd`

**Comment by bjhargrave** [comment]
The issue is here:

https://github.com/bndtools/bnd/blob/7407d061496bc4ce6ad5f304c61b2eca8c1751c3/bndtools.core/src/bndtools/explorer/BndtoolsExplorer.java#L370-L372

For non-Bnd workspace builds (like osgi-test which is a maven build), the call `Central.getWorkspaceBuildFile()` returns null since it is a standalone workspace. And then the job take an NPE since `workspaceBuildFile` is null.
