### ISSUE TITLE
Replace Central.getWorkspace() with something better

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#4108]
@rotty3000 and I discussed this and we need something better. I would like to use this issue to capture the requirements we currently meet and what we want a replacement solution to do better.

[Goals]
- support non-bndtools-workspace scenarios (like M2E and in the future ?buildship?)
- identify workspace tasks that need to be executed whenever the workspace object is replaced vs. task that merely need to execute at that moment in time with whatever workspace is available (for instance a task that repopulates the UI on some event vs. task performing one time setup (and therefore would need to be informed of a new/different workspace instance)

**Comment by rotty3000** [comment]
One significant issue is when other tool chains wish to participate in the Bndtools UI but there is no _real_ bndtools workspace. For instance, M2E projects. The issue is that Central's work queue is only resolved when a real bndtools workspace exits; as opposed to the default workspace that is created when there is no actual bndtools workspace.
