### ISSUE TITLE
[gradle] Add runtime dependency information

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4186]
Forgive me if I haven't understood something properly here; however it seems that the Gradle TestOSGi task doesn't add any dependency information for runbundles (and probably not for runpath). At least, my experience indicates that this seems to be the case when using it with a custom bndrun file.

This being the case, it would be good if the `TestOSGi` task examined `-runbundles` and `-runpath`, and automatically added dependency information for any bundles it finds that are artifacts of other projects in the current workspace (ie, those flagged as `version=snapshot`).

My use case: in order to try and debug the intermittent integration testing issues (#4163), I tried to create a trimmed-down version of the build script that would do the minimal building required to run the specific integration tests that I was interested in. However, simply running "gradlew :bndtools.core.test:check" didn't work as there were a number of run-time dependencies that weren't built. Even when I tried "gradlew assemble :bndtools.core.test:check` it would fail intermittently (which I suspect is due to parallel building).

**Comment by bjhargrave** [comment]
The `testOSGi` task depends upon the project's `jar` task

https://github.com/bndtools/bnd/blob/b49f6c5252e54b43bbad40e7b4d380412ad77e8b/biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy#L381

But any additional dependencies for execution tasks such as `testOSGi` are not considered as there is no reasonable way to safely know what they are. We explicitly do not compute the runbundles or runpath during project preparation.

https://github.com/bndtools/bnd/blob/b49f6c5252e54b43bbad40e7b4d380412ad77e8b/biz.aQute.bndlib/src/aQute/bnd/build/Project.java#L423-L427

This is because it is quite possible and sometimes reasonable to have project circularity in the run lists. Such circularity must not prevent building. So the computation of the run lists is always deferred until they are actually needed for execution.

https://github.com/bndtools/bnd/blob/b49f6c5252e54b43bbad40e7b4d380412ad77e8b/biz.aQute.bndlib/src/aQute/bnd/build/Project.java#L962

Since Gradle must compute all task dependencies during the configuration phase, the Bnd gradle plugin cannot safely ask Bnd for the run lists since we risk triggering project circularity issues which do not apply to building.

So I don't think we can safely do what you ask here.

**Comment by kriegfrj** [comment]
Hmm, ok - for now I have manually added the dependencies to the gradle task definition.
