### ISSUE TITLE
SCR won't resolve

### ISSUE THREAD

**Issue by dkorchagin** [bndtools/bnd#4196]
After upgrading bndtools to 5.1.1 I started to face an issue that org.apache.felix.scr stopped resolving and now reports the following capability missing:

Resolution failed. Capabilities satisfying the following requirements could not be found:
    [<<INITIAL>>]
      ⇒ osgi.identity: (osgi.identity=org.apache.felix.scr)
          ⇒ [org.apache.felix.scr version=2.0.6]
              ⇒ osgi.implementation: (osgi.implementation=osgi.metatype)
                  ⇒ [org.eclipse.equinox.metatype version=1.4.100.v20150408-1437]
                      ⇒ osgi.wiring.package: (&(osgi.wiring.package=org.eclipse.osgi.util)(version>=1.1.0)(!(version>=2.0.0)))

When I blacklist org.eclipse.equinox.metatype it reports this:

Resolution failed. Capabilities satisfying the following requirements could not be found:
    [<<INITIAL>>]
      ⇒ osgi.identity: (osgi.identity=org.apache.felix.scr)
          ⇒ [org.apache.felix.scr version=2.0.2]
              ⇒ osgi.implementation: (osgi.implementation=osgi.metatype)
    [org.apache.felix.scr version=2.0.6]
      ⇒ osgi.implementation: (osgi.implementation=osgi.metatype)

It obviously need that osgi.metatype implementation but from my repositories it's only provided by that equinox bundle. I have the following Distro repository configuation (from my old cnf):

-plugin.1.Distro:\
	aQute.bnd.repository.maven.pom.provider.BndPomRepository;\
		releaseUrls=https://<...>;\
		revision=org.osgi:osgi.enroute.pom.distro:2.0.0;\
		name=Distro;\
		location=/tmp/src/cnf/cache/enroute-distro.xml

Maybe something happens to that Distro repo and I need to update it?

Please advise.

**Comment by rotty3000** [comment]
Such resolution failure could be attributed to a number of things. Could you provide a small repository that reproduces the issue we can try?

**Comment by dkorchagin** [comment]
I am using BndPomRepository plugin, pointing out to our internal corporate proxy, which in turn points out to Maven Central I believe, so that should be exact enroute Distro. Or what do you mean by a "small repository"?

**Comment by dkorchagin** [comment]
Even empty bare bone Felix runtime, pluss gogo shell and gogo command project fails to resolve when you add scr as a requirement.

**Comment by rotty3000** [comment]
Sorry for not being clear enough. I meant something like a git repository that reproduces the issue which I could clone and test.

> Even empty bare bone Felix runtime, pluss gogo shell and gogo command project fails to resolve when you add scr as a requirement.

Understood, but there are many ways to assemble a project using bnd and there's not enough details to reproduce the one your are having issues with.

**Comment by dkorchagin** [comment]
Ok.. I attempted to reproduce the issue in my home env, so installed new Eclipse IDE, and bndtools, but everything worked just fine. However, I noticed difference in how newly created cnf is layed out, and I can see the runtime repository is different, so am going to reinstate the same in my working environment and see if it fixes my issue.

**Comment by dkorchagin** [comment]
I had to manually create cnf and stuff inside it. It looks like that solved the SCR resolving issue. Now I am facing a different one that whatever I add to the -buildpath in a project's bnd.bnd file it won't appear on the project build path. In fact, there's no Bnd Bundle Path resource inside the project , nor there's Referenced libraries one. Also I noticed the folder layout becomes sort of Mavenish, which I don't want. Can you advise how I can make it more 'traditional', like Eclipsish?

**Comment by dkorchagin** [comment]
I suspect that they've ruined my Eclipse installation, so will reinstall it clean and see.
My question about 'Mavenish vs. Eclipsish remains' - can you suggest anything @rotty3000 please?

**Comment by dkorchagin** [comment]
So restored everything - was that Eclipse installed under user directory was vulnarable. Reinstalled it clean into local and it works. I have also removed that maven-layout.bnd from cnf/ext and it stopped generating those Mavenish folders. Just need someone to confirm that was the right way to get rid of maven layout. Can you please confirm?

**Comment by rotty3000** [comment]
> I have also removed that maven-layout.bnd from cnf/ext and it stopped generating those Mavenish folders. Just need someone to confirm that was the right way to get rid of maven layout. Can you please confirm?

That is correct! :)

Nice job solving all this on your own!

**Comment by kriegfrj** [comment]
> Now I am facing a different one that whatever I add to the -buildpath in a project's bnd.bnd file it won't appear on the project build path. In fact, there's no Bnd Bundle Path resource inside the project , nor there's Referenced libraries one. 

I've noticed this issue come up sometimes - there are two possible causes:

1. For some reason, your project's `.classpath` file is missing the BndContainer - there should be an entry like `<classpathentry kind="con" path="aQute.bnd.classpath.container"/>`. Alternatively, you need to have the Bndtools builder and nature in your `.project`, which can also be missing. This doesn't normally happen unless you've manually messed around with these files or if you've created a plain Java project in Eclipse instead of a Bndtools project. To fix it, compare it with an existing Bndtools project and make sure you add any missing entries (but then, please see the next point).
2. Sometimes your project has the right entries in `.classpath` and `.project`, but Bndtools still doesn't notice them for some reason. I've not done any systematic investigation of this, but I think it usually happens when the files are updated outside of Eclipse - typical reasons this has happened to me are: I've copied the new project into my workspace directly on the filesystem, or it's been created by a recent checkout from Git, or I've manually messed with the project files (eg, as in the first point). In these cases, restarting Eclipse fixes the issue - in fact, I think more recently I tried the (less time consuming) approach of simply closing the affected project and re-opening it, which also seems to work.

**Comment by dkorchagin** [comment]
Thanks @kriegfrj & @rotty3000 for your comments!
In my particular case there was obviously an issue in how our corporate virtual machines are handled, so that they messed up with Eclipse and configuration files and that caused a lot of crazy problems. Also you, guys, have changed a lot since I was here to get bndtools for the first time. Well, I think it's now better, but it's simply not compatible with earlier stuff and that was not very obvious.
Anywise, thanks for you help!
