### ISSUE TITLE
WAP mode of bnd-maven-plugin:5.0.1:bnd-process (default-bnd-process) should ignore SYSTEM dependencies

### ISSUE THREAD

**Issue by verastoyanova** [bndtools/bnd#4211]
Please check out AbstractBndMavenPlugin.java line 253. 

I believe the Artifact.SCOPE_SYSTEM should be also excluded.  It brings dependencies of type system within the WEB-INF/lib directory and messes up with the MANIFEST.MF creation. 

if (isWab && !hasWablibs && !Artifact.SCOPE_PROVIDED.equals(artifact.getScope())
&& !Artifact.SCOPE_TEST.equals(artifact.getScope()) && !artifact.isOptional()) {
......

**Comment by bjhargrave** [comment]
Perhaps you can make a pull request? See CONTRIBUTING.md in the repo for information on contributing.

**Comment by verastoyanova** [comment]
If you agree that the SCOPE_SYSTEM should be ignored and it is not deliberately left out from the if, I would gladly create a pull request.

**Comment by bjhargrave** [comment]
> If you agree that the SCOPE_SYSTEM should be ignored

I will let @rotty3000 make the call on that.

**Comment by rotty3000** [comment]
We just need to confirm the behaviour of the maven-war-plugin with respect
to how it handles system dependencies and follow suite. I'm suggesting that
the existing code possibly contains an oversight in this regard.

**Comment by rolfwilms** [comment]
Please consider the following analysis of how the maven-war-plugin handles dependency scopes.

a) maven-war-plugin
Reference: https://github.com/apache/maven-war-plugin/blob/master/src/main/java/org/apache/maven/plugins/war/packaging/ArtifactsPackagingTask.java
Line 82: final ScopeArtifactFilter filter = new ScopeArtifactFilter( Artifact.SCOPE_RUNTIME );
Line 99: if ( !artifact.isOptional() && filter.include( artifact ) )

b) maven-common-artifact-filters/ ScopeArtifactFilter.java
Reference: https://github.com/apache/maven-common-artifact-filters/blob/master/src/main/java/org/apache/maven/shared/artifact/filter/ScopeArtifactFilter.java
Line 50: private boolean includeSystemScope; 
Line 85: public ScopeArtifactFilter( String scope )
Line 91: else if ( DefaultArtifact.SCOPE_RUNTIME.equals( scope ) )
Line 93: setIncludeRuntimeScopeWithImplications( true );
Line 395: 
    public ScopeArtifactFilter setIncludeRuntimeScopeWithImplications( boolean enabled )
    {
        includeCompileScope = enabled;
        includeRuntimeScope = enabled;
        return this;
    }
Line 139: 
        else if ( Artifact.SCOPE_SYSTEM.equals( artifact.getScope() ) )
        {
            systemScopeHit = true;
            result = includeSystemScope;
        }

**So looking at the code the maved-war-plugin uses to filter artifatcs to be packaged, SYSTEM scope dependencies are NOT included.**

I'd recommend to use the same code in bnd the maven-war-plugin uses to filter dependencies to be packaged.
I.e. using 

final ScopeArtifactFilter filter = new ScopeArtifactFilter( Artifact.SCOPE_RUNTIME );
 if ( !artifact.isOptional() && filter.include( artifact ) ) {...}

instead of using 

if (isWab && !hasWablibs && !Artifact.SCOPE_PROVIDED.equals(artifact.getScope())
&& !Artifact.SCOPE_TEST.equals(artifact.getScope()) && !artifact.isOptional()) {...}

**Comment by rolfwilms** [comment]
I've created a test ([see here](https://github.com/rolfwilms/maven-artifact-test)) which uses `ScopeArtifactFilter(Artifact.SCOPE_RUNTIME )` to check which artifact scopes are packaged by the maved-war-plugin. Please see the result in the table below.

System scope artifacts are in fact NOT packaged by the maved-war-plugin.
AFAICS this is the only omission in the corresponding bnd code, as the scopes provided and test are already excluded.

|Scope|Artifact Scope|Included|
|--------------------|--------------------|----------|
|runtime|compile|YES|
|runtime|compile+runtime|YES|
|runtime|import|YES|
|runtime|provided|NO|
|runtime|runtime|YES|
|runtime|runtime+system|YES|
|runtime|system|NO|
|runtime|test|NO|
