### ISSUE TITLE
Programmatically exclude packages from being exported which are included via includeresource

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#4219]
In my bnd I have an include like
```
-includeresource: @some-bundle-[0-9.]*(-SNAPSHOT)?.jar
```
together with
```
# export all versioned packages except for conditional ones (https://github.com/bndtools/bnd/issues/3721#issuecomment-579026778)
-exportcontents: ${removeall;${packages;VERSIONED};${packages;CONDITIONAL}}
```

The bundle with filename `some-bundle-...jar` is by that completely embedded in my current bundle. Still its packages are being exported as well, due to the `-exportcontents` statement.

It would be nice to be able to exclude also the packages which are embedded via some query for [macro `packages`](https://bnd.bndtools.org/macros/packages.html) similar to what can be done with `CONDITIONAL`.

**Comment by bjhargrave** [comment]
The adding of content via `-includeresource` is done (in Builder) before analyzing the content (in Analyzer). 

https://github.com/bndtools/bnd/blob/38ef85e389678370304846d6b09ffd31f9efb87d/biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java#L114-L124

`-includeresource` also does not understand packages as a complete unit, so it can add things to a package already included in the jar.

During analysis, Bnd does not know that a package came in (whole or part) via `-includeresource`. So there is no way to generate a list of packages which came in via `-includeresource`. And since `-includeresource` can add to a package, it is not clear whether such a package should be in a list of packages which came in via `-includeresource`.

**Comment by rotty3000** [comment]
Couldn't you use:
```
Import-Package: \
    !foo.*,\
    !bar.*,
    *
```
along with the other instructions to indicate what should NOT be imported? This is what I've always used.

**Comment by rotty3000** [comment]
Sorry, exported... not imported, I read but did not compute that...

**Comment by kwin** [comment]
I was hoping for a way, which doesn't force me to list all embedded packages manually, but as @bjhargrave points out, this is not easily doable that way. Thanks guys for the answers.

**Comment by bjhargrave** [comment]
Closing since we don't know that a package is in the bundle due to `-includeresource`.

**Comment by strmecki** [comment]
@kwin did you find a solution for this? I raised a similar issue: https://github.com/bndtools/bnd/issues/4631

**Comment by kwin** [comment]
No, I ended up manually maintaining the export for the affected bundles.
