### ISSUE TITLE
[jareditor] BndtoolsJAREditorTempFiles should move somewhere else

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#4247]
The temp files folder created by the jar editor goes in the top-level folder of the Bnd workspace and often gets in the road, falsely appearing as a project or a resource in Eclipse. In the latest installment it seems that `BndtoolsBuilder` actually tried to build it, because I have a compiler compilance warning about the resource `BndtoolsJAREditorTempFiles`. :smile:

Given that this is a Bndtools implementation detail and not a Bnd-wide folder, perhaps it would be better if it went somewhere else. A couple of suggestions:

* In the private storage area for the `bndtools.jareditor` plugin
* In the user's temp directory

**Comment by bjhargrave** [comment]
@pkriens and @gamerson would be the most knowledgeable here.

**Comment by bjhargrave** [comment]
@gamerson Can you look into this?

**Comment by gamerson** [comment]
Because of how Eclipse resources work, the temp jar files work best if they are stored in a "real" project that is "mounted" in the workspace.  We install filters that hide this project by default so you should be "seeing it" unless you disable the filters.  @kriegfrj  if you are "seeing" this project in the Bndtools/package/project explorer by default let me know.

 About the ` compiler compilance warning ` there is no reason that I can think of that the temp project should be a `java` project.  We should be able to leave it as a normal "general" project which shouldn't get built by Bndtools builder.  

I'll look into this issue.

**Comment by gamerson** [comment]
FYI:  this change doesn't require any migration, however, if you want to get the "simpler" form of the TempProject, i.e. the temp project that has java nature removed, then perform the following steps:

1) close any open jar files
2) unhide the temp project filter from view
3) delete existing temp folder

The `BndtoolsJAREditorTempFiles` will be recreated in simpler form  on next jar editor instance.

**Comment by kriegfrj** [comment]
> Because of how Eclipse resources work, the temp jar files work best if they are stored in a "real" project that is "mounted" in the workspace. 

Right, i suppose that way you can leverage the inter-project navigation features of Eclipse, etc? Makes sense. 

> @kriegfrj if you are "seeing" this project in the Bndtools/package/project explorer by default let me know.
> 

There was a specific case; if i come across it again I'll try and capture it.
