### ISSUE TITLE
Upgrading to 5.2.0 breaks junit5 build

### ISSUE THREAD

**Issue by marcphilipp** [bndtools/bnd#4371]
Upgrading to 5.2.0 from 5.1.2 makes the junit5 build fail:
https://ge.junit.org/s/v2k7fc734iy56/failure#1

Here's a branch in case you want to try for yourself:
https://github.com/junit-team/junit5/tree/marc/bnd-5.2.0

Any ideas what might be causing this?

**Comment by bjhargrave** [comment]
@marcphilipp You seem to have changed the `Bundle-SymbolicName` of `junit-jupiter-params` (and perhaps all other artifacts) to add `-all` on the end:

```
Bundle-Name                             JUnit Jupiter Params
Bundle-SymbolicName                     junit-jupiter-params-all
```

And the `verifyOSGi` testing task is looking for an artifact with a `Bundle-SymbolicName` equal to the project name:

```
	property("-runrequires", "osgi.identity;filter:='(osgi.identity=${project.name})'")
```

But no `Bundle-SymbolicName' of `junit-jupiter-params` exists.

Do you mean to add `-all` to the end of the `Bundle-SymbolicName`s? This will cause load of issue for downstream users in OSGi since all their dependencies on `Bundle-SymbolicName` (similar to the bndrun file here) will be broken.

**Comment by marcphilipp** [comment]
No, that was not intentional. Why doesn't that fail with 5.1.2?

**Comment by bjhargrave** [comment]
Bnd 5.2.0 changed to include the jar task archiveClassifier property, if set, in the default `Bundle-SymbolicName` value:

https://github.com/bndtools/bnd/pull/4284

Since the build seems to set the `archiveClassifier` jar task property, it results in an undesired value for `BundleSymbolicName`.

See https://github.com/junit-team/junit5/compare/marc/bnd-5.2.0...bjhargrave:marc/bnd-5.2.0?expand=1 for the proposed fix. This explicitly sets `BundleSymbolicName` to the jar task's `archiveBaseName` property (which defaults to the project name.)

**Comment by marcphilipp** [comment]
Thanks for the explanation! I will fix it as you suggested. 👍

**Comment by bjhargrave** [comment]
FYI, I updated the fix for the export package versions to elide the SNAPSHOT qualifier in SNAPSHOT builds. The export version should not include qualifiers.
