### ISSUE TITLE
OSGiHeader.parseHeader() changes types

### ISSUE THREAD

**Issue by rovarga** [bndtools/bnd#4391]
This is coming from downstream, the original issue is here: https://issues.apache.org/jira/browse/FELIX-6337 .

The background is that maven-bundle-plugin wants to make builds repeatable, so it ends up sorting manifest entries and also manifest entry values -- all this having been done in https://github.com/apache/felix-dev/commit/76dba132d4abbab75f20dc5096649842c52e4810 .

During this operation, though, we lose type information, as suddenly `objectClass:List<String>` becomes `objectClass:String`, which has different semantics and fails at runtime.

I did not find a way of expressing to OSGiHeader, so it should at least have a method to achieve this.

Alternatively, it would be nice if bnd sorted the values, so maven-bundle-plugin would receive them ready to go.

**Comment by bjhargrave** [comment]
The order of entries in a manifest header value can matter. So Bnd should not sort the entries since that can possible break semantics.

maven-bundle-plugin can do that if it wishes and knows that the order does not if fact matter. But maven-bundle-plugin should use the actual Bnd type `Parameters` as the return type for `OSGiHeaders.parseHeaders`. Or at the very least `Map<String, Attrs>`. The `Attrs` type understands the type information. You can then correctly write a sort operation on the `Attrs` object which preserves the type information.

**Comment by pkriens** [comment]
Notice that Attrs and Parameters use LinkedHashMap so that the order should be repeatable. And as BJ states, sometimes the order is relevant.

**Comment by bjhargrave** [comment]
> The background is that maven-bundle-plugin wants to make builds repeatable

> Notice that Attrs and Parameters use LinkedHashMap so that the order should be repeatable.

Also, this sorting should not be necessary for repeatability. Bnd already strives very hard to support repeatable builds. So perhaps you should reconsider the need to sort the output of Bnd. Or point out where Bnd fails to properly be repeatable so we can address that.  Sorting the output of Bnd would just wallpaper over a real repeatability issue in Bnd.

**Comment by rovarga** [comment]
Thanks for the prompt response. I will take it back to maven-bundle-plugin to see what the original problem getting fixed was and come back.
