### ISSUE TITLE
[bnd-maven-plugin] -snapshot=${tstamp} implicitly set when Bundle-Version property not set

### ISSUE THREAD

**Issue by mfriedemann** [bndtools/bnd#4405]
Hey,

I found an issue with the bnd-maven-plugin (using version 4.3.1) and maven projects specifying a -SNAPSHOT version.
Specifically, it was replacing the -SNAPSHOT with a timestamp qualifier, despite the [bnd documentation](https://bnd.bndtools.org/instructions/snapshot.html) clearly saying

> The default is no substitution.

Switching verbose logging on showed that bnd was invoked with -snapshot=${tstamp}, which baffled us.
After consulting the difference to another project, where the -SNAPSHOT qualifier was kept, we found that when explicitly specifying "Bundle-Version" in the .bnd configuration files, bnd is not invoked with the -snapshot option.

Digging through the code, we arrived at

https://github.com/bndtools/bnd/blob/885ee4045ab3ffe4205473063c8f7f8b42c9abfa/maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/AbstractBndMavenPlugin.java#L312-L318

If the .bnd configuration files do not explicitly specify the "Bundle-Version" property, the plugin extracts the version from the maven POM and additionally sets the -snapshot argument to "${tstamp}", causing the replacement handling to kick in for -SNAPSHOT qualifiers and replacing them with the current timestamp.

It would be appreciated if this was either documented prominently or made configurable in the maven plugin.

Thanks,
M.

**Comment by bjhargrave** [comment]
This is an historical oddity of `bnd-maven-plugin`. See <https://github.com/bndtools/bnd/tree/master/maven/bnd-maven-plugin#reproducible-builds> where it is mentioned. Since some users may depend upon this behavior and the behavior only affects snapshot builds and not release builds, we have retained the behavior. As you can see from the code, for [reproducible builds](https://maven.apache.org/guides/mini/guide-reproducible-builds.html), we no longer use `TSTAMP` for snapshot builds.

> made configurable in the maven plugin.

It is configurable by configuring reproducible builds or by configuring  the Bnd instruction `-snapshot: SNAPSHOT`.

**Comment by mfriedemann** [comment]
Yes, I understand that you can overwrite that option yourself.
It is, however, not at all clear where and why it is active in the first place. AFAICS, there is no mention of this behaviour anywhere.

That is why in the closing remark I wrote it would be appreciated if the implicit addition of "-snapshot=${tstamp}" could at least be [b]prominently[/b] documented, so the next person doesn't hit it and spends time trying to find the cause.

M.
