### ISSUE TITLE
[mvn,test] Resolve and Run bndruns paralell

### ISSUE THREAD

**Issue by stbischof** [bndtools/bnd#4421]
Provide a way to resolve and run bndruns of one project in paralell.

**Comment by bjhargrave** [comment]
For maven projects, each bndrun can be a separate execution and if you configure maven for parallel mode, then can't you have the goals run in parallel? Our maven plugins support parallel. `threadSafe = true`

https://github.com/bndtools/bnd/blob/db576fae6accab19453403c4a505a3160ec63da5/maven/bnd-testing-maven-plugin/src/main/java/aQute/bnd/maven/testing/plugin/TestingMojo.java#L41

**Comment by rotty3000** [comment]
In fact each bndrun _should_ be associated with a separate execution since the bndrun configuration is tied to execution configuration AND integration with M2e is simply limited to 1:1 bndrun<->execution. I feel the fact that we allow multiple bndruns in bnd-*-maven-plugins should be deprecated at some point and perhaps document it as a caveat not to be used. I feel that was an early oversimplification which ultimately doesn't align well with the maven configuration model.

**Comment by rotty3000** [comment]
You'll notice that the most recent bnd-run-maven-plugin only accepts a single bndrun to reflect this.
