### ISSUE TITLE
Bndtools can't find model because project has no bnd.bnd file

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#4422]
I suddenly get errors on projects that have no bnd.bnd file.

Now I do think they should have a bnd.bnd file but this was not the case before, was it? At least I've never seen this error.

There error also does not go away when you create a bnd.bnd file.

**Comment by bjhargrave** [comment]
It has always been the case that a folder is not a Bnd project unless it has a bnd.bnd file. This is why the ProjectTracker has always required this as does the Bnd Gradle plugin.

**Comment by pkriens** [comment]
A better solution is to track the files on disk. However, we once tried to do this and then the Java support sucked for watchers. I remember especially for the Mac. Always impressed how fast git knows when files change.

Moving to abeyance for someone to write the watch support.

**Comment by bjhargrave** [comment]
But a folder without a bnd.bnd file is still not a Bnd Project. Are you asking that Bnd Projects no longer must have a bnd.bnd file? How would we recognize that a folder is a Bnd Project without a bnd.bnd file?

**Comment by pkriens** [comment]
Ok, sorry, not clear. The error is correct (although not easy to understand), it is not a project. However, the secondary problem is that if you add the file, the project tracker does not pick this up. There are probably alternative ways but I could only think of rebooting Eclipse. The refresh button of the workspace did not work for some reason.

**Comment by kriegfrj** [comment]
> I suddenly get errors on projects that have no bnd.bnd file.
> 

That would be because we merged #4404. I made the error checking on these issues quite a bit more thorough.

> The error is correct (although not easy to understand), it is not a project. 

This is good feedback - I didn't like the error message either when I actually saw it in a real scenario! If you have suggestions for how to improve the error message, let me know. It would be nice to get it right before 5.3 is released.

The code in questions is here: 
https://github.com/bndtools/bnd/blob/281ba24d230c3676e4a29f748d5335c307cee373/bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java#L133-L153

As you can see, the error message that you are seeing is the default message after it has exhausted the other known possible causes. I guess I could add one more check for the existence of a `bnd.bnd` file as another known cause before falling back to the default message - that would help. But if you have any suggestions on how to improve the default message that would be good too.

**Comment by kriegfrj** [comment]
> A better solution is to track the files on disk. However, we once tried to do this and then the Java support sucked for watchers. I remember especially for the Mac.

This is one of the rare areas where Windows is ahead as a development environment. Eclipse has a native implementation of file watching on Windows. On other environments (Mac/Linux), the file watching relies on polling and so doesn't scale well. As a result, Eclipse normally ships with this option  disabled by default. But I've started using it recently on Windows and it seems to work well. With this enabled, Eclipse will notice when a project gets a bnd.bnd file added and issue a `ResourceChange` event that you can pick up and respond to.

> Always impressed how fast git knows when files change.
> 

Me too. If we could do whatever EGit is doing, that seems to work well on all platforms. But then, I suspect all EGit needs to do is monitor a single .git directory for changes, which it can probably do efficiently use polling. I'm not sure that we can do the same - it wouldn't scale well in large workspaces to poll every single project (or candidate project) to see if the bnd.bnd file had appeared (or disappeared), or worse to see if a new project had appeared in the directory...

**Comment by pkriens** [comment]
I do notice more and more that under certain conditions, Eclipse does automatically refresh files. If I had time, I'd look into this.

**Comment by rotty3000** [comment]
> On other environments (Mac/Linux), the file watching relies on polling and so doesn't scale well.

This is simply not true. Mac/Linux have native inotify implementations which have existed eons before Windows ever had a FS notification mechanism and which Eclipse has been using for a decade at least. The only limitation is the ulimit set on the system level (number of allowed open file descriptors) which defaults to 1024, which is low (but set that way for safety and backward compatibility), but on modern systems can easily be set into the 100k range without any adverse effects.

**Comment by pkriens** [comment]
@rotty3000 sensitive anyone? :-)

**Comment by rotty3000** [comment]
Ughh... the past 3 months I've been forced to use Windows (since it's the ONLY OS allowed on corp laptops; which is wrong on so many levels). The REALLY sad part is that it's so bad the company's solution for doing any and all development work is to install Linux in Virtual Box!!! So yeah, I'm a little annoyed by Windows these days.

**Comment by kriegfrj** [comment]
> > On other environments (Mac/Linux), the file watching relies on polling and so doesn't scale well.
> 
> This is simply not true. Mac/Linux have native inotify implementations which have existed eons before Windows ever had a FS notification mechanism and which Eclipse has been using for a decade at least. The only limitation is the ulimit set on the system level (number of allowed open file descriptors) which defaults to 1024, which is low (but set that way for safety and backward compatibility), but on modern systems can easily be set into the 100k range without any adverse effects.

🤷 I'm only going by what the [Eclipse documentation](https://help.eclipse.org/2020-09/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Freference%2Fref-9.htm&cp%3D0_4_1_54) says:

**Refresh using native hooks or polling**: If this option is turned on then the workspace resources will be synchronized with their corresponding resources in the file system automatically using native refresh providers (on Windows) or a polling mechanism. **Note**: This can potentially be a lengthy operation depending on the number of resources you have in your workspace. **Default**: Off.

There is an [open Eclipse issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=108697) for the native Linux support which is over 15 years old (and I just noticed that you commented on that bug a few years ago!). It looks like from that bug that there are a few third-party refresh provider implementations, but that nothing has been integrated into the base Eclipse platform itself as yet. The bug is still open and there was a comment as recently as January this year.

Are you using the built-in provider (polling) on Linux without noticing any performance issues? Or are you using one of the experimental/3rd-party refresh providers that use native hooks or Java 7's `FileWatcher` API?
