### ISSUE TITLE
Performance [Idea]

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#4431]
Some of my customers are complaining that a full build is too slow, for some this was the reason to move to Intellij since the full build uses gradle --parallel.

I wonder if we could make a function that builds the full workspace in gradle but the refreshes the Eclipse workspace in a way that does not trigger a rebuild.

Clearly we will need to update the BndContainer and there are likely other things. However, lots of people work on several branches and then the rebuild can become killing.

For discussion.

**Comment by kriegfrj** [comment]
See also #3175 which might help fix this issue for changing branches. Often a bundle's implementation changes but its public API does not. If #3175 were implemented, those bundles would get rebuilt but their dependencies (and the dependencies of those dependencies) would not have to be rebuilt.

**Comment by pkriens** [comment]
Yes, that is a goal worth pursuing. However, we know the dependency graph so we can do a parallel build. The bnd command line is already doing a decent job. So doing a clean parallel build somehow seems as low hanging fruit?

**Comment by bjhargrave** [comment]
Maybe the answer to this is to figure out how to work with Buildship?

**Comment by kriegfrj** [comment]
I was thinking that too. That way it has long-term utility rather than a short-term hack.

This also raises another crazy thought: if the Buildship integration can be made to work well and with enough features (perhaps even with parallel build support), could this make the native `BndtoolsBuilder` obsolete? What does the `BndtoolsBuilder` give us that a full-featured Buildship implementation couldn't? I personally don't know enough about Buildship to answer that question, but I think it is a question worth asking.

**Comment by chrisrueger** [comment]
Today I was just experimenting a bit with:

`./gradlew build --parallel -t export.myapp`

- `--parallel` for parallel build
- `-t` for continuous build (based on [this article](https://blog.gradle.org/introducing-continuous-build))
- disabled _Build automatically_ in Eclipse to avoid that the two builders are triggering each other
- disabled _Build before launch_ in _Preferences / BNDtools_

It is building fine, I can also start the app via `bndrun` and also picking up code changes _continuous_ and it also seems bundles are properly uninstalled and re-installed (although it takes a bit longer than when Eclipse / bndbuilder starts building...). 
Only Eclipse is full of red markers now and both systems do not really play nice together perfectly. It obviously seems to be the problem @pkriens mentions initially. 

Advantage I see is that Eclipse "feels" more responsive when grade is building in the background.... I can save (press Ctrl+S) continue typing and do more things without Eclipse UI hanging.... not measured, just "feeling" so far. 

I find this issue here very interesting and just wanted to add this to the discussion.
