### ISSUE TITLE
bnd automatically adds maven dependencies

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#4438]
I got a complaint from a customer today that an OpenAPI gradle plugin suddenly had lots of dependencies. It turned out that, without me opting in, this plugin suddenly had lots of dependencies in the POM. One of the primary ideas behind OSGi is to work with package dependencies and not create long transitive dependencies, this felt rather regressive.

I fixed it by setting `-maven-dependencies` to empty, which seems to be the only way to disable it?

How come this was changed without me opting in to this big change in the metadata?

**Comment by bjhargrave** [comment]
We make changes to Bnd all the time to do a better job. We now are better at emitting service capabilities for factory components, for example.

When one upgrades to a newer Bnd version in their build, they will be exposed to new features. This is true for any build dependency (new maven version, new gradle version, new java version). So the developer must understand the impacts of updating a build dependency.

> I fixed it by setting `-maven-dependencies` to empty, which seems to be the only way to disable it?
> 
> How come this was changed without me opting in to this big change in the metadata?

This is the pom and this change was made several releases back. We use this extensively in our own build to generate useful pom information since our jars are also used in maven and gradle build which need valid pom dependencies to place the proper jars on the runtime classpath. I would assume that your OpenAPI jar must have some dependencies which you need to ensure are on the runtime classpath in a gradle build? So you would need to make sure that the pom you generate in the jar has the proper dependencies.

**Comment by pkriens** [comment]
In bnd you can make sure that you embed the packages you need. So the `compile` dependencies are completely wrong, dragging me back in transitive dependency hell. In my mind, dependencies are expensive and are a design thing. Bnd(tools) and OSGi try to provide a solution without transitive dependencies. Our default should be to _not_ have transitive dependencies. In this case, the plugin was designed to only depend on classes from the VM & Gradle. As it should be.

Surely this is useful for some people that live in a maven world, but we should never introduce these types of features without an opt-in.

**Comment by bjhargrave** [comment]
> but we should never introduce these types of features without an opt-in.

I guess we can agree to disagree.

In your special case (no actual need for the dependencies at runtime since you must conditional package them), you can disable the dependencies or scope them to provided. We generally do the latter in the Bnd build for conditional packaged dependencies.

Given that we have generated maven dependencies for several releases now (since 4.2.0), turning that off now (by making opt-in only) will be a breaking change for users currently expect them.

> Surely this is useful for some people that live in a maven world

Well it only matters for use in a maven (or gradle) world since the dependencies are only in the maven pom. If you are making a jar that is never used in a maven world, then it really does not matter what the pom dependencies are :-)

**Comment by pkriens** [comment]
No, no changes on a new release is pretty important for me. This is the umpteenth time I am bit by this. A new feature must mean opt in. 

And with this proposal, it is quite cheap and people that want to live dangerously do not pin the version.

**Comment by bjhargrave** [comment]
> No, no changes on a new release is pretty important for me.

What is the point of a new release if it does not do anything? Or, conversely, why upgrade Bnd if you don't want any new things?

> A new feature must mean opt in.

I don't agree. We should discuss in the larger maintainer team.

**Comment by pkriens** [comment]
yeah, we need to discuss this. Surprised with your objection though. With this proposal we make the living dangerous a choice without much cost. And it is more consistent.  We do not have to introduce these silly `-noxxx` instructions because we want to enable them by default for a new release. Sounds like a win-win to me.

**Comment by rotty3000** [comment]
Over time adding all the new feature flags would get tiring. What I've come to understand and admire of bnd(lib) is that over time it lets me do more by saying less. I actually make a concerted effort to eliminate as much configuration over time as I can. Therefore it would be counter productive in my mind to have to opt into new things all the time. Now, I agree where something might break we could/should have a period of graceful opt-in before making it default and I believe we have been trying to do that. Maybe we haven't caught every single case but that's not because we wished any bad experiences. However I think building a firewall around every new feature is not the right solution. I think we need a bit of case by case analysis (but also not block innovation) and remind ourselves we're human.

**Comment by pkriens** [comment]
I could not agree more that it should be easy, even automatic if you want, to take the new defaults. So did you read what I proposed? I just want to instill a discipline that _every feature is opt-in_, but we handle the opt-in via a release specific bnd properties file built in the release. I.e. the maven dependencies should have been driven by the -maven-dependencies instruction, which was in a properties file named bnd-5.0.0.bnd.

You can accept the defaults for a new release and automatically opt in. The version default file documents all the new features of this release and opts in. The more careful people can take advantage of bug fixes of a new release and then decide to opt in gradually or try the new release.

I also like the style that each feature is always an opt-in, we just make it convenient with a default opt in bnd file that is bound to the release version.

The problem is that we now have coupled bug fixes in a new release to the new feature. And that is imho a really bad coding style. For stable products, you might not touch a build for a long time. I always opposed this style, and I've bitten numerous times by this, but did not see a good solution. This proposal gives us _automatic opt-in_, documentation of new features pre release in a consistent way,  and a way to take the improvements of a new release without cratering your build.

The opposition feels kind of odd. We go out of our way to be backward compatible in our code but do not care that we break our customers willy nilly with new features that make fundamental changes in their metadata?

What is not to like?

**Comment by rotty3000** [comment]
Where does this bnd-5.0.bnd file live in every other scenario besides workspace? You mean I have to, not only update the plugin version, but also sprinkle these other bnd files all over the place (and in the future know to merge or replace old ones)? I don't think that is a nice experience and I certainly wouldn't endorse it for (non-workspace) gradle or maven use cases.

**Comment by pkriens** [comment]
No, it is the defaults bnd file in the bndlib. We already read a defaults.bnd for the workspace. We just have to make them per version. For the users there is nothing to do. Only if you want to stay on a given release, do you set the -defaultsversion instruction. From then on, you're in a stable feature mode for the chosen release. You can then enable new features one by one or pick a newer version for your defaults.

**Comment by bjhargrave** [comment]
We need to add documentation for maven dependency generation in poms.
