### ISSUE TITLE
Graceful compatibility

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#4439]
The change in maven dependencies, and the import of java, indicates that we do not have a good backward compatibility strategy. On one hand you want people to pick up the latest and greatest, on the other hand we do not want to crater builds when a new version is introduced.

I've already tried several approaches but not worked well. 

- `-gestalt` – too much work
– `-require` – Require a bnd version
– `since()` – Way, way too much work and it pollutes the code terribly

So I've got a new idea ... What if we make the defaults version specific? All our new features MUST have an opt-in model. However, we have one instruction that sets the defaults for a given version. 

         -versiondefaults      5.2

When 5.3 introduces a new feature, it is off by default. However, the version defaults for 5.2 opt-in for that feature if that is the best solution. So for maven dependencies, the opt-in could be:

          5.3 defaults
               -maven-dependencies                    *
               ....

Without this instruction, no dependencies are calculated.

Users not setting a `-versiondefaults` will revert to the current version, as today. However, more conservative users can manage them.

This is quite trivially to implement since we already read the defaults in the Workspace

WDYT?

**Comment by bjhargrave** [comment]
Sorry, but I am not at all understanding what problem you are raising here.

> The change in maven dependencies, and the import of java, indicates that we do not have a good backward compatibility strategy.

What do you mean here?

**Comment by pkriens** [comment]
We screw customers, in this case me, by introducing features that change things for them. I.e. the java import screwed me, got an upset customer. Now the maven dependencies screwed me again, another upset customer. 

We add features, which is good, but we should never enable them by default. Changing bnd should not create a different output unless people opt in to a specific feature.

This proposes a way to not opt in for each feature separately. Instead you can stay on older defaults, which do not opt-in of the newer features. These defaults also document nicely what features will be enabled.

**Comment by bjhargrave** [comment]
I think that having to wrap each new thing we do in an "enablement" block is a huge code bloat issue and detrimental to contributions. Why update Bnd if you don't want to use any new features?

I don't think this is a wise thing to do or impose on the Bnd developers. I would be opposed to it. We should instead be more clear in release notes about changes to Bnd so that if you do update Bnd to a newer version, you know what will be changing and if don't like it, you can disable it. For example, the Bnd 5.2.0 release notes clearly describe the change to import java packages and the `-noimportjava` option to disable that.

We are constantly improving things by making existing features more robust and complete. Having to wrap every such change in a code block which doesn't do the new thing unless some option is set will be a major mess in the code base and a huge source of bugs and we will need to then make test for both the enabled and disabled modes to ensure we are correct. I am not interested in signing up for that.

To the extent that a new feature may cause some users a problem, we generally provide a `-noxxx` instruction to enable people to disable it and we then document that in the docs and release notes.

**Comment by kriegfrj** [comment]
Ok, if I may summarise (what I think is) the story so far:

@pkriens has been bitten a couple of times when he upgraded to a later version and got a new feature he didn't want.
@bjhargrave said when you upgrade, you should be expecting new features, otherwise, why upgrade?
@pkriens said he upgraded because he needed a bug fix that was in the new version.

I kind-of agree with @bjhargrave that new features should not be disabled by default. However, they should not necessarily be enabled by default either. IMHO, the default should be whatever we anticipate the most common use case will be for the feature. That way we minimise the amount of configuration required.

However, perhaps it is reasonable to have an upgrade path that allows you to adopt bug fixes without having to adopt/adapt to new features.

Perhaps an alternative to this is to do a better job of releasing point-releases for bug fixes? That way @pkriens could update the latest micro release without worrying about a new feature that might break his build?

**Comment by pkriens** [comment]
> Perhaps an alternative to this is to do a better job of releasing point-releases for bug fixes? That way @pkriens could update the latest micro release without worrying about a new feature that might break his build?

@kriegfrj Your proposal to have bug fixes will make things more complicated for everybody, I think. The ad hoc handling of new features we had so far will make it hard to control that nothing slips through the crack in a bug fix. And then you're still stuck that if you want the new version for one feature, you have to accept all.

One advantage of the proposal is that we will have explicit list of the defaults for each feature, for each release.  This is exactly what my proposal achieves. By having all the new features enabled/disabled in the version specific default file for bndlib we can have it all? I can stick to the feature set defined by version X. If I want to follow what bnd does, I go with the flow. If I want to remain at X, I set the -versiondefaults specifically to the version I want. 

I am a bit flummoxed with the opposition. This proposal seems to give us:

* A well defined progress path since today it is an ad hoc decision of a designer if a feature is default enabled or not, 
* Consistent handling of new features (no more ugly negative -noxxx instructions, all features need to be explicitly enabled), 
* Very little extra work for us, just record the feature default enablement in the default-X.Y.Z.bnd file in bndlib,
* One place documentation of the feature feature set and their default enablement, 
* Per feature override, and 
* Allow adopting the new version's feature's defaults set as an explicit choice.

_Nothing_ changes for existing customers except that they get a _new feature_ to remain at an older version of the feature set if they explicitly chose so. It seems one of those rare cases where there is no downside for anybody? Can you see any?

If we do not go for this solution, I think we must make the default enablement of a new feature a decision in the bnd meeting or handle via an issue. I just do not have time to verify every PR that I am not going to be bit by it. And I am afraid that I will by default oppose enabling new features that change any metadata. For example, I would have opposed the Java import & the maven dependencies since they change metadata in a way that can hurt existing setups, like they did for all my customers at times.

Now some specific answers:

> I think that having to wrap each new thing we do in an "enablement" block is a huge code bloat issue and detrimental to contributions. Why update Bnd if you don't want to use any new features?

Well, looking at the problem I realized how un-bnd the Maven dependencies were done. All over bnd the basic idea is to use a _scope_ and then allow selection (*), rejection (!), addition(...), and attribute augmenting (*;foo=bar). I.e. the features of the Instructions class. The -maven-dependencies is now used to disable it but unfortunately, it does not provide any of the features one has come to expect of instructions, it is an odd beast. It is all or nothing while the problem at hand would suit the bnd model very well. I.e. if -mavendependencies had been a proper Parameters one could reject some dependencies or make sure the proper version is used. If you work this way, the enablement/disablement is basically built in. That is why Parameters and Instructions accept null. I think we have the same problem for the java import. It would have been more natural to have a -javaimport header that would allow the augmentation. Although I cannot think of one, there are always cases where you need this kind of override.

So if you do features the bnd way, it is not more code. However, even if you did have an enablement block, it would be 2 lines ... A huge code bloat issue? And it is moot, since the -noxxx instruction needs to be handled conditionally. Even the -maven-dependencies is tested.

> I don't think this is a wise thing to do or impose on the Bnd developers. I would be opposed to it. We should instead be more clear in release notes about changes to Bnd so that if you do update Bnd to a newer version, you know what will be changing and if don't like it, you can disable it. For example, the Bnd 5.2.0 release notes clearly describe the change to import java packages and the -noimportjava option to disable that.

You make the classic mistake of highly involved people. For you, bnd is your world. For many people it is a detail and they often do not look at it for a long time. Many workspaces work fine and do not need to be updated for a very long time. For them bnd is a tiny detail of their workload. The reason for an update is often a bug or the desire to use a new features. We've had numerous complaints of people that did this upgrade from a 4.1.0 release. That is a lot of release notes to crawl though and, lets not kid ourselves, they are not perfect. This proposal gives you a clear list of features in one place and their enablement for a given version. If you go from version X to Y, you compare the version defaults. You can then take the latest (as is today, developer controls the default), pick a version, or look at the latest list and override the ones you disagree with.

> To the extent that a new feature may cause some users a problem, we generally provide a -noxxx instruction to enable people to disable it and we then document that in the docs and release notes.

Yeas, and these -noxxx instructions are ugly. They sort in the wrong place and they force people to think the wrong way. Worse, they are inconsistently applied. I used them and accepted them because I did not see another solution to provide good defaults for most people, but always disliked them. However, this proposal finaly allows me to eat my cake and have it too. All features are disabled by default and are explicitly disabled in the code and then enabled by the version specific defaults in bndlib.

----

This is a collaborative process and I think we need some rules to not step on each other's toes. This proposal provides a consistent way to handle new features that we lack today.

**Comment by bjhargrave** [comment]
> Can you see any?

Yes. It is a massive burden on us, the Bnd maintainers, to ensure every new thing is firewalled off by some instruction. We need to maintain tests for the feature being activated and not being activated. This does not scale since new things may depend upon old things or sets of old things.


>  I think we must make the default enablement of a new feature a decision in the bnd meeting or handle via an issue.

Every new thing in Bnd is introduced by issues and PR. There is no secret add of new things not visible to everyone. I get that we are all busy. We don't release constantly so there is always time to feedback on new things before they enter a release.

For the most part, I do not thing the way Bnd has evolved has been a problem for the vast majority of user. Yes, it appears to have affected you on a few occasions (and I am sorry), but I don't think this rises to the level to impose a new regime on adding features to Bnd. I still don't understand how your proposal works in maven or gradle cases where the vast majority of Bnd users don't have or want any Bnd configuration. It seems quite odd to have to update the Bnd plugin version and then also have to add some configuration to turn on the new Bnd plugin's features.

I think your proposal here needs more detail to explain how it works as I am afraid it is still not clear to me how it is to work and how it works for all the modes of Bnd use here (Bnd workspace, maven, gradle).

**Comment by kriegfrj** [comment]
> > Perhaps an alternative to this is to do a better job of releasing point-releases for bug fixes? That way @pkriens could update the latest micro release without worrying about a new feature that might break his build?
> 
> @kriegfrj Your proposal to have bug fixes will make things more complicated for everybody, I think. The ad hoc handling of new features we had so far will make it hard to control that nothing slips through the crack in a bug fix. And then you're still stuck that if you want the new version for one feature, you have to accept all.
>

On the issue of making it hard to control so that nothing slips through the cracks - I don't see that your proposal changes that a lot. Care will still be needed and stuff can still slip through the cracks.

I do see your point about if you want a new feature, you have to accept all features of that version. But this is not uncommon for software. I don't know of a software platform where new releases have all of the new features disabled by default. Especially given that we're using semantic versioning - we should expect breaking behaviour when upgrading to the next major version, and if we're not ready/willing to handle it then we should stay on the version we've got.
 
> One advantage of the proposal is that we will have explicit list of the defaults for each feature, for each release. This is exactly what my proposal achieves. By having all the new features enabled/disabled in the version specific default file for bndlib we can have it all? I can stick to the feature set defined by version X. If I want to follow what bnd does, I go with the flow. If I want to remain at X, I set the -versiondefaults specifically to the version I want.
>

If you want to remain at X, you can just stay on version X of Bnd?

> I am a bit flummoxed with the opposition.

I'm not strictly against your proposal. I haven't really made up my mind, to be honest (not that my opinion should count for much in the face of the opinion of the much more experienced and wiser heads around here). But I can see that BJ is against it at the moment, and as I hold you both in high regard I'm trying to hear both sides of the argument.

> If we do not go for this solution, I think we must make the default enablement of a new feature a decision in the bnd meeting or handle via an issue. I just do not have time to verify every PR that I am not going to be bit by it. And I am afraid that I will by default oppose enabling new features that change any metadata. For example, I would have opposed the Java import & the maven dependencies since they change metadata in a way that can hurt existing setups, like they did for all my customers at times.
> 

To be fair, I think that this is already what is happening. Certainly, I know if I am proposing a change that is not strictly backwards compatible, I always put it into an issue for discussion first. I know for certain that the java.* imports were discussed extensively in an issue to determine exactly what the default behaviour should be and when & how it should be enabled.

> So if you do features the bnd way, it is not more code. However, even if you did have an enablement block, it would be 2 lines ... A huge code bloat issue? And it is moot, since the -noxxx instruction needs to be handled conditionally. Even the -maven-dependencies is tested.
>

This I agree with. Options like the java import need to be configurable. Whether the default is enabled or disabled doesn't really affect the amount of bloat, and you still need to test both the default and the configured behaviour.
 
> > I don't think this is a wise thing to do or impose on the Bnd developers. I would be opposed to it. We should instead be more clear in release notes about changes to Bnd so that if you do update Bnd to a newer version, you know what will be changing and if don't like it, you can disable it. For example, the Bnd 5.2.0 release notes clearly describe the change to import java packages and the -noimportjava option to disable that.
> 
> You make the classic mistake of highly involved people. For you, bnd is your world. For many people it is a detail and they often do not look at it for a long time. Many workspaces work fine and do not need to be updated for a very long time. For them bnd is a tiny detail of their workload. The reason for an update is often a bug or the desire to use a new features. We've had numerous complaints of people that did this upgrade from a 4.1.0 release. That is a lot of release notes to crawl though and, lets not kid ourselves, they are not perfect. This proposal gives you a clear list of features in one place and their enablement for a given version. If you go from version X to Y, you compare the version defaults. You can then take the latest (as is today, developer controls the default), pick a version, or look at the latest list and override the ones you disagree with.
>

This I partially agree with. Yes, I think that we who are involved in Bnd development probably find the release notes a lot easier to read than the average person who doesn't use Bnd a lot (I remember the days when I started using Bnd, which wasn't that long ago, and I can remember how unintelligible some of the documentation seemed when now it is really quite straightforward).

However, correct me if I'm wrong or if I've misinterpreted, but it seems you're describing the experience of someone who upgraded directly from 4.1.0 to the latest (5.2.0)? On that point, I have some sympathy, but I think a bit less. It is rare that you can jump that many versions in one hit and not run into problems. Especially given that we are using semantic versioning and there is a change of a major version number, which implies it is not 100% backwards compatible. In my former life as a sysadmin I would have studiously avoided skipping that many versions in a mission-critical environment, as I would be _expecting_ to run into problems that would need ironing out. I know it's tempting to take the "if it ain't broke, don't fix it" approach to upgrading your environment, but if you get too far behind head you can expect more pain when you are eventually forced to catch up for some reason (eg, a new feature that you want, or a bug fix that you need).

> > To the extent that a new feature may cause some users a problem, we generally provide a -noxxx instruction to enable people to disable it and we then document that in the docs and release notes.
> 
> Yeas, and these -noxxx instructions are ugly. They sort in the wrong place and they force people to think the wrong way. Worse, they are inconsistently applied. I used them and accepted them because I did not see another solution to provide good defaults for most people, but always disliked them. However, this proposal finaly allows me to eat my cake and have it too. All features are disabled by default and are explicitly disabled in the code and then enabled by the version specific defaults in bndlib.
> 

I certainly agree with the assertion that "noxxx" instructions are ugly and sort badly.

Anyway, they are just some random observations. For what little it's worth, I think Peter's suggestion is an interesting possibility, and if it's not too much overhead to implement maybe we should consider it. But I'll let you guys duke it out and I'm sure I'll be content with the result either way. :wink: Thank you again gentlemen for all that you do.

**Comment by pkriens** [comment]
> Yes. It is a massive burden on us, the Bnd maintainers, to ensure every new thing is firewalled off by some instruction. 

Massive? We're already doing this? If you have a `-mavendependencies` & `-nojavaimport` that can disable these features, what is the difference here? 

The amount of work to do was a problem with the `-since` instruction, that was very intrusive and that is why it never caught on. However, this is as non-intrusive as possible. It is mostly the philosophy in the way you write your code. By default, do no harm but provide convenient defaults for the majority of users.
 
I also do not think it is necessary to do this for _every_ change. The java import & maven dependencies were so harmful because they added new dependencies, upsetting the apple carts downstream.

> For the most part, I do not think the way Bnd has evolved has been a problem for the vast majority of users. Yes, it appears to have affected you on a few occasions (and I am sorry), but I don't think this rises to the level to impose a new regime on adding features to Bnd.

You do not have a problem so nobody has? Most people just move on, hating these kind of discussions. Regardless, I have a problem & a responsibility; This proposal is an elegant way to fix my problem as well as making our future instructions more consistent in their behavior.

> Every new thing in Bnd is introduced by issues and PR. There is no secret add of new things not visible to everyone. 

But to make this manageable for people like me that are not full time in bnd I will need some way to get a more formal process for changes that affect metadata or the instruction set. I just do not have the time to review each PR and engage in the sometimes difficult discussions with you.

> I think your proposal here needs more detail to explain how it works as I am afraid it is still not clear to me how it is to work and how it works for all the modes of Bnd use here (Bnd workspace, maven, gradle).

I made a proposal, see #4442

**Comment by kriegfrj** [comment]
Interestingly, someone made a similar complaint about Eclipse itself today:

https://www.eclipse.org/lists/eclipse-dev/msg11585.html

**Comment by laeubi** [comment]
> Yes. It is a massive burden on us, the Bnd maintainers, to ensure every new thing is firewalled off by some instruction. We need to maintain tests for the feature being activated and not being activated. This does not scale since new things may depend upon old things or sets of old things.

If there are already -noXXX switches I could think of an strategy I have seen in another lib where it was possible to set a feature-version (e.g. -features=2.3). Then there is an isEnabledXXX that work like this:

`return featureVersion > 2.3 && !noXXX`

Another strategy would be to have "relase-notes-as-code" where one can issue something like myTool -release 2.3

This will then emit all new options since the 2.3 release. If you want to male this even more useful, allow to specify a config file and emit a new one that includes disablement switches for all new features then the user can remove them one-by-one.
