### ISSUE TITLE
Gradle 7.0 deprecation warning for ProjectLayout.configurableFiles() should be avoided

### ISSUE THREAD

**Issue by marcphilipp** [bndtools/bnd#4451]
I noticed a new deprecation warning in the junit5 build today:
> The ProjectLayout.configurableFiles() method has been deprecated.
> This is scheduled to be removed in Gradle 7.0.
> Please use the ObjectFactory.fileCollection() method instead.
 
Build scan: https://ge.junit.org/s/twdqmusjkwknq/deprecations?expanded=WyI0Il0&expanded-stacktrace=WyI2Il0

I found two occurences in `BundleTaskConvention` that should be replaced. Instead of `layout.configurableFiles(...)` it should be `objectFactory.fileCollection().from(...)`.

**Comment by bjhargrave** [comment]
Gradle 5.3 [introduced](https://docs.gradle.org/5.3/javadoc/org/gradle/api/model/ObjectFactory.html#fileCollection--) `ObjectFactory.fileCollection` and simultaneously [deprecated](https://docs.gradle.org/5.3/javadoc/org/gradle/api/file/ProjectLayout.html#configurableFiles-java.lang.Object...-) `ProjectLayout.configurableFiles`. The current minimum Gradle version supported by the Bnd Gradle Plugins is 5.1.

> These plugins requires at least Gradle 5.1 for Java 8 to Java 12, at least Gradle 6.0 for Java 13, and at least Gradle 6.3 for Java 14.

So in order to switch to use `ObjectFactory.fileCollection`, I would need to raise the minimum Gradle version to [5.3](https://gradle.org/releases/#5.3). 5.3 was released on Mar 20, 2019 which is coming up on 2 years ago. Does anyone object to raising the minimum Gradle version from 5.1 to 5.3? We will be forced to do it anyway when Gradle 7.0 releases and removed the `ProjectLayout.configurableFiles` method.

**Comment by marcphilipp** [comment]
@bjhargrave Gradle 7.0 is going to be the next version of Gradle, the first milestone is planned to be published soon. If possible, it would be great if this change would be released soon so that builds like JUnit's can try it out.
