### ISSUE TITLE
bnd error: Unclosed group near index \$(?:repo

### ISSUE THREAD

**Issue by maho7791** [bndtools/bnd#4483]
While migrating a bnd gradle project into maven I experienced this error in **bnd-maven-plugin**:5.2.0

The error goes back to these lines in the projects bnd.bnd file:

```
-includeresource: \
	@${repo;com.github.sarxos:webcam-capture:jar:sources;${lib.version}}!/META-INF/*,\
	OSGI-OPT/src=@${repo;com.github.sarxos:webcam-capture:jar:sources;${lib.version};EXACT},\
	bundle.properties=bundle.properties
```

Without the two $repo lines, the build works.

**Comment by maho7791** [comment]
This maybe a similar issue like in #3640.

**Comment by bjhargrave** [comment]
In the bnd instructions for `bnd-maven-plugin`, you cannot use the `repo` macro. There is no Bnd Workspace since you are using maven. So when migrating to maven, you cannot use any "workspace" macros like `repo`.

You would need to use the [maven-dependency-plugin](https://maven.apache.org/plugins/maven-dependency-plugin/) to copy content from an artifact into your bundle.
