### ISSUE TITLE
[gradle] Gradle seems to not obey -dependson for parallel tests

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#4484]
I have a test project where I specify that it depends on all other projects:

     -dependson *

This works when I run gradlew without the `--parallel` but with parallel enabled the tests are run _before_ the other projects have been build, and thus the test fails.

If I add the projects literally to `-dependson`, it still fails. However, when I add them to `-buildpath` these dependencies are properly build ahead of the test execution. 

Using `bnd debug` in the test project directory, I can see that in all cases the dependencies are listed in the DependsOn section. It seems bnd does provide the proper information. It almost feels as if the Gradle parallel execution does not take `-dependson` into account?

I can consistently repeat this with this workspace that I cannot share. If needed I can make a test workspace. However, since this depend on the scheduling rules of the parallel tasks, I expect there is non-determinism is involved. Maybe we can first take a look at the source code if the scheduling takes `-dependson` into account.

**Comment by bjhargrave** [comment]
The gradle `test` task is for plain JUnit tests and does _not_ depend upon the gradle `jar` task since normally plain JUnit tests do not require the built jar and you do not want to build the jar before the tests pass. This is standard gradle behavior. 

The gradle `jar` task is configured by the Bnd gradle plugin to depend upon all the jars on `-buildpath` and `-dependson` as provided by `Project.getBuildDependencies()`.

https://github.com/bndtools/bnd/blob/8473689e6988a0e1874831f02cc7be3d721ff89d/biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy#L296-L297

https://github.com/bndtools/bnd/blob/8473689e6988a0e1874831f02cc7be3d721ff89d/biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy#L577-L583

If your `test` task needs to depend upon the `jar` task and thus indirectly on the `jar` task's dependencies, then you need to declare this in the `build.gradle` file for the project. For example:

https://github.com/bndtools/bnd/commit/965d27e9b5487b012e98a109659ebeb5d97ecfa1

https://github.com/bndtools/bnd/blob/8473689e6988a0e1874831f02cc7be3d721ff89d/biz.aQute.bndlib.tests/build.gradle#L5-L11

**Comment by pkriens** [comment]
I think the default should be to follow the eclipse behavior closely and not the Gradle behavior. For Gradle behavior we have another plugin. And Eclipse builds all the dependency jars _before_ JUnit testing. I am also confused what the purpose is for this behavior? Eclipse workspace users rarely use the command line so tests are normally run on the CI server. And there it is quite crucial that the behavior of Eclipse is mimicked.

Has this behavior changed or is it just that it is now visible because --parallel is used?

Can we make this the default please?
