### ISSUE TITLE
Move away from bintray and jcenter usage in the build

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#4525]
[Into the Sunset on May 1st: Bintray, JCenter, GoCenter, and ChartCenter](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)

**Comment by kriegfrj** [comment]
First Cloudbees went, now bintray... we're constantly being evicted... :smile:

One of the problems we'll have to deal with is the OSGi repository for Eclipse 2018-12. I seem to remember the main motivation for this repo was to improve the CI build reliability (because the Eclipse servers were causing intermittent failures when we tried to use the P2 repos directly). Here are some quick suggestions for this particular issue:

1. Re-host the Eclipse 2018-12 OSGi repo on GitHub.
2. Perhaps the Eclipse servers are more reliable now and we can go back to using the p2 repo directly?
3. As an intermediate of point 2, perhaps we can generate an OSGi index that indexes the bundles in-place and references them in their original location? This might reduce the amount of downloading the CI needs to do to run the tests and launch the app, and mitigate any unreliability of the Eclipse servers.
4. It's actually (at this stage) only a relatively small subset of the Eclipse bundles that are needed for the CI; the remainder are only needed for launching the Eclipse test instance from `bndtools.core`. Perhaps we shrink our OSGi repo smaller and only include those dependencies that are needed for the build, then add a p2 repo to the workspace for the rest that links direct to Eclipse (intermittent failures are less of an issue during development).

**Comment by pkriens** [comment]
I like 3,  making an index of the remote Eclipse bundles. This will significantly decrease the downloads. With a bit of work, bnd command line could convert a p2 repo to an OSGi index with remote urls.

I'd prefer to keep it at one set.

**Comment by bjhargrave** [comment]
I think I had done 3 before and it was still not reliable. I don't think the Eclipse download servers are robust enough especially around their quarterly releases. I made a repo in our jfrog artifactory to hold the Eclipse dependencies.

**Comment by bjhargrave** [comment]
I think this is done now with the 2 commits.
