### ISSUE TITLE
Normalize Require-Capability

### ISSUE THREAD

**Issue by markt-asf** [bndtools/bnd#4591]
While working on reproducible builds for Apache Tomcat I noticed that, with `reproducible` set to `true` I was seeing variation in the `Require-Capability` attribute from one build to the next.

I was unable to determine the root cause of the variability. Full details of what I tried and what i found are in the [discourse topic](https://bnd.discourse.group/t/require-capability-attribute-not-consistent/113).

It was suggested. although I did not observe any variation, that `Provide-Capability` may need similar normalization.

**Comment by bjhargrave** [comment]
The fix does not normalize the Require-Capability header as I suggested in the discourse discussion. Instead, the fix is more focused and uses a LinkedHashSet instead of a HashSet to ensure the encounter order of processing contracts is preserved as the iteration order when adding contracts to the Require-Capability header. This should be sufficient to address the reproducibility issue around contacts in the Require-Capability header.

**Comment by markt-asf** [comment]
Thanks for the update. I'll get testing with a snapshot and let you know how I get on.

**Comment by markt-asf** [comment]
LGTM. Many thanks.
