### ISSUE TITLE
Fix "Bndtools: bnd's testsrc folder 'test' is not in the Eclipse build path" warning display

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#4624]
In many OSGi projects, there is no `testsrc` folder on disk nor is it mentioned in the `.classpath` file. Bndtools has now started warning about the `testsrc` folder not being mentioned in the `.classpath` file. 

Bndtools should only warn _if_ the `testsrc` folder exists on disk and is not mentioned in the `.classpath` file. Otherwise there is nothing wrong that justifies a warning. 

This change is now causing almost all of the OSGi projects to display the warning which makes it hard to see real warnings which need attention.

**Comment by pkriens** [comment]
I think the problem is that the testsrc _does_ exist. The validator does check for the existence.

See  https://github.com/bndtools/bnd/blob/ba0bd37c2c33afe4ccfd8660b1a37b1c1ac52eaa/bndtools.builder/src/org/bndtools/builder/validate/ProjectPathsValidator.java#L238

The problem is that the absence of a test folder creates a buildpath problem in Eclipse. So I added a check in the global refresh to create this folder when absent. 

I do think there are many subtle issues not having this folder. In principle, the .classpath is a derivative of the bnd.bnd file. I've seen problems several times that people change .classpath using PDE menus, which of course wreaks havoc. 

I guess the solution is to let bndtools sync the .classpath with the bnd file. This can take into account if there are test sources, although I am not sure this is worth the extra complexity? Personally I like the symmetry of having all projects identical.

A quick solution might be to check if the folder is empty ...

**Comment by bjhargrave** [comment]
> I think the problem is that the testsrc _does_ exist.

But why does it exist? It is not in git. Did Bndtools create the folder? I don't think Bndtools should create source folders that don't exist.

**Comment by bjhargrave** [comment]
> Did Bndtools create the folder?

It appears so. When I delete the empty testsrc folder, the folder is recreated by Bndtools. I think this is wrong.

**Comment by pkriens** [comment]
>  I think this is wrong

Well, we disagree there ... the bnd metadata sets testsrc to a value. I think it is really wrong to have two masters of the metadata: bnd & .classpath.
