### ISSUE TITLE
bnd-maven-plugin:bnd-process modifies target/classes which leads to warns in subsequent builds

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#4678]
The `bnd-maven-plugin` might copy over classes to the build directory (i.e. `target/classes`). If now the same Maven build is executed again (without running `mvn clean` in between, the bnd-maven-plugin will emit warnings like 

```
[WARNING] /Users/konradwindszus/git/sling/sling-org-apache-sling-xss/bnd.bnd [0:0]: Split package, multiple jars provide the same package:org/apache/batik
Use Import/Export Package directive -split-package:=(merge-first|merge-last|error|first) to get rid of this warning
Package found in   [Jar:classes, Jar:batik-util-1.13]
Class path         [Jar:classes, Jar:antisamy-1.5.10, Jar:batik-css-1.13, Jar:batik-shared-resources-1.13, Jar:batik-util-1.13, Jar:batik-constants-1.13, Jar:batik-i18n-1.13, Jar:xmlgraphics-commons-2.4, Jar:xml-apis-ext-1.3.04, Jar:nekohtml-1.9.22, Jar:httpclient-4.5.12, Jar:httpcore-4.4.13, Jar:commons-logging-1.2, Jar:xercesImpl-2.12.0, Jar:commons-codec-1.14, Jar:xml-apis-1.4.01, Jar:xalan-2.7.2, Jar:serializer-2.7.2, Jar:esapi-2.2.1.1, Jar:xom-1.2.10, Jar:commons-beanutils-1.9.4, Jar:commons-configuration-1.10, Jar:commons-fileupload-1.3.3, Jar:log4j-1.2.17, Jar:commons-collections4-4.2, Jar:bsh-2.0b6, Jar:encoder-1.2.2, Jar:javax.servlet-api-3.1.0, Jar:osgi.core-6.0.0, Jar:osgi.cmpn-6.0.0, Jar:org.osgi.annotation.versioning-1.1.0, Jar:slf4j-api-1.7.25, Jar:org.apache.sling.api-2.11.0, Jar:org.apache.sling.serviceusermapper-1.2.0, Jar:annotations-16.0.2, Jar:geronimo-json_1.0_spec-1.0-alpha-1, Jar:commons-lang3-3.6, Jar:commons-io-2.6, Jar:org.apache.sling.commons.metrics-1.2.6, Jar:metrics-core-3.2.3, Jar:jcr-2.0]
```

This is due to the fact that `target/classes` has not been cleared and the split-packages are due to leftovers from the last run of bnd-maven-plugin.

You can reproduce by just executing `mvn package` twice on `https://github.com/apache/sling-org-apache-sling-xss/tree/feature/upgrade-parent-pom`.

**Comment by bjhargrave** [comment]
> https://github.com/apache/sling-org-apache-sling-xss/tree/feature/upgrade-parent-pom

That URL does not answer.

bnd-maven-plugin obviously cannot clear `target/classes` since it is an input as well as an output. It also cannot know what in `target/classes` can or should be ignored. The issue would seem to be you are using `-includeresource` to copy content from classpath jars into your bundle which means bnd-maven-plugin will put them in `target/classes` (so that maven-jar-plugin will package them in to the jar). And when you run bnd-maven-plugin again, it will see the classes in both `target/classes` (an input) and the classpath jars. You should just either put the suggested `-split-package` on the Import-Package clauses or add a `-fixupmessage` to elide the warning.

**Comment by bjhargrave** [comment]
> Wouldn't it be an option to somehow mark thoses classes (with a specific timestamp or other fs attribute)>

bnd-maven-plugin uses Builder to build an in-memory Jar from the inputs and then expands that Jar into target/classes so that maven-jar-plugin will jar it up. There is no easy way for bnd-maven-plugin to know what in the in-memory Jar should be marked as special and then to tell the Builder to ignore those files in the input target/classes. 

This is just fundamental to how bnd-maven-plugin works by mutating target/classes for maven-jar-plugin since there is no way in maven to "hook into" the maven-jar-plugin operation to influence content.

One thing you can try is to configure the [`outputDir` property](https://github.com/bndtools/bnd/tree/master/maven/bnd-maven-plugin#configuration-parameters) of bnd-maven-plugin to be something other than target/classes and then configure maven-jar-plugin [`classesDirectory` property](https://maven.apache.org/plugins/maven-jar-plugin/jar-mojo.html#classesDirectory) to use that directory instead of target/classes. Then the output of a prior bnd-maven-plugin execution is not the input to a subsequent execution.

**Comment by rotty3000** [comment]
Another possibility is to set `<includeClassesDir>false</includeClassesDir>` which reverts the `bnd-maven-plugin`'s behaviour of

> everything in the `target/classes` should go into the jar

This then starts to work more like what is done in the bnd workspace where what bnd analyzes is a function of the bnd instructions like `Export-Package`, `-includeresource`, etc.

However, you then have to teach `maven-jar-plugin` about this difference by telling it what to include or exclude from `target/classes`.

**Comment by kwin** [comment]
Thanks for the suggestions. As I don't see any way to improve the handling by default feel free to just close this issue. Maybe just the readme at https://github.com/bndtools/bnd/blob/master/maven/bnd-maven-plugin/README.md could be extended with those hints...

**Comment by kwin** [comment]
Maybe this can be considered for #4174?
