### ISSUE TITLE
Gradle 7.1 compatibility

### ISSUE THREAD

**Issue by marcphilipp** [bndtools/bnd#4699]
Using conventions on `Jar` tasks in Gradle 7.1-rc-2 produces warnings such as [these](https://ge.junit.org/s/h2goaupclsprc/console-log?task=:buildSrc:compileKotlin):
> w: /Users/marc/Repositories/junit5/buildSrc/src/main/kotlin/osgi-conventions.gradle.kts: (62, 2): 'getter for convention: Convention' is deprecated. Deprecated in Java	
> w: /Users/marc/Repositories/junit5/buildSrc/src/main/kotlin/osgi-conventions.gradle.kts: (96, 2): 'withConvention(KClass<ConventionType>, ConventionType.() -> ReturnType): ReturnType' is deprecated. The concept of conventions is deprecated. Use extensions instead.

It seems the Gradle plugin's approach of adding OSGi manifest entries to jar files needs to be reconsidered. I'll see to it that someone from the Gradle build tool team takes a look and comments here.

**Comment by big-guy** [comment]
I believe that all the uses in the bnd plugin could be replaced with extensions or by moving the properties/methods added by the convention. Extensions have been around since Gradle 1.0, so backwards compatibility isn't a concern there.

The main issue with compatibility will be for users. Adding a convention to a type implicitly adds all the properties/methods to that type in a flat hierarchy. Extensions don't do that. e.g., a convention with property `foo` is accessed by `foo` and not `extensionName.foo`. This is one of the reasons we're removing conventions. 

For `BndPluginConvention`, maybe this can be deprecated and removed completely since it looks like it's already delegating to the `BndProperties` extension for the most part.
https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPluginConvention.groovy

For `FileSetRepositoryConvention`, maybe this can be rolled into `Bndrun` directly? I'm not sure I completely understand what it's doing.
https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.gradle/src/aQute/bnd/gradle/FileSetRepositoryConvention.groovy

For `BundleTaskConvention`, this looks the most complicated to remove. Maybe some functionality could be duplicated into `Bundle`, but I think the easiest thing to do is to add an extension named `bndTools` (or similar) to tasks and have people configure all the bnd related things through that extension. 
https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy

Instead of accessing `bndfile` directly in a jar task, someone would do `bndTools.bndfile = ...` or `bndTools { bndfile = ... }`. The convention could be made to delegate to the extension or vice versa. 

If you're going to introduce a new extension, I would also take a pass at all of the properties you're providing. I suspect you'll be able to simplify a lot of things depending on the minimum version of Gradle you need to support. A few things I noticed:

1. You don't need to explicitly call `ObjectFactory` to create all of the properties. If you make your class abstract or an interface, you can just add unimplemented getters and Gradle will implement them for you (managed properties: https://docs.gradle.org/current/userguide/custom_gradle_types.html#managed_properties)
2. You shouldn't call `new` directly for types that are used in the DSL. This prevents Gradle from adding decorations to make Closures and Providers work in a consistent way. You can call `ObjectFactory.newInstance` instead or use a different factory method.
3. You shouldn't add explicit setters for Provider API types, if you can absolutely avoid it. All users should be funneled into using `fooProperty.set(...)` or similar.

I think all of these suggestions are applicable for Gradle 5.1+

HTH

**Comment by bjhargrave** [comment]
@big-guy I made a number of updates to the Bnd Gradle plugins (in 6.0.0-SNAPSHOT). The minimum Gradle version they require is now 6.7 (due to another change to support java toolchains for Bndrun and TestOSGi tasks).

I made a [branch](https://github.com/bjhargrave/junit5/tree/bnd-6.0.0-convention-deprecation) of junit5 to test the [changes](https://github.com/bjhargrave/junit5/commit/145a5f0da892983470cb7a5d24f4d6da0ead93ee).  And they seem to work fine.

One question I have is whether I missed something to be able to use the `bundle` extension more directly in the Kotlin scripts. In https://github.com/bjhargrave/junit5/commit/145a5f0da892983470cb7a5d24f4d6da0ead93ee#diff-3251c349ec43ecbcf322a65c57f8eac19bb75e8e005fd080581f76dd3df37c09, I was able to change from using `withConvention` to `configure<>`:

```diff
 tasks {
 	jar {
-		withConvention(BundleTaskConvention::class) {
+		configure<BundleTaskExtension> {
 			bnd("""
 				Provide-Capability:\
 					org.junit.platform.engine;\
```

But it would be nicer to just say `bundle { ... }`. In the changes for Gradle 7.1 to the Groovy sourceSet support, you can now say `groovy { ... }` to modify the Groovy SourceDirectorySet extension. Is there any thing that could be done in the Bnd Gradle plugins to enable Kotlin scripts to use `bundle { ... }` to modify the BundleTaskExtension?

**Comment by marcphilipp** [comment]
@bjhargrave Sounds great, thanks for looking into this! 👍 

For Kotlin scripts, you can do what the test-retry plugin does for its `retry` extension on `Test` tasks:
https://github.com/gradle/test-retry-gradle-plugin/blob/2f199ce3a4e65d1e5bb1623cecc32a45f7bcab59/plugin/src/main/kotlin/org/gradle/kotlin/dsl/testRetry.kt

**Comment by bjhargrave** [comment]
I looked at the link and I think I understand it, but I can't add the `kotlin-dsl` plugin to my groovy build script. I suspect I would have to convert the project's build script to kotlin in order to build this kotlin code (sigh) and this exceeded my kotlin knowledge. I was finally able to get a compilable kotlin build script, but it ran `compileKotlin` before `compileGroovy` which meant the kotlin code could not see the types built by the groovy code (e.g. BundleTaskExtension) as available.

```
> Task :biz.aQute.bnd.gradle:compileKotlin FAILED
e: /Users/hargrave/git/bnd/biz.aQute.bnd.gradle/src/org/gradle/kotlin/dsl/jarBundle.kt: (6, 18): Unresolved reference: gradle
e: /Users/hargrave/git/bnd/biz.aQute.bnd.gradle/src/org/gradle/kotlin/dsl/jarBundle.kt: (8, 17): Unresolved reference: BundleTaskExtension
e: /Users/hargrave/git/bnd/biz.aQute.bnd.gradle/src/org/gradle/kotlin/dsl/jarBundle.kt: (9, 13): Not enough information to infer type variable T
e: /Users/hargrave/git/bnd/biz.aQute.bnd.gradle/src/org/gradle/kotlin/dsl/jarBundle.kt: (11, 27): Unresolved reference: BundleTaskExtension
e: /Users/hargrave/git/bnd/biz.aQute.bnd.gradle/src/org/gradle/kotlin/dsl/jarBundle.kt: (12, 16): None of the following functions can be called with the arguments supplied: 
public abstract fun <T : Any!> configure(p0: Class<TypeVariable(T)!>, p1: Action<in TypeVariable(T)!>): Unit defined in org.gradle.api.plugins.ExtensionContainer
public abstract fun <T : Any!> configure(p0: String, p1: Action<in TypeVariable(T)!>): Unit defined in org.gradle.api.plugins.ExtensionContainer
public abstract fun <T : Any!> configure(p0: TypeOf<TypeVariable(T)!>, p1: Action<in TypeVariable(T)!>): Unit defined in org.gradle.api.plugins.ExtensionContainer
e: /Users/hargrave/git/bnd/biz.aQute.bnd.gradle/src/org/gradle/kotlin/dsl/jarBundle.kt: (12, 26): Unresolved reference: BundleTaskExtension
```

I tried to make `compileKotlin` run after `compileGroovy` but that lead to a task circularity issue.

```
* What went wrong:
Circular dependency between the following tasks:
:biz.aQute.bnd.gradle:compileGroovy
\--- :biz.aQute.bnd.gradle:compileJava
     \--- :biz.aQute.bnd.gradle:compileKotlin
          \--- :biz.aQute.bnd.gradle:compileGroovy (*)
```

So I am not sure how to make this work in our build. :-(

**Comment by marcphilipp** [comment]
Have you tried sth. like this? https://stackoverflow.com/a/61139616/6327046

If you want, I can take a look at a branch.

**Comment by bjhargrave** [comment]
> Have you tried sth. like this? https://stackoverflow.com/a/61139616/6327046

Yes, but that does not work since there appears to be a direct `dependsOn` link. From some debug output in my build script:

```
compileJava dependsOn: task ':biz.aQute.bnd.gradle:compileKotlin'
compileTestJava dependsOn: task ':biz.aQute.bnd.gradle:compileTestKotlin'
```

The following (along with other configuration) seems to fix things up.

```kotlin
afterEvaluate {
  tasks.compileJava {
    getDependsOn().clear()
  }
  tasks.compileTestJava {
    getDependsOn().clear()
  }
}
```

I hope to have a PR soon.
