### ISSUE TITLE
Export Gradle Task fails in 6.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#4761]
I have been using Gradle Export task since long:

In`5.3.0`, the following works perfectly:
```
tasks.register('exportbndrun', Export) {
    description 'Copies all runtime bundles to Distribution Directory'

    bndrun 'com.amitinside.product.luther.application/rtm-dep-nop.bndrun'
    exporter 'bnd.runbundles'
    destinationDir 'dist/output/current'
}
```

Now, after switching to `6.0.0-SNAPSHOT`, it does fail with the following:
```
A problem occurred configuring root project 'com.amitinside.runtime'.
Could not create task ':exportbndrun'.
  Could not create task of type 'Export'.
    Could not get unknown property 'distsDirectory' for root project 'com.amitinside.runtime' of type org.gradle.api.Project.
```

I am not sure if the `destinationDir` property has been changed to something else. Could anyone kindly help me regarding this? Thanks in advance.

**Comment by amitjoy** [comment]
According to `aQute.bnd.gradle.Export.groovy`, I tried to change the `destinationDir` to `destinationDirectory` but it doesn't work either. It always searches for `distsDirectory` property.

I also tried to not specify the destination directory property at all but explicitly set the project property while executing the `exportbndrun` task:

./gradlew exportbndrun -PdistsDirectory=dist/output/current

Unfortunately, it failed with a different exception:

```
* What went wrong:
A problem occurred configuring root project 'com.amitinside.runtime'.
> Could not create task ':exportbndrun'.
   > Could not create task of type 'Export'.
      > Cannot cast object 'dist/output/current' with class 'java.lang.String' to class 'org.gradle.api.provider.Provider' 
```

Any idea how to specify the `DirectoryProperty` as a project property?

**Comment by bjhargrave** [comment]
Please see the release notes at https://github.com/bndtools/bnd/wiki/Changes-in-6.0.0#bnd-gradle-plugins. You need to modify your buildscript like the following example.

```groovy
tasks.register('exportbndrun', Export) {
    description = 'Copies all runtime bundles to Distribution Directory'

    bndrun = file('com.amitinside.product.luther.application/rtm-dep-nop.bndrun')
    exporter = 'bnd.runbundles'
    destinationDir = distsDirectory.dir('current')
}
```

**Comment by bjhargrave** [comment]
Also, you need to use Gradle 6.7 or later.

**Comment by bjhargrave** [comment]
The exact replacement for `destinationDir 'dist/output/current'` is `destinationDirectory.set(file('dist/output/current'))` if you don't want to use the distDirectory property as the base directory.

**Comment by amitjoy** [comment]
Thanks BJ for the quick response. I tried both the following versions as you proposed:

```
tasks.register('exportbndrun', Export) {
    description = 'Copies all runtime bundles to Distribution Directory'

    bndrun = file('com.amitinside.product.luther.application/rtm-dep-nop.bndrun')
    exporter = 'bnd.runbundles'
    destinationDir = destinationDirectory.set(file('dist/output/current'))
}
```
and 
```
tasks.register('exportbndrun', Export) {
    description = 'Copies all runtime bundles to Distribution Directory'

    bndrun = file('com.amitinside.product.luther.application/rtm-dep-nop.bndrun')
    exporter = 'bnd.runbundles'
    destinationDir = distsDirectory.dir('dist/output/current')
}
```
Unfortunately in both cases, it fails with the same exception asking for `distsDirectory` property. I am currently using Gradle 6.9.

**Comment by bjhargrave** [comment]
The property you are setting is `destinationDirectory` not `destinationDir` (I have fixed my original example). So the left side of the assignment statement must be `destinationDirectory`.

**Comment by bjhargrave** [comment]
> Unfortunately in both cases, it fails with the same exception asking for `distsDirectory` property. I am currently using Gradle 6.9.

See https://docs.gradle.org/6.7/dsl/org.gradle.api.Project.html#org.gradle.api.Project:distsDirectory

**Comment by amitjoy** [comment]
Thanks BJ for your continuous assistance. I tried all your proposals but unfortunately it didn't work. That's why I have prepared a dummy repo [1] reproducing the issue. Could you kindly have a look?

[1] - https://github.com/amitjoy/bnd-gradle-export-task-issue

**Comment by bjhargrave** [comment]
Well it is not going to work in your example since the root project does not have the `java` plugin applied and thus does not have the `distsDirectory` property (which is applied to a project by the `java` plugin).

The 5.3.0 version of the Export task supported older versions of gradle which did not have the `distsDirectory` property and so it worked around it by using the `distsDirName` property (also applied by the `java` plugin). 

https://github.com/bndtools/bnd/blob/fe6b49cf8e56bf870bd29de6773b42b7e1f29514/biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Export.groovy#L91-L93

But the access to the `distsDirName` property was deferred in a provider which was never called (and thus never failed) since you set the old `destinationDir` property which replaced the default value to be supplied by the provider. 

The net is that all the Bnd Gradle tasks generally assume they are being used in a project which has the `java` plugin applied and therefore they have access to any properties applied to the project by the `java` plugin. So it is just luck that your task worked in the root project before. You should move the export task into a project which has the `java` plugin applied like your `com.amitinside.product.luther.application` project.

**Comment by amitjoy** [comment]
Thanks BJ for your detailed explanation. We are currently adapting our build for the next major bndtools release and I saw that it requires Gradle 6.7+ and that's why while incorporating the required changes, I did encounter such problems. Now it works perfectly. Thanks a lot for your cooperation and assistance as always 👍
