### ISSUE TITLE
Bnd $permissions macro generates deprecated "export" instead of "exportonly"

### ISSUE THREAD

**Issue by chrisr3** [bndtools/bnd#4778]
Observed that [Bnd 5.3.0](https://bnd.bndtools.org/releases/5.3.0/macros/permissions.html) still generates `export`, although `export` is apparently deprecated in favour of `exportonly` [according to the Javadocs](http://docs.osgi.org/javadoc/osgi.core/8.0.0/).

I also noticed that OSGi defines:
```
(org.osgi.framework.PackagePermission "java.*" "import")
```
as an "implied permission" that the framework is supposed to apply automatically. This _would_ explain why `${packages}` doesn't include it too... except that I still seem to need to add it myself anyway to get things working :thinking:.

**Comment by bjhargrave** [comment]
I am going to close this issue. We discussed and decided it is better to continue to use the old "export" action as it is supported by old OSGi framework implementations and, while deprecated, supported by all new OSGi implementations because the code that cares is in the OSGi PackagePermission class which will never remove support for the "export" action.
