### ISSUE TITLE
Tester code still writes to stdout for SKIPPED tests

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#4808]
In our build, the testOSGi test still writes info on SKIPPED tests to stdout. This should not be the case.

```
TEST bndtools.core.test.editors.quickfix.BuildpathQuickFixProcessor_WithEmptyBuildpath_Test#withSimpleInnerType_suggestsBundles() <<< SKIPPED
TEST bndtools.core.test.editors.quickfix.BuildpathQuickFixProcessor_WithSimpleOnBuildpath_Test#withInconsistentHierarchy_forTypeArgumentImplementingForeignInterface_suggestsBundles() <<< SKIPPED
TEST bndtools.core.test.editors.quickfix.BuildpathQuickFixProcessor_WithSimpleOnBuildpath_Test#withFQClassLiteral_inheritingFromInterfaceFromAnotherBundle_asAnnotationParameter_suggestsBundles() <<< SKIPPED
```

**Comment by kriegfrj** [comment]
This needs a bit of thought & discussion as any fix here is likely to affect other users too.

The relevant code is here:
https://github.com/bndtools/bnd/blob/f5dec256812f81dff27379d90bd56a2286b74fd4/biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/Activator.java#L188-L213

The tester adds three listeners that output direct to the console (in addition to the the XML generator and the Eclipse listener if appropriate).

* The `LoggingListener` provides detailed output on the test execution progressing using the `trace()` function. `trace()` outputs to stdout, but only if `tester.trace` is set to `true`.
* The `SummaryGeneratingListener` outputs the results summary at the end. `trace()` is again used.
* The anonymous listener which @rotty3000 added (https://github.com/bndtools/bnd/pull/3515) to try and more closely emulate the old tester. This outputs all failures, aborts and skips to stdout.
 
On closer inspection, it is a slight departure from the old tester - the old tester would log failures to stdout always, but aborts only if `tester.trace` was set (the old tester hand no concept of a "skip", but "skip" more closely aligns with "abort" than "fail" so it would make sense if it behaved the same).

The simplest fix I think will be to change the anonymous lister to make aborts & skips use `trace()` instead of `message()`. I think I will do that for now.

But because people have different preferences for what they want to see in their output there is a longer-term question about how to tweak default logging behaviour, which at the moment is largely hard-coded, (only the single boolean `tester.trace` configuration option). The current implementation gives you the ability to add your own custom logging, but not to completely suppress the built-in logging (ie, nothing to stop failures appearing on stdout).
