### ISSUE TITLE
Request to build milestone releases

### ISSUE THREAD

**Issue by amitjoy** [bndtools/bnd#4837]
Our team comprises avid users of Bndtools who use bndtools for the primary work of our jobs. Since our workspace currently comprises around 300 bundles, we kind of use lots of advanced features of Bndtools to get the most out of it. Since Bndtools 6 will be a major release, I proposed the team to move to Bndtools 6 SNAPSHOT but the team was a bit reluctant to switch to SNAPSHOT as in our earlier days when we migrated our workspace from PDE to Bndtools we were using the Bndtools 5.x SNAPSHOT and all of a sudden, a breaking change caused pipelines to fail continuously. After digging deep, we found the cause to be in the snapshot version which we got fixed after we reported it to Bndtools but there was a small phase where everything was put on hold until we figured it out. We couldn't even go back to using the previous release version as lots of important features of the snapshot were in use already. I know this is not ideal but it gave us ample amount of time to start integrating new features to the existing workspace and keep the workspace up-to-date always.

Such an incident is the cause of reluctance of integrating Bndtools 6 SNAPSHOT once again into our build. But we still believe the use of Bndtools 6 will be vital for us as we would then be able to test the existing features thoroughly and integrate new ones without the rush. If we find problems, we would still have enough time to report or discuss with the Bndtools team before the final release. Finding bugs or breaking changes after the final release would not only hamper our development but would cause you problems building another release later with the fix. That's why, it is, we believe, beneficial for us to start using Bndtools 6 now.

I would, therefore, like to request you, if at all possible, to build a biweekly or triweekly version of Bndtools 6 SNAPSHOT and host it somewhere for users like us. It would be, kind of, a milestone release that we can keep on using in our builds.

I believe, we both will be mutually benefitted from this as it would give us a sufficient amount of time to start testing the existing features and integrate the new ones. On the other hand, if anything doesn't work as expected, we would be able to report it immediately before the final release.

I would appreciate your further feedback in this regard.

**Comment by amitjoy** [comment]
Since `https://bndtools.jfrog.io/bndtools/libs-snapshot-local` comprises all the snapshots as well as releases, we could think of deploying the milestone release artefacts to the same repo.

**Comment by bjhargrave** [comment]
> Such an incident is the cause of reluctance of integrating Bndtools 6 SNAPSHOT once again into our build

Well your main build should not use a SNAPSHOT tool. But you should have test builds which use the SNAPSHOT Bnd. OSGi does this. See <https://github.com/osgi/osgi/actions/workflows/bnd-test.yml>. Then we know when Bnd changes causes issues for OSGi.

> I would, therefore, like to request you, if at all possible, to build a biweekly or triweekly version of Bndtools 6 SNAPSHOT

As you know, we already build SNAPSHOT builds all the time. If you are looking for a build that does not have any bugs... well we all want that but we are not perfect. Even if we call them Milestone builds, they can still contain disruptive bugs.

I have updated the build so that we can publish Milestone and RC builds to libs-release-local where they will be stable and not overwritten like SNAPSHOT builds are by the next build. Then you can use those internally after some internal testing to make sure they work with your build environment.

But I do not have time to do the release management of such milestone builds on an ongoing basis.

> Since `https://bndtools.jfrog.io/bndtools/libs-snapshot-local` comprises all the snapshots as well as releases

libs-snapshot-local is only SNAPSHOTs. libs-release-local is only releases and is where Milestone and RC builds will now go.

I am test building 6.0.0-M1 now and hope to build RC1 tomorrow. And we will make more RC builds as we ramp down to the final 6.0.0 build.

**Comment by bjhargrave** [comment]
6.0.0-M1 build is now available. See <https://github.com/bndtools/bnd#using-the-latest-development-milestonerelease-candidate-build-of-bndbndtools> for how to access it.

**Comment by amitjoy** [comment]
@bjhargrave Thanks a lot for your valuable feedback and support. I agree with you completely that every version will certainly contain bugs to some extent, be it releases, milestones or snapshots. The expectation is to have a release that doesn't break the most used features of bnd. Since you are busy with different projects, I understand completely that you won't have enough time to maintain the milestone builds. I'd be happy to assist you in any way if you need.

**Comment by pkriens** [comment]
I'd like to disscus this Friday ...
