### ISSUE TITLE
Adding transitive dependencies in BND?

### ISSUE THREAD

**Issue by strmecki** [bndtools/bnd#4894]
Is it possible to have transitive dependencies in -includeresoruce as part of the bnd-maven-plugin?

The old maven-bundle-plugin had an `<Embed-Transitive>true</Embed-Transitive>` flag/option.

**Comment by bjhargrave** [comment]
In general, the concept of embedding your dependency jars is not a great idea. One should depend upon your dependencies via Import-Package. If you need to have a private copy of some packages in your bundle because you don't want to expose the dependency externally, you can [`-conditionalpackage`](https://bnd.bndtools.org/instructions/conditionalpackage.html) those packages and Bnd will "slurp" those packages into your bundle.

You can also manually embedded jar from the classpath using the `lib:=true` directive of `-includeresource` if you really must. [example](https://github.com/lakshya-aggarwal/aem-elastic-search/blob/47ca6e394461f9a95aae97e326d3df76da361ac3/core/pom.xml#L85-L99)

So I do not see adding `<Embed-Transitive>true</Embed-Transitive>` function to bnd-maven-plugin.

**Comment by pspuri91** [comment]
@bjhargrave I agree with what you are saying and sounds like the most efficient and ideal way to do it. But, the problem arises when your dependencies have multi-level transitive dependencies going n-level deep. But, the difference in usage between -conditionalpackage/lib:=true and Embed-Transitive is that Embed-Transitive didn't require us to know the details of every nth level deep transitive dependency and its Java package name. It creates an all-inclusive jar/bundle automatically. With these methods, you will be required to know either those Java packages names(in case of -conditionalpackage) or artifact-ids of all the transitive dependencies that your dependency is further dependent on. 
With lib:=true, since it embeds jar from the classpath, you need to declare all the transitive dependencies to be your direct dependencies as well, which wasn't the case with Embed-Transitive.
Please let me know if I'm missing something and if there is a better/quicker way to embed these transitive dependencies.

**Comment by rotty3000** [comment]
First of all, everyone, I feel your pain. I have worked with a large OSGi based enterprise product for many years and we have re-packaged countless non-OSGi dependencies, without a transitive dependency function.

You could approach the problem from two points of view:
- *the purist* - OSGi is foremost about modularity. The thought of blindly accepting the transitive dependencies without consideration the cost, potential impacts, understanding how that dependency works is abhorrent and counter not only to best practices but to the true nature of OSGi itself.
- *the pragmatist* - I really just want to use dependency X. I'll accept the consequences.

Our team started as purists. However, eventually we built a transitive dependency embedder tool on top of bnd because the cost to development was too high. However, this tool has resulted in deferred costs of maintenance. Why? Because not carefully understanding dependencies is bad. Embedding those dependencies inside another artifact without careful analysis is worse.

Just look at the log4j vulnerability. Would you really want to go looking through all those `Embed-Transitive` bundles right now? The whole idea of OSGi is intended to be a mitigating factor to this kind of problem by permitting systems built with clear, visible inter-dependencies that one can calculate using tooling.

**Comment by bjhargrave** [comment]
> Just look at the log4j vulnerability.

:-) QED

**Comment by pkriens** [comment]
And this is the root of most software evil:

> But, the difference in usage between -conditionalpackage/lib:=true and Embed-Transitive is that Embed-Transitive didn't require us to know the details of every nth level deep transitive dependency 

I am an old guy, and as probably most old guys  I cannot watch but with horror to what is happening in the software world today. The idea to send something out in the world and you are not even intircately aware off that it is inside, is not ethical in my opinion. As a curmudgeon, to me software seems become less and less  an engineering discipline. I doubt Log4j is going to be the last disaster. (A few months, I actually removed it from customer's build, among hundreds of other dependencies we could remove. Yeah!)

I've worked for hundreds of companies and what I've seen is that the most productive organizations were disciplined, and that included their handling of dependencies. Probably any technology works well in those organizations but OSGi then works perfect to enforce that discipline automatically on all levels. When I get into a company, the first thing is to make sure there is an automated build and _all_ the dependencies are brought to heel. Even if those companies are not that organized in their dependencies, once the system is cleaned up the advantages are so glaringly clear they never revert, and OSGi helps tremendously to keep the system pure. And pure pays off handsomely.

OSGi was designed to enforce strong modularity. Fight it, and embedded dependencies _is_ fighting it, will quickly show that OSGi is a bitch, _as she should be_; she is defending your bundle's integrity. 

As [Parnas](https://prl.ccs.neu.edu/img/p-tr-1971.pdf) showed in 1971, the benefits of modularity are very sensitive to _how_ you decompose the system. In his paper, he takes a simple problem and then decomposes it into different modules to show how some decomposition's are much easier to maintain than others. His invaluable contribution to computer science is that the key to good software is _high cohesion_, the level of relatedness the adjacent parts in the same enclosure.

I know this is all a bit pedantic. However, you're asking us to add features that go against some of the most basic held believes about how software should be build. In my opinion, when you really need these features, you probably don't need OSGi :-)
