### ISSUE TITLE
[maven] Resolution of com.sun.jna fails

### ISSUE THREAD

**Issue by kenwenzel** [bndtools/bnd#4985]
Using

`mvn bnd-resolver:resolve`

in the following example project https://github.com/kenwenzel/bnd-resolver-issue triggers the exception:

```
[ERROR] Resolution failed. Capabilities satisfying the following requirements could not be found:
    [<<INITIAL>>]
      ⇒ osgi.identity: (osgi.identity=com.sun.jna)
          ⇒ [com.sun.jna version=5.10.0]
              ⇒ osgi.native: (|(&(osgi.native.osname~=win32)(osgi.native.processor~=x86))(&(osgi.native.osname~=win32)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=win)(osgi.native.processor~=x86))(&(osgi.native.osname~=win)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=win)(osgi.native.processor~=aarch64))(&(osgi.native.osname~=wince)(osgi.native.processor~=arm))(&(osgi.native.osname~=sunos)(osgi.native.processor~=x86))(&(osgi.native.osname~=sunos)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=sunos)(osgi.native.processor~=sparc))(&(osgi.native.osname~=sunos)(osgi.native.processor~=sparcv9))(&(osgi.native.osname~=aix)(osgi.native.processor~=ppc))(&(osgi.native.osname~=aix)(osgi.native.processor~=ppc64))(&(osgi.native.osname~=linux)(osgi.native.processor~=ppc))(&(osgi.native.osname~=linux)(osgi.native.processor~=ppc64))(&(osgi.native.osname~=linux)(osgi.native.processor~=ppc64le))(&(osgi.native.osname~=linux)(osgi.native.processor~=x86))(&(osgi.native.osname~=linux)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=linux)(osgi.native.processor~=arm))(&(osgi.native.osname~=linux)(osgi.native.processor~=arm_le))(&(osgi.native.osname~=linux)(osgi.native.processor~=armel))(&(osgi.native.osname~=linux)(osgi.native.processor~=aarch64))(&(osgi.native.osname~=linux)(osgi.native.processor~=ia64))(&(osgi.native.osname~=linux)(osgi.native.processor~=sparcv9))(&(osgi.native.osname~=linux)(osgi.native.processor~=mips64el))(&(osgi.native.osname~=linux)(osgi.native.processor~=S390x))(&(osgi.native.osname~=freebsd)(osgi.native.processor~=x86))(&(osgi.native.osname~=freebsd)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=openbsd)(osgi.native.processor~=x86))(&(osgi.native.osname~=openbsd)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=macosx)(osgi.native.processor~=ppc))(&(osgi.native.osname~=macosx)(osgi.native.processor~=ppc64))(&(osgi.native.osname~=macosx)(osgi.native.processor~=x86))(&(osgi.native.osname~=macosx)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=macosx)(osgi.native.processor~=aarch64)))
```

The result of `uname -a` is 
`Linux ubuntu-vbox 5.4.0-86-generic #97-Ubuntu SMP Fri Sep 17 19:19:40 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`.

It may be that this exception just happens on my system.
Can you give me any advice what to do?

**Comment by njbartlett** [comment]
Your bndrun should include a line of the form:

    -runsystemcapabilities: ${native_capability}

Explanation:

The JNA bundle contains native code and therefore has a requirement for at
least one of the platforms for which the library binary is included. When
used at runtime, the osgi.native capability is derived from the machine on
which you are actually running OSGi. However, resolving a bndrun with the
bnd-resolver goal is a tool, and it does not assume any particular target
platform. For example, although you may run the Maven build on a Linux
machine, you may want to produce a set of bundles that will run on a
Windows machine, or vice versa. As a result, bnd does not set the
osgi.native capability to any particular value.

In order to resolve the JNA bundle then, you need to provide *either* a
platform, or just use the ${native_capability} macro which uses the
platform that the tool is currently running on. For example:

    # Resolve for Windows on 64 bit Intel/AMD
    -runsystemcapabilities: osgi.native; osgi.native.osname=win32;
osgi.native.processor=x86_64
    # Resolve for MacOS on ARM
    -runsystemcapabilities: osgi.native; osgi.native.osname=macosx;
osgi.native.processor=aarch64
    # Resolve for the current machine
    -runsystemcapabilities: ${native_capability}

**Comment by bjhargrave** [comment]
Usage questions should be asked in the Bnd Discourse Group. See <https://github.com/bndtools/bnd#feedback>.
