### ISSUE TITLE
gradle plugin should configure java plugin

### ISSUE THREAD

**Issue by mnlipp** [bndtools/bnd#5002]
The gradle plugin forwards `javac.source` and `javac.target` values from the bnd configuration to every [java compile task](https://github.com/bndtools/bnd/blob/c9ca99a4982282150084db4165cb14916ec1baee/gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/BndPlugin.java#L422). It does not, however, set `sourceCompatibilty` and `targetCompatibility` of the java plugin (wouldn't this be easier in the first place?).

This results in the generation of inconsistent settings files by the `eclipse` plugin ("`./gradlew eclipse`"), because the `ecplise` plugin [takes the value from the `java` plugin settings](https://docs.gradle.org/current/dsl/org.gradle.plugins.ide.eclipse.model.EclipseJdt.html).

Once aware of the problem, a work-around is easy.
```gradle
    // Set by bnd (as of 6.1.0) for each compile task but not for
    // "java" and is thus not forwarded to the eclipse configuration    
    java {
        if (bnd.get("javac.source")) {
            sourceCompatibility = bnd.get("javac.source");
        }
        if (bnd.get("javac.target")) {
            targetCompatibility = bnd.get("javac.target");
        }
    }

```

However, I think the bnd gradle plugin should do this itself.

**Comment by bjhargrave** [comment]
The java plugin switches from JavaPluginConvention to JavaPluginExtension at Gradle 7.1. So I try to avoid these types where possible. And since the source/target/release settings can be set on the compile tasks without regard to the JavaPluginConvention to JavaPluginExtension switch it made sense to do it that way. 

But given that some other plugins seem to care, I can make a fix to also configure the JavaPluginExtension (or JavaPluginConvention) as well.
