### ISSUE TITLE
Need way to limit concurrent connections to maven repository

### ISSUE THREAD

**Issue by kurthuwig** [bndtools/bnd#5035]
Our firewall blocks IP addresses that open more than 100 connections (SYN flood protection). Unfortunately the firewall blocks the whole traffic and not just new SYN packets.

It would be great if we could limit the number of concurrent HTTP connections.

As I workaround, I let my machine block itself:

`sudo iptables -A OUTPUT -p tcp --syn -d nexus3.huwig.de -m connlimit --connlimit-above 10 -j DROP`

**Comment by bjhargrave** [comment]
https://github.com/bndtools/bnd/blob/8368bad44603fb913daa8a74cc54af1c0b1a82ac/biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java#L145

You can set the `bnd.executor.maximumPoolSize` system property to limit the thread pool size. The HttpClient uses this thread pool and will use all available threads. 

> As I workaround, I let my machine block itself:

I suspect that is a better solution since it is that host with the issue and not other activities which use the thread pool.
