### ISSUE TITLE
"Clean storage area before launch" has no (or not the expected) effect

### ISSUE THREAD

**Issue by mnlipp** [bndtools/bnd#5061]
With some previous version (before 6.1.0) I could successfully preserve changes made with Configuration Admin between launches by unchecking the "Clean storage area before launch" flag in the Eclipse Run/Debug configuration.

Using 6.1.0, the flag no longer works. Even if unchecked, the information maintained by Configuration Admin is lost (simply use felix with GoGo shell, enter some configuration information and check after restart). A workaround for preserving the information between launches is to add `-runkeep` to `bnd.bnd` (I'm not using a separate `*.bndrun` because this is just a small test project).

**Comment by kriegfrj** [comment]
The only real work I can think of that happened on the launch delegate was when I changed it to use a facade. It's possible I broke it then. I'll try and have a look.

**Comment by kriegfrj** [comment]
I have verified that this is indeed occurring. I am able to reproduce a disappearing data file.

However, I am also able to verify that the launch delegate is doing the right thing - if I uncheck the "clear storage" option in the launch delegate and run with `-runtrace: true`, then I am seeing " # using working dir: C:\Users\fr.jkrieg\bnd\runtests.bndrun with keeping=true" in the console log, which is what it should do. It seems for some reason that it is not honouring the "keep" setting. This is using Felix 5.6.10.

Investigating further.

**Comment by kriegfrj** [comment]
Ok, here's what seems to be happening:

* `ProjectLauncher.calculateProperties()` will set the `FRAMEWORK_STORAGE_CLEAN` key of `runproperties` iff the `keep` flag is set to `false` (sets it to `onFirstInit`).
* `calculateProperties()` is called by `updateFromProject()`.
* `ProjectLauncher.setKeep()` simply sets the internal boolean field `keep`. It does not does not update the contents of `runproperties`.
* When `ProjectLauncherImpl.writeProperties()` is called, it writes out the launcher constant properties as special cases, and then copies the contents of `runproperties` verbatim.

To make this confusing, there are two flags that control this behaviour:
* LauncherConstants.LAUNCH_KEEP, which will get set to the value of the `keep` field when `writeProperties()` is called;
* `org.osgi.framework.Constants.FRAMEWORK_STORAGE_CLEAN`, which is what gets stored as one of the `runproperties`.

So when you launch using the `OSGiLaunchDelegate`, it calls `setKeep()` appropriately, and this value gets written as the property `launch.keep` to the launcher properties file (hence the correct log message coming out about "keep=true" when I run it with `-runtrace: true`). However, it does nothing to change the value of the `FRAMEWORK_STORAGE_CLEAN` key in `runproperties`, which has already been set to `onFirstInit` by this stage. So even though the *launcher* will not clear the storage area before launching, the framework (eg Felix) will.

Possible solution: The portion of `calculatedProperties()` that updates the `FRAMEWORK_STORAGE_CLEAN` property should move into `setKeep()`. Thus:

```java
	public void setKeep(boolean keep) {
		this.keep = keep;
		if (!keep)
			runproperties.put(org.osgi.framework.Constants.FRAMEWORK_STORAGE_CLEAN,
				org.osgi.framework.Constants.FRAMEWORK_STORAGE_CLEAN_ONFIRSTINIT);
	}
```
However, `calculatedProperties()` seems like it's trying to avoid writing directly to `runproperties`. Maybe the issue is that `ProjectLauncher.updateFromProject()` should not be calling `calculatedProperties(runproperties)` directly, and instead `ProjectLauncherImpl.writeProperties()` should be doing it on a copy of the props instead of on the original stored in the field.


Another thing that is counter-intuitive with this is that, if `-runkeep` evaluates to `false`, then the value of `FRAMEWORK_STORAGE_CLEAN` is *always* overwritten with `onFirstInit`. I also noticed similar behaviour for other framework properties that are updated by `ProjectLaunche.calculatedProperties()` - specifically, `FRAMEWORK_SYSTEMCAPABILITIES_EXTRA` and `FRAMEWORK_SYSTEMPACKAGES_EXTRA` will be overwritten by the `-runsystemcapabilities` and '`-runsystempackages` instructions respectively. If this is by design, then perhaps the launcher implementation should warn when it is ignoring/overwriting a value that the user has set explicitly in `-runproperties`.

**Comment by bjhargrave** [comment]
@kriegfrj Nice analysis. I have a PR coming with a fix!
