### ISSUE TITLE
[6.2.0] aQute.bnd.build.CircularDependencyException in Gradle Build

### ISSUE THREAD

**Issue by maho7791** [bndtools/bnd#5190]
I experience this exception, while building with gradle 7.4 and bnd 6.2.
The Eclipse IDE has no problems and I dont see any circular dependencies. It is also running on 6.2

It obviously belongs to the first project in the list. If I rename it, so that is not the first project anymore the build works fine. I attached the output.

[bnd-gradle-circular.txt](https://github.com/bndtools/bnd/files/8355866/bnd-gradle-circular.txt)

the Project can be found here:
https://github.com/geckoprojects-org/org.gecko.emf.utils

**Comment by bjhargrave** [comment]
The reported error in the attached file was collected during workspace initialization but was not reported until a gradle task operated on the project which provided the opportunity for the collected error to be displayed.

This is in the `-library` support code path which is not well conceived (IMO) especially when used on projects rather than the workspace. 

```
at aQute.bnd.build.LibraryHandler.getLibrary(LibraryHandler.java:249)
at aQute.bnd.build.LibraryHandler.update(LibraryHandler.java:221)
at aQute.bnd.build.Workspace.doExtend(Workspace.java:1851)
at aQute.bnd.build.Project.propertiesChanged(Project.java:2267)
```

If you remove `-library: enable-emf` from `org.gecko.emf.pushstreams/bnd.bnd` and `org.gecko.emf.collections/bnd.bnd` does the problem still occur?

When using `-library` in a project, Bnd must load all the Projects in case one of them builds the library. 

    at aQute.bnd.build.WorkspaceRepositoryDynamic.findProviders(WorkspaceRepositoryDynamic.java:33)

But this is a circularity problem when initializing the Workspace since to initialize the first project using `-library`, you need to initialize all projects and index their build files. 

    at aQute.bnd.build.Project.parseBuildResources(Project.java:3626)

But you are still trying to initialize a project. And since you are back to initializing projects, you need to try and load the library again. Circularity.

The circularity exception is saying that a project depends upon itself (which makes no real sense):

    [org.gecko.emf.bson],org.gecko.emf.bson

When using `-library` in the workspace, we do not look in projects. So we avoid the circularity problem. We may need to change to do this for using `-library` in projects. This then would mean that `-library` can only reference resources in the workspace's configured repositories and not in the workspace's projects.

**Comment by maho7791** [comment]
Hi,
I removed the -library instruction from the collection and pushstream projects. So now there is only a -library in the workspace left. The build works now.
