### ISSUE TITLE
Remove creation of module-info.java in Bnd project wizard

### ISSUE THREAD

**Issue by fipro78** [bndtools/bnd#5239]
When creating a new Bnd OSGi Project via the wizard, a dialog will popup at the end asking if you want to create the module-info.java. If you select "Create" you start a hard time getting the newly created project to work.

1. The created project shows directly compile errors.

This is because the module-info.java is empty and the osgi-annotations are not resolved then. Probably because the modulepath has higher priority than the Classpath. To fix this you need to know that you have to modify the module-info.java manually (I haven't found a working Quick Fix), e.g. like this:

```
module org.fipro.modifier.api {
	requires static osgi.annotation;
}
```

2. This adds the next issue, because osgi.annotation.jar is not available on the modulepath, it is not resolved. Fortunately there is a quick fix that proposes to move it from the Bnd Bundle Path to the modulepath.
3. After applying the quick fix, you see a warning because the osgi.annotation.jar does not have an Automatic-Modulename (shouldn't it have one? Should there be another ticket for this?)

The above is only for an API Bundle. For a Provider Bundle additional steps come into place, like adding the API package, org.osgi.service.component.annotations, and exporting the implementation package (which is of course something confusing for an OSGi guy to export a private package, but well, surely an issue of JPMS compared to OSGi, not a topic of Bndtools).

Actually the only option to get a working project in the IDE and a working module at the end, is to always say "Don't Create". So the dialog is only confusing for users and doesn't create a real benefit. I would suggest to drop that dialog. If a user wants to manually create a module-info.java file, he can do, otherwise it should be generated.

**Comment by pkriens** [comment]
I think this might be fixed. I cannot get the dialog to show anymore. Please open if it is still there with a small example repo and the exact steps to get this dialog.

**Comment by scottslewis** [comment]
I think that the NewJavaProjectPageOne class no longer (as of 2022-12 onward) opens a separate dialog...but rather has the specification of the module info on the NewJavaProjectPageOne (from which NewBndProjectPageOne inherits).

The change was merged in as part of this issue:  https://bugs.eclipse.org/bugs/show_bug.cgi?id=574640

In Eclipse 2022-12 onward, here's how the NewJavaProjectWizardPageOne looks

![image](https://user-images.githubusercontent.com/159988/213589847-2aae5843-11dd-4205-bcf0-4b9568ac372e.png)

Unfortunately, this addition to NewJavaProjectWizardPageOne actually breaks the proper functioning of NewBndProjectWizardPageOne because there is some verification logic in NewJavaProjectWizardPageOne that doesn't function properly...since NewJavaProjectWizardPageOne.createControl is overridden, and so the module info section never actually gets created by NewBndProjectWizardPageOne, and the verification that tries to use it fails.   This results in no available entries in the JRE Execution Environment combo box.

Here's a picture of NewBndProjectWizardPageOne on 2022-12 and newer:

![image](https://user-images.githubusercontent.com/159988/213590406-7de998c8-9ddd-4b5b-abc2-173d8f299ad3.png)

Note that neither of the combo boxes in the JRE section have any entries...making them useless.

I have a fix for this:  adding a bit of code to NewBndProjectWizardPageOne so that the module validation can occur properly in superclass, but keeping the module section from NewJavaProjectWizardPageOne invisible.   @pkriens if you would like open an issue for this I'll contribute my fix/workaround for review.

Unfortunately this change to NewJavaProjectWizardPageOne in org.eclipse.jdt.ui actually b

**Comment by pkriens** [comment]
I can reopen this. Your PR is welcome! 

I've been thinking of completely overriding the project creation since we only need a project name, all other info should come form the workspace. We already override almost anything from the Java parent classes and do not get any value from it since we override most of the .classpath content anyway.

**Comment by scottslewis** [comment]
> I can reopen this. Your PR is welcome!
> 
> I've been thinking of completely overriding the project creation since we only need a project name, all other info should come form the workspace. We already override almost anything from the Java parent classes and do not get any value from it since we override most of the .classpath content anyway.

Hi Peter.   Well...as it is the NewBndWizardProjectPageOne overrides the NewJavaProjectWizardPageOne createControl method.  As Eclipse 2022-12 NewJavaProjectWizardPageOne now sets up the module info section in the createControl method...and NewBndWizardProjectPageOne overrides createControl, the module info control doesn't get initialized...when the validation is attempted it throws an exception...because the validation code references the module info control...that hasn't been initialized because createControl was overridden and module info section initialization skipped.

You can see the 2022-12 New Java Project wizard page (with the module info section at bottom) in comment above.

This could/should be fixed by asking the NewJavaProjectWizardPageOne (platfrom) to fix this so that subclasses can override createControl (to leave out module section as NewBndProjectWizardPageOne does)...and modifying the validation code so that it doesn't require the initialization of module section to complete the validation.   But this would require restructuring code in NewJavaProjectWizardPageOne a fair amount (e.g. making private methods called to do validation protected), and my guess is that that's not going to be 'easy' to get platform folks to do.

In the immediate term, however, I've got small changes to the NewBndProjectWizardPageOne (only) that

1) Initializes the module info section but doesn't actually show it
2) Overrides the setPageComplete method so that the NewJavaProjectWizardPageOne validation is ignored

1 and 2 are essentially work-arounds rather than a proper fix for NewJavaProjectWizardPageOne, but at least allow the NewBndProjectWizardPageOne to function as subclass of the 2022-12+ version of NewJavaProjectWizardPageOne.   As things are now, NewBndProjectWizardPageOne doesn't function on 2022-12+ which is kind of a bad look for those of us who prefer to be on the front end of new eclipse releases.

After I fork and get things setup, I'll submit a pr that references this issue.

**Comment by pkriens** [comment]
@scottslewis can I close this?

**Comment by scottslewis** [comment]
Yes
