### ISSUE TITLE
Bndtools 6.3.1 Build stuck after project import

### ISSUE THREAD

**Issue by maho7791** [bndtools/bnd#5396]
# Initial project import
When importing a gradle bnd shape workspace into Eclipse for the first time, the build stucks.
It looks like an endless interaction between Building and Analysing Imports

I attached a JMC recording with 6 thread dumps from JMC

interesting are 
* **Worker-39: Building** and 
* **Worker-41: Analyse Imports**

It happened in this workspace:
https://github.com/geckoprojects-org/org.gecko.emf/tree/snapshot

at project org.gecko.emf.osgi.codegen

[bnd-build.zip](https://github.com/bndtools/bnd/files/9777127/bnd-build.zip)

# Eclipse Restart
I killed the java process, restarted Eclipse. Everything seems fine, the build finieshed. But there are  two threads left of kind **Analyse Imports** Worker 5 and 7 from bnd-build-restart.zip. 

I also attached the jfr from JMC
[bnd-build-restart.zip](https://github.com/bndtools/bnd/files/9777148/bnd-build-restart.zip)

# New Eclipse workspace and import again
I created a new Eclipse workspace, ran the project import again.

Now everything works.

I run Exlipse with Java 11, Ubuntu Linux

**Comment by pkriens** [comment]
Did you see the exceptions?

![image](https://user-images.githubusercontent.com/200494/196434121-fb55bd90-afb1-473c-9f06-889b4c4c23a2.png)

The Worker 39 is holding the lock but seems to be ok, none of the other threads is waiting for the lock. The Worker 41 is also bnd but since it does not use the workspace it does not have to be locked.

Any change to get the output the log?

**Comment by juergen-albert** [comment]
@maho7791 can we look if we can still reproduce this, as we have no clue right now how to precede here.
