### ISSUE TITLE
The bnd-testing-maven-plugin should report tests run

### ISSUE THREAD

**Issue by timothyjward** [bndtools/bnd#5397]
The output of the bnd-testing-maven plugin after a successful run is:

    [INFO] No Errors

Surefire, however, does

    [INFO] Running xxx.yyy.zzz.FooTest
    [INFO] Tests run: 41, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.422 s - in xxx.yyy.zzz.FooTest

It would be great for the bnd-testing-maven plugin to output the names of the tests that ran and the pass/fail/error/skip count. Even if this is only possible in aggregate that would still be useful as a flag that some tests ran.

**Comment by bjhargrave** [comment]
This will be hard since the Bnd testing is done in a different JVM than the maven build. So a JUnit listener cannot be easily used. It would probably require the `bnd-testing-maven-plugin` to process all the `TEST-*.xml` files created by the test JVM to collect up the tests/failure/errors/skipped counts so that a log entry can be created.

**Comment by timothyjward** [comment]
> This will be hard since the Bnd testing is done in a different JVM than the maven build. 

Doesn’t surefire do this when forking is enabled?

I’m sure we could depend on surefire to get the results out.

**Comment by bjhargrave** [comment]
The `bnd-testing-maven-plugin` (and the gradle `TestOSGi` task type) use the Bnd `Run` object's `test` method to launch the test JVM and run the tests. I don't see how we can easily depend upon the surefire plugin. Also, any solution here should also benefit the gradle `TestOSGi` task type.

**Comment by kriegfrj** [comment]
I think relying on processing those xml files is really a legacy approach.

I had an idea for the Gradle TestOSGi task to use a TestExecutionListener that runs over some kind of rpc to communicate to the host process. The host process can then process the test output directly in a form suitable for its environment (eg,in Gradle you could log the test errors as Gradle errors,  test warnings as Grasle warnings, 
etc). The bnd-testing-maven-plugin could use the same approach and possibly share the client-side implementation.

**Comment by kriegfrj** [comment]
Re: the above idea for using RPC to communicate to the host process: does anyone have a good idea about which RPC technology to use? Given that it is tightly-coupled and I would expect that client & server are both running on the same machine, I don't think it needs to be a full-fledged distributed RPC protocol with advanced discovery mechanisms, fault tolerance, etc. The host process should be able to start the RPC server implementation and pass the address (eg, TCP port number) to the test process when it starts. The test process will fire up the client and connect to the server on the address provided. It should ideally be a lightweight and fast protocol (eg, avoid XML-RPC or even JSON-RPC, instead use some efficient binary format). While the client-side will be in an OSGi framework, the same assumption cannot be made of the server-side.

Will also need a mechanism to delay running the tests until after the client-side listener has connected to the host.

Thoughts? Perhaps @scottslewis has some insights?

**Comment by scottslewis** [comment]
I think a remote service using a lightweight distribution provider would be useful here.   One nice thing about using remote services...the separation of discovery from distribution means you can/could simply use the edef-file-based discovery for dynamic service discovery on a single host.   

Of the distribution providers that ECF currently the following providers are relatively light weight (as compared to http-based providers):

1) TCP distribution provider - https://github.com/ECF/tcpsocketdistributionprovider.   This is a simple ServerSocket/Socket + Java Object Serialization
2) rOSGi distribution provider - This is an ECF distribution provider based upon rOSGI, which is itself based upon simple tcp ServerSocket/ClientSocket and Java Serialization - https://wiki.eclipse.org/Distribution_Providers#r-OSGi_Provider
3) ECF generic distribution provider - Also socket/Java serialization based - Used as the default provider in ECF examples.  Heavily tested and used. - https://wiki.eclipse.org/Distribution_Providers#Generic_Provider
4) xmlrpc distribution provider - Based upon xmlrpc...which is not used very more...probably because it's based upon xml and tcp socket rather than http - https://wiki.eclipse.org/Distribution_Providers#XML-RPC_Provider.   There has not been much recent use of this provider...that I know of so it may be out of date.
5) Google gRPC - This is a much more complicated distribution provider (by Google) but it's relatively heavyweight nature comes with support for using http2, binary wire protocol, support for streaming services/flow control (although I'm not clear if that would be desirable/necessary for this use case). - https://wiki.eclipse.org/Distribution_Providers#Google_Grpc_Provider

If something even more performant/custom was necessary (e.g. unix domain sockets) it would be pretty easy to create a new provider that used unix domain sockets (supported in Java 16 I understand).

**Comment by timothyjward** [comment]
> I think a remote service using a lightweight distribution provider would be useful here. One nice thing about using remote services...the separation of discovery from distribution means you can/could simply use the edef-file-based discovery for dynamic service discovery on a single host.

I'm sure that this would work, but it does feel like a lot of capability for a very minimal requirement. The amount of data being transferred is pretty low (a few kb at most) and the RPC will be running outside the launched OSGi framework. 

Can we not piggy-back on the existing reporting from the bnd test launcher, e.g. the socket connection defined by [this property](https://github.com/bndtools/bnd/blob/master/biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/Activator.java#L146)?

**Comment by bjhargrave** [comment]
I think we only need something very lightweight and not require a complex RPC mechanism. We don't really need to have any remote calls. All we need is for the VM running the tests to stream information back to the VM running the build. We already have an example of this in https://github.com/bndtools/bnd/blob/master/biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/JUnitEclipseListener.java for streaming the test results back to the Eclipse IDE. 

So all we need to do it make the test task in the build VM process the same results being sent to Eclipse on the tester port. (what Tim said.)

**Comment by pkriens** [comment]
aQute.lib contains the Link class that is used in the RemoteWorkspaceServer & Launchpad. An almost identical class is in use the remote agent.

It provides a fully bidirectional link between a client & a host. The communication is defined in an interface for either side. It is a very small, simple, and already in bnd. it uses the bnd JSON codec & Converter for the communications. 

PK

**Comment by kriegfrj** [comment]
> So all we need to do it make the test task in the build VM process the same results being sent to Eclipse on the tester port. (what Tim said.)

The `JUnitEclipseTestListener` *is* effectively an RPC mechanism that uses a highly customised, hand-written serialisation protocol. The only thing going for it is that it's what Eclipse uses for its JUnit integration. Reusing it for our purpose could be done, but would be non-trivial. We'd either need to write a custom deserialiser, or else try and lift the deserialisation code from Eclipse without bringing in any Eclipse dependencies. Both would be error prone - it's typically easier to serialise than deserialise, and writing the custom serialiser was hard enough. The only reason I wrote it is because we were constrained to integrate with the JUnit-Eclipse infrastructure. Plus, it is not a perfect match for JUnit 5's events and you lose a little bit when you try and force it to fit.

Given that there are so many RPC frameworks out there that will happily handle the serialisation/deserialisation for us, there would have to be a compelling reason to re-use the JUnit-Eclipse protocol instead of one of those. I know that @timothyjward has only asked for the summary at this point, but more is possible if we go down an RPC route (eg, in the Gradle world, integrating with the Gradle output and providing progress reporting at user-configurable verbosity).

> aQute.lib contains the Link class that is used in the RemoteWorkspaceServer & Launchpad. An almost identical class is in use the remote agent.
aQute.lib contains the Link class that is used in the RemoteWorkspaceServer & Launchpad. An almost identical class is in use the remote agent.
>
> It provides a fully bidirectional link between a client & a host. The communication is defined in an interface for either side. It is a very small, simple, and already in bnd. it uses the bnd JSON codec & Converter for the communications
It provides a fully bidirectional link between a client & a host. The communication is defined in an interface for either side. It is a very small, simple, and already in bnd. it uses the bnd JSON codec & Converter for the communications.

This ticks all the boxes, I think! I'll try and have a look next week.

**Comment by bjhargrave** [comment]
Currently the launched side of the tester (`aQute.tester.junit.platform`) does not depend on any other Bnd packages (outside of the jar). So I would be very cautious about bringing in any new package dependencies. The `aQute.lib.link` package has dependencies on other packages which in turn have more dependencies.

```
aQute.lib.link                          aQute.bnd.exceptions
                                        aQute.lib.io
                                        aQute.lib.json
                                        org.slf4j
```
