### ISSUE TITLE
bnd-testing-maven-plugin hangs indefinitely when tests are disabled

### ISSUE THREAD

**Issue by reckart** [bndtools/bnd#5460]
I wanted to run only a specific test in a particular reactor module using `mvn -Dtest=MyTest -pl :module-to-test -am`.

`test-utils` is a dependency of `module-to-test` and uses `bnd-testing-maven-plugin` as well but has no test called `MyTest`.

When I run the build, `bnd-testing-maven-plugin` hangs indefinitely in `test-utils` waiting for tests to complete (note there are no matching tests in this module).

I expect the  `bnd-testing-maven-plugin` to simply do nothing if there are no matching tests and let the build proceed with the next module in the reactor.

**Comment by bjhargrave** [comment]
> -Dtest=MyTest

Is the fully qualified name of your test class really "MyTest"?

We already test using test selection: https://github.com/bndtools/bnd/blob/f6194df9f04ce01a9147426cb17811654b99b10b/maven-plugins/bnd-testing-maven-plugin/src/it/test-single-test/pom.xml#L38-L40

If there is a real problem here, I will need a small github repo which demonstrates the problem.

**Comment by reckart** [comment]
No, the fully qualified name is not `MyTest`. But surefire does not require a FQN. See the example from the [surefire documentation](https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#test):

```
"-Dtest=???Test, !Unstable*, pkg/**/Ci*leTest.java, *Test#test*One+testTwo?????, #fast*+slowTest"
```

**Comment by bjhargrave** [comment]
Yes, but bnd-testing-maven-plugin is not surefire. bnd-testing-maven-plugin requires fqn and does not handle wildcarding.

**Comment by reckart** [comment]
That may be, but it is inconvenient :) IMHO, for a seamless integration, the bnd testing plugin should respect the same configurations as the standard surefire plugin.

In my scenario, I run tests once with surefire and then again once with the bnd testing plugin to ensure that they work properly outside and inside OSGI. That helps among other things discovering OSGI-specific issues which do not appear outside OSGI. 

I don't find documentation for the "test" configuration parameter. Does it support specifying multiple tests? If so, what is the separator? Which property can I specify on the command line to set the parameter? If it is `test`, then it conflicts with surefire if the two are not compatible.

**Comment by bjhargrave** [comment]
They share the same "test" property. bnd-testing-maven-plugin uses a comma separator  between test class fqns.

surefire is "operating" at the source code level which is why it uses ".java" as the suffix for the patterns. bnd-testing-maven-plugin is operating at the runtime level on bundles containing classes. Test bundles have a "Test-Cases" header listing the test class fqns to run. Multiple bundles can have Test-Cases headers. So it is much more complex to apply a set of globs to test names in the bnd-testing-maven-plugin scenario than it is for surefire.

The test name selection is part of the low level Bnd tester code which is used by both the gradle and maven plugins. So any improvement would have to occur here which would benefit all downstream users of testing.




> I don't find documentation for the "test" configuration parameter.

See https://github.com/bndtools/bnd/tree/master/maven-plugins/bnd-testing-maven-plugin#configuration-properties

**Comment by bjhargrave** [comment]
See https://github.com/bndtools/bnd/issues/5353 where a similar conversation took place.
