### ISSUE TITLE
[tester] Add an option to print a line for each executed test

### ISSUE THREAD

**Issue by laeubi** [bndtools/bnd#5507]
I'm currently experimenting with https://bnd.bndtools.org/chapters/310-testing.html and while running a lengthy test I noticed that that it is completely silent.

It would be good to have an option to print one line per test e.g.

```
Running <TestName1> OK
Running <TestName2> FAILED
Running <TestName1> 
```

Even though one can implement a custom `TestExecutionListener` (not sure if this will work for the "default" runner), this requires additional coding and deployment, and it seems offering it as an option does not add too much overhead.
The option might be named `tester.printTests`

**Comment by pkriens** [comment]
I am a bit confused why this is important? One can follow all that quite nicely in the Eclipse IDE?

**Comment by laeubi** [comment]
Not all test runs run in an IDE....

**Comment by pkriens** [comment]
No, but in gradle you get line by line information if you want ...

**Comment by laeubi** [comment]
> No, but in gradle you get line by line information if you want ...

What about maven then? Also I suspect we probably talking about different things, if there is no output from BND how could gradle print an info inf the test runs inside bnd?

**Comment by kriegfrj** [comment]
> 

Perhaps check out https://github.com/osgi/osgi-test/tree/main/org.osgi.test.junit5.listeners.log.osgi

It will log test output (as reported by JUnit platform through the TestExecutionListener) through the OSGi Log Service. Test failures are logged as errors, skipped tests as warnings, successful tests as info. Other test events (eg, about to start a new test) are logged at the debug level, so I think this will give you the progress that you are after and help you to debug long-running (perhaps deadlocked?) tests. I think it was a similar scenario that originally prompted me to develop that bundle. By appropriately configuring your log output you should be able to filter it to the information that you're after.

I also have a variant (that I have not yet polished enough to be part of osgi-test) that logs directly via SLF4J rather than using the OSGi Log Service. If the OSGi Log Service variant won't work for you but SLF4J will, I might be able to find some time to dust it off and commit it to osgi-test. (It's been a while, but I think the only thing that stopped me from committing it, apart from time, was trying to come up with a regression test.)

I have also toyed with a variant that implements a Java RMI implementation of the TestExecutionListener, which could then in turn be used by the Gradle or Maven test plugins to log through their respective build framework's logging environment. I got the RMI part working but didn't find the time to do the deep-dive necessary on the Gradle/Maven side of things.

**Comment by kriegfrj** [comment]
Btw, for reference, as you expressed an interest in console-based testing rather than in Eclipse...

JUnit 5 has some nice text-based reporting listeners that report JUnit Platform-based test output. Unfortunately, they have made the implementations private which means they can't be used easily by third parties without some gymnastics. There is an open issue in the JUnit repository to make them public: junit-team/junit5#1963 - I already submitted a PR to fix it but they didn't merge it as they didn't think there was enough demand to justify the additional ongoing maintenance commitment that making them public entails. If it's something that you're interested in, cast your vote there (a couple of others already have).
