### ISSUE TITLE
[testing] add in option to incrementally update the test-result file

### ISSUE THREAD

**Issue by laeubi** [bndtools/bnd#5508]
While evaluating https://bnd.bndtools.org/chapters/310-testing.html with a long running test, I noticed that the result file is created at test start, but only updated when all the tests finished.

It would be good to have an option to update the file after each test finished, e.g. `tester.incremental`

**Comment by pkriens** [comment]
The reporter JunitXmlReport creates the XML structure in memory. This will be a significant amount of work with imho little value.

**Comment by kriegfrj** [comment]
With the JUnit Platform test launcher, it is possible to install custom test listeners. The listener that produces the XML output is but one example of such a listener, and it is essentially a cut-and-paste from the JUnit project ([LegacyXmlReportGeneratingListener](https://junit.org/junit5/docs/5.8.2/api/org.junit.platform.reporting/org/junit/platform/reporting/legacy/xml/LegacyXmlReportGeneratingListener.html)) that has been moved into a different Java package. Playing with it would be essentially creating our own fork which is something I would like to avoid.

However, it is possible to produce your own test listener that listens to the test results as they come and reports them in whatever format you wish. It is not well documented, but you can do this simply by registering a service that implements [TestExecutionListener](https://junit.org/junit5/docs/5.8.2/api/org.junit.platform.launcher/org/junit/platform/launcher/TestExecutionListener.html) (you can use DS for this).

I would not have time to implement this suggestion but if someone else is willing to put in the hard yards I could fine the time to review it.

**Comment by laeubi** [comment]
> However, it is possible to produce your own test listener that listens to the test results as they come and reports them in whatever format you wish.

For sure I can also write my own test runner, or even an won test-framework, the point is that if one uses a lib / plugin / extension / ... it is to not reinvent the whole infrastructure or writing code that has nothing to do with the actual testing, so its a bit annoying if all _enhancement proposals_ are answered with "you can write your own code for that", see e.g. also 
- https://github.com/bndtools/bnd/issues/5514
- https://github.com/bndtools/bnd/issues/5520
- https://github.com/bndtools/bnd/issues/5507
- ...

So yes, some proposals might be relative easy to write on my own, but having that code *once* is much more efficient that asking each user to fire up there own "bnd-test-util" library. Some proposals might be *challenging* but again that's the purpose of using a library that solves these challenges one and for all.

**Comment by kriegfrj** [comment]
> So yes, some proposals might be relative easy to write on my own, but having that code _once_ is much more efficient that asking each user to fire up there own "bnd-test-util" library. Some proposals might be _challenging_ but again that's the purpose of using a library that solves these challenges one and for all.

My sincerest of apologies if I was seeming dismissive - that was not my intent. As I am not in a position to implement this for free for someone else, I was merely trying to outline the challenges that a willing implementer might face. I did offer to review any attempts to implement this suggestion, which I thought implied that I was open to it.

Certainly, I understand the benefits of writing and sharing libraries to do common tasks. It's more a matter of where is the best place to put all of these enhancements. 

When I originally wrote https://github.com/osgi/osgi-test/tree/main/org.osgi.test.junit5.listeners.log.osgi, I submitted a PR in this repository. After some discussion with @bjhargrave and others, it was decided that it is best to try use a more modular approach where the core tester plugin is kept relatively simple and focuses on the core functionality, and enhancements are implemented in optional add-in modules. Also, the functionality of the OSGi Log listener is not really bnd-specific (you could conceivably use it in a PDE environment, for example), so it made more sense to have it osgi-test. The problem if we try and make the core tester plugin be all things to all people is that it could get overly bloated and end up failing everyone.

I have had a quick look at `LegacyXmlReportGeneratingListener`. Having one file and appending as you go (as you suggested) would be non-trivial, I think, because the code as currently written using inbuilt Java XML libraries, which are geared around writing complete and compliant XML files, and are certainly not set up for appending to existing incomplete XML files. Changing it to use some other library that could output and maintain an XML file-in-progress would probably require writing the XML by hand.

One fairly trivial way it could be changed is to output more & smaller XML files - at the moment, it will output one per bundle. This could be changed to one per class or even one per method. I think that this is the option that I would recommend if you still feel that this is worth the effort.

So again, if you have the time & energy I'm willing to review a PR that implements something like this. But given that XML is already considered a "legacy" way of reporting test output, before investing too much time in this, perhaps it would be worthwhile taking a step back and investigating if there is a more modern replacement (that either exists already or that we can work towards implementing) can help you do what you want. Perhaps the RMI-based `TestExecutionListener` that reports test output directly through the Gradle or Maven build environment?

**Comment by kriegfrj** [comment]
> One fairly trivial way it could be changed is to output more & smaller XML files - at the moment, it will output one per bundle. This could be changed to one per class or even one per method. I think that this is the option that I would recommend if you still feel that this is worth the effort.
> 

Well, it's amazing what a little bit of GitHub archaeology can reveal... it looks like I already submitted a PR along these lines to the JUnit team but it was not accepted: see junit-team/junit5#1980 for the issue and junit-team/junit5#1981 for the associated (rejected) PR.

Now that we have a clone of `LegacyXmlReportGeneratingListener` in our own repository, you could use my old PR as a guide and implement it in our repository. And perhaps it would be worth us considering hiving it off into osgi-test too. However, see below...

> But given that XML is already considered a "legacy" way of reporting test output, before investing too much time in this, perhaps it would be worthwhile taking a step back and investigating if there is a more modern replacement (that either exists already or that we can work towards implementing) can help you do what you want.

The above archaeological dig also led me to the reason why my change to the LegacyXmlReportingListener was rejected (https://github.com/junit-team/junit5/issues/1980#issuecomment-532634061) - because it's legacy. But it also pointed me toward its replacement, which has since been implemented: junit-team/junit5#2868 implements a `TestExecutionListener` that outputs test information in the new Open Test Alliance format (open-test-reporting - see https://github.com/ota4j-team/open-test-reporting

My preferred way forward for this would be to OSGi-ify this new `TestExecutionListener` and include it as part of the osgi-test repo, I think. Would @laeubi, would this serve your needs? I"m not sure if Maven and Gradle and other tools have caught up with the new format yet, but if they have then I think it's better to try and spend our precious dev cycles on the future system rather than waste time on the legacy.

**Comment by laeubi** [comment]
- For the new format, if there is a successor for the "classic" format I think that's fine and its fair enough to expect consumers to adapt.
- About the legacy part, so what format is currently written? The main point is if you have a long running test (e.g. osgi-cm TCK runs ~ 20 minutes) and it is a single test, you only get one big XML file (what as itself is fine), but you only have zero way to observer it with standard BND run (see https://github.com/bndtools/bnd/issues/5507, https://github.com/bndtools/bnd/issues/5513 and https://github.com/bndtools/bnd/issues/5509), so even if one cancel the test it just all or nothing and a user can easliy get the impression the test is hung and do "nothing"
- On the other hand when you look at the result XML, then there *are* sections that relate to a test method that *seem* to be a valid result that might be written part by part (of course the file it self will always be overwritten to have a valid XML!), so at best it would start with an empty result file, then add the first executed test, then the second and so on if "incremental reporting" is activated, just as if the test has already completed
- About OSGi test, I think it could be a good place to host/manage the code so it can be shared, but still it would be useful for bnd test to have it included and all setup by an simple option, because that would increase user experience, as a tool user I really don't want to know all the details, I want to test my code! So every additional step needs additional documentation, additional configuration and decorates my test with stuff I actually don't want/need and do not pay on my primary goal
- That's also why I most of the time open a ticket, to suggest an improvement in the user experience not that I could "hack around it" in one way or the other (at least the debugger showed me in my case that tests are actually executed and I'm just not patient enough).
- Regarding contributions: Usually I like to contribute to open-source projects (and already tried so for bnd/osgi-test) but the contributor experience is rather bad: Issues are  closed for being not useful for anyone "from BND", so it is often vague, PRs are lingering around for ever or there always debates if one should actually change anything because everything is fine, if one actually should add a feature because "the BND" not directly see advantage of it and no one needs it (see before) ... so I resigned a bit of giving suggestions and hoping that a few are "useful enough" to be considered by a person that has enough bnd-power for their change to be accepted ;-)
