### ISSUE TITLE
Tests use deprecated `System.setSecurityManager`

### ISSUE THREAD

**Issue by wborn** [bndtools/bnd#5569]
A few tests use `System.setSecurityManager` which is deprecated in Java 17 ([JEP 411](https://openjdk.org/jeps/411)) causing warnings during builds:

```shell

./gradlew :build

...

> Task :biz.aQute.tester.test:test
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by aQute.tester.junit.platform.test.ActivatorJUnitPlatformTest$ActivatorJUnitPlatformTest_WithCustomAssertions (file:/home/wouter/git/github/bnd/biz.aQute.tester.test/bin_test/)
WARNING: Please consider reporting this to the maintainers of aQute.tester.junit.platform.test.ActivatorJUnitPlatformTest$ActivatorJUnitPlatformTest_WithCustomAssertions
WARNING: System::setSecurityManager will be removed in a future release
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by aQute.tester.testbase.AbstractActivatorCommonTest (file:/home/wouter/git/github/bnd/biz.aQute.tester.test/bin_test/)
WARNING: Please consider reporting this to the maintainers of aQute.tester.testbase.AbstractActivatorCommonTest
WARNING: System::setSecurityManager will be removed in a future release
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by aQute.tester.junit.platform.test.GogoShellTests (file:/home/wouter/git/github/bnd/biz.aQute.tester.test/bin_test/)
WARNING: Please consider reporting this to the maintainers of aQute.tester.junit.platform.test.GogoShellTests
WARNING: System::setSecurityManager will be removed in a future release
```

See also the results of this code search:

https://github.com/search?q=repo%3Abndtools%2Fbnd+System.setSecurityManager&type=code

**Comment by kriegfrj** [comment]
Thanks @wborn.

I'm aware of this issue.

The purpose of the security manager in those tests is to intercept calls to `System.exit()` so that we can run the tester and check the exit code without having it exit the JVM (and hence exit the test suit).

Unfortunately, there is no good replacement for this technique yet. See https://stackoverflow.com/questions/5549720/how-to-prevent-calls-to-system-exit-from-terminating-the-jvm/71150677#71150677, https://bugs.openjdk.org/browse/JDK-8199704. The good news is that it looks like the OpenJDK ticket on this has had some recent activity. But until a replacement is available, our only feasible alternatives are to put up with (or suppress) the warnings, or else disable those tests. Even when a replacement becomes available, it will be in a future JVM version that we won't move to for some time.

Another alternative would be to fork a new JVM to run the test, but then interfacing the results from the child process with the parent test process becomes a non-trivial task which I don't think I have time for.

**Comment by pkriens** [comment]
Duplicate of #5114
