### ISSUE TITLE
Multi-Release Jars and Executable JARs

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#5619]
Multi Release Jars act differently on different VMs.

Normally an assembly is created for a specific VM version. However, when we create an executable Jar we can set a minimum VM but we do not know the final target yet. Currently we always assumed backward compatibility in later VMs. Since an MRJ can have different requirements based on the JVM version, we need to consider 

- restricting the executable JAR on a range of VMs, or 
- create the superset of all the dependencies for all VMs and let the launcher select the proper set based on the current VM. We cannot install all of them since there might be conflicts.

I think we need a mode for the resolver that gives us a set of runbundles marked with the VM filter that they can be running on. (This could probably be made generic.)

This is a serious complication of the launcher. I more and more get the feeling the MRJs were intended as an OSGi killler ...

Any ideas?

**Comment by laeubi** [comment]
>  I more and more get the feeling the MRJs were intended as an OSGi killler ...

Not everyone is always on a rampage against OSGi... MRJs are completely independent from any technology based on java, and your described problem is a pure deployment problem, backward compatibility was already not ensured since Java 9+, you can even have modular JVMs that have not all modules included and so on.

As the set of version classes is fixed an know, and we assume there is release 11 and Release 14 and a minimum of Java 8 you simply need to compute three sets of jars, (J8, J11, J14), then you store them under:

```
/bundles.properties
/META-INF/versions/11/bundles.properties
/META-INF/versions/14/bundles.properties
```

The the launcher can lookup the resource from the jar with [JarFile#getJarEntry(`bundles.properties)`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/jar/JarFile.html#getJarEntry(java.lang.String)) to know what is the right choice, you probably also want  to store the jars only relevant for one version also in the version folders, this should also work for a Classloader#getResource (at laest the URLClassLoader is using a JarUrlConnection that uses JarFile#getEntry)....

**Comment by pkriens** [comment]
An issue is that some customers expand this executable JAR on the file system (it actually has an unzip built in for this).

So clever idea but we probably need something that works from the normal file system

**Comment by laeubi** [comment]
As said it all depends on who is using this "unzipped content"... e.g. Equinox/Eclipse can use "unexploded" bundles, still there must be something that starts the framework somehow, this code then might choose the right variant.

**Comment by pkriens** [comment]
see the content of the executable jars. it contains a windows and *nix shell start script to start the same way for the `java -jar ...` behavior. It increases performance because it requires the unzip at startup.

But I need to figure out of the MRJ loading works without a JAR, that would probably the best problem since then we can leave the logic to the VM.

We still need to figure out how to create the super set of all dependencies and of course create the different lists of bundles for each supported VM versions.

**Comment by pkriens** [comment]
No time to work on this so moving to abeyance
