### ISSUE TITLE
OSGi unit tests with MethodSource fail after upgrading to JUnit 5.9.3.

### ISSUE THREAD

**Issue by chrisr3** [bndtools/bnd#5655]
A `TestOSGi` task running a `@ParameterizedTest` with a `@MethodSource` fails after upgrading JUnit 5.9.2 -> 5.9.3.

I have already raised this with JUnit as [PR#3279](https://github.com/junit-team/junit5/issues/3279), and the JUnit developers have asked me to cross-reference that report here.

**Comment by kriegfrj** [comment]
@chrisr3 I think that you correctly diagnosed the root of this problem here: https://github.com/junit-team/junit5/issues/3279#issuecomment-1531238782_

**Comment by kriegfrj** [comment]
I'm fairly confident that this is a JUnit issue rather than a Bnd issue, and given that the class resolving is done by JUnit code with no external API to change that behaviour I don't think I could come up with a workaround as I have for some other problems. so I'm going to close this issue. It is nonetheless good that we have this issue here as a reference in case people run into this problem and come here looking for answers. If further investigation reveals a problem on Bnd's end we can re-open this.
