### ISSUE TITLE
Uses directive not automatically calculated for duplicate export-package names

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#5789]
Sometimes the same package needs to be exported in two different versions.
The 2nd export-package statement with the overwritten version does not contain the uses directive by default nor can it be explicitly added via the `<<USES>>` placeholder (documented in https://bnd.bndtools.org/heads/export_package.html)

I.e. the following bnd statement

```
Export-Package: *,my.package;uses:="<<USES>>";version="1.1.0"
```

leads to the following Manifest-Header

```
Export-Package: my.package;version="2.0";uses:="some.other.package",my.package;version="1.1.0"
```

(where `my.package` is exported as version="2.0" according to package annotations)

Therefore there is the need to manually add the uses directive e.g. in https://github.com/qos-ch/slf4j/blob/7c164fab8d54f823dd55c01a5a839c153f578297/slf4j-api/pom.xml#L66

I tried with maven-bundle-plugin 5.1.9 leveraging Bnd 6.3.1.

**Comment by kwin** [comment]
I added a simple reproducer in https://github.com/kwin/multi-version-export-bundle/tree/missing-uses-directive.
This one generates the manifest:

```
Export-Package: org.example.multiversionpackage;version="2.0.0";uses:=
 "org.example.anotherpackage",org.example.anotherpackage;version="2.0.
 0",org.example.multiversionpackage;version="1.0.0"
```

while it should be 
```
Export-Package: org.example.multiversionpackage;version="2.0.0";uses:=
 "org.example.anotherpackage",org.example.anotherpackage;version="2.0.
 0",org.example.multiversionpackage;version="1.0.0;uses:=
 "org.example.anotherpackage"
```

**Comment by pkriens** [comment]
When you start adding _noble lies_ like exporting multiple package exports the uses clause because hard to reason about. Its purpose is to handle multiple releases of the same program but you just faked that. Uses are specified without a version because they rely on the single namespace of the class loader.

I am trying to come up wit an example where the lack of uses in this cases would cause a problem. Clearly in the slf4j.api case, there are no uses. Also in this example, assuming there us a single bundle with `org.example.anotherpackage`, there is no issue.

So the simplest use case that might cause this problem is I think this scenario
```
Bundle A            export a;version=2;uses:=c, a;version=1
                    import c; version = [1,2)
Bundle C1           export c;version=1
Bundle C2           export c;version=2
Bundle B1           import a;version=2, c; version=2
Bundle B2           import a;version=1, c; version=2
```
B1 will be properly flagged as unresolveable because c is in the uses of a and A and B1 must be bound to different bundles for c. However, B2 would resolve and get a class cast exception in runtime.

The best solution is to manually fill in the uses for the literal version. You know the older version and can look at what imports it uses in its public API. This is by definition the API of the older version, not the current. Since this cannot change ever, it is therefore not much of a maintenance issue. I.e. if you 2.0.0 adds a uses constrain foo, you do not need to list foo in the old package since by definition it cannot have a reference through the API. Actually, the <<USES>> clause will likely over constrain the older package.

```
Export-Package \
     *,
     slf4j.api; version=1.78; uses:=slf4j.impl, \
     slf4j.helper; version=1.78

Should work imho.

My resistance is caused because I learned that you destroy core key value of a product when you go out of your way to support hacks that are needed **only** for pragmatic reasons. OSGi is the sweetest fairy with proper metadata but becomes a bitch when you start adding _noble lies_. I can handle the argument that OSGi has significant complexity but that is caused because it does a very difficult job, but we've often been blamed for problems that are caused by these kind of noble lies. Virtually every class cast exception in OSGi can be traced to false metadata.
