### ISSUE TITLE
Duplicate Export-Package header names lead to unresolved * placeholder

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#5795]
According to https://bnd.bndtools.org/heads/export_package.html the character `*` can be used to insert the automatically calculated values. But using this with overlapping package name leads to `*` being emitted as is.

Example:

```
<plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <version>5.1.9</version>
        <configuration>
          <instructions>
           ...
          <!-- Export the client/user package of slf4j-api version 1 to make the slf4j-api bundle in version 2 usable for bundles that only import slf4j-1.x -->
            <!-- Uses directive not automatically added: https://github.com/bndtools/bnd/issues/5789 -->
            <Export-Package><![CDATA[
              org.slf4j;uses:="<<USES>>";version="${backwards.compatible.version}",\
              org.slf4j.helper;uses:="<<USES>>";version="${backwards.compatible.version}",\
              *
            ]]></Export-Package>

....
```

leads to the following Manifest:

```
Export-Package: org.slf4j;uses:="org.slf4j.event,org.slf4j.helpers,org.s
 lf4j.spi";version="1.8.0",org.slf4j.event;uses:="org.slf4j,org.slf4j.he
 lpers";version="2.0.10",org.slf4j.helpers;uses:="org.slf4j,org.slf4j.ev
 ent,org.slf4j.spi";version="2.0.10",org.slf4j.spi;uses:="org.slf4j,org.
 slf4j.event,org.slf4j.helpers";version="2.0.10",org.slf4j.helper;versio
 n="1.8.0",*;version="2.0.10"
```

This seems to be related to issue #5789 as the order of those headers obviously matter (the USES is correctly calculated for a package the first time, but there is no export for  `org.slf4j` in version 2.0.10 and the export for `*` is obviously a bug.

**Comment by pkriens** [comment]
When bnd analyzes the bundles, it creates a database about packages in the project and their metadata. For Import-Package and Export-Package this database is the scope, it is kind of the work list to process. The content of the headers are a selection filter on this work list. This is why the `!` works. When you say `!foo.*`, all packages beginning with `foo.*` are removed from the work list and are thus not processed later when the `*` wildcard is reached, which would match the remaining items in the work list.

If bnd finds a fully specified literal match (no wildcards) that is not in the work list it it treats it as if it was matched but of course there is no metadata then to set the version or <<USES>>. You're on your own with such a literal. As you should be because this is hacking that corrupts the invariants of OSGi/bnd. You better know what you're doing because you get into this god awful metadata hacking that tends to turn OSGi from a benign fairy like god angel into a fury bitch. 

However, since we have had to make test cases for bad OSGi metadata bnd is quite flexible. In this case you want to augment the existing metadata, so you should first let bnd do its thing. Then as a bad (although sadly sometimes inevitable) afterthought you can sneak in the hack.

       Export-Package: \
                *, \
                org.slf4j.api;version=2.0.0, \
                org.slf4j.helper;version=2.0.0

You will _not_ get `<<USES>` support this way. The metadata for this has been gone at that time. The statements that do not match the work list are treated as literals. This does not seem to be an issue unless you want to use this already warped metadata in an OSGI framework that would support version 3 of  slf4j in the same VM? If that is the intention then my mind will finally detonate.

**Comment by pkriens** [comment]
I am going to close this since I think this can be solved
