### ISSUE TITLE
Wrong package version calculated for package exported with both implicit and explicit version

### ISSUE THREAD

**Issue by kwin** [bndtools/bnd#5796]
When the same package should be exported in two versions, one manually set in Bnd file and the other one determined from the package-info.class, the second export uses incorrectly the bundle version instead of the version determined by the Annotation `org.osgi.annotation.versioning.Version`.

You find an example in <https://github.com/kwin/multi-version-export-bundle/tree/main> (leveraging `bnd-maven-plugin`, 6.4.0)
This one incorrectly generates the following MANIFEST.MF

```
Export-Package: org.example.multiversionpackage;version="1.0.0",org.ex
 ample.anotherpackage;version="2.0.0",org.example.multiversionpackage;
 version="0.0.1"
```

while it should be 
```
Export-Package: org.example.multiversionpackage;version="1.0.0",org.ex
 ample.anotherpackage;version="2.0.0",org.example.multiversionpackage;
 version="2.0.0"
```

**Comment by kwin** [comment]
The order in the `bnd.bnd` seems to matter here, when exporting the implicit version first it takes the correct version "2.0.0".

**Comment by pkriens** [comment]
When bnd analyzes the bundles, it creates a database about packages in the project and their metadata. For Import-Package and Export-Package this database is the scope, it is kind of the worklist to process. The content of the headers are a filter on this worklist. This is why the `!` works. When you say `!foo.*`, all packages beginning with `foo.*` are removed from the work list and are thus not processed later when the `*` wildcard is reached, which matches the remaining items in the worklist.

If bnd finds a fully specified literal match (no wildcards) that is not in the wordlist it it treats it as if it was matched but of course there is no metadata then to set the version or <<USES>>. You're on your own with such a literal. As you should be because this is hacking that corrupts the invariants of OSGi/bnd. You better know what you're doing because you get into this god awful metadata hacking, in those cases OSGi tends to turn from a fairy like god mother into a the mean fury witch. 

However, since we have had to make test cases for bad OSGi metadata bnd is quite flexible. In this case you want to augment the existing metadata, so you should first let bnd do its thing. Then as an afterthought you can sneak in the hack.

       Export-Package: \
                *, \
                org.slf4j.api;version=2.0.0, \
                org.slf4j.helper;version=2.0.0

You will _not_ get `<<USES>` support this way. The metadata for this has been gone. The statements that do not match the work list are treated as literals.

**Comment by kwin** [comment]
Please look at the example from https://github.com/kwin/multi-version-export-bundle/blob/main/bnd.bnd (which does not leverage `*`).
This issue is only about the wrong version number being exported implicitly (bundle version instead of package version).
I assume the same underlying root cause applies here as well which is that bnd (incorrectly) assumes that each package name is only mentioned once in Export-Package. I guess the proper fix in bnd is to not remove packages from the metadata database once they are exported once. So somehow the flag of processed packages must be separately persisted (and not by removing the item from the metadata database).

**Comment by pkriens** [comment]
Did you try:
```
Export-Package: \
      o.e.m, \
      o.e.a, \
      o.e.m;version=1.0.0
```
Once it is matched, it is removed from the work list. So you should first allow to do its work, and then add literals.

**Comment by kwin** [comment]
I know about the workaround, but IMHO bnd should provide a proper fix.

**Comment by pkriens** [comment]
You can set `-nodefaultversion` to true. In that case you won't end up with the `0.0.1` version.

I do not see anything to fix here, you can do what you want to do when you put the literals at the end. Exporting packages on multiple versions in the OSGi world is like putting termites in your basement. It is just a _really bad idea_, it should only be done when the alternative is worse and you're sure you _fully_ understand the implications. It kills a large part of the OSGi value proposition. I fail to see a reason to optimize this use case.

**Comment by kwin** [comment]
> You can set -nodefaultversion to true. In that case you won't end up with the 0.0.1 version.

But then I wouldn't end up with the deliberate version 2.0.0 either, rather the version wouldn't be set at all.

> you can do what you want to do when you put the literals at the end.

Yes, but this is completely undocumented then at least. Because https://bnd.bndtools.org/heads/export_package.html does not mention anything about "consumption" of package names. Also it says explicitly: "If the source packages have an associated version (from their manifest of packageinfo file), then this version is automatically added to the clauses." with no condition whatsoever.

> I fail to see a reason to optimize this use case.

Well, I think SLF4J is a good example. It is not maintained with OSGi headers in mind by its maintainers. Rather those have been added later on by some contributors who want to leverage it in OSGi context. With version 2.x it was missed to update those headers accordingly (again, due to lack of OSGi knowledge) and now the package version 2.x is exported in the wild with no easy option to get rid of it (i.e. OSGi consumer might require version 2 or newer). Still it is fully backwards compatible to 1.7.x. Therefore exporting the same package twice is the only way out of this predicament, which would otherwise make other bundles support either 1.x or 2.x but never both!
Therefore it would be highly beneficial if at least the uses directives would be automatically generated for both package versions by bnd. With that optimization one could easily fix this issue as well (most probably implicitly fixed).

**Comment by pkriens** [comment]
I am a bit lost. If you do:
```
Export-Package: \
    *, \
    org.slf4j.api;version=1.0.0, \
    org.slf4j.helper;version=1.0.0
```
this gives you in the Manifest first the actual package versions and then after all standard package clauses, the _noble lies_:
```
Export-Package  \
    org.slf4j.api;version=2.0.0, \
    org.slf4j.helper;version=2.0.0, \
    org.slf4j.api;version=1.0.0, \
    org.slf4j.helper;version=1.0.0
```
I am not sure what you're missing now?

**Comment by pkriens** [comment]
I'd love a PR for the doc.  It is really quite bad actually.
