### ISSUE TITLE
Handle effectively `final` classes

### ISSUE THREAD

**Issue by ppkarwasz** [bndtools/bnd#5808]
Classes that only have private constructors are _effectively_ final. Adding or removing the `final` qualifier should not constitute a breaking change and there is also an [OpenRewrite recipe](https://docs.openrewrite.org/recipes/staticanalysis/finalclass) that does exactly that.

It would be nice if the `bnd-baseline-maven-plugin` didn't mark these changes as `MAJOR`.

**Comment by pkriens** [comment]
Thinking about this puts me a bit in a conundrum, I think.

Treating a private constructor only class as FINAL will create a backward incompatible change for everybody else because these classes suddenly become marked with final.

We could handle this via some option but managing that option seems a lot more work than just adding the final in the source code?

I really do not see a good solution. The baseline creates a tree of each element type and then compares the tree. This works very nice but it does not allow for rules like the OpenRewrite to be applied between the current and reference bundles.

There is also the situation that a FINAL bit has consequences for the JIT that might be consequential but I have not thought through that case. Might not be an issue since it

Last but not least, I get the following code to compile:
<img width="375" alt="image" src="https://github.com/bndtools/bnd/assets/200494/00b9e4c4-81a1-431a-834f-1143f1fe47d0">

Demonstrating that there are cases where final is not identical to private constructors.

So I am inclined to not do this unless someone convinces me.

**Comment by pkriens** [comment]
I am going to close as not going to be addressed. Feel free to open it again when you have really strong arguments to convince me :-)

**Comment by ppkarwasz** [comment]
> Thinking about this puts me a bit in a conundrum, I think.
> 
> Treating a private constructor only class as FINAL will create a backward incompatible change for everybody else because these classes suddenly become marked with final.

Yes, indeed it would be a backward incompatible change.

What about treating the addition/removal of the `final` modifier on a class the same way it is currently done, but demoting the kind of change from `MINOR/MAJOR` to `MICRO` if the class has only private/package constructors?

> Last but not least, I get the following code to compile: <img alt="image" width="375" src="https://user-images.githubusercontent.com/200494/274664839-00b9e4c4-81a1-431a-834f-1143f1fe47d0.png">
> 
> Demonstrating that there are cases where final is not identical to private constructors.

Classes with only a `private` (or package) constructor can indeed be extended, but only in the same package. Even if the kind of change to the `final` modifier is demoted to `MICRO`, the cumulative effect of removing/adding the `final` modifier **and** adding/removing a public/protected derivative class should still be `MINOR/MAJOR`.

**Comment by pkriens** [comment]
These problems are always hurting my brain :-( You're right that the extension is not an issue since we talk about public API and a class with private constructors can not be publicly extended. So that is not an issue.

I think I also did not have a proper mental model. You're right that if a class has made a class effectively final with private constructors between releases, it is a MAJOR publicly visible API change. It is actually a bug we do not report this.

As far as I can see now, we should be ok. This is the current situation that ignores the private constructors, so we have:

* F – `class.isFinal`
* P –  `all cons : class.getConstructors | cons.isPrivate`
* ' – the _next_ version.

|From  to:|  _ _        | _ F'         | P' F'         | P' _        |
|---------|---------|---------|---------|---------|
| _ _         | 🆗         | MAJOR | MAJOR  | 🆗            |
| _ F         | MINOR  | 🆗         |  🆗         | MINOR  |
| P F         | MINOR  | 🆗         |  🆗           | MINOR  |
| P _         | 🆗            | MAJOR | MAJOR  | 🆗           |

```
MAJOR = not F and F' 
MINOR =  F and not F' 
```
If we change FINAL to include all private constructors:

|From  to:|  _ _        | _ F'         | P' F'         | P' _        |
|---------|---------|---------|---------|---------|
| _ _         | 🆗         | MAJOR | MAJOR  | MAJOR 😳 |
| _ F         | MINOR  | 🆗         |  🆗         | 🆗  |
| P F         | MINOR  | 🆗         |  🆗         | 🆗  |
| P _         | MINOR 😳  | 🆗         | 🆗      | 🆗           |
```
MAJOR = ( F or P ) and not (F' or P')
MINOR = not ( F or P ) and (F' or P')
```

We do have 2 places with a backward incompatibility. However, I can live with this because it does observe a runtime error we are missing today. The difference we get rid of are actually not relevant.

I guess we're replacing the FINAL field with the concept of an EXTENDABLE, where the `EXTENDABLE` is `P or F`.

```
E = P or F
MAJOR = not E and E'
MINOR = E and not E'
```

I guess you convinced me :-)

**Comment by pkriens** [comment]
@bjhargrave hate to bother you but would appreciate it if you could verify my attempts to reason about this?

**Comment by bjhargrave** [comment]
I think the table has some errors. Here is a fix:

|From  to:|  _ _        | _ F'         | P' F'         | P' _        |
|---------|---------|---------|---------|---------|
| _ _         | 🆗         | MAJOR | MAJOR  | MAJOR 😳 |
| _ F         | MINOR  | 🆗         |  MAJOR (1)         | MAJOR (1) |
| P F         | MINOR  | MINOR (2)         |  🆗         | 🆗 |
| P _         | MINOR 😳  | MINOR (2)        | 🆗      | 🆗           |

1. Class goes from being constructable (has a non-private constructor) to not being constructable (only private constructors).
2. Adds a non-private constructor.

**Comment by pkriens** [comment]
You're right as usual. I think the implementation I made (setting the FINAL bit when all constructors are private) was already covering this since the differences you indicate were signalled by the addition/removal of public constructors.

But it is a good point that needs testing. I will update the test cases.

**Comment by pkriens** [comment]
@bjhargrave uncanny, tested the table you gave and this was exactly what I'd implemented. I had just tested the addition and removal of FINAL, but now I could directly compare the output of the classes tree diff!

https://github.com/pkriens/bnd/blob/85a44e0463f8504d3bf2084be090d84bd3549fe0/biz.aQute.bndlib.tests/test/test/baseline/BaselineTest.java#L100
