### ISSUE TITLE
[bndtools] package-info.java quickfix uses deprecated Version annotation

### ISSUE THREAD

**Issue by kriegfrj** [bndtools/bnd#5828]
When you export a package in Bndtools and there is no package-info, it will warn you and give you the opportunity to create one for your automatically. However, the automatically created one uses the Bnd annotation, which is now (since Bnd 7.0.0) deprecated in favour of the OSGi standard Version annotation. Should generate it using the new annotation.

**Comment by pkriens** [comment]
Are you sure the OSGi annotations are on your classpath? 

Looking at https://github.com/bndtools/bnd/blob/84e1bab7e8b2fcd6b09ef85a3ae2a7060eaf237c/bndtools.core/src/bndtools/editor/contents/PackageInfoStyle.java#L104-L109 I think it first tries to find the OSGi spec version and then as backup the bnd?

The functionality should be aligned with https://github.com/bndtools/bnd/blob/84e1bab7e8b2fcd6b09ef85a3ae2a7060eaf237c/biz.aQute.bndlib/src/aQute/bnd/build/PackageInfo.java imho. We seem to have an undocumented `-packageinfotype` that should control this decision.

**Comment by pkriens** [comment]
@kriegfrj did you check if the new annotation was on your class path?

**Comment by kriegfrj** [comment]
Have not had a chance to follow up yet,  so sorry!

**Comment by pkriens** [comment]
no problem! Appreciate all the work you do and energy you radiate!

**Comment by pkriens** [comment]
@kriegfrj sorry to push, but I want this list to be as small as possible ... We can always close it and then you can reopen it later.

**Comment by kriegfrj** [comment]
Ok, I've had a look - I can verify that, if osgi.annotation is on the build path, it uses `org.osgi.annotation.versioning.Version` instead.

I still don't think that this is the most useful behaviour. If I, as a seasoned user of Bndtools, can get confused or annoyed by it, then I think others probably will too.

I propose the following modifications to make the behaviour more useful:

1. Always use `org.osgi.annotation.versioning.Version`, even if it can't find it on the `-buildpath` of the current project.
2. The quick fix processor will be able to assist the user to fix the build error that results if that class is not on the `-buildpath`.
   a. Possible enhancement: automate this quickfix step - if there is only one matching bsn in the workspace for the `org.osgi.annotation.versioning.Version` class, then automatically add that to the `-buildpath`. 
3. Never attempt to use the deperated Bnd annotation.

I don't think it's helpful if our quick fixes generate deprecated code. For the user who doesn't know better it is confusing; for the user who *does* know better and still wants to use deprecated code, they will have the know-how to do so manually.

If there are no objections to this proposal, I will submit a PR.

**Comment by pkriens** [comment]
Sounds fine to me ...

**Comment by pkriens** [comment]
@kriegfrj I am working on changes in supporting the annotations in package-info.java. This code referred here is still very much associated with the Export-Package instruction. I do not think this is all too relevant anymore since we've been moving to use the -includepackage and then let the annotation drive it. 

I actually think we need to fundamentally change the BndEditor. Currently it is an editor for Import-Package and Export-Package but we should change it to show the actual result. It needs an overhaul. However, a bit unsure how are going to handle backward compatibility :-( Currently it is a bit of a mess and does not work well when you use -includepackage, which is actually the default ...

I also intend to add a lot of new refactorings, I developed a few helper classes to make it much easier to refactor. So before you work on this, let's discuss
