### ISSUE TITLE
Gradle build behaves differently than Eclipse bndtools when mvn package not found

### ISSUE THREAD

**Issue by dmm9** [bndtools/bnd#5858]
The summary is the following: on Eclipse+bndtools and using the bndtools.workspace.min template, I can build and run my bnd workspace successfully. But when trying to set up the Gradle build, the build fails. Therefore the build process is not consistent between Eclipse and Gradle.

The error:
```
> Task :app.monolith:compileJava FAILED
error  : app :No metadata for revision biz.aQute:biz.aQute.osgi.templates:1.0.0-SNAPSHOT
```
The root cause is that the version "1.0.0-SNAPSHOT" does not exist in maven central, which I have solved by commenting out this package in cnf/build.mvn
 
Suggested solution:
1. Unify the fail criteria in Gradle and Eclipse when a package is not found
- The error "No metadata for revision..." is reported in the [Maven repository provider](https://github.com/bndtools/bnd/blob/b82dc867a7920edfcf32cb2cfa408795f4af6aea/biz.aQute.repository/src/aQute/maven/provider/MavenRepository.java#L112) (L112 or L98, in version 7.0.0). For Gradle, it causes the build to fail. For Eclipse, it can go through it.
2. Fix the [bnd.workspace.min template](https://github.com/bndtools/bndtools.workspace.min/blob/5177798959113ab8515d2487b4bd72921acd5a35/cnf/ext/build.mvn):
  - Change the reference `biz.aQute:biz.aQute.osgi.templates:1.0.0-SNAPSHOT` to a valid version (a version which exists in maven central) or remove it if not needed.

Log:
```
2023-10-31T19:58:18.145+0100 [DEBUG] [aQute.bnd.repository.maven.provider.IndexFile] Failed to get biz.aQute:biz.aQute.osgi.templates:1.0.0-SNAPSHOT: Not found
java.io.FileNotFoundException: For Maven artifact biz.aQute:biz.aQute.osgi.templates:1.0.0-SNAPSHOT from [RemoteRepo [base=https://oss.sonatype.org/content/repositories/snapshots/, id=71DE1882, user=null]]
	at aQute.maven.provider.MavenRepository.lambda$get$0(MavenRepository.java:159)
	at org.osgi.util.promise.DeferredPromiseImpl$Submit.run(DeferredPromiseImpl.java:755)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by pkriens** [comment]
I've updated the bnd.workspace.min workspace: https://github.com/bndtools/bndtools.workspace.min/pull/10

Doesn't Eclipse report this on the Repositories View?

![image](https://github.com/bndtools/bnd/assets/200494/2c04d707-fb8b-446a-9c16-710b4bf25752)

I am not sure if in this case it needs to be perfectly the same since it is an error case and since Eclipse is interactive, it runs in the codepaths that the user directs. The erroneous setup might never be encountered.

I am closing this but feel free to reopen when you think you have a better solution and want to provide a PR.
