### ISSUE TITLE
UnsupportedOperationException when calling BndEditModel.setIncludeResource(...)

### ISSUE THREAD

**Issue by laeubi** [bndtools/bnd#5919]
```
java.lang.UnsupportedOperationException
	at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142)
	at java.base/java.util.ImmutableCollections$AbstractImmutableCollection.removeAll(ImmutableCollections.java:151)
	at aQute.bnd.build.model.BndEditModel.setIncludeResource(BndEditModel.java:1190)
```

the method tries to remove entries from one of the returned lists, but the returned value is an immutable collection.

**Comment by pkriens** [comment]
Don't use immutable lists? I could not find anywhere this method is used.

I'll fix it it because I despise `removeAll` and this is truly sucky code but the problem is in your novel use of ImmutableList. We nowhere specify that we do not touch the lists you give us, bad, but so is life. And nobody in bnd/bndtools use this method. 

If you run in these issues, please provide a PR and not an issue.

**Comment by laeubi** [comment]
> Don't use immutable lists?

I don't use one, BndModel do it... 

> And nobody in bnd/bndtools use this method.

That's probably because that bug didn't get noticed.

**Comment by pkriens** [comment]
> That's probably because that bug didn't get noticed.

As I said. Not that many people use the API directly outside the group and I have no direct ambition nor pay master to support this beyond our tools. 

And it is wonderful that you do exercise this code but then please fix the problem in a PR since:

* you're the only person with the problem, and 
* you're already at the place to fix it, and 
* you're part of the group. 

There is no use to report this as an issue since nobody will fix it for you.
