### ISSUE TITLE
[win] slow IO.getBasedFile

### ISSUE THREAD

**Issue by jukzi** [bndtools/bnd#6014]
since [JDK ](https://bugs.openjdk.org/browse/JDK-8207005) disable the file canonicalization cache File.getCanonicalPath is very slow on windows.
example sampling during building eclipse platform workspace.
![image](https://github.com/bndtools/bnd/assets/51790620/8f12c9dc-4287-47e5-97d7-aa533e73dc97)

the zipslip check in https://github.com/bndtools/bnd/blame/f6371af9346e75f0170987ceb52ce40cf5a8fa9b/aQute.libg/src/aQute/lib/io/IO.java#L850
could be much faster to just return child in the normal case that the filename does not contain an directory escape:
`if (!file.contains("..")) return getFile(base, file);`
which avoid costly file name capitalization at all.

**Comment by pkriens** [comment]
How would that affect links?

**Comment by jukzi** [comment]
for sure the return value of this function would not be the same, but that does not matter, because when the return value is used it will always write to the same effective file not matter if it's referenced by link or not. The purpose of this function never was to resolve links but only to prevent escaping the path. i.e. a filename in a zip file "../f" would not write to the the desired target, but "a/../f" would be legal - same as pure "f".

**Comment by pkriens** [comment]
I looked deeper. I do not think the simple check for '..' is reliable? We also need to handle absolute paths and paths containing backslashes, UNC paths, DOS paths etc. (I HATE WINDOWS). That said, i do agree this method was surprisingly inefficient. Since the path must be relative, there is no need to make it canonical.

I think this is the minimum that would make it reliable?
```
	final static Path DOTDOT = Path.of("..");

	/**
	 * Resolve the relativePath from the absolute file base. The relativePath
	 * must not resolve to a path that is not in the subtree of files from base.
	 * it may contain .. as long as this does not end up at the start when
	 * normalized.
	 *
	 * @param base the absolute base directory
	 * @param relativePath the relative path
	 * @return the absolute file resolved from base with relativePath
	 * @throws IOException
	 */
	public static File getBasedFile(File base, String relativePath) throws IOException {
		return getBasedFile(base.toPath(), relativePath).toFile();
	}

	public static Path getBasedFile(Path base, String relativePath) throws IOException {
		assert base.isAbsolute();
		Path f = Path.of(relativePath)
			.normalize();
		if (f.isAbsolute()) {
			throw new IOException("The relative path '" + relativePath + "' is absolute and it must be relative");
		}
		if (f.getName(0)
			.equals(DOTDOT)) {
			throw new IOException(
				"The relative path '" + relativePath + "' when normalized starts with ..: '" + f + "'");
		}

		return base.resolve(f);
	}
```
I added these test cases but I have a hard time testing the Windows check since my Windows machine hasn't been used for years and is slow as hell and seems to want to update everything :-( and all is broken.

Could you test this in IOTest.java? (I might have some matching strings wrong and I do not want to build it umpteen tines on Github actions).
```
	@Test
	public void testGetBasedFile() throws IOException {
		File base = new File("base").getAbsoluteFile();
		assertThat(IO.getBasedFile(base, "")).isEqualTo(base);
		assertThat(IO.getBasedFile(base, "foo/../bar")).isEqualTo(new File(base, "bar"));
		assertThat(except(() -> IO.getBasedFile(base, "..")))
			.contains("The relative path '..' when normalized starts with ..: '..'");
		assertThat(except(() -> IO.getBasedFile(base, "bar/../../..")))
			.contains("The relative path 'bar/../../..' when normalized starts with ..: '../..'");
		assertThat(except(() -> IO.getBasedFile(base, "/foo/bar")))
			.contains("The relative path '/foo/bar' is absolute and it must be relative");
		assertThat(except(() -> IO.getBasedFile(base, "//./foo/bar")))
			.contains("The relative path '//./foo/bar' is absolute and it must be relative");
	}

	@EnabledOnOs(WINDOWS)
	@Test
	public void testGetBasedFileWindows() throws IOException {
		File base = new File("base").getAbsoluteFile();
		assertThat(IO.getBasedFile(base, "foo\\..\\bar")).isEqualTo(new File(base, "bar"));
		assertThat(IO.getBasedFile(base, "")).isEqualTo(base);
		assertThat(except(() -> IO.getBasedFile(base, "..\\..")))
			.contains("The relative path '..\\..' when normalized starts with ..:");
		assertThat(except(() -> IO.getBasedFile(base, "c:/foo/bar")))
			.contains("The relative path 'c:/foo/bar' is absolute and it must be relative");
		assertThat(except(() -> IO.getBasedFile(base, "c:\\foo\\bar")))
			.contains("The relative path 'c:\\foo\\bar' is absolute and it must be relative");
		assertThat(except(() -> IO.getBasedFile(base, "\\\\sys0\\c$\\foo\\bar")))
			.contains("The relative path '\\\\sys0\\c$\\foo\\bar' is absolute and it must be relative");
		assertThat(except(() -> IO.getBasedFile(base, "\\\\.\\foo\\bar")))
			.contains("The relative path '\\\\.\\foo\\bar' is absolute and it must be relative");
	}

	private String except(RunnableWithException run) {
		try {
			run.run();
			return null;
		} catch (Exception e) {
			return e.toString();
		}
	}
```

**Comment by jukzi** [comment]
your JUnit with you implemenatation fails on windows:
```
java.lang.AssertionError: 
Expecting actual:
  "java.io.IOException: The relative path 'bar/../../..' when normalized starts with ..: '..\..'"
to contain:
  "The relative path 'bar/../../..' when normalized starts with ..: '../..'" 
	testGetBasedFile(IO.java:53)
```

**Comment by pkriens** [comment]
Can you take a look at the test cases if I cover all situations? https://github.com/bndtools/bnd/pull/6023/files

I did actually learn something about File ... I always thought that it worked like URI, that if you passed an absolute path it would return that one. I now see that it actually has a very special way of resolving. It does explain a couple of times File puzzled me ...

Anyway. That makes it look like we went completely overboard. 

I made the IO class now have separate implementations for Windows and other OSes since they differ so much here. If you are ok, let me know. And would be interested in performance improvements.
