### ISSUE TITLE
Repositories restored from XML are inconstent

### ISSUE THREAD

**Issue by mnlipp** [bndtools/bnd#6211]
(I know that this is an internal API, but the issue may have impacts that are yet unnoticed.)

bnd 7.0.0 (or some earlier version) has introduced the multirelease resources (using the more general concept of supporting resources). The supporting resources of a resource are accessible as `SupportingResource::getSupportingResources`. The implementation class `ResourceImpl` simply returns the value of an attribute.

This attribute is properly initialized if the `Resource` is built from a jar file. It is, however, not initialized when the `Resource` is restored using `XMLReosurceParser::parse`. I could also not find any code that fixes this when the resources thus obtained are used to initialize a repository (e.g. `PomRepository::read`). I could also not find any code that "lazily" restores the attribute.

The unexpected result of this is that e.g. a `Capability` returned from `ResourcesRepository::findProvider` has supporting resources if the repository was created from the jars, but it does not have these supporting resources if it was created from the XML (which I use for caching in order to avoid unnecessary downloading of jars).

https://bnd.discourse.group/t/multirelease-jar-and-resolution/308/11 may be related to this.

**Comment by pkriens** [comment]
I finally got around in looking at this but I am not sure this is a problem?

The **only** reason we have SupportingResource is because the bnd code base assumed everywhere that 1 jar == 1 Resource. MRJs turned this assumption invalid, suddenly a single JAR could provide multiple resources. The Supporting Resource interface allowed us to carry the multiple resources representing a single JAR, usually from ResourceBuilder, to the places like the ResourcesRepository where they are then expanded and become normal resources again.

So from an OSGi perspective there is no SupportingResource, nor should there be. A repository build with MRJs is properly OSGi serialized in the XMLResourceGenerator and properly read back in the XMLResourceParser. 

The SupportingResource is a kludge.

**Comment by mnlipp** [comment]
> suddenly a single JAR could provide multiple resources

Sorry, it seems that I didn't adapt my code to this change. Finding the required information being provided as SupportingResources after initial analysis of a jar made me assume that this is the place where it was *supposed* be found in the API -- after all, it *can* be restored from the `bnd.multirelease` information . I didn't consider that the SupportingResources might additionally be "blown up" to top-level resources.

**Comment by pkriens** [comment]
Np. As said it is a kludge but it is our kludge. As the primary author of the OSGi Resource model I am pretty strong on the idea that there only exists Resources with Capability and Requirements. It is better to create a more complicated model than introduce new concepts in this model.
Multi Release JARs are incredibly badly thought out since their capabilities and requirements depend on the running VM. There were two ways to model this. Either as one resource per VM range or the chosen model, a base resource and supporting resources that provide the VM dependent requirements and capabilities.

**Comment by mnlipp** [comment]
The only thing I'm wondering about is why the multirelease aspect couldn't simply be ignored. As far as I know, multirelease jars provide some classes in variants suitable for specific java versions. The java runtime picks the right one. The API provided by the different implementation classes (if exposed at all) must be the same, else the jar would be unusable.

So why should I bother about this multirelease feature from an OSGi perspective? It's simply as if the user had programmed some dependency on the runtime explicitly. The provided API and capabilities don't depend on which variant is used at runtime.

(I'm sure I'm missing something here.)

**Comment by pkriens** [comment]
Yup you're missing something :-)

You're missing the dependencies that are created by the implementation variations. E.g. on a java 17 there is an Http client, before that there was none. So a bundle can include an okhttp implementation for VMs < 17 and use the Java 17 Http client. If you run that bundle on a Java 17 VM then you do not want to require okhttp. 

Officially a MRJ must not provide public API in the versions but this is not enforced by the VM. So yes, sometimes you can even introduce new capabilities.

But they are a HUGE pita for, imho, very little value. If sun (ok Oracle) had thought about dependencies when I was still young, they would've never designed it like this.
