### ISSUE TITLE
[New Create new Workspace] No option to create bnd workspace outside of the eclipse workspace

### ISSUE THREAD

**Issue by juergen-albert** [bndtools/bnd#6302]
We usually have our bnd workspace outside of the eclipse workspace. I'm not sure if I overlook something, but it seems that this is not possible with the new mechanism?

**Comment by chrisrueger** [comment]
It seems possible but not intuitive. Not sure how to make it better but here is a manual workaround:

1. Create an empty Eclipse workspace somewhere e.g. 

<img width="423" alt="image" src="https://github.com/user-attachments/assets/7fcf3f66-1339-478d-b34e-5cb3e16f401d">

<img width="604" alt="image" src="https://github.com/user-attachments/assets/79d27403-f3a2-4aef-b5fe-9f5aac5bda9a">

2. Then do the "New bnd workspace" wizard

<img width="841" alt="image" src="https://github.com/user-attachments/assets/927a316d-1f39-4808-a807-41acdf7218a5">

3. choose a path outside eclipse workspace.
Uncheck all checkboxes.

<img width="586" alt="image" src="https://github.com/user-attachments/assets/2dc737c8-18f2-4cb3-a808-89e07eae8ea3">

When you press "Finish" nothing will happen (but the Bnd workspace was actually created outside eclipse). You now have to import it. 

4. Now import the workspace via **File / Import / Bndtools / Existing Bnd Workspace**

<img width="586" alt="image" src="https://github.com/user-attachments/assets/d097943b-d600-4da5-bd41-fdc2f385baa4">

4a. Choose the path outside Eclipse

<img width="586" alt="image" src="https://github.com/user-attachments/assets/149ceafc-bd5d-4371-8bfc-0fbec675ace5">


5. get this

<img width="997" alt="image" src="https://github.com/user-attachments/assets/90f552cb-ed91-419e-859a-83b0104fe452">




## Question

How do you do it today?

**Comment by pkriens** [comment]
We will not deprecate the previous workspace create so that can be used when you want to separate the Eclipse workspace from the bnd/git workspace. 

To be honest, I am not sure why it would be useful to separate those? If this is really important you can always use this function and create a new Eclipse workspace using the normal Eclipse functions?

For the release i want this out of the way, so open a new issue if you think this new workspace function needs a UI to specify the Eclipse workspace.
