### ISSUE TITLE
[bndlib] Provide a `-nice` option

### ISSUE THREAD

**Issue by laeubi** [bndtools/bnd#6321]
Felix Bundle plugin has [a `niceManifest` option](https://github.com/apache/felix-dev/blob/736d48ca46f9f7e2f60430333cf2db9df3c355e5/tools/maven-bundle-plugin/src/main/java/org/apache/felix/bundleplugin/BundlePlugin.java#L138) that [formats Manifest](https://github.com/apache/felix-dev/blob/master/tools/maven-bundle-plugin/src/main/java/org/apache/felix/bundleplugin/ManifestWriter.java) 

> Output a nicely formatted manifest that still respects the 72 character line limit.

It would be good if bnd offers a `-nice` option as well, as manifest are sometimes inspected on raw text editors as well, used in debug outputs and so on.
If bndlib offer the code, felix can even migrate to that code to reduce duplication of such efforts.

**Comment by stbischof** [comment]
`-prittyprint`

**Comment by chrisrueger** [comment]
bnd cli already has [print](https://bnd.bndtools.org/commands/print.html) command (via [JarPrinter.java](https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/print/JarPrinter.java) which is also used in the print view of the JarViewer), but after reading your sentence again, I don't think it respects the 72 character limit.

**Comment by chrisrueger** [comment]
I updated my comment.

we could try to integrate it.
I think in bnd the manifest writing part is in https://github.com/bndtools/bnd/blob/master/aQute.libg/src/aQute/lib/manifest/ManifestUtil.java

and hook in https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java#L366 do read a new "-nice" / "prettyprintManifest" instruction 

String nice = getProperty(NICE);

and pass it along. 
Should be doable. 

Could you contribute the addition to ManifestUtil so that it can do what Felix [ManifestWriter](https://github.com/apache/felix-dev/blob/master/tools/maven-bundle-plugin/src/main/java/org/apache/felix/bundleplugin/ManifestWriter.java) does?

**Comment by chrisrueger** [comment]
@pkriens if you don't have any objections in general, you can assign this to me.

**Comment by pkriens** [comment]
Why not make it the standard? No option? They are functionally the same manifests and it only adds a few more characters.

**Comment by chrisrueger** [comment]
> Why not make it the standard? No option? They are functionally the same manifests and it only adds a few more characters.

Can I then have an "ugly" option? sorry couldn't resit 🤣

**Comment by pkriens** [comment]
Yeah, that would work :-)

The only problem might be test case ... We are actually looking at the manifest in some places I think.

**Comment by chrisrueger** [comment]
> The only problem might be test case ... We are actually looking at the manifest in some places I think.

There were indeed two testcases in bnd which failed after I added the nice-writer from felix. 
I fixed them in commit https://github.com/bndtools/bnd/pull/6323/commits/0503ff76aefc63a909e6e47847acc16e374a727b

**Comment by pkriens** [comment]
@chrisrueger can this be closed?

**Comment by chrisrueger** [comment]
> @chrisrueger can this be closed?

I won't have the time right now to work on it. There is still your suggestion in closed PR https://github.com/bndtools/bnd/pull/6323#issuecomment-2407597883 So maybe somebody can take this over in the future. Yes, so let's close it.
