### ISSUE TITLE
Cannot resolve bundle from bndrun file in M2E project: Cannot find framework

### ISSUE THREAD

**Issue by sad-poet** [bndtools/bnd#6393]
Using the latest Bndtools snapshot in a M2E workspace, attempting to resolve a .bndrun file from the Eclipse IDE results in an error.

When trying to resolve the same file with Bndtools 7.1.0, a different error appears, as described in #6380.

This is a regression from Bndtools version 7.0.0, where everything works as expected.

## Steps to reproduce

I have prepared a reproducer Maven project that builds a minimal bundle using bnd-maven-plugin. The project contains a run.bndrun file that runs this bundle with Equinox, as well as debug.bndrun file that includes run.bndrun and adds Apache Felix Gogo console. The POM is configured to export executable JAR using bnd-export-maven-plugin.

1. Launch Eclipse IDE 2024-12 with Bndtools version 7.2.0.DEV-202412050913-g8c79789 (installed from https://bndtools.jfrog.io/bndtools/update-snapshot without Bndtools PDE integration).
2. Import the reproducer project from the archive: [bndtools-resolve-reproducer.tar.gz](https://github.com/user-attachments/files/18049710/bndtools-resolve-reproducer.tar.gz)
3. Open `run.bndrun` in Bnd Run File Editor and choose Run tab in the bottom of the editor.
4. Click Resolve button.

## Actual result

The following error message is displayed in the Resolution Results window:

```
Resolution failed. Summary:
      ⇒ Bundle: org.example.bndtools.bndrun.reproducer cannot be resolved

Note: The summary above may be incomplete. Please check the full output below for more hints.
Resolution failed. Capabilities satisfying the following requirements could not be found:

    [<<INITIAL>>]
      ⇒ osgi.identity: (osgi.identity=org.example.bndtools.bndrun.reproducer)

resolvedebug log: INFO: Using framework org.eclipse.osgi;3.21.0
ERROR: Cannot find framework org.eclipse.osgi;3.21.0
DEBUG: for osgi.identity;filter:='(osgi.identity=org.example.bndtools.bndrun.reproducer)' found []
DEBUG: for osgi.identity;filter:='(osgi.identity=org.example.bndtools.bndrun.reproducer)' found []
```

Bndtools version 7.0.0 can resolve the file correctly. bnd-resolver-maven-plugin v7.1.0 configured in the POM also works as expected (`mvn bnd-indexer:index bnd-resolver:resolve`).

## Expected result

There should be no error. A Resolution Results window should open, displaying the required resources used to create the Run Bundles list, which must contain exactly one bundle built from the project itself:

```
-runbundles: org.example.bndtools.bndrun.reproducer;version='[1.0.0,1.0.1)'
```

**Comment by chrisrueger** [comment]
Thanks for the report and for the reproducer. I could reproduce it. 

I have the feeling the bndrun cannot see the repositories, and thus cannot resolve the bundles.
![image](https://github.com/user-attachments/assets/f1f36f87-cd67-45ba-b7b3-5c8e01a5a770)

`biz.aQute.resolve.BndrunResolveContext.getAllRepos()` also returns an empty list, because the single EclipseWorkspaceRespository (returned by `project.getWorkspace()getPlugins(Repository.class, Constants.REPOTAGS_RESOLVE)` ) is filtered out. So the 2 Maven Repositories which are shown in the Repository Browser are not seen by the bndrun resolver. 

@pkriens I have no clue at the moment, but maybe the BndEditModel rework somehow is missing something so that the 2 Maven Repositories are not seen. Maybe because it is not a Bnd cnf Workspace. 

In a quick debug session I noticed that a default workspace instance is created. Not sure this is helpful
![image](https://github.com/user-attachments/assets/fa475196-6d4a-46dd-815d-d79bd10aca23)
Not sure this default workspace 


@sad-poet Could you maybe check which repositories you see in the Bnd Run Editor (first screenshot) with Bnd 7.0.0?

I have the feeling your other issues (https://github.com/bndtools/bnd/issues/6394 , https://github.com/bndtools/bnd/issues/6395 ) are related.

**Comment by chrisrueger** [comment]
Thanks @sad-poet I have created PR which could fix this. But need some feedback from @pkriens next days.
