### ISSUE TITLE
Move to use JDK 8 as the build JDK

### ISSUE THREAD

**Issue by bjhargrave** [bndtools/bnd#710]
We currently build bnd with JDK 7. See the .travis.yml file for example. When building with JDK 8, there are numerous warnings and one compiler error. These need to be fixed so was can change .travis.yml and cloudbees to build bnd with JDK 8.

**Comment by marcdejonge** [comment]
I tries to build with JDK 8 on my windows machines and there were 2 major problems:

1) Java 8 adds a java.util.Base64. This makes the java.util.* import ambiguous for the Base64 class, since it is also in aQute.lib.base64. This can easily be fixed by making the imports more specific, instead of just starring all packages.
2) The aQute.lib.collections.MultiMap class has a remove(K key, V value) method. The Java 8 compiler returns an error that it does not override the remove(Object, Object) but it has the same erasure.

The second problem is a bit more troublesome, because this will cause a major change in the API to fix (according to the baseline check).

**Comment by timothyjward** [comment]
A major change to the API would be possible in the move to 3.0, but not 3.1. 

Even if we're not going to build with JDK8 until bnd 3.1 we should think about making the API change now to avoid having to move the package version to 4.0 immediately after releasing 3.0.

**Comment by bjhargrave** [comment]
Java 8 added [Map#remove(Object,Object)](https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#remove-java.lang.Object-java.lang.Object-), so we need to rename the multimap method to avoid this.

**Comment by bjhargrave** [comment]
Closing for now.
