### ISSUE TITLE
[DS] configuration-policy incorrectly set to require

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bnd#827]
I have a DS component with

```
@Component(designate = Config.class)
```

When I look in the generated component xml I see
```
configuration-policy="require"
```

While the default for that setting is ```false``` according to my annotations jar:

```
Git-Descriptor: 2.4.0.REL-24-g6423e3d
Git-SHA: 6423e3d3856fc21167227f87eb22d1a3ff72c47b
```

**Comment by timothyjward** [comment]
The behaviour of the designate attribute of the bnd component annotation alters the default behaviour of the configurationPolicy attribute. When a designate is supplied the default configurationPolicy becomes required.

Note that this behaviour is different from the behaviour of the standard annotations.

The current behaviour has been the case since it was first introduced in [this commit](https://github.com/bndtools/bnd/blob/06016bf2971a6fef0c1dd6d8ce3124bb1dd9b2ac/biz.aQute.bndlib/src/aQute/bnd/make/component/ServiceComponent.java#L266)

Changing this behaviour would break existing components.

**Comment by fhuberts** [comment]
Ah ok I didn't know that, obviously.
Thanks.

**Comment by timothyjward** [comment]
No problem :)
