### ISSUE TITLE
Maven SNAPSHOT version in bnd-maven-plugin

### ISSUE THREAD

**Issue by donald-w** [bndtools/bnd#895]
Would you be interested in a pull request, which provides a maven bnd-maven-plugin configuration option which would allow for conversion of, say, 1.0.0-SNAPSHOT to 1.0.0.SNAPSHOT instead of 1.0.0.${tstamp}?  At the moment, https://github.com/bndtools/bnd/blob/master/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/MavenVersion.java forces ${tstamp} behaviour, with no way to override it (as far as I can tell).

```java

		if (qualifier != null) {
			int i = qualifier.indexOf(SNAPSHOT);
			if (i >= 0) {
				qualifier = new StringBuilder()
					.append(qualifier.substring(0, i))
					.append(TSTAMP)
					.append(qualifier.substring(i + SNAPSHOT.length()))
					.toString();
			}
		}
```

**Comment by bjhargrave** [comment]
I think something is needed here. We need a way for people to get a timestamp if they want and not get one if they don't want. This mapping of SNAPSHOT to timestamp was done by @njbartlett for the original 2.4.1 release of this plugin. But I think we need to do something for the 3.0 release (from the master branch.)

So I would be open to a PR (against the master branch for 3.0).

**Comment by hqstevenson** [comment]
I think we need this as well.  I'm currently trying to migrate some Maven projects from the maven-bundle-plugin to the bnd-maven-plugin, and this has turned out to be an issue for me.  The default behavior of the maven-bundle-plugin creates .SNAPSHOT versions, and I could use those inside Karaf for basic testing.  

I have yet to get working versions of a few of my bundles using the bad-maven-plugin because of this.

**Comment by bjhargrave** [comment]
Moving back to 3.2 as I think we need to allow for SNAPSHOT qualifiers in generated bundles.

**Comment by hqstevenson** [comment]
This isn't such a huge issue for me anymore - I've got my bundles working the way I'd expect now (it turned out to be user error, not the bnd-maven-plugin).

I still think this would be nice to have to avoid unexpected changes when migrating from the maven-bundle-plugin, but it's not killing me anymore.

**Comment by hqstevenson** [comment]
The SNAPSHOT behavior using -snapshot=SNAPSHOT isn't the same as the maven-bundle-plugin when SNAPSHOT versions are used when it comes to the Export-Package header.

The maven-bundle-plugin will append .SNAPSHOT to the exported package version, but the bnd-maven-plugin does not.

I tried creating a packinfo file, but that seemed to be ignored with 3.2.  

I also tried creating a package-info.java file with an annotation like this
@Version( "$[replace;${project.version};(.*)-SNAPSHOT;$1.SNAPSHOT]" )
and that seemed to work, but I get a warning about the versioning annotations being deprecated

aQute.bnd.annotation.Version annotation used in class com.pronoia.osgi.service.package-info. Bnd versioning annotations are deprecated as of Bnd 3.2 and support will be removed in Bnd 4.0. Please change to use OSGi versioning annotations.

Is there a way to set some sort of a version policy so that SNAPSHOT is preserved in the Export-Package header?

**Comment by hqstevenson** [comment]
Sorry - stupid user error as far as the packageinfo file being ingnored - it isn't.  But I'd rather not have to add this file to every package if I don't have to.

**Comment by bjhargrave** [comment]
First off, this issue is closed. If you really have a new problem, you should open a new issue.

> The SNAPSHOT behavior using -snapshot=SNAPSHOT isn't the same as the maven-bundle-plugin when SNAPSHOT versions are used when it comes to the Export-Package header.
> 

Why would you want to use SNAPSHOT in package versions? I can understand using it in Bundle-Version. In fact, the `-snapshot` instruction only operates on the Bundle-Version: <https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java#L392>.

So if maven-bnd-plugin has some support for SNAPSHOT in package versions, that is some special processing of the maven-bnd-plugin which is not part of bndlib or the bnd-maven-plugin.
 
> The maven-bundle-plugin will append .SNAPSHOT to the exported package version, but the bnd-maven-plugin does not.
> 
> I tried creating a packinfo file, but that seemed to be ignored with 3.2.

The file name is `packageinfo`. 

> 
> I also tried creating a package-info.java file with an annotation like this
> @Version( "$[replace;${project.version};(.*)-SNAPSHOT;$1.SNAPSHOT]" )
> and that seemed to work, but I get a warning about the versioning annotations being deprecated
> 
> aQute.bnd.annotation.Version annotation used in class com.pronoia.osgi.service.package-info. Bnd versioning annotations are deprecated as of Bnd 3.2 and support will be removed in Bnd 4.0. Please change to use OSGi versioning annotations.
> 
> Is there a way to set some sort of a version policy so that SNAPSHOT is preserved in the Export-Package header?

No since that support must be a "value add" of maven-bnd-plugin and not part of bndlib or bnd-maven-plugin.

**Comment by hqstevenson** [comment]
Sorry - I didn't notice the issue was closed.  Thank you for answering anyway.

I'm not sure why the maven-bundle-plugin does what it does, but I did get it to work with a packageinfo file.

Thank You
