### ISSUE TITLE
Gradle build template fails for a freshly created workspace

### ISSUE THREAD

**Issue by timothyjward** [bndtools/bnd#919]
I'm using Bndtools 3.0.0.20150410-101427-gc62b6e5 in Eclipse Mars M6, and tried to create a minimal Gradle build.

I used the OSGi Component template to create a bndtools project called foo.test, and accepted all of the defaults for the generated cnf project. I then tried to run the gradle command line build from the workspace root:

    Timothys-MacBook-Pro:gradle timothyjward$ gradle build

    FAILURE: Build failed with an exception.

    * Where:
    Settings file '/Users/timothyjward/test/gradle/settings.gradle' line: 18

    * What went wrong:
    A problem occurred evaluating settings 'gradle'.
    > Could not resolve all dependencies for configuration 'classpath'.
       > Could not find biz.aQute.bnd:biz.aQute.bnd.gradle:${bndlib-version-base}.
         Searched in the following locations:
             https://jcenter.bintray.com/biz/aQute/bnd/biz.aQute.bnd.gradle/${bndlib-version-base}/biz.aQute.bnd.gradle-${bndlib-version-base}.pom
             https://jcenter.bintray.com/biz/aQute/bnd/biz.aQute.bnd.gradle/${bndlib-version base}/biz.aQute.bnd.gradle-${bndlib-version-base}.jar
         Required by:
             unspecified:unspecified:unspecified

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

    BUILD FAILED

    Total time: 2.973 secs

**Comment by bjhargrave** [comment]
BTW, the gradle build still won't work but for a different reason. The problem I fixed was that the wrong macro name was used. With the fix, the version of bnd used by the bndtools build (3.0 at the time of this writing) will be used in the gradle.properties file. However, since 3.0 is still under development, JCenter will not have the 3.0 version of the gradle plugin and thus the offline build will still fail. Once, we release bnd 3.0, the gradle plugin for 3.0 will then be released into jcenter.

**Comment by timothyjward** [comment]
Thanks for the quick fix, and the details of how I can run the dev version :)
