### ISSUE TITLE
bnd-maven-plugin - unable to use pom properties in the bnd file

### ISSUE THREAD

**Issue by timothyjward** [bndtools/bnd#924]
I wish to override my bundle symbolic name to be:

    Bundle-SymbolicName: ${project.groupId}.${project.artifactId}

However this results in an exception, the root cause of which is:

    Caused by: org.apache.maven.plugin.MojoExecutionException: Symbolic Name has invalid format: ${project.groupId}.${project.artifactId}
    	at org.bndtools.maven.BndMavenPlugin.reportErrorsAndWarnings(BndMavenPlugin.java:156)
    	at org.bndtools.maven.BndMavenPlugin.execute(BndMavenPlugin.java:133)
    	... 21 more

I would expect to be able to reference pom properties in my bnd file.

**Comment by bjhargrave** [comment]
This would have to be a feature enhancement. Current maven properties are not exposed to bnd.

**Comment by bjhargrave** [comment]
Assigned to @rotty3000.

**Comment by bjhargrave** [comment]
BTW, I looked at adding the properties from [MavenProject.getProperties()](https://maven.apache.org/ref/3.2.3/apidocs/org/apache/maven/project/MavenProject.html#getProperties%28%29) to the Builder since we already have the MavenProject object injected in the plugin. However that Properties object only seems to contain the user specified properties in the pom rather than all available properties. For example, from the integration tests:

    project.reporting.outputEncoding=UTF-8
    project.build.sourceEncoding=UTF-8

So `project.groupId` and `project.artifactId` are not present in MavenProject.getProperties.

**Comment by gamerson** [comment]
hey @bjhargrave  Likely you would have to do something like this: 
```
@Parameter(defaultValue = "${project.groupId}", readonly = true)
private String projectGroupId;
`
@Parameter(defaultValue = "${project.artifactId}", readonly = true)
private String projectArtifactId;
```

Problem with that is what happens when in a bnd file we want to say ```${project.projectDirectory``` etc.  So it seems that one way to handle this is to write some type of plugin to add to bnd's Builder that could use the MavenProject and look for any ${project.*} and then use reflection to expand those properties.  Perhaps maven even has the code it uses internally available as an API that you could call?

**Comment by bjhargrave** [comment]
I suspect that using a property like `${project.xxx}` may be converted to a call to MavenProject.getXxx(). So we may need to add such code to the bnd maven plugin. Either walk the getters on MavenProject and add those properties to the Builder, or subclass Processor and delegate lookups for missing properties whose name starts with `project.` to a getter on MavenProject.

**Comment by bjhargrave** [comment]
I have a fix and will make a PR tomorrow.

**Comment by rotty3000** [comment]
Thx @bjhargrave! You're a machine!
