### ISSUE TITLE
XMLAttribute defined for @Target(ElementType.METHOD) not applied

### ISSUE THREAD

**Issue by rotty3000** [bndtools/bnd#955]
Given the definition:
```java
	@XMLAttribute(
		embedIn = "*",
		namespace = "meta-type-model-hints",
		prefix = "mh"
	)
	@Retention(RetentionPolicy.CLASS)
	@Target(ElementType.METHOD)
	public @interface Editor {
		boolean editor() default true;
		boolean localized() default false;
		int maxLength() default 2000000;
	}
```
the class:
```java
@ObjectClassDefinition()
public interface Fum {

	@AttributeDefinition(required = false)
	@Editor
	public String html();

}
```
No attribute is added to the resulting XML. And no error.

**Comment by rotty3000** [comment]
OK so the problem lies in that the default elements of the annotation are not used as attributes on the outputted xml element.

For instance, even though `@Editor` is implemented with defaults:
```java
        boolean editor() default true;
        boolean localized() default false;
        int maxLength() default 2000000;
```
when applied to a member simply as:
```java
    @AttributeDefinition(required = false)
    @Editor
    public String html();
```
no attributes are added.

I'd expect this to result in:
```xml
mh:editor="true" mh:localized="false" mh:maxLength="2000000"
```

Is that assumption incorrect?

**Comment by rotty3000** [comment]
Maybe the type `aQute.bnd.osgi.Annotation` could hold an additional `Map<String,Object>	defaults` to access those in cases were getting the defaults is desirable?

**Comment by djencks** [comment]
Maybe I have a different use case in mind.  The problem with putting defaults into the xml is that then there is no way to not have that particular attribute.  In both my use cases, I have a lot of attributes in the same name space, but usually on any one member you'd only use one or two.  If annotation defaults were written into the xml, I'd need maybe 10 annotations instead of one.

Maybe we could have a @Default meta-annotation to supply a default value that _is_ written into the xml?

BTW in DS processing I do need to extract the defaults out of an annotation, so the hard part is already done.  I don't recall what I did with the values.

**Comment by rotty3000** [comment]
don't annotate the member? Why would you annotate it if you don't want any attributes added?

**Comment by djencks** [comment]
My public example is for felix ds options, where there are about 5 or 6 flags and you are unlikely to want more than 2.  Obviously if you don't want any you won't use the annotation. I think that:
- defaulting all the options to "false" and putting optionX="false" in the xml is too verbose
- separate annotations for each option will mean they are all named FelixDSOptionX(...) which is also too verbose.  I guess this __might__ be ok if you typically only use one. Completion in an editor would still be a lot easier with just one annotation, since the editor can show you all the members of the single annotation more easily than all the possible annotations in a package.

**Comment by rotty3000** [comment]
here's an example of what I'm working with:
```java
public interface Hint {

	public static final String NS =
		"http://www.liferay.com/xsd/meta-type-hints_7_0_0";
	public static final String PREFIX = "mh";
	public static final String EMBED_IN = "*";

	@XMLAttribute(
		embedIn = Hint.EMBED_IN,
		namespace = Hint.NS,
		prefix = Hint.PREFIX)
	@Retention(RetentionPolicy.CLASS)
	@Target({ElementType.TYPE})
	public @interface Category {
		String[] category();
	}

	@XMLAttribute(
		embedIn = Hint.EMBED_IN,
		namespace = Hint.NS,
		prefix = Hint.PREFIX)
	@Retention(RetentionPolicy.CLASS)
	@Target(ElementType.METHOD)
	public @interface Date {
		boolean date() default true;
		boolean dayNullable() default false;
		boolean monthNullable() default false;
		boolean yearNullable() default false;
		boolean showTime() default false;
	}

	@XMLAttribute(
		embedIn = Hint.EMBED_IN,
		namespace = Hint.NS,
		prefix = Hint.PREFIX)
	@Retention(RetentionPolicy.CLASS)
	@Target(ElementType.METHOD)
	public @interface Editor {
		boolean editor() default true;
		boolean localized() default false;
		int maxLength() default 2000000;
	}

	@XMLAttribute(
		embedIn = Hint.EMBED_IN,
		namespace = Hint.NS,
		prefix = Hint.PREFIX)
	@Retention(RetentionPolicy.CLASS)
	@Target(ElementType.METHOD)
	public @interface Hidden {
		boolean hidden() default true;
	}

	@XMLAttribute(
		embedIn = Hint.EMBED_IN,
		namespace = Hint.NS,
		prefix = Hint.PREFIX)
	@Retention(RetentionPolicy.CLASS)
	@Target(ElementType.METHOD)
	public @interface ReadOnly {
		boolean readOnly() default true;
	}

	@XMLAttribute(
		embedIn = Hint.EMBED_IN,
		namespace = Hint.NS,
		prefix = Hint.PREFIX)
	@Retention(RetentionPolicy.CLASS)
	@Target(ElementType.METHOD)
	public @interface TextArea {
		int displayHeight() default 105;
		int displayWidth() default 500;
		boolean localized() default false;
		int maxLength() default 4000;
		boolean textarea() default true;
	}

}
```

would you really make all that one single annotation? Wouldn't it be impossible to comprehend?

Here it is applied:
```java
@Hint.Category(category = "category.content")
@ObjectClassDefinition(
	id = "com.liferay.amazon.rankings.web.configuration.AmazonRankingsConfiguration"
)
public interface AmazonRankingsConfiguration {

	@AttributeDefinition(
		defaultValue = {
			"0066620996","0131412752","0201633612","0310205719","0310241448"
		},
		required = false
	)
	public String[] isbns();

	@AttributeDefinition
	@Hint.Hidden
	@Hint.ReadOnly
	public long companyId();

	@AttributeDefinition(required = false)
	@Hint.Editor
	public String html();

}
```

**Comment by rotty3000** [comment]
I'm trying to convert to the patter you suggest but it's not really feeling right.

**Comment by rotty3000** [comment]
Ok, so since it's only caused by defaults not being printed (even if that feels strange) there's no real bug with respect to the annotated methods.

**Comment by djencks** [comment]
I'm slowly coming to the conclusion that most likely more smaller annotations are easier to use and that using the annotation defaults is a good idea.

**Comment by rotty3000** [comment]
David what I did to try to mitigate the IDE auto completion support (not completely) was to use a parent interface type to host the smaller annotations.

This also gave me somewhere central to put the schema info.

**Comment by rotty3000** [comment]
David should I open a new bug specifically about "using annotation defaults"?
