### ISSUE TITLE
servicefactory doesn't work on standalone components

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bnd#969]
I have a stand-alone component that needs a few services but doesn't provide a service to the registry.
It DOES implement an important piece of the application, one that is externally visible.
I want this functionality instantiated multiple times with different configuration.
I use ```servicefactory=true``` for that but that doesn't work for this component.

```
Warning: The servicefactory:=true directive is set but no service is provided, ignoring it
```

Why?

I can see why you would want to have the warning, but ignoring the instruction is very much undesired IMHO.

Can you please NOT ignore the instruction.
I think this is a valid use-case.

**Comment by bjhargrave** [comment]
`servicefactory=true` means that a new instance of the component must be created for each bundle using  the service. But since there is no service, then `servicefactory=true` is meaningless to the runtime. So why shouldn't bnd complain about it and ignore it?

It seems like you just want an immediate component associated with a factory configuration so that each configuration will result in a new instance of the component.

**Comment by fhuberts** [comment]
Ok, the immediate component works too.
A gap in my understanding, fixed now. :-)

BTW if you really want to keep ignoring the instruction then I think it should be an error. Because you get something entirely different from what you intended.

**Comment by fhuberts** [comment]
Also, the warning message might be changed to say something like 'maybe you meant to use an immediate component'

**Comment by djencks** [comment]
you don't need to explicitly specify immediate for a component that doesn't provide any services, it has to be immediate because there is nothing else to trigger its activation.

Since we can produce a correct xml by ignoring the service-factory or scope I'm not totally convinced an error is necessary, but I'll change it if everyone agrees it's a good idea.

david jencks

**Comment by timothyjward** [comment]
Since we can produce a correct xml by ignoring the service-factory or scope I'm not totally convinced an error is necessary, but I'll change it if everyone agrees it's a good idea.

I'd probably leave it as a warning, but make sure that a warning marker appears on the class type in bndtools (i.e. set the error details correctly).
