### ISSUE TITLE
packages only used in annotations not imported

### ISSUE THREAD

**Issue by Andy-L** [bndtools/bnd#989]
I'm using the Gradle Plugin for non Workspace builds, and have found that imports are not created for packages which are only used in Annotations.  e.g. if in bundle A I annotate a Service as:
 ```
import a.b.c.SomeInterface
  .
  .
  .
@Provides(specifications = SomeInterface.class)
public class MyClass extends MyAbstractClass {
```
 where ```a.b.c.SomeInterface``` and ```a.b.d.MyAbstractClass``` are in another bundle B, and the only reference to the package containing ```SomeInterface``` is that annotation, bundle A gets produced without an import of ```a.b.c``` unless it is manually specified.

(edited to clarify abstract class usage)

**Comment by djencks** [comment]
I'm not sure how this is unexpected.  For instance, if we did automatically import packages used in annotations, using the osgi ds spec annotations would be difficult, because you usually use an enumeration from the annotation package, so the annotation package would be dragged in, which we never want.

Could you explain your situation in more detail?  I'm having problems figuring out a situation in which you _would_ want the packages used only as annotation parameters imported.  What does your code do with them, since they aren't used in code?

thanks
david jencks

**Comment by bjhargrave** [comment]
I think your example is wrong. I assume the @Provides is to state the MyClass class is a component which provides the SomeInterface service. However the MyClass class does not implement SomeInterface. If it did this, then bnd would see the type reference to SomeInterface and generate the necessary Import-Package to a.b.c.

Can you provide more detail on the @Provides annotation since my assumptions above may be wrong?

**Comment by Andy-L** [comment]
Well, the annotation in question is used by Apache Felix iPOJO to do service registration at runtime.  So without it, wiring fails.  More information [here](http://felix.apache.org/documentation/subprojects/apache-felix-ipojo/apache-felix-ipojo-gettingstarted/how-to-use-ipojo-annotations.html#provides) and [here](http://felix.apache.org/ipojo/api/1.12.1/org/apache/felix/ipojo/annotations/Provides.html)

Your point about the interface is a good one though.  Right now MyClass extends an abstract class which implements SomeInterface (and the abstract class is in bundle B, but a different package from SomeInterface).  So a reasonable workaround would be to reiterate the implementation of SomeInterface.

My naïve expectation is that you'd want to retain package references from runtime-retention annotations, but I haven't enough experience with osgi to guess what that might break.

**Comment by bjhargrave** [comment]
Well in your example, you did not show MyClass extending or implementing anything :-)

If MyClass does extends some other class, then bnd should generate the necessary Import-Packages for it or subtypes/subinterfaces. What version of bnd are you using to build your bundle?

**Comment by bjhargrave** [comment]
Also, `@Provides` class retention annotation since it does not specific `@Retention` and the default is `RetentionPolicy.CLASS`.

**Comment by Andy-L** [comment]
looking at the manifest, it's Bnd-3.0.0.201506222013

**Comment by bjhargrave** [comment]
OK. But since the `@Provides` annotation is CLASS retention, there is no need to bnd to import any packages it references since the annotation is not visible at runtime.

**Comment by pkriens** [comment]
Only RUNTIME annotations are processed so bnd never sees this annotation and its references. Since the remainder of the code has no reference to this interface, from bnd's perspective the actual of that SomeInterface class is irrelevant.
