### ISSUE TITLE
Include-Resource didn't work in command line wrap

### ISSUE THREAD

**Issue by anylain** [bndtools/bnd#990]
I try wrap `jtds-1.3.1.jar` with bnd command line, but `Include-Resource` is never working and no any warning or error.

here is my `jtds.bnd` and `command`

```
version=1.3.1
Bundle-Name: jTDS JDBC Driver
Bundle-SymbolicName: net.sourceforge.jtds
Bundle-Version: ${version}
Export-Package: *;version=${version}
Include-Resource: jcifs-1.3.17.jar
```

```
java -jar biz.aQute.bnd-latest.jar wrap -p jtds.bnd -o output.jar jtds-1.3.1.jar
```
This is a Bug? Or the way I use the wrong?

**Comment by pkriens** [comment]
Can you make a zip file that contains it all?

**Comment by anylain** [comment]
Yes, this can not be done automatically yet? Or am I missing some configuration?

**Comment by bjhargrave** [comment]
@pkriens is asking if you can zip up the project with the problem so he can play with it.

**Comment by anylain** [comment]
Oh! :scream:  Sorry! My English is poor. 

here is the zip contains all: https://github.com/anylain/bnd_wrap/raw/master/wrap_jtds.zip

**Comment by rotty3000** [comment]
I've taken a look at this (trying to give Peter a hand) and it's a fundamental limitation of `wrap` due to the fact that it's core is `aQute.bnd.osgi.Analyzer`.

`includeresource` is implemented by `aQute.bnd.osgi.Builder` which is a subclass of Analyzer. The entire feature would have to be reimplemented.

**Comment by pkriens** [comment]
Thanks Ray. This helps, Include-Resource does not work for wrap since it it only calculates the manifest.

The solution is `bnd buildx jtds.bnd` and make the `jdts.bnd` file something like:

version=1.3.1
Bundle-Name: jTDS JDBC Driver
Bundle-SymbolicName: net.sourceforge.jtds
Bundle-Version: ${version}
Export-Package: *;version=${version}
-includeresource: @jtds-1.3.1.jar, @jcifs-1.3.17.jar

**Comment by vsingleton** [comment]
Where is the "-includeresource" directive documented?

**Comment by rotty3000** [comment]
http://bnd.bndtools.org/instructions/includeresource.html

PRs to improve the docs are welcome!

;)

- Ray

On Thu, Jan 14, 2016 at 3:30 PM, Vernon Singleton <notifications@github.com>
wrote:

> Where is the "-includeresource" directive documented?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bndtools/bnd/issues/990#issuecomment-171657840>.
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by bjhargrave** [comment]
`-includeresource` is the same as `Include-Resource` but does not start with a Capital letter and thus does not end up in the bundle's manifest.`Include-Resource` is legacy from before instructions starting with `-` were added.
